easy-coding-standard.neon
src/Rector/AbstractChangeMethodNameRector.php
src/Rector/Contrib/Nette/HtmlAddMethodRector.php
src/Rector/Contrib/Nette/PhpGeneratorDocumentMethodRector.php
tests/Rector/Contrib/Nette/PhpGeneratorDocumentMethod/Correct/correct.php.inc
tests/Rector/Contrib/Nette/PhpGeneratorDocumentMethod/Test.php
tests/Rector/Contrib/Nette/PhpGeneratorDocumentMethod/Wrong/wrong.php.inc

[Rector] allow AbstractChangeMethodNameRector work with multiple objects and methods

---

src/Rector/AbstractChangeParentClassRector.php
src/Rector/Contrib/Symfony/ConstraintValidatorTestClassRenameRector.php
tests/Rector/Contrib/Symfony/ConstraintValidatorTestClassRenameRector/Correct/correct.php.inc
tests/Rector/Contrib/Symfony/ConstraintValidatorTestClassRenameRector/Test.php
tests/Rector/Contrib/Symfony/ConstraintValidatorTestClassRenameRector/Wrong/wrong.php.inc

Resolved https://github.com/symfony/symfony/blob/master/UPGRADE-4.0.md#validator

Symfony Constraint test class

---

src/Console/Command/ReconstructCommand.php

When we set a directory then make sense search recursive in subdirectories too.
Reference to `Nette\Utils` API - https://api.nette.org/2.4/Nette.Utils.Finder.html#_from

search files recursive in directories

---

src/Builder/MethodBuilder.php
src/NodeFactory/NodeFactory.php
src/Rector/Contrib/Nette/Utils/MagicMethodRector.php
src/Regex/MagicMethodMatcher.php
tests/Rector/Contrib/Nette/Utils/MagicMethodRector/Correct/correct2.php.inc
tests/Rector/Contrib/Nette/Utils/MagicMethodRector/Test.php
tests/Rector/Contrib/Nette/Utils/MagicMethodRector/Wrong/wrong2.php.inc

Ref https://github.com/nette/utils/blob/v2.4/src/Utils/ObjectMixin.php#L328
Closes #49

MagicMethodRector - add setter, added option

---

packages/DeprecationExtractor/src/NodeAnalyzer/TriggerErrorAnalyzer.php
src/Builder/Method/MethodStatementCollector.php
src/NodeFactory/NodeFactory.php
src/NodeTraverser/ShutdownNodeTraverser.php
src/NodeVisitor/PropertyToClassAdder.php
src/NodeVisitor/StatementToMethodAdder.php
src/Rector/Contrib/PHPUnit/ExceptionRector.php
src/Rector/Contrib/PHPUnit/GetMockRector.php
src/config/level/phpunit/phpunit60.yml
tests/Rector/Contrib/PHPUnit/ExceptionRector/Correct/correct.php.inc
tests/Rector/Contrib/PHPUnit/ExceptionRector/Test.php
tests/Rector/Contrib/PHPUnit/ExceptionRector/Wrong/wrong.php.inc
tests/Rector/Contrib/PHPUnit/GetMockRector/Correct/correct.php.inc
tests/Rector/Contrib/PHPUnit/GetMockRector/Test.php
tests/Rector/Contrib/PHPUnit/GetMockRector/Wrong/wrong.php.inc
tests/Rector/Dynamic/NamespaceReplacerRector/Test.php
tests/Rector/Dynamic/NamespaceReplacerRector/config/rector.yml
tests/Rector/Dynamic/NamespaceReplacerRector/correct/correct4.php.inc
tests/Rector/Dynamic/NamespaceReplacerRector/wrong/wrong4.php.inc

[PHPUnit] rectors for 6.0 complete

---

composer.json
easy-coding-standard.neon
packages/BetterReflection/src/Reflector/MethodReflector.php
packages/BetterReflection/src/Reflector/SmartClassReflector.php
packages/BetterReflection/tests/Reflector/ClassReflectorOnSourceTest.php
packages/DeprecationExtractor/src/Console/Command/ExtractDeprecationsCommand.php
packages/DeprecationExtractor/src/Rector/RectorGuesser.php
packages/DeprecationExtractor/src/RectorGuess/RectorGuessFilter.php
src/Application/FileProcessor.php
src/Builder/StatementGlue.php
src/NodeVisitor/PropertyToClassAdder.php
src/Rector/Contrib/Nette/Utils/MagicMethodRector.php
src/Rector/Contrib/Nette/Utils/NetteObjectToSmartTraitRector.php
src/Rector/Dynamic/NamespaceReplacerRector.php
src/Rector/Dynamic/PseudoNamespaceToNamespaceRector.php
src/Rector/MagicDisclosure/GetAndSetToMethodCallRector.php
src/Rector/MagicDisclosure/UnsetAndIssetToMethodCallRector.php
src/Regex/MagicMethodMatcher.php

Ref https://github.com/nikic/PHP-Parser/issues/426#issuecomment-337361786

Adder tuning

---

packages/NodeTypeResolver/src/PerNodeTypeResolver/NameTypeResolver.php
packages/NodeTypeResolver/src/PerNodeTypeResolver/PropertyFetchTypeResolver.php
packages/NodeTypeResolver/src/PerNodeTypeResolver/PropertyTypeResolver.php
packages/NodeTypeResolver/tests/PerNodeTypeResolver/NameTypeResolver/Source/ParentCall.php.inc
packages/NodeTypeResolver/tests/PerNodeTypeResolver/NameTypeResolver/Test.php
src/Node/NodeFactory.php
src/NodeAnalyzer/MethodNameAnalyzer.php
src/NodeAnalyzer/StaticMethodCallAnalyzer.php
src/Rector/Contrib/PhpParser/IdentifierRector.php
src/Rector/Contrib/PhpParser/UseWithAliasRector.php
src/Rector/Dynamic/MethodNameReplacerRector.php
tests/Rector/Dynamic/MethodNameReplacerRector/Test.php
tests/Rector/Dynamic/MethodNameReplacerRector/config/rector.yml
tests/Rector/Dynamic/MethodNameReplacerRector/correct/correct6.php.inc
tests/Rector/Dynamic/MethodNameReplacerRector/wrong/wrong6.php.inc

Closes #109
Closes https://github.com/nikic/PHP-Parser/issues/431

MethodRename - include parent calls

---

ecs-after-rector.neon
packages/ReflectionDocBlock/src/DocBlock/TidingSerializer.php
packages/ReflectionDocBlock/src/NodeAnalyzer/DocBlockAnalyzer.php
packages/ReflectionDocBlock/tests/NodeAnalyzer/DocBlockAnalyzerTest.php
src/Node/MethodCallNodeFactory.php
src/Rector/Contrib/PHPUnit/ExceptionAnnotationRector.php
src/Rector/Contrib/PHPUnit/GetMockRector.php
src/Rector/Contrib/PHPUnit/SpecificMethodRector.php
src/config/level/phpunit/phpunit60.yml
tests/Rector/Contrib/Nette/Utils/MagicMethodRector/Correct/correct.php.inc
tests/Rector/Contrib/Nette/Utils/MagicMethodRector/Correct/correct2.php.inc
tests/Rector/Contrib/PHPUnit/ExceptionAnnotationRector/Correct/correct.php.inc
tests/Rector/Contrib/PHPUnit/ExceptionAnnotationRector/Test.php
tests/Rector/Contrib/PHPUnit/ExceptionAnnotationRector/Wrong/wrong.php.inc

[PHPUnit] new rectors

---

src/Console/Application.php

Closes #139 
@greg0ire What do you think?

[Console] allow verbose option, improve default definition to opt-out

---

.travis.yml
composer.json
easy-coding-standard.neon
tests/Rector/Contrib/Nette/Application/InjectPropertyRector/Correct/correct.php.inc
tests/Rector/Contrib/Nette/Utils/MagicMethodRector/Correct/correct.php.inc
tests/Rector/Contrib/Nette/Utils/MagicMethodRector/Correct/correct2.php.inc

Bump to recent https://github.com/nikic/PHP-Parser/releases/tag/v4.0.0alpha2

php-parser dependency update

---

README.md
docs/HowToCreateOwnRector.md
src/Rector/Dynamic/PropertyToMethodRector.php
src/Rector/MagicDisclosure/ToStringToMethodCallRector.php
tests/Rector/Dynamic/PropertyToMethodRector/Test.php
tests/Rector/Dynamic/PropertyToMethodRector/config/rector.yml
tests/Rector/Dynamic/PropertyToMethodRector/correct/correct.php.inc
tests/Rector/Dynamic/PropertyToMethodRector/wrong/wrong.php.inc

[Dynamic] Add  PropertyToMethodRector

---

easy-coding-standard.neon
packages/NodeTypeResolver/src/NodeCallerTypeResolver.php
src/Rector/Contrib/Symfony/Process/ProcessBuilderGetProcessRector.php
src/Rector/Contrib/Symfony/Process/ProcessBuilderInstanceRector.php
src/config/level/symfony/symfony40.yml
tests/Rector/Contrib/Symfony/Process/ProcessBuilderGetProcessRector/Correct/correct.php.inc
tests/Rector/Contrib/Symfony/Process/ProcessBuilderGetProcessRector/Test.php
tests/Rector/Contrib/Symfony/Process/ProcessBuilderGetProcessRector/Wrong/wrong.php.inc
tests/Rector/Contrib/Symfony/Process/ProcessBuilderInstanceRector/Correct/correct.php.inc
tests/Rector/Contrib/Symfony/Process/ProcessBuilderInstanceRector/Test.php
tests/Rector/Contrib/Symfony/Process/ProcessBuilderInstanceRector/Wrong/wrong.php.inc

Closes #186 
Ref Symfony Documentation https://github.com/symfony/symfony-docs/pull/8881
Added as part of `symfony40` level
```php
$process = ProcessBuilder::instance($args)->getProcess();
```
```php
$process = new Process($args);
```

[Symfony] Add ProcessBuilder Rector

---

src/Rector/Contrib/PHPUnit/SpecificMethodRector.php

[PHPUnit] Fix array_key_exists() argument up-lifting

---

src/Rector/Contrib/PHPUnit/SpecificMethodInternalTypeRector.php
src/config/level/phpunit/phpunit60.yml
tests/Rector/Contrib/PHPUnit/SpecificMethodInternalTypeRector/Correct/correct.php.inc
tests/Rector/Contrib/PHPUnit/SpecificMethodInternalTypeRector/Test.php
tests/Rector/Contrib/PHPUnit/SpecificMethodInternalTypeRector/Wrong/wrong.php.inc

@TomasVotruba I've start to code `SpecificMethodInternalTypeRector`. Here's what I got so far, and want your opinion before continue :smile:

[PHPUnit] Create SpecificMethodInternalTypeRector

---

src/FileSystem/PhpFilesFinder.php

This is a try to fix #221. Still testing it.

Potencial fix for subfolders problem

---

packages/NodeValueResolver/src/PerNodeValueResolver/ConstFetchResolver.php
packages/NodeValueResolver/tests/NodeValueResolverTest.php

[ConstFetchResolver] Support keyword in uppercase

---

.travis.yml

To separate reponsibility and possibly speed up test runs

travis: split phpstan and cs

---

src/Rector/Contrib/PhpParser/UseWithAliasRector.php
src/Rector/Dynamic/PropertyToMethodRector.php
src/Rector/MagicDisclosure/ToStringToMethodCallRector.php

Use MethodCallNodeFactory by Rector

---

README.md

This was suggested by @TomasVotruba for me [a while ago](https://github.com/rectorphp/rector/issues/208#issuecomment-353549916).

Explicit install Rector dev-master

---

README.md

Use diffs in README.md

---

src/Printer/FormatPerservingPrinter.php

[FormatPerservingPrinter] Force boolean

---

README.md

Following [the last commit](https://github.com/rectorphp/rector/commit/6ac95bdb2fa163e57e6fcee734313c84df0d80e3), we now cand link them :smile:

[README] Link list to headers

---

README.md
docs/HowUseWithOldPhp.md

Change UseWithOldPhp.md to use dev-master

---

src/Console/Command/ProcessCommand.php

Add one line between the progress bar and Exception trace.
Before:
After:

[ProcessCommand] Add one line between the progress bar and Exception trace

---

LICENSE

Following [`symfony/symfony#25646`](https://github.com/symfony/symfony/pull/25646) :tada:

Update LICENSE year forever

---

.gitignore
README.md
docs/HowItWorks.md
src/Rector/Contrib/PHPUnit/SpecificMethod/AssertComparisonToSpecificMethodRector.php
src/Rector/Contrib/PHPUnit/SpecificMethod/AssertFalseStrposToContainsRector.php
tests/Rector/RectorOrder/Correct/correct.php.inc
tests/Rector/RectorOrder/RectorOrderTest.php
tests/Rector/RectorOrder/Wrong/wrong.php.inc
tests/Rector/RectorOrder/config/rector.yml

Replacement for #269 to `master` branch

[Rector] order test

---

tests/Rector/Contrib/Symfony/HttpKernel/TemplateAnnotationRector/Correct/correct5.php.inc
tests/Rector/Contrib/Symfony/HttpKernel/TemplateAnnotationRector/Correct/correct6.php.inc
tests/Rector/Contrib/Symfony/HttpKernel/TemplateAnnotationRector/Wrong/wrong5.php.inc
tests/Rector/Contrib/Symfony/HttpKernel/TemplateAnnotationRector/Wrong/wrong6.php.inc

added tests for more use cases

---

packages/NodeTypeResolver/src/NodeVisitor/ClassAndMethodResolver.php
phpstan.neon
src/Rector/Contrib/Nette/Bootstrap/RemoveConfiguratorConstantsRector.php
src/Rector/Contrib/PHPUnit/SpecificMethod/AssertCompareToSpecificMethodRector.php
src/Rector/Contrib/Sensio/Helper/TemplateGuesser.php
src/Rector/Dynamic/ArgumentReplacerRector.php
src/Rector/Dynamic/ClassReplacerRector.php
src/Rector/Dynamic/MethodNameReplacerRector.php

@TomasVotruba What I send to you on Hangouts. I let you know when I finish, so you can review and merge!

Fixes from PHPStan

---

README.md
src/Rector/AbstractRector.php
src/Rector/Dynamic/FluentReplaceRector.php
tests/Rector/Dynamic/FluentReplaceRector/Correct/correct.php.inc
tests/Rector/Dynamic/FluentReplaceRector/FluentReplaceRectorTest.php
tests/Rector/Dynamic/FluentReplaceRector/Wrong/wrong.php.inc
tests/Rector/Dynamic/FluentReplaceRector/config/rector.yml

Added FluentReplacerRector 

---

packages/NodeTypeResolver/src/TypesExtractor/ConstructorPropertyTypesExtractor.php
src/NodeChanger/PropertyAdder.php

Found with https://github.com/vlajos/misspell_fixer

Fix some misspellings

---

README.md
easy-coding-standard.neon
src/Console/Command/ProcessCommand.php
src/Console/Output/ProcessCommandReporter.php
src/Reporting/FileDiff.php
src/config/services.yml

@carusogabriel Could you review and merge if ok? Thank you

add FileDiff object over array

---

composer.json
src/Console/Application.php

This will become tag while installed in `/vendor`

[Console] add version on bin/rector [closes #298]

---

CODE_OF_CONDUCT.md

Use HTTPS instead of HTTP

---

tests/Rector/Dynamic/MethodNameReplacerRector/Correct/correct7.php.inc
tests/Rector/Dynamic/MethodNameReplacerRector/MethodNameReplacerRectorTest.php
tests/Rector/Dynamic/MethodNameReplacerRector/Wrong/wrong7.php.inc

Add test for issue #310. Is it a bug or expected behavior?

MethodNameReplacerRector extra test

---

README.md
bin/rector_bootstrap.php
composer.json
easy-coding-standard.neon
phpunit.dist.xml
phpunit.xml
src/Console/Command/ProcessCommand.php
src/DependencyInjection/ContainerFactory.php
src/Rector/Contrib/Nette/Application/ValidateControlRector.php
src/Rector/Contrib/Symfony/Form/OptionNameRector.php
src/config/external-services.yml

Cherry picked from #319 
Few fixed and improvement not related to PHAR, that would be great to have in `master` in meaintime

Bug fixes and optimizations

---

src/Rector/Contrib/PHPUnit/SpecificMethod/AssertTrueFalseToSpecificMethodRector.php
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertTrueFalseToSpecificMethodRector/Wrong/wrong.php.inc

Fix AssertTrueFalseToSpecificMethodRector

---

composer.json

Added missing composer dependency

---

src/Rector/Contrib/PHPUnit/SpecificMethod/AssertTrueFalseToSpecificMethodRector.php
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertTrueFalseToSpecificMethodRector/Correct/correct.php.inc
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertTrueFalseToSpecificMethodRector/Wrong/wrong.php.inc

Fix 3th argument of is_a

---

config/level/phpunit/phpunit-specific-method.yml
src/Rector/Contrib/PHPUnit/SpecificMethod/AssertNotOperatorRector.php
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertNotOperatorRector/AssertNotOperatorRectorTest.php
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertNotOperatorRector/Correct/correct.php.inc
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertNotOperatorRector/Wrong/wrong.php.inc
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertNotOperatorRector/config.yml

Inspired by https://github.com/drush-ops/drush/pull/3478

[PHPUnit] Add AssertNotOperatorRector

---

src/Rector/Contrib/Symfony/FrameworkBundle/AbstractToConstructorInjectionRector.php
tests/Rector/Contrib/Symfony/FrameworkBundle/GetToConstructorInjectionRector/Correct/correct2.php.inc
tests/Rector/Contrib/Symfony/FrameworkBundle/GetToConstructorInjectionRector/GetToConstructorInjectionRectorTest.php
tests/Rector/Contrib/Symfony/FrameworkBundle/GetToConstructorInjectionRector/Wrong/wrong2.php.inc

Fix AbstractToConstructorInjectionRector to work with class names in get arguments.

AbstractToConstructorInjectionRector fix

---

phpstan.neon
src/Node/NodeFactory.php
src/Rector/Contrib/PHPUnit/SpecificMethod/AssertInstanceOfComparisonRector.php
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertInstanceOfComparisonRector/Correct/correct.php.inc
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertInstanceOfComparisonRector/Wrong/wrong.php.inc

This resolves #377 by resolving the class name with `ClassName::class` instead of `'ClassName'`

Make assertInstanceOf Rector smarter

---

src/Rector/Contrib/Nette/Bootstrap/RemoveConfiguratorConstantsRector.php
src/Rector/Contrib/PHPUnit/SpecificMethod/AssertSameBoolNullToSpecificMethodRector.php

Reopening #331 based on https://github.com/rectorphp/rector/pull/379#discussion_r177717471

Use toLowerString method

---

easy-coding-standard.neon
packages/NodeTypeResolver/src/TypeContext.php
packages/ReflectionDocBlock/src/NodeAnalyzer/DocBlockAnalyzer.php
packages/ReflectionDocBlock/tests/NodeAnalyzer/DocBlockAnalyzerTest.php
phpstan.neon
src/Node/NodeFactory.php
src/NodeAnalyzer/ClassLikeAnalyzer.php
src/NodeAnalyzer/ClassMethodAnalyzer.php
src/NodeAnalyzer/MethodArgumentAnalyzer.php
src/NodeAnalyzer/MethodCallAnalyzer.php
src/NodeAnalyzer/PropertyFetchAnalyzer.php
src/NodeAnalyzer/StaticMethodCallAnalyzer.php
src/Rector/Architecture/RepositoryAsService/ReplaceParentRepositoryCallsByRepositoryPropertyRector.php
src/Rector/Contrib/Nette/DI/CompilerCompileArgumentsRector.php
src/Rector/Contrib/Nette/DI/CompilerGenerateCodeArgumentsRector.php
src/Rector/Contrib/Nette/DI/ExpandFunctionToParametersArrayRector.php
src/Rector/Contrib/Nette/DI/ExpandFunctionToStaticExpandFunctionRector.php
src/Rector/Contrib/PHPUnit/DelegateExceptionArgumentsRector.php
src/Rector/Contrib/PHPUnit/GetMockRector.php
src/Rector/Contrib/PHPUnit/SpecificMethod/AssertFalseStrposToContainsRector.php
src/Rector/Contrib/PHPUnit/SpecificMethod/AssertPropertyExistsRector.php
src/Rector/Contrib/PHPUnit/SpecificMethod/AssertTrueFalseToSpecificMethodRector.php
src/Rector/Contrib/PhpParser/IdentifierRector.php
src/Rector/Contrib/Symfony/Controller/AddFlashRector.php
src/Rector/Contrib/Symfony/Controller/RedirectToRouteRector.php
src/Rector/Contrib/Symfony/DependencyInjection/CompilerAddPassPriorityRector.php
src/Rector/Contrib/Symfony/DependencyInjection/ContainerBuilderCompileEnvArgumentRector.php
src/Rector/Contrib/Symfony/VarDumper/VarDumperTestTraitMethodArgsRector.php
src/Rector/Dynamic/FunctionToMethodCallRector.php

I've made a several clean up in our `phpstan.neon` file by fixing some phpDocs, asserting not nullable values, rewrite some conditions, etc :)

Several fixes from PHPStan

---

easy-coding-standard.neon
src/Node/NodeFactory.php

Following #381, this PR proposes the removal of "dead" coding standards rules.

Remove dead coding standards rules

---

src/Console/Application.php

Following https://github.com/Symplify/Symplify/pull/705.
IMHO we should add this, to give the user all possible options to run their commands :)

Add shortcuts for levels and config

---

packages/NodeTypeResolver/tests/PerNodeTypeResolver/AssignTypeResolver/AssignTypeResolverTest.php
packages/NodeTypeResolver/tests/PerNodeTypeResolver/MethodCallTypeResolver/MethodCallTypeResolverTest.php
packages/NodeTypeResolver/tests/PerNodeTypeResolver/MethodCallTypeResolver/NestedMethodCallTest.php
packages/NodeTypeResolver/tests/PerNodeTypeResolver/NameTypeResolver/NameTypeResolverTest.php

Skip more PHP 7.1 or lower tests

---

composer.json

Bump rector/better-reflection

---

composer.json
phpstan.neon
src/Node/MethodCallNodeFactory.php
src/Node/NodeFactory.php
src/Rector/Architecture/RepositoryAsService/MoveRepositoryFromParentToConstructorRector.php
src/Rector/Contrib/Nette/DI/CompilerGenerateCodeArgumentsRector.php
src/Rector/Contrib/Nette/DI/ExpandFunctionToStaticExpandFunctionRector.php
src/Rector/Contrib/PHPUnit/SpecificMethod/AssertInstanceOfComparisonRector.php

This resolves #385 by using the new methods available at `BuilderFactory`.

Use BuilderFactory new methods

---

phpstan.neon
src/NodeChanger/ExpressionAdder.php
src/Rector/AbstractRector.php
src/Rector/Architecture/PHPUnit/ArrayToYieldDataProviderRector.php
tests/Rector/Architecture/PHPUnit/ArrayToYieldDataProviderRectorTest.php
tests/Rector/Architecture/PHPUnit/Correct/correct.php.inc
tests/Rector/Architecture/PHPUnit/Wrong/wrong.php.inc
tests/Rector/Architecture/PHPUnit/config.yml

```php
/**
* @return mixed[]
*/
public function provideData(): array
{
return [
['item']
];
}
```
```php
/**
*/
public function provideData(): \Iterator
{
(yield ['item']);
}
```

Add ArrayToYieldDataProviderRector

---

src/Rector/Contrib/PHPUnit/SpecificMethod/AssertFalseStrposToContainsRector.php
src/Rector/Contrib/PHPUnit/SpecificMethod/AssertInstanceOfComparisonRector.php
src/Rector/Contrib/PHPUnit/SpecificMethod/AssertNotOperatorRector.php
src/Rector/Contrib/PHPUnit/SpecificMethod/AssertPropertyExistsRector.php

Inspired by the logic applied at `AssertTrueFalseInternalTypeToSpecificMethodRector`

DRY methods to be found in Assert Rectors

---

README.md
bin/rector
composer.json
packages/ConsoleDiffer/src/Console/Formatter/DiffConsoleFormatter.php
packages/ConsoleDiffer/src/DifferAndFormatter.php
packages/ConsoleDiffer/src/config/external-services.yml
packages/ConsoleDiffer/src/config/services.yml
packages/ReflectionDocBlock/src/NodeAnalyzer/DocBlockAnalyzer.php
src/Builder/PropertyBuilder.php
src/Configuration/Option.php
src/Console/Command/DescribeCommand.php
src/Rector/Dynamic/ArgumentReplacerRector.php
src/Rector/Dynamic/MethodNameReplacerRector.php
src/config/services.yml

Add Describe command

---

config/level/phpunit/phpunit-specific-method.yml
src/Rector/Contrib/PHPUnit/SpecificMethod/AssertRegExpRector.php
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertRegExpRector/AssertRegExpRectorTest.php
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertRegExpRector/Correct/correct.php.inc
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertRegExpRector/Wrong/wrong.php.inc
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertRegExpRector/config.yml

This closes #386 
PS: should be rebased and merged after #414, as it contains CS fixes already.

[PHPUnit] Create AssertRegExpRector

---

src/Rector/Dynamic/NamespaceReplacerRector.php

Hey, I think this condition is unnecessary as next method that retrieve name, also checks that:)

remove unnecessary condition(NamespaceReplacerRector)

---

README.md
src/Autoloading/AdditionalAutoloader.php
src/FileSystem/FileGuard.php
src/Testing/PHPUnit/AbstractRectorTestCase.php

Add autoload_files parameter

---

config/level/code-quality/code-quality.yml
src/Rector/Contrib/CodeQuality/InArrayAndArrayKeysToArrayKeyExistsRector.php
tests/Rector/Contrib/CodeQuality/InArrayAndArrayKeysToArrayKeyExistsRector/Correct/correct.php.inc
tests/Rector/Contrib/CodeQuality/InArrayAndArrayKeysToArrayKeyExistsRector/InArrayAndArrayKeysToArrayKeyExistsRectorTest.php
tests/Rector/Contrib/CodeQuality/InArrayAndArrayKeysToArrayKeyExistsRector/Wrong/wrong.php.inc
tests/Rector/Contrib/CodeQuality/InArrayAndArrayKeysToArrayKeyExistsRector/config.yml

As suggested in https://github.com/rectorphp/rector/issues/424#issuecomment-383379319.
Reference that the two logics are the same: https://3v4l.org/2ok4M

[CodeQuality] Create InArrayAndArrayKeysToArrayKeyExistsRector

---

packages/NodeTypeResolver/tests/PerNodeTypeResolver/AssignTypeResolver/AssignTypeResolverTest.php
packages/NodeTypeResolver/tests/PerNodeTypeResolver/ClassLikeTypeResolver/ClassLikeTypeResolverTest.php
packages/NodeTypeResolver/tests/PerNodeTypeResolver/MethodCallTypeResolver/MethodCallTypeResolverTest.php
packages/NodeTypeResolver/tests/PerNodeTypeResolver/MethodCallTypeResolver/NestedMethodCallTest.php
packages/NodeTypeResolver/tests/PerNodeTypeResolver/NameTypeResolver/NameTypeResolverTest.php
packages/NodeTypeResolver/tests/PerNodeTypeResolver/ParamTypeResolver/ParamTypeResolverTest.php
packages/NodeTypeResolver/tests/PerNodeTypeResolver/PropertyFetchTypeResolver/PropertyFetchTypeResolverTest.php
packages/NodeTypeResolver/tests/PerNodeTypeResolver/PropertyTypeResolver/PropertyTypeResolverTest.php
packages/NodeTypeResolver/tests/PerNodeTypeResolver/VariableTypeResolver/VariableTypeResolverTest.php
packages/RectorBuilder/tests/BuilderRector/BuilderRectorTest.php
packages/ReflectionDocBlock/src/NodeAnalyzer/DocBlockAnalyzer.php
tests/Rector/Architecture/PHPUnit/ArrayToYieldDataProviderRectorTest.php
tests/Rector/Architecture/PHPUnit/Correct/correct3.php.inc
tests/Rector/Architecture/PHPUnit/Wrong/wrong3.php.inc

Fix ArrayToYieldDataProviderRector for empty docs

---

easy-coding-standard.yml
src/Builder/PropertyBuilder.php
src/Naming/PropertyNaming.php
src/Node/NodeFactory.php
src/Php/TypeAnalyzer.php
src/Rector/Dynamic/ReturnTypehintRector.php
src/config/level/sylius/sylius10.yml
tests/Rector/Dynamic/ReturnTypehintRector/Correct/correct.php.inc
tests/Rector/Dynamic/ReturnTypehintRector/Correct/correct2.php.inc
tests/Rector/Dynamic/ReturnTypehintRector/Correct/correct3.php.inc
tests/Rector/Dynamic/ReturnTypehintRector/Correct/correct4.php.inc
tests/Rector/Dynamic/ReturnTypehintRector/Correct/correct5.php.inc
tests/Rector/Dynamic/ReturnTypehintRector/ReturnTypehintRectorTest.php
tests/Rector/Dynamic/ReturnTypehintRector/Wrong/wrong.php.inc
tests/Rector/Dynamic/ReturnTypehintRector/Wrong/wrong2.php.inc
tests/Rector/Dynamic/ReturnTypehintRector/Wrong/wrong3.php.inc
tests/Rector/Dynamic/ReturnTypehintRector/Wrong/wrong4.php.inc
tests/Rector/Dynamic/ReturnTypehintRector/Wrong/wrong5.php.inc
tests/Rector/Dynamic/ReturnTypehintRector/config.yml

Add Rector\Rector\Dynamic\ReturnTypehintRector 

---

src/NodeAnalyzer/MethodArgumentAnalyzer.php
src/Rector/Contrib/Doctrine/AliasToClassRector.php
tests/Rector/Contrib/Doctrine/AliasToClassRector/AliasToClassRectorTest.php
tests/Rector/Contrib/Doctrine/AliasToClassRector/Correct/correct.php.inc
tests/Rector/Contrib/Doctrine/AliasToClassRector/Wrong/wrong.php.inc
tests/Rector/Contrib/Doctrine/AliasToClassRector/config.yml

Closes #438 
Check it and let me know what you think:)

doctrine alias to entity class rector

---

src/NodeAnalyzer/MethodArgumentAnalyzer.php
src/Rector/Contrib/Doctrine/AliasToClassRector.php
src/Rector/Contrib/Nette/DI/ExpandFunctionToParametersArrayRector.php
src/Rector/Contrib/Nette/DI/ExpandFunctionToStaticExpandFunctionRector.php
src/Rector/Contrib/Sylius/Review/ReplaceCreateMethodWithoutReviewerRector.php
src/Rector/Contrib/Symfony/Controller/RedirectToRouteRector.php
tests/NodeAnalyzer/MethodArgumentAnalyzerTest.php

I noticed ArgumentAnalyzer has methods like isFirstSomething, IsSecondSomething. I think we should generalize it. Check it and let me know what you think.

improvement - argument analyzer dynamic

---

src/Rector/Contrib/PHPUnit/SpecificMethod/AssertPropertyExistsRector.php
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertPropertyExistsRector/AssertPropertyExistsRectorTest.php
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertPropertyExistsRector/Correct/correct2.php.inc
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertPropertyExistsRector/Wrong/wrong2.php.inc

Fix AssertPropertyExistsRector

---

src/NodeAnalyzer/StaticMethodCallAnalyzer.php
src/Rector/Contrib/PHPUnit/SpecificMethod/AssertNotOperatorRector.php
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertNotOperatorRector/Correct/correct.php.inc
tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertNotOperatorRector/Wrong/wrong.php.inc

As requested https://github.com/rectorphp/rector/issues/447#issuecomment-385260542

Failing test for #447

---

src/config/config.yml
tests/Rector/Contrib/Symfony/FrameworkBundle/GetToConstructorInjectionRector/InvalidConfigurationConstructorInjectionRectorTest.php

Add Default kernel class

---

src/Bridge/Symfony/DefaultAnalyzedSymfonyApplicationContainer.php
src/config/config.yml
tests/Rector/Contrib/Symfony/FrameworkBundle/GetToConstructorInjectionRector/InvalidConfigurationConstructorInjectionRectorTest.php

Add more default Kernel class names

---

.travis.yml
composer.json
packages/NodeTypeResolver/src/PerNodeTypeResolver/NameTypeResolver.php

Lower deps to Symfony3.4

---

README.md
packages/NodeTypeResolver/src/PerNodeTypeResolver/AssignTypeResolver.php
packages/NodeTypeResolver/src/PerNodeTypeResolver/VariableTypeResolver.php
src/Rector/Interface_/MergeInterfacesRector.php
tests/Rector/Interface_/MergeInterfacesRector/Correct/correct.php.inc
tests/Rector/Interface_/MergeInterfacesRector/Correct/correct2.php.inc
tests/Rector/Interface_/MergeInterfacesRector/MergeInterfacesRectorTest.php
tests/Rector/Interface_/MergeInterfacesRector/Source/SomeInterface.php
tests/Rector/Interface_/MergeInterfacesRector/Source/SomeOldInterface.php
tests/Rector/Interface_/MergeInterfacesRector/Wrong/wrong.php.inc
tests/Rector/Interface_/MergeInterfacesRector/Wrong/wrong2.php.inc
tests/Rector/Interface_/MergeInterfacesRector/config.yml

Closes #491 + needs ClassReplacerRector for the rest of cases like: https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/614d2e6f7af5a5b0be5363ff536aed2b7ee5a31d#diff-2e9f7f65bf619b906cd1666fa1e493e9

[Rector] Add MergeInterfaceRector

---

src/DependencyInjection/CompilerPass/CollectorCompilerPass.php
src/Rector/Constant/RenameClassConstantsUseToStringsRector.php
src/Rector/Dynamic/ReturnTypehintRector.php
src/Rector/Interface_/MergeInterfacesRector.php
tests/Rector/Architecture/DependencyInjection/ActionInjectionToConstructorInjectionRector/Source/SomeKernelClass.php

Together with PHPStorm and https://github.com/kalessil/phpinspectionsea, here are some improvements that we can make to Rector :smile:

Improvements

---

config/level/symfony/symfony32.yml
packages/Symfony/src/Rector/Yaml/SpaceBetweenKeyAndValueYamlRector.php
packages/Symfony/tests/Rector/Yaml/SpaceBetweenKeyAndValueYamlRector/Correct/correct.yml
packages/Symfony/tests/Rector/Yaml/SpaceBetweenKeyAndValueYamlRector/SpaceBetweenKeyAndValueYamlRectorTest.php
packages/Symfony/tests/Rector/Yaml/SpaceBetweenKeyAndValueYamlRector/Wrong/wrong.yml
packages/Symfony/tests/Rector/Yaml/SpaceBetweenKeyAndValueYamlRector/config.yml

[Symfony] Add space after colon YamlRector

---

config/level/symfony/symfony34.yml
packages/Symfony/src/Rector/Yaml/SessionStrictTrueByDefaultYamlRector.php
packages/Symfony/tests/Rector/Yaml/SessionStrictTrueByDefaultYamlRector/Correct/correct.yml
packages/Symfony/tests/Rector/Yaml/SessionStrictTrueByDefaultYamlRector/SessionStrictTrueByDefaultYamlRectorTest.php
packages/Symfony/tests/Rector/Yaml/SessionStrictTrueByDefaultYamlRector/Wrong/wrong.yml
packages/Symfony/tests/Rector/Yaml/SessionStrictTrueByDefaultYamlRector/config.yml

[Symfony] Add use_strict_mode removal

---

config/level/symfony/symfony41.yml
packages/YamlRector/src/DependencyInjection/CompilerPass/AutowireYamlRectorCompilerPass.php
packages/YamlRector/src/PathResolver.php
packages/YamlRector/src/Rector/RenameSubKeyYamlRector.php
packages/YamlRector/src/Rector/ReplaceValueYamlRector.php
packages/YamlRector/tests/Rector/ReplaceValueYamlRector/ReplaceValueYamlRectorTest.php
packages/YamlRector/tests/Rector/ReplaceValueYamlRector/config.yml
packages/YamlRector/tests/Rector/ReplaceValueYamlRector/correct/correct.yml
packages/YamlRector/tests/Rector/ReplaceValueYamlRector/wrong/wrong.yml
src/DependencyInjection/RectorKernel.php

[YamlRector] Init ReplaceValueYamlRector

---

composer.json
packages/YamlRector/src/Rector/RenameSubKeyYamlRector.php
packages/YamlRector/tests/Rector/RenameSubKeyYamlRector/RenameSubKeyYamlRectorTest.php
packages/YamlRector/tests/Rector/RenameSubKeyYamlRector/config.yml
packages/YamlRector/tests/Rector/RenameSubKeyYamlRector/correct/correct3.yml
packages/YamlRector/tests/Rector/RenameSubKeyYamlRector/wrong/wrong3.yml

Fixes cases like https://regex101.com/r/NJDMqX/4
This was an idea that came to me while sitting on the bench @JanMikes 
What do you think?

[YamlRector] Process replace by newline split

---

src/Exception/InvalidNodeTypeException.php
src/NodeModifier/VisibilityModifier.php
src/Rector/Visibility/ChangeMethodVisibilityRector.php
src/Rector/Visibility/ChangePropertyVisibilityRector.php
tests/Rector/Visibility/ChangeMethodVisibilityRector/ChangePropertyVisibilityRectorTest.php
tests/Rector/Visibility/ChangeMethodVisibilityRector/Correct/correct.php.inc
tests/Rector/Visibility/ChangeMethodVisibilityRector/Correct/correct2.php.inc
tests/Rector/Visibility/ChangeMethodVisibilityRector/Source/ParentObject.php
tests/Rector/Visibility/ChangeMethodVisibilityRector/Wrong/wrong.php.inc
tests/Rector/Visibility/ChangeMethodVisibilityRector/Wrong/wrong2.php.inc
tests/Rector/Visibility/ChangeMethodVisibilityRector/config.yml

[Rector] Add ChangeMethodVisibilityRector

---

src/NodeModifier/VisibilityModifier.php
src/Rector/Visibility/ChangeConstantVisibilityRector.php
src/Rector/Visibility/ChangeMethodVisibilityRector.php
src/Rector/Visibility/ChangePropertyVisibilityRector.php
tests/Rector/Visibility/ChangeConstantVisibilityRector/ChangeConstantVisibilityRectorTest.php
tests/Rector/Visibility/ChangeConstantVisibilityRector/Correct/correct.php.inc
tests/Rector/Visibility/ChangeConstantVisibilityRector/Source/ParentObject.php
tests/Rector/Visibility/ChangeConstantVisibilityRector/Wrong/wrong.php.inc
tests/Rector/Visibility/ChangeConstantVisibilityRector/config.yml

[Rector] Add ChangeConstantVisibilityRector

---

docs/AllRectorsOverview.md
phpstan.neon
src/Configuration/Option.php
src/Console/Command/DescribeCommand.php
src/Console/Command/ProcessCommand.php
src/Console/Output/DescribeCommandReporter.php
src/Guard/RectorGuard.php

Add dynamic Rector to DescribeCommand

---

README.md
composer.json
config/level/all.yml
docs/AllRectorsOverview.md
phpstan.neon
src/Console/Command/DescribeCommand.php
src/Console/Output/DescribeCommandReporter.php

Various DescribeCommand improvements

---

packages/Symfony/src/Bridge/DefaultAnalyzedSymfonyApplicationContainer.php
packages/Symfony/src/Rector/FrameworkBundle/GetToConstructorInjectionRector.php
packages/Symfony/tests/Rector/FrameworkBundle/AbstractToConstructorInjectionRectorSource/SomeKernelClass.php
packages/Symfony/tests/Rector/FrameworkBundle/AbstractToConstructorInjectionRectorSource/SomeTranslator.php
packages/Symfony/tests/Rector/FrameworkBundle/ContainerGetToConstructorInjectionRector/Correct/correct2.php.inc
packages/Symfony/tests/Rector/FrameworkBundle/GetToConstructorInjectionRector/Correct/correct3.php.inc
packages/Symfony/tests/Rector/FrameworkBundle/GetToConstructorInjectionRector/Correct/correct4.php.inc
phpstan.neon
src/Naming/PropertyNaming.php

Fix interface suffix property naming, resolve to parent interface if not accessible

---

config/level/guzzle/guzzle50.yml
src/Builder/MethodCall/ClearedFluentMethodCollector.php
src/Rector/MethodBody/FluentReplaceRector.php
src/Rector/MethodBody/ReturnThisRemoveRector.php
tests/Rector/MethodBody/FluentReplaceRector/Correct/correct2.php.inc
tests/Rector/MethodBody/FluentReplaceRector/Correct/correct3.php.inc
tests/Rector/MethodBody/FluentReplaceRector/FluentReplaceRectorTest.php
tests/Rector/MethodBody/FluentReplaceRector/Wrong/wrong2.php.inc
tests/Rector/MethodBody/FluentReplaceRector/Wrong/wrong3.php.inc
tests/Rector/MethodBody/FluentReplaceRector/config.yml

Decouple ReturnThisRemoveRector

---

bin/rector-prefixed/template/.travis.yml
scoper.inc.php

Fixes:
- https://travis-ci.org/rectorphp/rector-prefixed/jobs/416865143#L504
- https://travis-ci.org/rectorphp/rector-prefixed/jobs/416865143#L518

remove AbstractRectorTestCase.php from prefixed scope

---

README.md
composer.json
config/level/guzzle/guzzle50.yml
packages/NodeTypeResolver/src/DependencyInjection/NodeTypeResolverKernel.php
packages/NodeTypeResolver/src/config/services.yml
phpstan.neon
src/Autoloading/AdditionalAutoloader.php
src/Console/Output/ProcessCommandReporter.php
src/FileSystem/FilesFinder.php
src/config/config.yml
tests/AbstractConfigurableContainerAwareTestCase.php
tests/FileSystem/FilesFinder/ExcludePaths/ExcludePathsTest.php
tests/FileSystem/FilesFinder/ExcludePaths/Source/ShouldBeExcluded/FileWithMissingClass.php
tests/FileSystem/FilesFinder/ExcludePaths/Source/ThisShouldBeHere.php
tests/FileSystem/FilesFinder/ExcludePaths/config/config-with-excluded-paths.yml
tests/Printer/BetterStandardPrinterTest.php

Add "exclude_paths" parameter to exclude unwanted files/directories

---

ecs.yml
src/Application/Error.php
src/Console/Command/GenerateRectorOverviewCommand.php
src/Console/Command/LevelsCommand.php
src/Console/Command/ProcessCommand.php
src/Console/Output/ProcessCommandReporter.php
src/Console/Shell.php
src/config/services.yml

Ref: https://github.com/rectorphp/rector/issues/619#issuecomment-421799657
<br><br><br>
What do you think @dereuromark ?

make error on process non-blocking

---

README.md
composer.json
packages/ParameterGuider/config/config.yml
packages/ParameterGuider/src/Exception/ParameterTypoException.php
packages/ParameterGuider/src/ParameterGuider.php
packages/ParameterGuider/tests/ParameterGuiderTest.php
packages/ParameterGuider/tests/config.yml
src/Autoloading/AdditionalAutoloader.php
src/Console/Command/ProcessCommand.php
src/DependencyInjection/ContainerFactory.php
src/config/config.yml
src/config/external-services.yml
src/config/services.yml

Add ParameterGuide

---

.travis.yml
config/level/cakephp/cakephp34.yml
config/level/cakephp/cakephp35.yml

Complete CakePHP 3.5 upgrade set

---

config/level/php/php71.yml
config/level/php/php73.yml
packages/Php/config/config.yml
packages/Php/config/services.yml
packages/Php/src/DualCheckToAble.php
packages/Php/src/Rector/IsCountableRector.php
packages/Php/src/Rector/IsIterableRector.php
packages/Php/tests/Rector/IsCountableRector/Correct/correct.php.inc
packages/Php/tests/Rector/IsCountableRector/IsCountableRectorTest.php
packages/Php/tests/Rector/IsCountableRector/Wrong/wrong.php.inc
packages/Php/tests/Rector/IsCountableRector/config.yml
packages/Php/tests/Rector/IsIterableRector/Correct/correct.php.inc
packages/Php/tests/Rector/IsIterableRector/IsIterableRectorTest.php
packages/Php/tests/Rector/IsIterableRector/Wrong/wrong.php.inc
packages/Php/tests/Rector/IsIterableRector/config.yml

[PHP] Add iterable and countable Rectors

---

packages/Php/src/Rector/ExceptionHandlerTypehintRector.php
packages/Php/src/Rector/TernaryToNullCoalescingRector.php
packages/Php/tests/Rector/TernaryToNullCoalescingRector/Correct/correct.php.inc
packages/Php/tests/Rector/TernaryToNullCoalescingRector/Correct/correct2.php.inc
packages/Php/tests/Rector/TernaryToNullCoalescingRector/Correct/correct3.php.inc
packages/Php/tests/Rector/TernaryToNullCoalescingRector/Correct/correct4.php.inc
packages/Php/tests/Rector/TernaryToNullCoalescingRector/TernaryToNullCoalescingRectorTest.php
packages/Php/tests/Rector/TernaryToNullCoalescingRector/Wrong/wrong.php.inc
packages/Php/tests/Rector/TernaryToNullCoalescingRector/Wrong/wrong2.php.inc
packages/Php/tests/Rector/TernaryToNullCoalescingRector/Wrong/wrong3.php.inc
packages/Php/tests/Rector/TernaryToNullCoalescingRector/Wrong/wrong4.php.inc
packages/Php/tests/Rector/TernaryToNullCoalescingRector/config.yml

[Php] Add TernaryToNullCoalescingRector

---

config/level/php/php70.yml
packages/Php/src/Rector/PublicConstantVisibilityRector.php
packages/Php/src/Rector/RandomFunctionRector.php
packages/Php/tests/Rector/PublicConstantVisibilityRector/Correct/correct.php.inc
packages/Php/tests/Rector/PublicConstantVisibilityRector/PublicConstantVisibilityRectorTest.php
packages/Php/tests/Rector/PublicConstantVisibilityRector/Wrong/SomeClass.php
packages/Php/tests/Rector/PublicConstantVisibilityRector/config.yml
packages/Php/tests/Rector/RandomFunctionRector/Correct/correct.php.inc
packages/Php/tests/Rector/RandomFunctionRector/RandomFunctionRectorTest.php
packages/Php/tests/Rector/RandomFunctionRector/Wrong/wrong.php.inc
packages/Php/tests/Rector/RandomFunctionRector/config.yml

[Php] Add PublicCnstantRector 

---

README.md
config/level/php/php72.yml
packages/Php/src/Rector/Each/ListEachRector.php
packages/Php/src/Rector/Each/WhileEachToForeachRector.php
packages/Php/tests/Rector/Each/Correct/correct.php.inc
packages/Php/tests/Rector/Each/Correct/correct2.php.inc
packages/Php/tests/Rector/Each/Correct/correct3.php.inc
packages/Php/tests/Rector/Each/EachRectorTest.php
packages/Php/tests/Rector/Each/Wrong/wrong.php.inc
packages/Php/tests/Rector/Each/Wrong/wrong2.php.inc
packages/Php/tests/Rector/Each/Wrong/wrong3.php.inc
packages/Php/tests/Rector/Each/config.yml

[PHP] Add EachRector

---

config/level/php/php70.yml
ecs.yml
packages/NodeTypeResolver/src/NodeTypeAnalyzer.php
packages/NodeTypeResolver/src/PerNodeTypeResolver/VariableTypeResolver.php
packages/Php/src/Rector/Each/ListEachRector.php
packages/Php/src/Rector/List_/ListSplitStringRector.php
packages/Php/tests/Rector/List_/ListSplitStringRector/Correct/correct.php.inc
packages/Php/tests/Rector/List_/ListSplitStringRector/ListSplitStringRectorTest.php
packages/Php/tests/Rector/List_/ListSplitStringRector/Wrong/wrong.php.inc
packages/Php/tests/Rector/List_/ListSplitStringRector/config.yml
phpstan.neon

[PHP] string split

---

config/level/php/php71.yml
packages/Php/src/Rector/TryCatch/MultiExceptionCatchRector.php
packages/Php/tests/Rector/TryCatch/MultiExceptionCatchRector/Correct/correct.php.inc
packages/Php/tests/Rector/TryCatch/MultiExceptionCatchRector/MultiExceptionCatchRectorTest.php
packages/Php/tests/Rector/TryCatch/MultiExceptionCatchRector/Wrong/wrong.php.inc
packages/Php/tests/Rector/TryCatch/MultiExceptionCatchRector/config.yml
phpstan.neon

 [PHP] Add MultiExceptionCatchRector

---

composer.json
config/level/php/php71.yml
packages/NodeTypeResolver/src/NodeTypeAnalyzer.php
packages/Php/src/Rector/FuncCall/CountOnNullRector.php
packages/Php/tests/Rector/FuncCall/CountOnNullRector/Correct/correct.php.inc
packages/Php/tests/Rector/FuncCall/CountOnNullRector/Correct/correct2.php.inc
packages/Php/tests/Rector/FuncCall/CountOnNullRector/Correct/correct3.php.inc
packages/Php/tests/Rector/FuncCall/CountOnNullRector/Correct/correct4.php.inc
packages/Php/tests/Rector/FuncCall/CountOnNullRector/CountOnNullRectorTest.php
packages/Php/tests/Rector/FuncCall/CountOnNullRector/Source/CountableClass.php
packages/Php/tests/Rector/FuncCall/CountOnNullRector/Wrong/wrong.php.inc
packages/Php/tests/Rector/FuncCall/CountOnNullRector/Wrong/wrong2.php.inc
packages/Php/tests/Rector/FuncCall/CountOnNullRector/Wrong/wrong3.php.inc
packages/Php/tests/Rector/FuncCall/CountOnNullRector/Wrong/wrong4.php.inc
packages/Php/tests/Rector/FuncCall/CountOnNullRector/config.yml
phpstan.neon

 [PHP] Add CountOnNullRector

---

config/level/php/php73.yml
packages/Php/src/Rector/ConstFetch/SensitiveConstantNameRector.php
packages/Php/src/Rector/FuncCall/SensitiveDefineRector.php
packages/Php/tests/Rector/ConstFetch/SensitiveConstantNameRector/Correct/correct.php.inc
packages/Php/tests/Rector/ConstFetch/SensitiveConstantNameRector/SensitiveConstantNameRectorTest.php
packages/Php/tests/Rector/ConstFetch/SensitiveConstantNameRector/Wrong/wrong.php.inc
packages/Php/tests/Rector/ConstFetch/SensitiveConstantNameRector/config.yml
packages/Php/tests/Rector/FuncCall/SensitiveDefineRector/Correct/correct.php.inc
packages/Php/tests/Rector/FuncCall/SensitiveDefineRector/SensitiveDefineRectorTest.php
packages/Php/tests/Rector/FuncCall/SensitiveDefineRector/Wrong/wrong.php.inc
packages/Php/tests/Rector/FuncCall/SensitiveDefineRector/config.yml
src/DependencyInjection/Loader/ClassExistenceValidator.php
src/DependencyInjection/Loader/TolerantRectorYamlFileLoader.php
src/Exception/DependencyInjection/ClassNotFoundException.php

[Php] Add sensitive constant Rectors

---

composer.json
phpstan.neon
src/Rector/CodeQuality/CombinedAssignRector.php
tests/Rector/CodeQuality/CombinedAssignRector/CombinedAssignRectorTest.php
tests/Rector/CodeQuality/CombinedAssignRector/Correct/correct.php.inc
tests/Rector/CodeQuality/CombinedAssignRector/Correct/correct2.php.inc
tests/Rector/CodeQuality/CombinedAssignRector/Wrong/wrong.php.inc
tests/Rector/CodeQuality/CombinedAssignRector/Wrong/wrong2.php.inc
tests/Rector/CodeQuality/CombinedAssignRector/config.yml

[CodeQuality] Add CombinedAssignRector

---

src/Rector/CodeQuality/GetClassToInstanceOfRector.php
tests/Rector/CodeQuality/GetClassToInstanceOfRector/Correct/correct.php.inc
tests/Rector/CodeQuality/GetClassToInstanceOfRector/GetClassToInstanceOfRectorTest.php
tests/Rector/CodeQuality/GetClassToInstanceOfRector/Wrong/wrong.php.inc
tests/Rector/CodeQuality/GetClassToInstanceOfRector/config.yml

[CodeQuality] Add GetClassToInstanceOfRector

---

src/NodeAnalyzer/ConstFetchAnalyzer.php
src/NodeAnalyzer/FuncCallAnalyzer.php
src/Rector/CodeQuality/SimplifyArraySearchRector.php
src/Rector/CodeQuality/SimplifyConditionsRector.php
tests/Rector/CodeQuality/SimplifyArraySearchRector/Correct/correct.php.inc
tests/Rector/CodeQuality/SimplifyArraySearchRector/SimplifyArraySearchRectorTest.php
tests/Rector/CodeQuality/SimplifyArraySearchRector/Wrong/wrong.php.inc
tests/Rector/CodeQuality/SimplifyArraySearchRector/config.yml

[CodeQuality] Add SimplifyArraySearchRector

---

src/Rector/CodeQuality/SimplifyFuncGetArgsCountRector.php
tests/Rector/CodeQuality/SimplifyFuncGetArgsCountRector/Correct/correct.php.inc
tests/Rector/CodeQuality/SimplifyFuncGetArgsCountRector/SimplifyFuncGetArgsCountRectorTest.php
tests/Rector/CodeQuality/SimplifyFuncGetArgsCountRector/Wrong/wrong.php.inc
tests/Rector/CodeQuality/SimplifyFuncGetArgsCountRector/config.yml

[CodeQuality] Add SimplifyFuncGetArgsCountRector

---

composer.json
create-rector.yml
ecs.yml
packages/ContributorTools/config/config.yml
packages/ContributorTools/config/services.yml
packages/ContributorTools/src/Command/CreateRectorCommand.php
packages/ContributorTools/src/Configuration/Configuration.php
packages/ContributorTools/src/Configuration/ConfigurationFactory.php
packages/ContributorTools/src/Exception/ConfigurationException.php
packages/ContributorTools/templates/packages/_Package_/src/Rector/_Category_/_Name_.php
packages/ContributorTools/templates/packages/_Package_/tests/Rector/_Category_/_Name_/Correct/correct.php.inc
packages/ContributorTools/templates/packages/_Package_/tests/Rector/_Category_/_Name_/Wrong/wrong.php.inc
packages/ContributorTools/templates/packages/_Package_/tests/Rector/_Category_/_Name_/_Name_Test.php
packages/ContributorTools/templates/packages/_Package_/tests/Rector/_Category_/_Name_/config.yml
phpstan.neon

Closes #683
1. Create `create-rector.yml`
```yaml
package: 'CodeQuality'
name: 'SimplifyConfigRector' # w/wo suffix
node_types:
- 'FuncCall'
description: 'It adds man to hi'
code_before: 'hi'
code_after: 'hi man'
```
2. Run 
```
bin/rector create-rector
```
3. Update Rector code to make test pass

[ContributorTools] Add CreateRectorCommand

---

src/NodeAnalyzer/MethodCallAnalyzer.php
src/Rector/Assign/PropertyAssignToMethodCallRector.php
src/Rector/Constant/RenameClassConstantsUseToStringsRector.php
src/Rector/MethodCall/MethodCallToAnotherMethodCallWithArgumentsRector.php
tests/Rector/Assign/PropertyAssignToMethodCallRector/config.yml
tests/Rector/Constant/RenameClassConstantsUseToStringsRector/config.yml
tests/Rector/MethodCall/MethodCallToAnotherMethodCallWithArgumentsRector/config.yml

Unite configuration

---

config/level/code-quality/code-quality.yml

These new Rector were added in #684, #682, #681, #677 and #676

[CodeQuality] Add missing rectors

---

packages/CodeQuality/src/Rector/FuncCall/SimplifyArrayCallableRector.php
packages/CodeQuality/tests/Rector/FuncCall/SimplifyArrayCallableRector/Correct/correct.php.inc
packages/CodeQuality/tests/Rector/FuncCall/SimplifyArrayCallableRector/SimplifyArrayCallableRectorTest.php
packages/CodeQuality/tests/Rector/FuncCall/SimplifyArrayCallableRector/Wrong/wrong.php.inc
packages/CodeQuality/tests/Rector/FuncCall/SimplifyArrayCallableRector/config.yml
packages/ContributorTools/src/Command/CreateRectorCommand.php
packages/ContributorTools/templates/packages/_Package_/src/Rector/_Category_/_Name_.php
packages/Sylius/src/Rector/Review/ReplaceCreateMethodWithoutReviewerRector.php

[CodeQuality] Add SimplifyArrayCallableRector

---

packages/CodeQuality/src/Rector/Switch_/SimplifyBinarySwitchRector.php
packages/CodeQuality/tests/Rector/Switch_/SimplifyBinarySwitchRector/Correct/correct.php.inc
packages/CodeQuality/tests/Rector/Switch_/SimplifyBinarySwitchRector/SimplifyBinarySwitchRectorTest.php
packages/CodeQuality/tests/Rector/Switch_/SimplifyBinarySwitchRector/Wrong/wrong.php.inc
packages/CodeQuality/tests/Rector/Switch_/SimplifyBinarySwitchRector/config.yml
packages/ContributorTools/src/Configuration/ConfigurationFactory.php

[CodeQuality] Add SimplifyBinarySwitchRector

---

packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockAnalyzer.php
packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/FqnAnnotationTypeDecorator.php
src/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector.php
tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Correct/correct7.php.inc
tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/JmsRectorTest.php
tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Wrong/wrong7.php.inc
tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/jms-config.yml

Ref #700 
@bendavies Check this

 Add class-based annotation support to AnnotatedPropertyInject... Rector

---

config/level/php/php73.yml
packages/ContributorTools/src/Command/CreateRectorCommand.php
packages/Php/src/Rector/FuncCall/StringifyStrNeedlesRector.php
packages/Php/tests/Rector/FuncCall/StringifyStrNeedlesRector/Correct/correct.php.inc
packages/Php/tests/Rector/FuncCall/StringifyStrNeedlesRector/StringifyStrNeedlesRectorTest.php
packages/Php/tests/Rector/FuncCall/StringifyStrNeedlesRector/Wrong/wrong.php.inc
packages/Php/tests/Rector/FuncCall/StringifyStrNeedlesRector/config.yml

[PHP] Add StringifyStrNeedlesRector

---

config/level/php/php73.yml
packages/ContributorTools/src/Command/CreateRectorCommand.php
packages/ContributorTools/src/Configuration/Configuration.php
packages/ContributorTools/src/Configuration/ConfigurationFactory.php
packages/ContributorTools/templates/packages/_Package_/src/Rector/_Category_/_Name_.php
packages/Php/src/Rector/FuncCall/JsonThrowOnErrorRector.php
packages/Php/tests/Rector/FuncCall/JsonThrowOnErrorRector/Correct/correct.php.inc
packages/Php/tests/Rector/FuncCall/JsonThrowOnErrorRector/JsonThrowOnErrorRectorTest.php
packages/Php/tests/Rector/FuncCall/JsonThrowOnErrorRector/Wrong/wrong.php.inc
packages/Php/tests/Rector/FuncCall/JsonThrowOnErrorRector/config.yml

[PHP] Add JsonThrowOnErrorRector

---

config/level/php/php73.yml
packages/ContributorTools/src/Command/CreateRectorCommand.php
packages/Php/src/Rector/FuncCall/TrailingCommaArgumentsRector.php
packages/Php/tests/Rector/FuncCall/TrailingCommaArgumentsRector/Correct/correct.php.inc
packages/Php/tests/Rector/FuncCall/TrailingCommaArgumentsRector/TrailingCommaArgumentsRectorTest.php
packages/Php/tests/Rector/FuncCall/TrailingCommaArgumentsRector/Wrong/wrong.php.inc
packages/Php/tests/Rector/FuncCall/TrailingCommaArgumentsRector/config.yml
src/Printer/BetterStandardPrinter.php
src/config/external-services.yml

[PHP] Add TrailingCommaArgumentsRector

---

config/level/symfony/symfony30.yml
packages/Symfony/src/Rector/MethodCall/CascadeValidationFormBuilderRector.php
packages/Symfony/src/Rector/MethodCall/ReadOnlyOptionToAttributeRector.php
packages/Symfony/tests/Rector/MethodCall/CascadeValidationFormBuilderRector/CascadeValidationFormBuilderRectorTest.php
packages/Symfony/tests/Rector/MethodCall/CascadeValidationFormBuilderRector/Correct/correct.php.inc
packages/Symfony/tests/Rector/MethodCall/CascadeValidationFormBuilderRector/Wrong/wrong.php.inc
packages/Symfony/tests/Rector/MethodCall/CascadeValidationFormBuilderRector/config.yml
packages/Symfony/tests/Rector/MethodCall/ReadOnlyOptionToAttributeRector/config.yml
src/NodeAnalyzer/ArrayAnalyzer.php

[Symfony] Add ArrayAnalyzer and CascadeValidationFormBuilderRector

---

.coveralls.yml
.travis.yml
README.md

Inverse of https://github.com/rectorphp/rector/pull/585
For measuring coverage on merge

travis: add lowest run

---

docs/AllRectorsOverview.md
packages/CodeQuality/src/Rector/FuncCall/SimplifyEmptyArrayCheckRector.php
packages/CodeQuality/tests/Rector/FuncCall/SimplifyEmptyArrayCheckRector/Correct/correct.php.inc
packages/CodeQuality/tests/Rector/FuncCall/SimplifyEmptyArrayCheckRector/Correct/correct2.php.inc
packages/CodeQuality/tests/Rector/FuncCall/SimplifyEmptyArrayCheckRector/SimplifyEmptyArrayCheckRectorTest.php
packages/CodeQuality/tests/Rector/FuncCall/SimplifyEmptyArrayCheckRector/Wrong/wrong.php.inc
packages/CodeQuality/tests/Rector/FuncCall/SimplifyEmptyArrayCheckRector/Wrong/wrong2.php.inc
packages/CodeQuality/tests/Rector/FuncCall/SimplifyEmptyArrayCheckRector/config.yml

Ref #424 
Prove that the logic isn't changed: https://3v4l.org/nr0NG

[WIP][CodeQuality] Create SimplifyEmptyArrayCheckRector

---

config/level/symfony/symfony42.yml
packages/Symfony/src/Rector/New_/StringToArrayArgumentProcessRector.php
packages/Symfony/tests/Rector/New_/StringToArrayArgumentProcessRector/Correct/correct.php.inc
packages/Symfony/tests/Rector/New_/StringToArrayArgumentProcessRector/Correct/correct2.php.inc
packages/Symfony/tests/Rector/New_/StringToArrayArgumentProcessRector/Source/Process.php
packages/Symfony/tests/Rector/New_/StringToArrayArgumentProcessRector/Source/ProcessHelper.php
packages/Symfony/tests/Rector/New_/StringToArrayArgumentProcessRector/StringToArrayArgumentProcessRectorTest.php
packages/Symfony/tests/Rector/New_/StringToArrayArgumentProcessRector/Wrong/wrong.php.inc
packages/Symfony/tests/Rector/New_/StringToArrayArgumentProcessRector/Wrong/wrong2.php.inc
packages/Symfony/tests/Rector/New_/StringToArrayArgumentProcessRector/config.yml
src/Node/NodeFactory.php

[Symfony] Add ArrayArgumentProcessRector

---

config/level/symfony/symfony42.yml
packages/Symfony/src/Rector/New_/RootNodeTreeBuilderRector.php
packages/Symfony/tests/Rector/New_/RootNodeTreeBuilderRector/Correct/correct.php.inc
packages/Symfony/tests/Rector/New_/RootNodeTreeBuilderRector/Correct/correct2.php.inc
packages/Symfony/tests/Rector/New_/RootNodeTreeBuilderRector/RootNodeTreeBuilderRectorTest.php
packages/Symfony/tests/Rector/New_/RootNodeTreeBuilderRector/Source/TreeBuilder.php
packages/Symfony/tests/Rector/New_/RootNodeTreeBuilderRector/Wrong/wrong.php.inc
packages/Symfony/tests/Rector/New_/RootNodeTreeBuilderRector/Wrong/wrong2.php.inc
packages/Symfony/tests/Rector/New_/RootNodeTreeBuilderRector/config.yml

[Symfony] Add RootNodeTreeBuilderRector

---

packages/Php/tests/Rector/FuncCall/CountOnNullRector/Correct/correct6.php.inc
packages/Php/tests/Rector/FuncCall/CountOnNullRector/CountOnNullRectorTest.php
packages/Php/tests/Rector/FuncCall/CountOnNullRector/Wrong/wrong6.php.inc
src/Rector/TypeAnalyzerTrait.php

Fix CountOnNullRector for array typehint

---

bin/rector
src/Console/Style/SymfonyStyleFactory.php
src/config/external-services.yml

Ref https://github.com/rectorphp/rector/pull/758/files/3c4a110f6a6efbac8f82ddfd3fefd0a16c254c77#r230492402

Add SymfonyStyleFactory to remove memory-lock dependency on Application run()

---

ecs.yml
packages/CodeQuality/src/Rector/Foreach_/ForeachToInArrayRector.php
packages/CodeQuality/src/Rector/FuncCall/SimplifyEmptyArrayCheckRector.php
packages/CodeQuality/src/Rector/If_/SimplifyIfReturnBoolRector.php
packages/CodeQuality/tests/Rector/Foreach_/ForeachToInArrayRector/Correct/correct2.php.inc
packages/CodeQuality/tests/Rector/Foreach_/ForeachToInArrayRector/Correct/correct3.php.inc
packages/CodeQuality/tests/Rector/Foreach_/ForeachToInArrayRector/ForeachToInArrayRectorTest.php
packages/CodeQuality/tests/Rector/Foreach_/ForeachToInArrayRector/Wrong/wrong2.php.inc
packages/CodeQuality/tests/Rector/Foreach_/ForeachToInArrayRector/Wrong/wrong3.php.inc
packages/CodeQuality/tests/Rector/FuncCall/SimplifyEmptyArrayCheckRector/Correct/correct2.php.inc
packages/CodeQuality/tests/Rector/FuncCall/SimplifyEmptyArrayCheckRector/Wrong/wrong2.php.inc
packages/CodeQuality/tests/Rector/If_/SimplifyIfReturnBoolRector/Correct/correct8.php.inc
packages/CodeQuality/tests/Rector/If_/SimplifyIfReturnBoolRector/SimplifyIfReturnBoolRectorTest.php
packages/CodeQuality/tests/Rector/If_/SimplifyIfReturnBoolRector/Wrong/wrong8.php.inc

fix SimplifyIfReturnBoolRector

---

packages/CodeQuality/src/Rector/Foreach_/ForeachToInArrayRector.php
packages/CodeQuality/src/Rector/FuncCall/SimplifyEmptyArrayCheckRector.php
packages/CodeQuality/src/Rector/Identical/SimplifyConditionsRector.php
packages/CodeQuality/tests/Rector/FuncCall/SimplifyEmptyArrayCheckRector/Correct/correct.php.inc
packages/CodeQuality/tests/Rector/FuncCall/SimplifyEmptyArrayCheckRector/Correct/correct2.php.inc
packages/CodeQuality/tests/Rector/FuncCall/SimplifyEmptyArrayCheckRector/Correct/correct3.php.inc
packages/CodeQuality/tests/Rector/FuncCall/SimplifyEmptyArrayCheckRector/Wrong/wrong.php.inc
packages/CodeQuality/tests/Rector/FuncCall/SimplifyEmptyArrayCheckRector/Wrong/wrong2.php.inc
packages/CodeQuality/tests/Rector/FuncCall/SimplifyEmptyArrayCheckRector/Wrong/wrong3.php.inc
packages/Php/src/DualCheckToAble.php
src/PhpParser/Node/Maintainer/BinaryOpMaintainer.php

See https://github.com/laravel/framework/pull/26413#discussion_r231412580

fix SimplifyEmptyArrayCheckRector for not empty non-arrays

---

packages/Php/src/Rector/FunctionLike/ExceptionHandlerTypehintRector.php
packages/Php/tests/Rector/FunctionLike/ExceptionHandlerTypehintRector/Correct/correct_nullable.php.inc
packages/Php/tests/Rector/FunctionLike/ExceptionHandlerTypehintRector/ExceptionHandlerTypehintRectorTest.php
packages/Php/tests/Rector/FunctionLike/ExceptionHandlerTypehintRector/Wrong/wrong_nullable.php.inc

Includes failing test and fix
Fixes #789

ExceptionHandlerTypehintRector fails on nullable parameters

---

composer.json
src/CodingStyle/AfterRectorCodingStyle.php

And allow own cs tools
As suggested by @carusogabriel

make ECS optional dependency to reduce amount of installed packages

---

packages/Php/tests/Rector/FunctionLike/ParamAndReturnScalarTypehintsRector/Integration/nikic/anon_class.php.inc
src/DependencyInjection/Loader/TolerantRectorYamlFileLoader.php
src/PhpParser/Node/Commander/NodeAddingCommander.php
src/PhpParser/Node/Commander/NodeRemovingCommander.php
src/PhpParser/Node/Commander/PropertyAddingCommander.php
src/PhpParser/NodeTraverser/CallableNodeTraverser.php
src/PhpParser/Printer/BetterStandardPrinter.php

Ref https://github.com/nikic/PHP-Parser/issues/554

Compat fix

---

packages/NodeTypeResolver/src/NodeTypeAnalyzer.php
packages/Php/src/Rector/FuncCall/CountOnNullRector.php
packages/Php/tests/Rector/FuncCall/CountOnNullRector/CountOnNullRectorTest.php
packages/Php/tests/Rector/FuncCall/CountOnNullRector/Integration/preg_match_array.php.inc
src/PhpParser/Node/Resolver/NameResolver.php

fix preg_match-made array type

---

ecs.yml
packages/Symfony/src/Rector/New_/StringToArrayArgumentProcessRector.php
packages/Symfony/tests/Rector/New_/StringToArrayArgumentProcessRector/Fixture/fixture.php.inc
packages/Symfony/tests/Rector/New_/StringToArrayArgumentProcessRector/Fixture/fixture3.php.inc
packages/Symfony/tests/Rector/New_/StringToArrayArgumentProcessRector/Fixture/fixture4.php.inc
packages/Symfony/tests/Rector/New_/StringToArrayArgumentProcessRector/StringToArrayArgumentProcessRectorTest.php
phpstan.neon
src/PhpParser/NodeTransformer.php
src/Rector/NodeFactoryTrait.php
src/Util/RectorStrings.php

Symfony 4.2 process change

---

packages/NodeTypeResolver/src/Application/ClassLikeNodeCollector.php
packages/NodeTypeResolver/src/NodeVisitor/ClassLikeNodeCollectorNodeVisitor.php
packages/Php/src/Rector/FunctionLike/ParamScalarTypehintRector.php
packages/Php/src/Rector/FunctionLike/ReturnScalarTypehintRector.php
packages/Php/tests/Rector/FunctionLike/ParamAndReturnScalarTypehintsRector/Fixture/trait_interface.php.inc
packages/Php/tests/Rector/FunctionLike/ParamAndReturnScalarTypehintsRector/ParamAndReturnScalarTypehintsRectorTest.php
src/PhpParser/Node/Maintainer/ClassMaintainer.php

Testing *ScalarTypehintsRector on Symfony #3

---

src/Application/RectorApplication.php
src/Rector/AbstractRector.php
src/Rector/MethodCall/MethodNameReplacerRector.php
src/Testing/PHPUnit/AbstractRectorTestCase.php

Improve --debug reporting, fix MethodNameReplacerRector

---

config/level/phpunit/phpunit80.yml
packages/CodeQuality/tests/Rector/Assign/CombinedAssignRector/config.yml
packages/ContributorTools/src/Configuration/ConfigurationFactory.php
packages/ContributorTools/src/TemplateVariablesFactory.php
packages/ContributorTools/templates/packages/_Package_/tests/Rector/_Category_/_Name_/Fixture/fixture.php.inc
packages/PHPUnit/src/Rector/ExceptionAnnotationRector.php
packages/PHPUnit/src/Rector/MethodCall/AssertEqualsParameterToSpecificMethodsTypeRector.php
packages/PHPUnit/src/Rector/MethodCall/SpecificAssertContainsRector.php
packages/PHPUnit/src/Rector/MethodCall/SpecificAssertInternalTypeRector.php
packages/PHPUnit/tests/Rector/MethodCall/AssertEqualsParameterToSpecificMethodsTypeRector/AssertEqualsParameterToSpecificMethodsTypeRectorTest.php
packages/PHPUnit/tests/Rector/MethodCall/AssertEqualsParameterToSpecificMethodsTypeRector/Fixture/combination.php.inc
packages/PHPUnit/tests/Rector/MethodCall/AssertEqualsParameterToSpecificMethodsTypeRector/Fixture/refactor_canonize.php.inc
packages/PHPUnit/tests/Rector/MethodCall/AssertEqualsParameterToSpecificMethodsTypeRector/Fixture/refactor_delta.php.inc
packages/PHPUnit/tests/Rector/MethodCall/AssertEqualsParameterToSpecificMethodsTypeRector/Fixture/refactor_ignore_case.php.inc
packages/PHPUnit/tests/Rector/MethodCall/AssertEqualsParameterToSpecificMethodsTypeRector/Fixture/remove_max_depth.php.inc
packages/PHPUnit/tests/Rector/MethodCall/AssertEqualsParameterToSpecificMethodsTypeRector/config.yml
packages/PHPUnit/tests/Rector/MethodCall/SpecificAssertContainsRector/Fixture/fixture.php.inc
packages/PHPUnit/tests/Rector/MethodCall/SpecificAssertContainsRector/SpecificAssertContainsRectorTest.php
packages/PHPUnit/tests/Rector/MethodCall/SpecificAssertContainsRector/config.yml
packages/PHPUnit/tests/Rector/MethodCall/SpecificAssertInternalTypeRector/Fixture/fixture.php.inc
packages/PHPUnit/tests/Rector/MethodCall/SpecificAssertInternalTypeRector/SpecificAssertInternalTypeRectorTest.php
packages/PHPUnit/tests/Rector/MethodCall/SpecificAssertInternalTypeRector/config.yml
packages/Php/tests/Rector/FunctionLike/ParamAndReturnScalarTypehintsRector/Fixture/complex_array.php.inc
packages/Php/tests/Rector/FunctionLike/ParamAndReturnScalarTypehintsRector/Fixture/dunglas/type_aliases_and_whitelisting.php.inc
src/CodingStyle/AfterRectorCodingStyle.php
src/Php/TypeAnalyzer.php

Add PHPUnit 8.0 changes

---

.gitattributes
.gitignore

Resolves https://github.com/rectorphp/rector/issues/791

Add gitattributes file

---

packages/CodeQuality/src/Rector/Ternary/UnnecessaryTernaryExpressionRector.php
packages/CodeQuality/tests/Rector/Ternary/UnnecessaryTernaryExpressionRector/Fixture/fixture.php.inc
packages/CodeQuality/tests/Rector/Ternary/UnnecessaryTernaryExpressionRector/Fixture/fixture3.php.inc
packages/CodeQuality/tests/Rector/Ternary/UnnecessaryTernaryExpressionRector/Fixture/fixture4.php.inc
packages/CodeQuality/tests/Rector/Ternary/UnnecessaryTernaryExpressionRector/UnnecessaryTernaryExpressionRectorTest.php

Covers https://github.com/slevomat/coding-standard/issues/556#issue-381595647

Improve CodeQuality for Binary conditions

---

config/level/code-quality/code-quality.yml
create-rector.yml.dist
packages/CodeQuality/src/Rector/BinaryOp/SimplifyDeMorganBinaryRector.php
packages/CodeQuality/tests/Rector/BinaryOp/SimplifyDeMorganBinaryRector/Fixture/fixture.php.inc
packages/CodeQuality/tests/Rector/BinaryOp/SimplifyDeMorganBinaryRector/SimplifyDeMorganBinaryRectorTest.php
packages/CodeQuality/tests/Rector/If_/SimplifyIfReturnBoolRector/SimplifyIfReturnBoolRectorTest.php

[CodeQuality] Add SimplifyDeMorganBinaryRector

---

README.md

`rector:latest` is not available. You have to use `rector/rector:latest`

Adjust docker image name

---

bin/rector
src/Application/RectorApplication.php
src/Console/Application.php
src/Console/Command/AbstractCommand.php
src/Console/Command/GenerateRectorOverviewCommand.php
src/Console/Command/LevelsCommand.php
src/Console/Command/ProcessCommand.php
src/DependencyInjection/RectorKernel.php
src/EventDispatcher/AutowiredEventDispatcher.php
src/FileSystem/FilesFinder.php
src/config/external-services.yml
src/config/services.yml

Console usage UX improvements

---

packages/Php/src/Rector/FuncCall/RemoveExtraParametersRector.php
packages/Php/tests/Rector/FuncCall/RemoveExtraParametersRector/Fixture/better_func_get_all.php.inc
packages/Php/tests/Rector/FuncCall/RemoveExtraParametersRector/Fixture/external_scope.php.inc
packages/Php/tests/Rector/FuncCall/RemoveExtraParametersRector/Fixture/static_calls.php.inc
packages/Php/tests/Rector/FuncCall/RemoveExtraParametersRector/RemoveExtraParametersRectorTest.php
packages/Php/tests/Rector/FuncCall/RemoveExtraParametersRector/Source/MethodWithFuncGetArgs.php
phpstan.neon
src/PhpParser/Node/Maintainer/CallMaintainer.php

Fix RemoveExtraParametersRector for variadic external func

---

packages/NodeTypeResolver/src/NodeTypeAnalyzer.php
packages/NodeTypeResolver/src/Php/AbstractTypeInfo.php
packages/NodeTypeResolver/src/Php/VarTypeInfo.php
packages/NodeTypeResolver/src/StaticTypeToStringResolver.php
packages/Php/src/Rector/Property/CompleteVarDocTypePropertyRector.php
packages/Php/tests/Rector/FunctionLike/ParamAndReturnTypeDeclarationRector/Fixture/known_static.php.inc
packages/Php/tests/Rector/FunctionLike/ParamAndReturnTypeDeclarationRector/Fixture/known_static_conflicts.php.inc
packages/Php/tests/Rector/FunctionLike/ParamAndReturnTypeDeclarationRector/ParamAndReturnTypeDeclarationRectorTest.php
packages/Php/tests/Rector/Property/CompleteVarDocTypePropertyRector/CompleteVarDocTypePropertyRectorTest.php
packages/Php/tests/Rector/Property/CompleteVarDocTypePropertyRector/Fixture/assign_conflict.php.inc
packages/Php/tests/Rector/Property/CompleteVarDocTypePropertyRector/Fixture/callable_type.php.inc
packages/Php/tests/Rector/Property/CompleteVarDocTypePropertyRector/Fixture/default_value.php.inc
packages/Php/tests/Rector/Property/CompleteVarDocTypePropertyRector/Fixture/symfony_console_command.php.inc
packages/Php/tests/Rector/Property/CompleteVarDocTypePropertyRector/Fixture/typed_array.php.inc
packages/Php/tests/Rector/Property/CompleteVarDocTypePropertyRector/Fixture/typed_array_nested.php.inc
src/Php/TypeAnalyzer.php

```diff
final class SomeClass
{
+    /**
+     * @var EventDispatcher
+     */
private $eventDispatcher;
public function __construct(EventDispatcher $eventDispatcher)
{
$this->eventDispatcher = $eventDispatcher;
}
}
```
---
```diff
class TypedArrayNested
{
+    /**
+     * @var int[][]|bool[]
+     */
private $itemsNested;
/**
* @param int[][]|bool[] $itemsNested
*/
public function setItemsNested(array $itemsNested)
{
$this->itemsNested = $itemsNested;
}
}
```

[PHP] var property doc multi types

---

.travis.yml
composer.json
packages/ContributorTools/src/Command/CreateRectorCommand.php
packages/ContributorTools/src/Command/GenerateDocsCommand.php
packages/ContributorTools/src/Exception/Command/ContributorCommandInterface.php
packages/ContributorTools/src/Exception/Command/MaintainerCommandInterface.php
packages/NodeTypeResolver/src/StaticTypeToStringResolver.php
packages/Php/src/Rector/Property/CompleteVarDocTypePropertyRector.php
phpstan.neon
src/Collector/CallableCollectorPopulator.php
src/Console/Application.php
src/Exception/DependencyInjection/CallableCollectorException.php
src/PhpParser/Node/Resolver/NameResolver.php

Based on the idea by @jkuchar with function arg as listening class type, thanks :+1:

Add CallableCollectorPopulator

---

config/level/dead-code/dead-code.yml
packages/ContributorTools/src/TemplateVariablesFactory.php
packages/DeadCode/src/Rector/ClassMethod/RemoveUnusedParameterRector.php
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedParameterRector/Fixture/fixture.php.inc
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedParameterRector/Fixture/order.php.inc
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedParameterRector/Fixture/parent_required.php.inc
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedParameterRector/RemoveUnusedParameterRectorTest.php
packages/NodeTypeResolver/src/NodeTypeAnalyzer.php
src/PhpParser/Node/Maintainer/CallMaintainer.php
src/PhpParser/Node/Maintainer/ClassMethodMaintainer.php
src/PhpParser/Node/Maintainer/PropertyMaintainer.php
src/PhpParser/Printer/BetterStandardPrinter.php
src/Rector/BetterStandardPrinterTrait.php
tests/PhpParser/Printer/BetterStandardPrinterTest.php

[DeadCode] Add RemoveUnusedParameterRector

---

config/level/code-quality/code-quality.yml
packages/CakePHP/tests/Rector/MethodCall/ModalToGetSetRector/ModalToGetSetRectorTest.php
packages/CodeQuality/src/Rector/Foreach_/SimplifyForeachToArrayFilterRector.php
packages/CodeQuality/tests/Rector/Foreach_/SimplifyForeachToArrayFilterRector/Fixture/fixture.php.inc
packages/CodeQuality/tests/Rector/Foreach_/SimplifyForeachToArrayFilterRector/Fixture/skip.php.inc
packages/CodeQuality/tests/Rector/Foreach_/SimplifyForeachToArrayFilterRector/SimplifyForeachToArrayFilterRectorTest.php
utils/phpstan/generate-paths.php

[CodeQuality] Add ForeachToArrayFilter 

---

config/level/code-quality/code-quality.yml
packages/CodeQuality/src/Rector/FuncCall/SingleInArrayToCompareRector.php
packages/CodeQuality/tests/Rector/FuncCall/SingleInArrayToCompareRector/Fixture/fixture.php.inc
packages/CodeQuality/tests/Rector/FuncCall/SingleInArrayToCompareRector/SingleInArrayToCompareRectorTest.php

[CodeQuality] Add SingleInArrayToCompareRector

---

config/level/code-quality/code-quality.yml
create-rector.yml.dist
docs/AllRectorsOverview.md
packages/CodeQuality/src/Rector/If_/SimplifyIfElseToTernaryRector.php
packages/CodeQuality/tests/Rector/If_/SimplifyIfElseToTernaryRector/Fixture/fixture.php.inc
packages/CodeQuality/tests/Rector/If_/SimplifyIfElseToTernaryRector/Fixture/keep.php.inc
packages/CodeQuality/tests/Rector/If_/SimplifyIfElseToTernaryRector/SimplifyIfElseToTernaryRectorTest.php
packages/Php/src/Rector/ConstFetch/BarewordStringRector.php

[CodeQuality] Add SimplifyIfElseToTernaryRector

---

config/level/php/php70.yml
ecs.yml
packages/Php/src/Rector/If_/IfToSpaceshipRector.php
packages/Php/tests/Rector/If_/IfToSpaceshipRector/Fixture/complex.php.inc
packages/Php/tests/Rector/If_/IfToSpaceshipRector/Fixture/fixture.php.inc
packages/Php/tests/Rector/If_/IfToSpaceshipRector/Fixture/skip.php.inc
packages/Php/tests/Rector/If_/IfToSpaceshipRector/IfToSpaceshipRectorTest.php

Closes #872 
```diff
usort($languages, function ($a, $b) {
-    if ($a[0] == $b[0]) {
-        return 0;
-    }
-
-    return ($a[0] < $b[0]) ? 1 : -1;
+    return $b[0] <=> $a[0];
});
```

[PHP 7.3] Add IfToSpaceshipRector

---

config/level/php/mysql_to_mysqli.yml
config/level/php/php70.yml
packages/NodeTypeResolver/src/Application/FunctionLikeNodeCollector.php
packages/Php/src/Rector/If_/IfToSpaceshipRector.php
packages/Php/src/Rector/MethodCall/ThisCallOnStaticMethodToStaticCallRector.php
packages/Php/src/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector.php
packages/Php/tests/Rector/MethodCall/ThisCallOnStaticMethodToStaticCallRector/Fixture/another_call.php.inc
packages/Php/tests/Rector/MethodCall/ThisCallOnStaticMethodToStaticCallRector/Fixture/fixture.php.inc
packages/Php/tests/Rector/MethodCall/ThisCallOnStaticMethodToStaticCallRector/ThisCallOnStaticMethodToStaticCallRectorTest.php
packages/Php/tests/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector/Fixture/fixture.php.inc
packages/Php/tests/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector/Fixture/keep.php.inc
packages/Php/tests/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector/Fixture/with_constructor.php.inc
packages/Php/tests/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector/StaticCallOnNonStaticToInstanceCallRectorTest.php

[PHP] Static call on non static to  instantce call

---

config/level/phpunit/phpunit-mock.yml
docs/AllRectorsOverview.md
packages/PHPUnit/src/Rector/MethodCall/UseSpecificWillMethodRector.php
packages/PHPUnit/tests/Rector/MethodCall/UseSpecificWillMethodRector/Fixture/will.php.inc
packages/PHPUnit/tests/Rector/MethodCall/UseSpecificWillMethodRector/Fixture/with.php.inc
packages/PHPUnit/tests/Rector/MethodCall/UseSpecificWillMethodRector/UseSpecificWillMethodRectorTest.php

[PHPUnit] Add UseSpecificWillMethodRector

---

packages/CodingStyle/src/Rector/FuncCall/ConsistentImplodeRector.php
packages/CodingStyle/tests/Rector/FuncCall/ConsistentImplodeRector/ConsistentImplodeRectorTest.php
packages/CodingStyle/tests/Rector/FuncCall/ConsistentImplodeRector/Fixture/fixture.php.inc

[CodingStyle] Add ConsistentImplodeRector

---

config/level/coding-style/coding-style.yml
packages/CodingStyle/src/Rector/FuncCall/SetTypeToCastRector.php
packages/CodingStyle/tests/Rector/FuncCall/SetTypeToCastRector/Fixture/assign.php.inc
packages/CodingStyle/tests/Rector/FuncCall/SetTypeToCastRector/Fixture/fixture.php.inc
packages/CodingStyle/tests/Rector/FuncCall/SetTypeToCastRector/SetTypeToCastRectorTest.php

Close #919
```diff
-settype($int, 'string');
+$int = (string) $int;
```

[CodingStyle] Add SetTypeToCastRector

---

config/level/coding-style/coding-style.yml
packages/CodingStyle/src/Rector/Use_/RemoveUnusedAliasRector.php
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Fixture/fixture.php.inc
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Fixture/used.php.inc
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/RemoveUnusedAliasRectorTest.php
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Source/AbstractKernel.php
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Source/Another/AbstractKernel.php
packages/NodeTypeResolver/src/NodeScopeAndMetadataDecorator.php

[CodingStyle] Remove unused alias Rector

---

packages/CodingStyle/src/Rector/Use_/RemoveUnusedAliasRector.php
src/PhpParser/Node/Maintainer/PropertyMaintainer.php
src/PhpParser/Printer/BetterStandardPrinter.php

fix EncapsedString print in BetterStandardPrinter and static unused property

---

config/level/code-quality/code-quality.yml
packages/CodeQuality/src/Rector/Concat/JoinStringConcatRector.php
packages/CodeQuality/tests/Rector/Concat/JoinStringConcatRector/Fixture/fixture.php.inc
packages/CodeQuality/tests/Rector/Concat/JoinStringConcatRector/JoinStringConcatRectorTest.php

[CodeQuality] Add JoinStringConcatRector

---

composer.json
config/level/code-quality/code-quality.yml
packages/CodeQuality/src/Rector/If_/ConsecutiveNullCompareReturnsToNullCoalesceQueueRector.php
packages/CodeQuality/src/Rector/If_/SimplifyIfNotNullReturnRector.php
packages/CodeQuality/tests/Rector/If_/ConsecutiveNullCompareReturnsToNullCoalesceQueueRector/ConsecutiveNullCompareReturnsToNullCoalesceQueueRectorTest.php
packages/CodeQuality/tests/Rector/If_/ConsecutiveNullCompareReturnsToNullCoalesceQueueRector/Fixture/fixture.php.inc
packages/CodeQuality/tests/Rector/If_/ConsecutiveNullCompareReturnsToNullCoalesceQueueRector/Fixture/triplets.php.inc
packages/CodeQuality/tests/Rector/If_/SimplifyIfNotNullReturnRector/Fixture/skip.php.inc
packages/CodeQuality/tests/Rector/If_/SimplifyIfNotNullReturnRector/SimplifyIfNotNullReturnRectorTest.php
packages/ConsoleDiffer/src/Console/Formatter/DiffConsoleFormatter.php
packages/ConsoleDiffer/src/MarkdownDifferAndFormatter.php
src/PhpParser/Node/Commander/NodeRemovingCommander.php
src/PhpParser/Node/Maintainer/IfMaintainer.php
src/PhpParser/Printer/BetterStandardPrinter.php
src/Rector/AbstractRector.php
src/Rector/NodeCommandersTrait.php

Closes #855
```diff
-if (null !== $this->orderItem) {
-    return $this->orderItem;
-}
-if (null !== $this->orderItemUnit) {
-    return $this->orderItemUnit;
-}
-return null;
+return $this->orderItem ?? $this->orderItemUnit;
```

[CodeQuality] Add ConsecutiveNullCompareReturnsToNullCoalesceQueueRector

---

packages/CodingStyle/tests/Rector/ClassConst/CompleteVarDocTypeConstantRector/Fixture/fixture.php.inc
packages/NodeTypeResolver/src/Node/NodeToStringTypeResolver.php
packages/NodeTypeResolver/src/NodeTypeAnalyzer.php

... otherwise we get a empty "@var" comment.

fix for e.g. negative class const values in CompleteVarDocTypeConstantRector

---

src/Rector/Class_/ClassReplacerRector.php
tests/Rector/Class_/ClassReplacerRector/ClassReplacerRectorTest.php
tests/Rector/Class_/ClassReplacerRector/Fixture/class_to_interface.php.inc
tests/Rector/Class_/ClassReplacerRector/Fixture/interface_to_class.php.inc

prevent class <=> interface replacing on incorrect places

---

packages/NodeTypeResolver/src/Application/FunctionLikeNodeCollector.php
packages/Php/src/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector.php
packages/Php/tests/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector/Fixture/keep_annotated.php.inc
packages/Php/tests/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector/StaticCallOnNonStaticToInstanceCallRectorTest.php

Fix isStaticMethod() for method static annotation

---

ecs.yml
packages/CodingStyle/src/Rector/Use_/RemoveUnusedAliasRector.php
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Fixture/class_name.php.inc
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Fixture/fixture.php.inc
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Fixture/interace_extending.php.inc
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Fixture/no_namespace.php.inc
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Fixture/no_namespace_class_name.php.inc
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Fixture/trait_name.php.inc
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Fixture/unneeded_trait_name.php.inc
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/RemoveUnusedAliasRectorTest.php
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Source/AbstractInterface.php
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Source/ClassicTrait.php
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Source/Kernel.php
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Source/StandaloneClass.php
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Source/StandaloneTrait.php
phpstan.neon

Closes #978
- add support for interfaces
- add support for use traits

[CodingStyle] RemoveUnusedAliasRector improvements

---

packages/NodeTypeResolver/src/NodeTypeAnalyzer.php
packages/Php/src/Rector/FuncCall/CountOnNullRector.php
packages/Php/tests/Rector/FuncCall/CountOnNullRector/CountOnNullRectorTest.php
packages/Php/tests/Rector/FuncCall/CountOnNullRector/Fixture/double_same_variable.php.inc

Fix array static type resolver for NonEmptyArrayType

---

src/Rector/Architecture/Factory/NewObjectToFactoryCreateRector.php

Test is missing, shame on me 😢

Prevents NewObjectToFactoryCreateRector to cycle itself when refactoring factory class

---

src/Rector/Constant/ClassConstantReplacerRector.php
tests/Rector/Constant/ClassConstantReplacerRector/ClassConstantReplacerRectorTest.php
tests/Rector/Constant/ClassConstantReplacerRector/Fixture/fixture.php.inc
tests/Rector/Constant/ClassConstantReplacerRector/Source/DifferentClass.php

ClassConstantReplacerRector - Added support for replacing constant from different class

---

config/level/phpunit/phpunit80.yaml
src/Rector/Typehint/ReturnTypehintRector.php

add PHPUnit 8 void return types

---

.gitignore
.travis.yml
composer.json
docs/AllRectorsOverview.md
packages/ContributorTools/src/Command/DumpRectorsCommand.php
packages/ContributorTools/src/Command/GenerateDocsCommand.php
packages/ContributorTools/src/Contract/OutputFormatterInterface.php
packages/ContributorTools/src/Finder/RectorsFinder.php
packages/ContributorTools/src/OutputFormatter/JsonOutputFormatter.php
packages/ContributorTools/src/OutputFormatter/MarkdownOutputFormatter.php
packages/ContributorTools/src/RectorMetadataResolver.php
src/Console/Application.php

Json support for https://github.com/rectorphp/getrector.org/issues/14
```bash
vendor/bin/rector generate-docs
```
```bash
vendor/bin/rector dump-rectors --output-format markdown
vendor/bin/rector dump-rectors --output-format json
```

Extend `dump-rectors` command to json format

---

packages/NodeTypeResolver/src/ComplexNodeTypeResolver.php
packages/Php/src/Rector/Property/CompleteVarDocTypePropertyRector.php
packages/Php/src/Rector/Property/TypedPropertyRector.php
packages/Php/tests/Rector/Property/TypedPropertyRector/Fixture/default_values.php.inc
packages/Php/tests/Rector/Property/TypedPropertyRector/Fixture/static_analysis_based.php.inc
packages/Php/tests/Rector/Property/TypedPropertyRector/TypedPropertyRectorTest.php

```diff
final class StaticAnalysisBased
{
-    private $count;
+    private int $count;
public function setCount(int $count)
{
$this->count = $count;
}
}
```

[PHP7.4] decouple ComplexNodeTypeResolver, add PHP 7.4 type resolving from assigns

---

README.md

Small grammar thing.
Not sure about `doing` part though.

Fix sentence.

---

packages/Php/src/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector.php
packages/Php/tests/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector/Fixture/add_static_to_method.php.inc
packages/Php/tests/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector/Fixture/with_constructor.php.inc
packages/Php/tests/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector/StaticCallOnNonStaticToInstanceCallRectorTest.php
phpstan.neon
src/PhpParser/Node/Maintainer/ClassMethodMaintainer.php
src/PhpParser/Node/Maintainer/VisibilityMaintainer.php
src/Rector/Visibility/ChangePropertyVisibilityRector.php

Fix Static call on static method

---

packages/DeadCode/src/Rector/ClassMethod/RemoveUnusedParameterRector.php
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedParameterRector/Fixture/in_between_parameter.php.inc
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedParameterRector/Fixture/order.php.inc
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedParameterRector/RemoveUnusedParameterRectorTest.php
packages/Php/src/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector.php

Remove ctor param in RemoveUnusedParameterRector

---

ecs.yml
packages/NetteToSymfony/config/config.yaml
packages/NetteToSymfony/src/Event/EventInfo.php
packages/NetteToSymfony/src/Event/EventInfosFactory.php
packages/NetteToSymfony/src/Rector/ClassMethod/RenameEventNamesInEventSubscriberRector.php
packages/NetteToSymfony/tests/Rector/ClassMethod/RenameEventNamesInEventSubscriberRector/Fixture/event_class.php.inc
packages/NetteToSymfony/tests/Rector/ClassMethod/RenameEventNamesInEventSubscriberRector/Fixture/presenter_startup.php.inc
packages/NetteToSymfony/tests/Rector/ClassMethod/RenameEventNamesInEventSubscriberRector/RenameEventNamesInEventSubscriberRectorTest.php

[NetteToSymfony] Add event_class to RenameEventNamesInEventSubscriberRector

---

packages/CodeQuality/src/Rector/Foreach_/SimplifyForeachToCoalescingRector.php
packages/ConsoleDiffer/src/Console/Formatter/DiffConsoleFormatter.php
packages/Php/src/EregToPcreTransformer.php
packages/Php/src/Rector/FunctionLike/AbstractTypeDeclarationRector.php
packages/Symfony/src/Bridge/SymfonyKernelParameterGuard.php
packages/Symfony/src/Rector/HttpKernel/GetRequestRector.php
src/Application/RectorApplication.php
src/Console/Command/ProcessCommand.php
src/PhpParser/Node/Maintainer/CallMaintainer.php
src/PhpParser/Node/NodeFactory.php
src/Rector/Function_/FunctionReplaceRector.php
src/Rector/Namespace_/NamespaceReplacerRector.php

Add number of applied Rectors

---

packages/ContributorTools/src/Command/CreateRectorCommand.php
src/Rector/String_/StringToClassConstantRector.php
tests/Rector/String_/StringToClassConstantRector/Fixture/fixture.php.inc
tests/Rector/String_/StringToClassConstantRector/StringToClassConstantRectorTest.php

Add StringToClassConstantRector

---

packages/NetteToSymfony/src/Route/RouteInfoFactory.php
packages/NetteToSymfony/tests/Rector/ClassMethod/RouterListToControllerAnnotationsRetor/Fixture/with_parameter.php.inc
packages/NetteToSymfony/tests/Rector/ClassMethod/RouterListToControllerAnnotationsRetor/RouterListToControllerAnnotationsRectorTest.php

Fix param wrapper conversion in RouterListToControllerAnnotationsRector

---

packages/CodeQuality/src/Rector/BinaryOp/SimplifyDeMorganBinaryRector.php
packages/CodeQuality/tests/Rector/BinaryOp/SimplifyDeMorganBinaryRector/Fixture/multi_binary.php.inc
packages/CodeQuality/tests/Rector/BinaryOp/SimplifyDeMorganBinaryRector/SimplifyDeMorganBinaryRectorTest.php
src/Rector/AbstractRector.php
src/RectorDefinition/RectorDefinition.php
tests/RectorDefinition/RectorDefinitionTest.php

Fix SimplifyDeMorganBinaryRector

---

config/level/cakephp/cakephp34.yaml
packages/CakePHP/tests/Rector/MethodCall/ModalToGetSetRector/Fixture/fixture.php.inc

fix CakePHP 3.4 with config method

---

config/level/framework-migration/nette-to-symfony.yaml
packages/NetteToSymfony/src/Rector/MethodCall/WrapTransParameterNameRector.php
packages/NetteToSymfony/tests/Rector/MethodCall/WrapTransParameterNameRector/Fixture/fixture.php.inc
packages/NetteToSymfony/tests/Rector/MethodCall/WrapTransParameterNameRector/Source/SomeTranslator.php
packages/NetteToSymfony/tests/Rector/MethodCall/WrapTransParameterNameRector/WrapTransParameterNameRectorTest.php

[NTS] Add trans() param wrapper

---

config/level/code-quality/code-quality.yaml
packages/CodeQuality/src/Rector/If_/SimplifyIfIssetToNullCoalescingRector.php
packages/CodeQuality/tests/Rector/If_/SimplifyIfIssetToNullCoalescingRector/Fixture/fixture.php.inc
packages/CodeQuality/tests/Rector/If_/SimplifyIfIssetToNullCoalescingRector/SimplifyIfIssetToNullCoalescingRectorTest.php
phpstan.neon

[CodeQuality] Add SimplifyIfIssetToNullCoalescingRector

---

config/level/dead-code/dead-code.yaml
packages/DeadCode/src/Rector/ClassConst/RemoveUnusedPrivateConstantRector.php
packages/DeadCode/tests/Rector/ClassConst/RemoveUnusedPrivateConstantRector/Fixture/fixture.php.inc
packages/DeadCode/tests/Rector/ClassConst/RemoveUnusedPrivateConstantRector/RemoveUnusedPrivateConstantRectorTest.php
phpstan.neon
src/PhpParser/Node/Maintainer/ClassConstMaintainer.php

Ref #1059
```diff
class Something
{
-    private const FOO = 2;
public function addOne()
{
return 2;
}
}
```

[DeadCode] Add RemoveUnusedPrivateConstantRector

---

config/level/dead-code/dead-code.yaml
packages/DeadCode/src/Rector/ClassMethod/RemoveUnusedPrivateMethodRector.php
packages/DeadCode/tests/Rector/ClassConst/RemoveUnusedPrivateConstantRector/Fixture/keep_constant.php.inc
packages/DeadCode/tests/Rector/ClassConst/RemoveUnusedPrivateConstantRector/RemoveUnusedPrivateConstantRectorTest.php
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/fixture.php.inc
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/keep_anonymous.php.inc
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/static_method.php.inc
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/RemoveUnusedPrivateMethodRectorTest.php
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Source/AnotherCaller.php
packages/NodeTypeResolver/src/Application/FunctionLikeNodeCollector.php
packages/NodeTypeResolver/src/NodeVisitor/ClassAndMethodNodeVisitor.php
packages/NodeTypeResolver/src/NodeVisitor/NodeCollectorNodeVisitor.php
packages/Php/src/Rector/FunctionLike/ParamTypeDeclarationRector.php
src/PhpParser/Node/Maintainer/ClassConstMaintainer.php
src/PhpParser/Node/Maintainer/ClassMethodMaintainer.php
src/Rector/NodeFactoryTrait.php

Closes #1059
```diff
class Something
{
public function addOne()
{
return 2;
}
-
-    private function notRun()
-    {
-    }
}
```

[DeadCode] Add RemoveUnusedPrivateMethodRector

---

config/level/php/php52.yaml
packages/Php/src/Rector/Property/VarToPublicPropertyRector.php
packages/Php/tests/Rector/Property/VarToPublicPropertyRector/Fixture/fixture.php.inc
packages/Php/tests/Rector/Property/VarToPublicPropertyRector/VarToPublicPropertyRectorTest.php

```diff
class Some
{
-    var $name = 'Tom';
+    public $name = 'Tom';
}
```

[PHP 5.2] Add var to public property

---

config/level/code-quality/code-quality.yaml
packages/CodeQuality/src/Rector/NotEqual/CommonNotEqualRector.php
packages/CodeQuality/tests/Rector/NotEqual/CommonNotEqualRector/CommonNotEqualRectorTest.php
packages/CodeQuality/tests/Rector/NotEqual/CommonNotEqualRector/Fixture/fixture.php.inc

[CodeQuality] Add CommonNotEqualRector

---

config/level/php/php54.yaml
packages/Php/src/Rector/FuncCall/RemoveReferenceFromCallRector.php
packages/Php/tests/Rector/FuncCall/RemoveReferenceFromCallRector/Fixture/fixture.php.inc
packages/Php/tests/Rector/FuncCall/RemoveReferenceFromCallRector/RemoveReferenceFromCallRectorTest.php

[PHP] RemoveReferenceFromCallRector

---

config/level/php/php52.yaml
packages/Php/src/Rector/Switch_/ContinueToBreakInSwitchRector.php
packages/Php/tests/Rector/Switch_/ContinueToBreakInSwitchRector/ContinueToBreakInSwitchRectorTest.php
packages/Php/tests/Rector/Switch_/ContinueToBreakInSwitchRector/Fixture/fixture.php.inc
packages/Php/tests/Rector/Switch_/ContinueToBreakInSwitchRector/Fixture/skip_nested.php.inc

[PHP] Add ContinueToBreakInSwitchRector

---

config/level/code-quality/code-quality.yaml
packages/CodeQuality/src/Rector/Equal/UseIdenticalOverEqualWithSameTypeRector.php
packages/CodeQuality/tests/Rector/Equal/UseIdenticalOverEqualWithSameTypeRector/Fixture/fixture.php.inc
packages/CodeQuality/tests/Rector/Equal/UseIdenticalOverEqualWithSameTypeRector/Fixture/skip_objects.php.inc
packages/CodeQuality/tests/Rector/Equal/UseIdenticalOverEqualWithSameTypeRector/UseIdenticalOverEqualWithSameTypeRectorTest.php

[CodeQuality] Add UseIdenticalOverEqualWithSameTypeRector

---

config/level/dead-code/dead-code.yaml
packages/DeadCode/src/Rector/FunctionLike/RemoveCodeAfterReturnRector.php
packages/DeadCode/tests/Rector/FunctionLike/RemoveCodeAfterReturnRector/Fixture/fixture.php.inc
packages/DeadCode/tests/Rector/FunctionLike/RemoveCodeAfterReturnRector/Fixture/keep_nested.php.inc
packages/DeadCode/tests/Rector/FunctionLike/RemoveCodeAfterReturnRector/RemoveCodeAfterReturnRectorTest.php

[DeadCode] Add RemoveCodeAfterReturnRector

---

ecs.yml
packages/NodeTypeResolver/src/NodeTypeResolver.php
packages/Php/tests/Rector/FuncCall/RemoveExtraParametersRector/Fixture/static_call_parent.php.inc
packages/Php/tests/Rector/FuncCall/RemoveExtraParametersRector/RemoveExtraParametersRectorTest.php
packages/Php/tests/Rector/FuncCall/RemoveExtraParametersRector/Source/ChildOrmion.php
packages/Php/tests/Rector/FuncCall/RemoveExtraParametersRector/Source/Db.php
packages/Php/tests/Rector/FuncCall/RemoveExtraParametersRector/Source/Ormion.php

Resolve StaticCall::method corretly

---

src/Console/Command/ShowCommand.php

Show current configuration in "show" command

---

packages/CodingStyle/src/Rector/Use_/RemoveUnusedAliasRector.php
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Fixture/doc_block.php.inc
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/RemoveUnusedAliasRectorTest.php
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Source/Mapping.php

Fix used doc alias in RemoveUnusedAliasRector

---

config/level/php/php72.yaml
packages/Php/src/Rector/FuncCall/StringifyDefineRector.php
packages/Php/tests/Rector/FuncCall/StringifyDefineRector/Fixture/fixture.php.inc
packages/Php/tests/Rector/FuncCall/StringifyDefineRector/StringifyDefineRectorTest.php

[PHP 7.2] Add StringifyDefineRector

---

.travis.yml
config/level/code-quality/code-quality.yaml
ecs.yml
packages/CodeQuality/src/Rector/Identical/SimplifyBoolIdenticalTrueRector.php
packages/CodeQuality/tests/Rector/Identical/SimplifyBoolIdenticalTrueRector/Fixture/directly.php.inc
packages/CodeQuality/tests/Rector/Identical/SimplifyBoolIdenticalTrueRector/Fixture/negate.php.inc
packages/CodeQuality/tests/Rector/Identical/SimplifyBoolIdenticalTrueRector/SimplifyBoolIdenticalTrueRectorTest.php

[CodeQuality] Add SimplifyBoolIdenticalTrueRector

---

config/level/coding-style/coding-style.yaml
packages/CodingStyle/src/Rector/String_/SymplifyQuoteEscapeRector.php
packages/CodingStyle/tests/Rector/String_/SymplifyQuoteEscapeRector/Fixture/fixture.php.inc
packages/CodingStyle/tests/Rector/String_/SymplifyQuoteEscapeRector/Fixture/skip.php.inc
packages/CodingStyle/tests/Rector/String_/SymplifyQuoteEscapeRector/SymplifyQuoteEscapeRectorTest.php
packages/NodeTypeResolver/src/Node/Attribute.php

[CodingStyle] Add SymplifyQuoteEscapeRector

---

config/level/dead-code/dead-code.yaml
packages/DeadCode/src/Rector/ClassMethod/RemoveDeadConstructorRector.php
packages/DeadCode/tests/Rector/ClassMethod/RemoveDeadConstructorRector/Fixture/fixture.php.inc
packages/DeadCode/tests/Rector/ClassMethod/RemoveDeadConstructorRector/Fixture/skip.php.inc
packages/DeadCode/tests/Rector/ClassMethod/RemoveDeadConstructorRector/RemoveDeadConstructorRectorTest.php

[DeadCode] Add RemoveDeadConstructorRector

---

packages/NetteToSymfony/src/Annotation/SymfonyRoutePhpDocTagNode.php
packages/NetteToSymfony/src/Rector/ClassMethod/RouterListToControllerAnnotationsRector.php
packages/NetteToSymfony/tests/Rector/ClassMethod/RouterListToControllerAnnotationsRetor/Fixture/with_parameter.php.inc
phpstan.neon

[NetteToSymfony] Fix new route for already present annotation above method

---

composer.json
packages/Laravel/src/Rector/StaticCall/FacadeStaticCallToConstructorInjectionRector.php
packages/Laravel/tests/Rector/StaticCall/FacadeStaticCallToConstructorInjectionRector/FacadeStaticCallToConstructorInjectionRectorTest.php
packages/Laravel/tests/Rector/StaticCall/FacadeStaticCallToConstructorInjectionRector/Fixture/fixture.php.inc
packages/Laravel/tests/Rector/StaticCall/FacadeStaticCallToConstructorInjectionRector/Source/LaravelController.php
packages/NodeTypeResolver/src/NodeTypeResolver.php
packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php

[Laravel] Add FacadeStaticCallToConstructorInjectionRector

---

config/level/laravel/laravel58.yaml
ecs.yml
packages/Laravel/src/Rector/StaticCall/MinutesToSecondsInCacheRector.php
packages/Laravel/tests/Rector/StaticCall/MinutesToSecondsInCacheRector/Fixture/fixture.php.inc
packages/Laravel/tests/Rector/StaticCall/MinutesToSecondsInCacheRector/MinutesToSecondsInCacheRectorTest.php
packages/Laravel/tests/Rector/StaticCall/MinutesToSecondsInCacheRector/Source/ArrayStore.php
packages/Laravel/tests/Rector/StaticCall/MinutesToSecondsInCacheRector/Source/LaravelStoreInterface.php

Ref https://github.com/laravel/framework/pull/27276/files

[Laravel 5.8] Add MinutesToSecondsInCacheRector + misc

---

src/Rector/MagicDisclosure/GetAndSetToMethodCallRector.php
tests/Rector/MagicDisclosure/GetAndSetToMethodCallRector/Fixture/fixture.php.inc

If conditions was not considered 🙈

Fix GetAndSetToMethodCallRector on if conditions

---

config/level/shopware/shopware55.yaml

I am new to PHP-Parser. Feel free for ideas to improve 🙈

Add Shopware Rector config

---

config/level/symfony/symfony42.yaml
src/Rector/New_/NewToStaticCallRector.php
tests/Rector/New_/NewToStaticCallRector/Fixture/fixture.php.inc
tests/Rector/New_/NewToStaticCallRector/NewToStaticCallRectorTest.php
tests/Rector/New_/NewToStaticCallRector/Source/FromNewClass.php
tests/Rector/New_/NewToStaticCallRector/Source/IntoStaticClass.php

[Symfony 4.2] Add Cookie to create() deprecations

---

ecs.yml
src/Rector/ClassMethod/WrapReturnRector.php
tests/Rector/ClassMethod/WrapReturnRector/Fixture/already_array.php.inc
tests/Rector/ClassMethod/WrapReturnRector/WrapReturnRectorTest.php

Fix already array of WrapReturnRector

---

packages/Php/src/Rector/FuncCall/PregReplaceEModifierRector.php
packages/Php/tests/Rector/FuncCall/PregReplaceEModifierRector/Fixture/call_function.php.inc
packages/Php/tests/Rector/FuncCall/PregReplaceEModifierRector/Fixture/fixture.php.inc
packages/Php/tests/Rector/FuncCall/PregReplaceEModifierRector/Fixture/slashes.php.inc
packages/Php/tests/Rector/FuncCall/PregReplaceEModifierRector/PregReplaceEModifierRectorTest.php

[PHP] Add PregReplaceEModifierRector

---

config/level/laravel/laravel57.yaml
config/level/sylius/sylius10.yaml
config/level/symfony/symfony32.yaml
config/level/symfony/symfony33.yaml
config/level/symfony/symfony42.yaml
src/Rector/Argument/ArgumentAdderRector.php
tests/Rector/Argument/ArgumentAdderRector/ArgumentAdderRectorTest.php
tests/Rector/Argument/ArgumentAdderRector/Fixture/fixture3.php.inc

[Laravel] add argument adder rules

---

config/level/laravel/laravel57.yaml
packages/Laravel/src/Rector/StaticCall/Redirect301ToPermanentRedirectRector.php
packages/Laravel/tests/Rector/StaticCall/Redirect301ToPermanentRedirectRector/Fixture/fixture.php.inc
packages/Laravel/tests/Rector/StaticCall/Redirect301ToPermanentRedirectRector/Redirect301ToPermanentRedirectRectorTest.php
src/Rector/Argument/ArgumentAdderRector.php
src/Rector/Argument/ArgumentRemoverRector.php
tests/Rector/Argument/ArgumentAdderRector/ArgumentAdderRectorTest.php
tests/Rector/Argument/ArgumentAdderRector/Fixture/already_added.php.inc
tests/Rector/Argument/ArgumentAdderRector/Fixture/fixture3.php.inc
tests/Rector/Argument/ArgumentRemoverRector/ArgumentRemoverRectorTest.php
tests/Rector/Argument/ArgumentRemoverRector/Fixture/remove_in_middle.php.inc
tests/Rector/Argument/ArgumentRemoverRector/Source/RemoveInTheMiddle.php

[Laravel] Add Redirect301ToPermanentRedirect

---

packages/CodingStyle/src/Rector/Switch_/BinarySwitchToIfElseRector.php
packages/CodingStyle/tests/Rector/Switch_/BinarySwitchToIfElseRector/BinarySwitchToIfElseRectorTest.php
packages/CodingStyle/tests/Rector/Switch_/BinarySwitchToIfElseRector/Fixture/if_or.php.inc

[CodingStyle] Add || support for 2 cases with the same output

---

README.md
config/level/laravel/laravel50.yaml
config/level/laravel/laravel51.yaml
config/level/laravel/laravel52.yaml
docs/AllRectorsOverview.md
docs/NodesOverview.md
tests/Rector/String_/StringToClassConstantRector/Fixture/fixture.php.inc
tests/Rector/String_/StringToClassConstantRector/StringToClassConstantRectorTest.php

[Laravel] add Laravel 5.0, 5.1 and 5.2 sets

---

config/level/laravel/laravel53.yaml
packages/BetterPhpDocParser/src/PhpDocInfo/PhpDocInfo.php
packages/BetterPhpDocParser/src/PhpDocModifier.php
phpstan.neon
src/PhpParser/Node/Manipulator/ClassManipulator.php
src/PhpParser/Node/Manipulator/ClassMethodManipulator.php
src/PhpParser/Printer/BetterStandardPrinter.php
src/Rector/ClassLike/RemoveTraitRector.php
tests/Rector/ClassLike/RemoveTraitRector/Fixture/fixture.php.inc
tests/Rector/ClassLike/RemoveTraitRector/RemoveTraitRectorTest.php
tests/Rector/ClassLike/RemoveTraitRector/Source/TraitToBeRemoved.php

[Laravel 5.3] Add RemoveTraitRector

---

packages/Laravel/tests/Rector/StaticCall/RequestStaticValidateToInjectRector/Fixture/fixture-alias.php.inc
packages/Laravel/tests/Rector/StaticCall/RequestStaticValidateToInjectRector/RequestStaticValidateToInjectRectorTest.php

https://github.com/rectorphp/rector/issues/1176

[Laravel] add alias test case for RequestStaticValidateToInjectRector

---

composer.json
packages/Laravel/src/Rector/StaticCall/RequestStaticValidateToInjectRector.php
packages/NodeTypeResolver/src/NodeTypeResolver.php
packages/NodeTypeResolver/src/PHPStan/Scope/NodeScopeResolver.php
packages/NodeTypeResolver/src/PerNodeTypeResolver/ClassAndInterfaceTypeResolver.php
packages/NodeTypeResolver/src/PerNodeTypeResolver/ParamTypeResolver.php
packages/NodeTypeResolver/src/PerNodeTypeResolver/VariableTypeResolver.php
packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
packages/PHPUnit/src/Rector/TryCatchToExpectExceptionRector.php
packages/Php/src/Rector/Assign/AssignArrayToStringRector.php

See https://github.com/phpstan/phpstan/tree/0.11.3

Upgrade to PHPStan 0.11.3

---

packages/Php/src/Rector/BinaryOp/IsCountableRector.php
packages/Php/src/Rector/Ternary/TernaryToSpaceshipRector.php

Check minimum php version before running IsCountableRector and TernaryToSpaceshipRector

---

config/level/phpunit/phpunit-exception.yaml
config/level/phpunit/phpunit60.yaml
config/level/phpunit/phpunit70.yaml
config/level/phpunit/phpunit80.yaml
packages/PHPUnit/src/Rector/DelegateExceptionArgumentsRector.php
packages/PHPUnit/src/Rector/MethodCall/ReplaceAssertArraySubsetRector.php
packages/PHPUnit/tests/Rector/DelegateExceptionArgumentsRector/DelegateExceptionArgumentsRectorTest.php
packages/PHPUnit/tests/Rector/DelegateExceptionArgumentsRector/Fixture/message.php.inc
packages/PHPUnit/tests/Rector/DelegateExceptionArgumentsRector/Fixture/regexp.php.inc
packages/PHPUnit/tests/Rector/DelegateExceptionArgumentsRector/Fixture/self_nested.php.inc
src/Rector/AbstractPHPUnitRector.php

[PHPUnit] Improve DelegateExceptionArgumentsRector to work with setExpectedExceptionRegExp()

---

tests/Rector/Class_/RenameClassRector/Fixture/twig_case.php.inc
tests/Rector/Namespace_/PseudoNamespaceToNamespaceRector/Fixture/fixture6.php.inc

Failing tests

---

packages/DeadCode/src/Rector/ClassMethod/RemoveUnusedPrivateMethodRector.php
packages/NetteToSymfony/src/Rector/ClassMethod/RouterListToControllerAnnotationsRector.php
packages/NodeTypeResolver/src/NodeTypeResolver.php
packages/Shopware/src/Rector/MethodCall/ReplaceEnlightResponseWithSymfonyResponseRector.php
packages/Shopware/tests/Rector/MethodCall/ReplaceEnlightResponseWithSymfonyResponseRector/ReplaceEnlightResponseWithSymfonyResponseRectorTest.php
src/PhpParser/Node/Resolver/NameResolver.php
src/Rector/NameResolverTrait.php

add mask support to isName(), remove matchName()

---

src/HttpKernel/RectorKernel.php

In phar on boot of the kernel. The kernel tries to write inside the phar 🙈 
Btw got the phar version running 😊 
https://github.com/Symplify/Symplify/pull/1498

Fix logging in phar

---

composer.json
config/level/framework-migration/nette-tester-to-phpunit.yaml
docs/AllRectorsOverview.md
ecs.yaml
packages/ContributorTools/src/Command/CreateRectorCommand.php
packages/NetteTesterToPHPUnit/config/config.yaml
packages/NetteTesterToPHPUnit/src/AssertManipulator.php
packages/NetteTesterToPHPUnit/src/Rector/Class_/NetteTesterClassToPHPUnitClassRector.php
packages/NetteTesterToPHPUnit/src/Rector/RenameTesterTestToPHPUnitToTestFileRector.php
packages/NetteTesterToPHPUnit/src/Rector/StaticCall/NetteAssertToPHPUnitAssertRector.php
packages/NetteTesterToPHPUnit/tests/Rector/Class_/NetteTesterClassToPHPUnitClassRector/Copy/bootstrap.php
packages/NetteTesterToPHPUnit/tests/Rector/Class_/NetteTesterClassToPHPUnitClassRector/Fixture/assert_type.php.inc
packages/NetteTesterToPHPUnit/tests/Rector/Class_/NetteTesterClassToPHPUnitClassRector/Fixture/fixture.php.inc
packages/NetteTesterToPHPUnit/tests/Rector/Class_/NetteTesterClassToPHPUnitClassRector/Fixture/test_class.php.inc
packages/NetteTesterToPHPUnit/tests/Rector/Class_/NetteTesterClassToPHPUnitClassRector/NetteTesterClassToPHPUnitClassRectorTest.php
packages/NetteTesterToPHPUnit/tests/Rector/Class_/NetteTesterClassToPHPUnitClassRector/Source/NetteTesterTestCase.php
packages/NetteTesterToPHPUnit/tests/Rector/StaticCall/NetteAssertToPHPUnitAssertRector/Fixture/assert_type.php.inc
packages/NetteTesterToPHPUnit/tests/Rector/StaticCall/NetteAssertToPHPUnitAssertRector/Fixture/fixture.php.inc
packages/NetteTesterToPHPUnit/tests/Rector/StaticCall/NetteAssertToPHPUnitAssertRector/Fixture/various_asserts.php.inc
packages/NetteTesterToPHPUnit/tests/Rector/StaticCall/NetteAssertToPHPUnitAssertRector/NetteAssertToPHPUnitAssertRectorTest.php
packages/PHPUnit/src/Rector/MethodCall/SpecificAssertContainsRector.php
packages/PhpSpecToPHPUnit/src/Naming/PhpSpecRenaming.php
packages/PhpSpecToPHPUnit/src/Rector/Class_/PhpSpecClassToPHPUnitClassRector.php
src/PhpParser/Node/Manipulator/ClassManipulator.php
src/Testing/PHPUnit/AbstractRectorTestCase.php

[NetteToSymfony] Nette\Tester to PHPUnit

---

src/Rector/AbstractRector.php
tests/Issues/Issue1225/Fixture/fixture1225.php
tests/Issues/Issue1225/Issue1225Test.php
tests/Issues/Issue1225/config/config1225.yaml

Fix Twig set priority disorder

---

config/level/symfony/symfony-code-quality.yaml
packages/Symfony/src/Rector/BinaryOp/ResponseStatusCodeRector.php
packages/Symfony/tests/Rector/BinaryOp/ResponseStatusCodeRector/Fixture/fixture.php.inc
packages/Symfony/tests/Rector/BinaryOp/ResponseStatusCodeRector/ResponseStatusCodeRectorTest.php

Add ResponseStatusCodeRector, fixes #1229

---

config/level/phpspec/phpspec30.yaml
config/level/phpspec/phpspec40.yaml

[PhpSpec] Add 3.0 and 4.0 upgrade sets

---

config/level/dead-code/dead-code.yaml
packages/DeadCode/src/Rector/FunctionLike/RemoveDeadReturnRector.php
packages/DeadCode/tests/Rector/FunctionLike/RemoveDeadReturnRector/Fixture/fixture.php.inc
packages/DeadCode/tests/Rector/FunctionLike/RemoveDeadReturnRector/Fixture/keep.php.inc
packages/DeadCode/tests/Rector/FunctionLike/RemoveDeadReturnRector/RemoveDeadReturnRectorTest.php

[DeadCode] Add RemoveDeadReturnRector

---

packages/DeadCode/src/Rector/Array_/RemoveDuplicatedArrayKeyRector.php
packages/DeadCode/tests/Rector/Array_/RemoveDuplicatedArrayKeyRector/Fixture/last_man_standing.php.inc
packages/DeadCode/tests/Rector/Array_/RemoveDuplicatedArrayKeyRector/RemoveDuplicatedArrayKeyRectorTest.php

[DeadCode] Improve RemoveDuplicatedArrayKeyRector to clear items, that are ignored

---

packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
src/Rector/Class_/RenameClassRector.php
tests/Issues/Issue1242/Fixture/fixture1242.php
tests/Issues/Issue1242/Issue1242Test.php
tests/Issues/Issue1242/config/config1242.yaml

[Twig] Add doc replacer into RenameClassRector, add Throws tag to change type

---

packages/DeadCode/src/Rector/ClassMethod/RemoveUnusedParameterRector.php
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedParameterRector/Fixture/compact.php.inc
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedParameterRector/RemoveUnusedParameterRectorTest.php
src/PhpParser/Node/Manipulator/ClassMethodManipulator.php

Add compact() case to RemoveUnusedParameterRector

---

config/level/dead-code/dead-code.yaml
packages/DeadCode/src/Rector/For_/RemoveDeadIfForeachForRector.php
packages/DeadCode/tests/Rector/For_/RemoveDeadIfForeachForRector/Fixture/fixture.php.inc
packages/DeadCode/tests/Rector/For_/RemoveDeadIfForeachForRector/Fixture/side_effect_checks.php.inc
packages/DeadCode/tests/Rector/For_/RemoveDeadIfForeachForRector/RemoveDeadIfForeachForRectorTest.php
packages/Php/tests/Rector/FuncCall/RegexDashEscapeRector/Fixture/variable.php.inc

[DeadCode] Add RemoveDeadIfForeachForRector

---

packages/Php/src/Rector/Each/ListEachRector.php

Fix description of ListEachRector

---

config/config.yaml
src/Console/Command/ProcessCommand.php

Allows to process files with not php extension

---

README.md
config/level/nette/nette-utils-code-quality.yaml
docs/AllRectorsOverview.md
docs/NodesOverview.md
packages/Nette/src/Rector/FuncCall/PregFunctionToNetteUtilsStringsRector.php
packages/Nette/tests/Rector/FuncCall/PregFunctionToNetteUtilsStringsRector/Fixture/preg_match.php.inc
packages/Nette/tests/Rector/FuncCall/PregFunctionToNetteUtilsStringsRector/Fixture/preg_match_all.php.inc
packages/Nette/tests/Rector/FuncCall/PregFunctionToNetteUtilsStringsRector/Fixture/preg_replace.php.inc
packages/Nette/tests/Rector/FuncCall/PregFunctionToNetteUtilsStringsRector/Fixture/preg_replace_callback.php.inc
packages/Nette/tests/Rector/FuncCall/PregFunctionToNetteUtilsStringsRector/Fixture/preg_split.php.inc
packages/Nette/tests/Rector/FuncCall/PregFunctionToNetteUtilsStringsRector/PregFunctionToNetteUtilsStringsRectorTest.php
packages/Symfony/tests/Rector/Controller/ActionSuffixRemoverRector/ActionSuffixRemoverRectorTest.php

[Nette] Add PregFunctionToNetteUtilsStringsRector

---

composer.json
config/level/symfony/symfony-code-quality.yaml
docs/AllRectorsOverview.md
docs/NodesOverview.md
packages/CodeQuality/src/Rector/Identical/BooleanNotIdenticalToNotIdenticalRector.php
packages/CodeQuality/src/Rector/Identical/SimplifyBoolIdenticalTrueRector.php
packages/CodeQuality/tests/Rector/Identical/BooleanNotIdenticalToNotIdenticalRector/BooleanNotIdenticalToNotIdenticalRectorTest.php
packages/CodeQuality/tests/Rector/Identical/BooleanNotIdenticalToNotIdenticalRector/Fixture/fixture.php.inc
packages/CodeQuality/tests/Rector/Identical/BooleanNotIdenticalToNotIdenticalRector/Fixture/just_first.php.inc
packages/CodeQuality/tests/Rector/Identical/BooleanNotIdenticalToNotIdenticalRector/Fixture/keep.php.inc
packages/CodeQuality/tests/Rector/Identical/SimplifyBoolIdenticalTrueRector/Fixture/double_negate.php.inc
packages/CodeQuality/tests/Rector/Identical/SimplifyBoolIdenticalTrueRector/SimplifyBoolIdenticalTrueRectorTest.php

[CodeQuality] prevent double negative in SimplifyBoolIdenticalTrueRector

---

config/level/symfony/symfony-code-quality.yaml
packages/CodeQuality/src/Rector/Array_/CallableThisArrayToAnonymousFunctionRector.php
packages/CodeQuality/tests/Rector/Array_/CallableThisArrayToAnonymousFunctionRector/CallableThisArrayToAnonymousFunctionRectorTest.php
packages/CodeQuality/tests/Rector/Array_/CallableThisArrayToAnonymousFunctionRector/Fixture/fixture.php.inc
packages/CodeQuality/tests/Rector/Array_/CallableThisArrayToAnonymousFunctionRector/Fixture/skip.php.inc

[CodeQuality] Add CallableThisArrayToAnonymousFunctionRector

---

config/level/php/php70.yaml
packages/Php/src/Rector/Break_/BreakNotInLoopOrSwitchToReturnRector.php
packages/Php/tests/Rector/Break_/BreakNotInLoopOrSwitchToReturnRector/BreakNotInLoopOrSwitchToReturnRectorTest.php
packages/Php/tests/Rector/Break_/BreakNotInLoopOrSwitchToReturnRector/Fixture/Keep.php
packages/Php/tests/Rector/Break_/BreakNotInLoopOrSwitchToReturnRector/Fixture/fixture.php.inc
packages/Php/tests/Rector/Break_/BreakNotInLoopOrSwitchToReturnRector/Fixture/foreach_not.php.inc
packages/Php/tests/Rector/Break_/BreakNotInLoopOrSwitchToReturnRector/Fixture/return.php.inc
src/Context/ContextAnalyzer.php

[PHP] Add BreakNotInLoopOrSwitchToReturnRector

---

composer.json
config/level/solid/solid.yaml
packages/NodeTypeResolver/src/Application/ClassLikeNodeCollector.php
packages/SOLID/src/Rector/Class_/FinalizeClassesWithoutChildrenRector.php
packages/SOLID/tests/Rector/Class_/FinalizeClassesWithoutChildrenRector/FinalizeClassesWithoutChildrenRectorTest.php
packages/SOLID/tests/Rector/Class_/FinalizeClassesWithoutChildrenRector/Fixture/entity.php.inc
packages/SOLID/tests/Rector/Class_/FinalizeClassesWithoutChildrenRector/Fixture/fixture.php.inc
packages/SOLID/tests/Rector/Class_/FinalizeClassesWithoutChildrenRector/Fixture/skip.php.inc

[SOLID] Add FinalizeClassesWithoutChildrenRector

---

config/level/coding-style/coding-style.yaml
packages/CodingStyle/src/Rector/ClassConst/SplitGroupedConstantsAndPropertiesRector.php
packages/CodingStyle/tests/Rector/ClassConst/SplitGroupedConstantsAndPropertiesRector/Fixture/fixture.php.inc
packages/CodingStyle/tests/Rector/ClassConst/SplitGroupedConstantsAndPropertiesRector/Fixture/skip.php.inc
packages/CodingStyle/tests/Rector/ClassConst/SplitGroupedConstantsAndPropertiesRector/SplitGroupedConstantsAndPropertiesRectorTest.php
src/PhpParser/Node/Commander/NodeAddingCommander.php
src/Rector/NodeCommandersTrait.php

[CodingStyle] Add SplitGroupedConstantsAndPropertiesRector

---

packages/NodeTypeResolver/src/Application/ClassLikeNodeCollector.php
packages/NodeTypeResolver/src/Application/ConstantNodeCollector.php
packages/NodeTypeResolver/src/NodeScopeAndMetadataDecorator.php
packages/NodeTypeResolver/src/NodeVisitor/ClassAndMethodNodeVisitor.php
packages/NodeTypeResolver/src/NodeVisitor/NodeCollectorNodeVisitor.php
packages/NodeTypeResolver/src/PerNodeTypeResolver/NameTypeResolver.php
packages/SOLID/src/Rector/ClassConst/PrivatizeLocalClassConstantRector.php
packages/SOLID/tests/Rector/ClassConst/PrivatizeLocalClassConstantRector/Fixture/fixture.php.inc
packages/SOLID/tests/Rector/ClassConst/PrivatizeLocalClassConstantRector/Fixture/in_interface.php.inc
packages/SOLID/tests/Rector/ClassConst/PrivatizeLocalClassConstantRector/Fixture/in_interface_used_child_and_extended.php.inc
packages/SOLID/tests/Rector/ClassConst/PrivatizeLocalClassConstantRector/Fixture/in_interface_used_child_and_external.php.inc
packages/SOLID/tests/Rector/ClassConst/PrivatizeLocalClassConstantRector/Fixture/keep_public.php.inc
packages/SOLID/tests/Rector/ClassConst/PrivatizeLocalClassConstantRector/Fixture/protected.php.inc
packages/SOLID/tests/Rector/ClassConst/PrivatizeLocalClassConstantRector/Fixture/protected_parent_parent.php.inc
packages/SOLID/tests/Rector/ClassConst/PrivatizeLocalClassConstantRector/Fixture/skip_multi_overcomplex.php.inc
packages/SOLID/tests/Rector/ClassConst/PrivatizeLocalClassConstantRector/PrivatizeLocalClassConstantRectorTest.php
src/Php/Regex/RegexPatternArgumentManipulator.php
src/PhpParser/Node/Value/ValueResolver.php

[SOLID] Add PrivatizeLocalClassConstantRector

---

config/level/symfony/symfony43.yaml
packages/Symfony/src/Rector/MethodCall/SimplifyWebTestCaseAssertionsRector.php
packages/Symfony/tests/Rector/MethodCall/SimplifyWebTestCaseAssertionsRector/Fixture/fixture.php.inc
packages/Symfony/tests/Rector/MethodCall/SimplifyWebTestCaseAssertionsRector/Fixture/response_code_same.php.inc
packages/Symfony/tests/Rector/MethodCall/SimplifyWebTestCaseAssertionsRector/SimplifyWebTestCaseAssertionsRectorTest.php
packages/Symfony/tests/Rector/MethodCall/SimplifyWebTestCaseAssertionsRector/Source/FixtureWebTestCase.php

[Symfony 4.3] Add SimplifyWebTestCaseAssertionsRector

---

README.md

Drupal8 Rector moved to its official repository :)

Update reference to drupal8-rector/drupal8-rector

---

packages/Symfony/src/Bridge/DependencyInjection/ContainerFactory.php

This PR includes what I was asked for in issue #1319 . Thank you very much for the assistance!

Use `dev` as Symfony default env to fix issue #1319

---

packages/DeadCode/src/Rector/Assign/RemoveDoubleAssignRector.php
packages/DeadCode/tests/Rector/Assign/RemoveDoubleAssignRector/Fixture/skip_double_catch.php.inc
packages/DeadCode/tests/Rector/Assign/RemoveDoubleAssignRector/RemoveDoubleAssignRectorTest.php
packages/RemovingStatic/src/UniqueObjectOrServiceDetector.php

[DeadCode] Remove double

---

packages/DeadCode/src/Rector/Assign/RemoveDoubleAssignRector.php
packages/DeadCode/tests/Rector/Assign/RemoveDoubleAssignRector/Fixture/skip_double_case.php.inc
packages/DeadCode/tests/Rector/Assign/RemoveDoubleAssignRector/RemoveDoubleAssignRectorTest.php

[DeadCode] Keep different case in RemoveDoubleAssignRector

---

packages/DeadCode/src/Rector/ClassMethod/RemoveUnusedPrivateMethodRector.php
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/skip_local_called.php.inc
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/RemoveUnusedPrivateMethodRectorTest.php
src/NodeContainer/ParsedNodesByType.php
src/PhpParser/Node/Manipulator/ClassMethodManipulator.php

[DeadCode] Fix RemoveUnusedPrivateMethodRector for self call

---

packages/DeadCode/src/Rector/ClassMethod/RemoveUnusedPrivateMethodRector.php
packages/DeadCode/src/Rector/Property/RemoveUnusedPrivatePropertyRector.php
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/keep_in_trait.php.inc
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/RemoveUnusedPrivateMethodRectorTest.php

[DeadCode] Skip traits in RemoveUnusedPrivateMethodRector

---

.travis.yml
config/level/php/php74.yaml
packages/Php/src/Rector/Function_/ReservedFnFunctionRector.php
packages/Php/tests/Rector/Function_/ReservedFnFunctionRector/Fixture/fixture.php.inc
packages/Php/tests/Rector/Function_/ReservedFnFunctionRector/ReservedFnFunctionRectorTest.php

[PHP 7.4] Add ReservedFnFunctionRector

---

config/level/php/php56.yaml
packages/Php/src/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector.php
packages/Php/src/Rector/Function_/ReservedFnFunctionRector.php
packages/Php/tests/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/AddDefaultValueForUndefinedVariableRectorTest.php
packages/Php/tests/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/Fixture/fixture.php.inc
packages/Php/tests/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/Fixture/in_foreach.php.inc
packages/Php/tests/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/Fixture/keep_vimeo_unset.php.inc
packages/Php/tests/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/Fixture/vimeo_else.php.inc
packages/Php/tests/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/Fixture/vimeo_one.php.inc
packages/Php/tests/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/Fixture/vimeo_two.php.inc

[PHP] Add AddDefaultValueForUndefinedVariableRector

---

packages/CodeQuality/src/Rector/Array_/CallableThisArrayToAnonymousFunctionRector.php
packages/CodeQuality/src/Rector/Identical/BooleanNotIdenticalToNotIdenticalRector.php
packages/CodingStyle/src/Rector/ClassConst/SplitGroupedConstantsAndPropertiesRector.php
packages/CodingStyle/src/Rector/Namespace_/ImportFullyQualifiedNamesRector.php
packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/already_class_name.php.inc
packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/conflicting_endings.php.inc
packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/doc_combined.php.inc
packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/import_param_doc.php.inc
packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/import_return_doc.php.inc
packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/keep.php.inc
packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/keep_same_end.php.inc
packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/ImportFullyQualifiedNamesRectorTest.php
packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Source/AlreadyClassName.php
packages/Nette/src/Rector/Identical/EndsWithFunctionToNetteUtilsStringsRector.php
packages/Nette/src/Rector/Identical/StartsWithFunctionToNetteUtilsStringsRector.php
packages/Nette/src/Rector/NotIdentical/StrposToStringsContainsRector.php
packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
packages/Php/src/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector.php
packages/RemovingStatic/src/Rector/Class_/NewUniqueObjectToEntityFactoryRector.php
packages/RemovingStatic/src/Rector/Class_/PHPUnitStaticToKernelTestCaseGetRector.php
packages/RemovingStatic/src/Rector/Class_/PassFactoryToUniqueObjectRector.php
packages/RemovingStatic/src/Rector/Class_/StaticTypeToSetterInjectionRector.php
packages/SOLID/src/Rector/Class_/FinalizeClassesWithoutChildrenRector.php
packages/Symfony/src/Rector/MethodCall/SimplifyWebTestCaseAssertionsRector.php
src/NodeContainer/ParsedNodesByType.php
src/PhpParser/Node/BetterNodeFinder.php
src/PhpParser/Node/Manipulator/PropertyFetchManipulator.php

[CodingStyle] Fix interface short name identical with class name in ImportFullyQualifiedNamesRector

---

ecs.yaml
src/Rector/Class_/RenameClassRector.php
src/Rector/Psr4/MultipleClassFileToPsr4ClassesRector.php
tests/Rector/Psr4/MultipleClassFileToPsr4ClassesRector/Expected/Miss.php
tests/Rector/Psr4/MultipleClassFileToPsr4ClassesRector/Expected/Named.php
tests/Rector/Psr4/MultipleClassFileToPsr4ClassesRector/MultipleClassFileToPsr4ClassesRectorTest.php
tests/Rector/Psr4/MultipleClassFileToPsr4ClassesRector/Source/MissNamed.php

Fix file removal in MultipleClassFileToPsr4ClassesRector

---

config/level/dead-code/dead-code.yaml
packages/DeadCode/src/Rector/BooleanAnd/RemoveAndTrueRector.php
packages/DeadCode/tests/Rector/BooleanAnd/RemoveAndTrueRector/Fixture/fixture.php.inc
packages/DeadCode/tests/Rector/BooleanAnd/RemoveAndTrueRector/Fixture/keep_something.php.inc
packages/DeadCode/tests/Rector/BooleanAnd/RemoveAndTrueRector/RemoveAndTrueRectorTest.php

[DeadCode] Add RemoveAndTrueRector

---

config/level/code-quality/code-quality.yaml
config/level/symfony/symfony-code-quality.yaml
packages/CodeQuality/src/Rector/LogicalAnd/AndAssignsToSeparateLinesRector.php
packages/CodeQuality/tests/Rector/LogicalAnd/AndAssignsToSeparateLinesRector/AndAssignsToSeparateLinesRectorTest.php
packages/CodeQuality/tests/Rector/LogicalAnd/AndAssignsToSeparateLinesRector/Fixture/fixture.php.inc
packages/CodeQuality/tests/Rector/LogicalAnd/AndAssignsToSeparateLinesRector/Fixture/keep_in_condition.php.inc
packages/ContributorTools/src/Configuration/ConfigurationFactory.php

[CodeQuality] Add AndAssignsToSeparateLinesRector

---

config/level/symfony/symfony43.yaml
packages/Symfony/src/Rector/MethodCall/MakeDispatchFirstArgumentEventRector.php
packages/Symfony/tests/Rector/MethodCall/MakeDispatchFirstArgumentEventRector/Fixture/fixture.php.inc
packages/Symfony/tests/Rector/MethodCall/MakeDispatchFirstArgumentEventRector/MakeDispatchFirstArgumentEventRectorTest.php

Closes #1383 
See https://symfony.com/blog/new-in-symfony-4-3-simpler-event-dispatching

[Symfony 4.3] Add swapped dispatch() arguments for EventDispatcher

---

packages/CodingStyle/src/Rector/String_/SplitStringClassConstantToClassConstFetchRector.php

[SplitStringClassConstantToClassConstFetchRector] Remove duplicated namespace separator

---

config/level/php/php71.yaml
packages/Php/src/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector.php
packages/Php/tests/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/BinaryOpBetweenNumberAndStringRectorTest.php
packages/Php/tests/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/Fixture/fixture.php.inc

[PHP 7.1] Add BinaryOpBetweenNumberAndStringRector

---

packages/NodeTypeResolver/src/NodeTypeResolver.php
packages/Php/src/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector.php
packages/Php/tests/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/Fixture/fixture.php.inc
src/Rector/NodeTypeResolverTrait.php

[PHP 7.1] Add float to BinaryOpBetweenNumberAndStringRector

---

config/level/php/php73.yaml
packages/Php/src/Rector/FuncCall/RemoveMissingCompactVariableRector.php
packages/Php/tests/Rector/FuncCall/RemoveMissingCompactVariableRector/Fixture/fixture.php.inc
packages/Php/tests/Rector/FuncCall/RemoveMissingCompactVariableRector/Fixture/skip_maybe_defined.inc
packages/Php/tests/Rector/FuncCall/RemoveMissingCompactVariableRector/RemoveMissingCompactVariableRectorTest.php

[PHP] Add RemoveMissingCompactVariableRector

---

.github/FUNDING.yml

Ref
- https://twitter.com/github/status/1131477404843741184
- https://twitter.com/github/status/1131477029730308096

[supporŧ] add funding Github - news from Github Satellite

---

tests/Rector/Psr4/MultipleClassFileToPsr4ClassesRector/Expected/SomeClass.php
tests/Rector/Psr4/MultipleClassFileToPsr4ClassesRector/Expected/SomeClass_Exception.php
tests/Rector/Psr4/MultipleClassFileToPsr4ClassesRector/MultipleClassFileToPsr4ClassesRectorTest.php
tests/Rector/Psr4/MultipleClassFileToPsr4ClassesRector/Source/SomeClass.php

[MultipleClassFileToPsr4ClassesRector] Original file is deleted even if class matches filename

---

config/level/coding-style/coding-style.yaml
config/level/php/php55.yaml
packages/Php/src/Rector/String_/StringClassNameToClassConstantRector.php
packages/Php/tests/Rector/String_/StringClassNameToClassConstantRector/Fixture/fixture.php.inc
packages/Php/tests/Rector/String_/StringClassNameToClassConstantRector/Fixture/skip_error.php.inc
packages/Php/tests/Rector/String_/StringClassNameToClassConstantRector/StringClassNameToClassConstantRectorTest.php
src/Util/RectorStrings.php

[PHP][CodingStyle] string class to ::class

---

packages/Php/src/Rector/String_/StringClassNameToClassConstantRector.php
phpstan.neon
src/Configuration/Configuration.php
src/Configuration/Option.php
src/Console/Command/ProcessCommand.php
src/Console/Output/ConsoleOutputFormatter.php
src/Console/Output/OutputFormatterCollector.php
src/Contract/Console/Output/OutputFormatterInterface.php
src/Exception/Console/Output/MissingOutputFormatterException.php

introduce OutputFormatterCollector to allow extension of output formatters

---

composer.json
packages/Php/tests/Rector/Closure/ClosureToArrowFunctionRector/ClosureToArrowFunctionRectorTest.php
packages/Php/tests/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/ArraySpreadInsteadOfArrayMergeRectorTest.php
packages/PhpSpecToPHPUnit/tests/Rector/Class_/PhpSpecToPHPUnitRector/Fixture/mock_method_call_arguments.php.inc
src/PhpParser/Printer/BetterStandardPrinter.php

Ref https://github.com/nikic/PHP-Parser/tree/v4.2.2
:tada: 
```diff
-function ($x, $y) { return $x + $y; }
+fn => $x + $y;
```
```diff
-return iterator_to_array($values);
+return ...$values;
```

update to php-parser 4.2.2

---

composer.json

@JanMikes For your long contribution for Rector ecosystem in both its code and PHP community, I've decided to add you among authors.
Could you review? :)

composer: add authors

---

config/level/coding-style/coding-style.yaml
packages/CodingStyle/src/Naming/ClassNaming.php
packages/CodingStyle/src/Rector/Catch_/CatchExceptionNameMatchingTypeRector.php
packages/CodingStyle/tests/Rector/Catch_/CatchExceptionNameMatchingTypeRector/CatchExceptionNameMatchingTypeRectorTest.php
packages/CodingStyle/tests/Rector/Catch_/CatchExceptionNameMatchingTypeRector/Fixture/fixture.php.inc
packages/CodingStyle/tests/Rector/Catch_/CatchExceptionNameMatchingTypeRector/Fixture/skip.php.inc

[CodingStyle] Add CatchExceptionNameMatchingTypeRector

---

config/level/coding-style/coding-style.yaml
packages/CodingStyle/src/Rector/Property/ArrayPropertyDefaultValueRector.php
packages/CodingStyle/tests/Rector/Property/ArrayPropertyDefaultValueRector/ArrayPropertyDefaultValueRectorTest.php
packages/CodingStyle/tests/Rector/Property/ArrayPropertyDefaultValueRector/Fixture/fixture.php.inc
packages/CodingStyle/tests/Rector/Property/ArrayPropertyDefaultValueRector/Fixture/skip.php.inc
packages/CodingStyle/tests/Rector/Property/ArrayPropertyDefaultValueRector/Fixture/static_property.php.inc
packages/NodeTypeResolver/src/Php/VarTypeInfo.php

Ref #1466
```diff
/**
* @var int[]
*/
-private $values;
+private $values = [];
```

[CodingStyle] Add ArrayPropertyDefaultValueRector

---

config/level/code-quality/code-quality.yaml
docs/AllRectorsOverview.md
packages/CodeQuality/src/Rector/Class_/CompleteDynamicPropertiesRector.php
packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/CompleteDynamicPropertiesRectorTest.php
packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/Fixture/fixture.php.inc
packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/Fixture/multiple_types.php.inc
packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/Fixture/skip_defined.php.inc
packages/Php/src/Rector/Property/TypedPropertyRector.php

Closes #1476
```diff
{
+    /**
+     * @var string
+     */
+    public $outputFormat;
{
$this->outputFormat = 'name';
}
}
```
```diff
{
+    public string $outputFormat;
{
$this->outputFormat = 'name';
}
}
```

🎉 Rule #300  - [CodeQuality] Add CompleteDynamicPropertiesRector

---

config/level/symfony/symfony43.yaml

[Symfony 4.3] Add class renames, method renames and added arguments

---

packages/Php/tests/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/AddDefaultValueForUndefinedVariableRectorTest.php
packages/Php/tests/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/Fixture/take_static_into_account.php.inc

Ensure `static` variables are considered as declared.

---

packages/Php/src/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector.php
packages/Php/tests/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/Fixture/ignore_concatenation_dot.php.inc

[PHP] Fix BinaryOpBetweenNumberAndStringRector for concat

---

packages/CodeQuality/src/Rector/Array_/CallableThisArrayToAnonymousFunctionRector.php
packages/CodeQuality/src/Rector/Class_/CompleteDynamicPropertiesRector.php
packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/CompleteDynamicPropertiesRectorTest.php
packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/Fixture/skip_parent_property.php.inc
packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/Fixture/skip_trait_used.php.inc
packages/Php/src/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector.php

[CodeQuality] Add trait and parent class support for CompleteDynamicPropertiesRector

---

config/level/symfony/symfony43.yaml
packages/DomainDrivenDesign/src/Rector/ObjectToScalar/ObjectToScalarDocBlockRector.php
packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
src/Rector/Class_/RenameClassRector.php

fix RenameClassRector to change only direct class names, not children

---

docs/AllRectorsOverview.md
packages/ContributorTools/src/Finder/RectorsFinder.php

make RectorsFinder return consistent order by shorter names

---

packages/Php/tests/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/AddDefaultValueForUndefinedVariableRectorTest.php
packages/Php/tests/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/Fixture/anonymous_function.php.inc

Failing test for anonymous functions.

---

packages/Php/tests/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector/Fixture/with_only_static_methods.php.inc
packages/Php/tests/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector/Source/WithOnlyStaticMethods.php
packages/Php/tests/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector/StaticCallOnNonStaticToInstanceCallRectorTest.php

Really ignore really static methods.

---

packages/BetterPhpDocParser/src/PhpDocParser/BetterPhpDocParser.php
packages/BetterPhpDocParser/src/Printer/MultilineSpaceFormatPreserver.php
packages/BetterPhpDocParser/src/Printer/PhpDocInfoPrinter.php
packages/BetterPhpDocParser/tests/PhpDocInfo/PhpDocInfoPrinterSource/multiline6.txt
packages/BetterPhpDocParser/tests/PhpDocInfo/PhpDocInfoPrinterTest.php

Closes #1532
More details on the issue:
- https://github.com/rectorphp/rector/issues/1532#issuecomment-498582361

Fix phpdoc-parser BC break for generic multiline nodes

---

packages/BetterPhpDocParser/src/Printer/PhpDocInfoPrinter.php
packages/BetterPhpDocParser/tests/PhpDocInfo/PhpDocInfoPrinterSource/doc14.txt
packages/BetterPhpDocParser/tests/PhpDocInfo/PhpDocInfoPrinterTest.php

fix unescaped regular

---

packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Fixture/different_namespaces_same_name.php.inc
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/RemoveUnusedAliasRectorTest.php
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Source/DifferentNamespace/StandaloneClass.php

Don't remove aliases of classes with same name but different namespaces.

---

packages/CodeQuality/src/Rector/Class_/CompleteDynamicPropertiesRector.php
packages/CodeQuality/src/Rector/For_/ForToForeachRector.php
packages/CodeQuality/src/Rector/Foreach_/ForeachToInArrayRector.php
packages/CodingStyle/src/Rector/Catch_/CatchExceptionNameMatchingTypeRector.php
packages/CodingStyle/src/Rector/Use_/RemoveUnusedAliasRector.php
packages/NetteToSymfony/src/Rector/Class_/NetteControlToSymfonyControllerRector.php
packages/Php/src/Rector/Assign/AssignArrayToStringRector.php
packages/Php/src/Rector/FuncCall/ParseStrWithResultArgumentRector.php
packages/Php/src/Rector/FuncCall/PregReplaceEModifierRector.php
packages/Php/src/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector.php
packages/RemovingStatic/src/Rector/Class_/NewUniqueObjectToEntityFactoryRector.php
packages/RemovingStatic/src/Rector/Class_/PHPUnitStaticToKernelTestCaseGetRector.php
packages/Symfony/src/Rector/Class_/MakeCommandLazyRector.php
packages/Twig/src/Rector/SimpleFunctionAndFilterRector.php
src/PhpParser/NodeTraverser/CallableNodeTraverser.php
src/Rector/AbstractRectorTrait.php
src/Rector/CallableNodeTraverserTrait.php

add CallableNodeTraverserTrait

---

packages/Php/src/Rector/String_/StringClassNameToClassConstantRector.php
packages/Php/tests/Rector/String_/StringClassNameToClassConstantRector/Fixture/skip_sensitive.php.inc
packages/Php/tests/Rector/String_/StringClassNameToClassConstantRector/StringClassNameToClassConstantRectorTest.php

make StringClassNameToClassConstantRector case sensitive [closes #1539]

---

config/level/solid/solid.yaml

Currently solid.yaml references to not existed class. This PR fix this

Fix solid.yaml

---

packages/DeadCode/src/Rector/Concat/RemoveConcatAutocastRector.php
packages/NodeTypeResolver/src/NodeTypeResolver.php
tests/Rector/ClassMethod/AddMethodParentCallRector/AddMethodParentCallRectorTest.php
tests/Rector/MethodCall/RenameMethodRector/Fixture/under_anonymous_class.php.inc
tests/Rector/MethodCall/RenameMethodRector/RenameMethodRectorTest.php

Fix anonymous class method return type resolving

---

packages/NodeTypeResolver/src/NodeTypeResolver.php
packages/Php/src/Rector/FuncCall/CountOnNullRector.php
packages/Php/tests/Rector/FuncCall/CountOnNullRector/CountOnNullRectorTest.php
packages/Php/tests/Rector/FuncCall/CountOnNullRector/Fixture/local_property.php.inc
packages/Php/tests/Rector/FuncCall/CountOnNullRector/Fixture/nullable_array.php.inc
packages/Php/tests/Rector/FuncCall/CountOnNullRector/Fixture/property_with_doc.php.inc
packages/Php/tests/Rector/FuncCall/CountOnNullRector/Fixture/skip_array_merge.php.inc

Fix CountOnNullRector for nullable and invalid property

---

config/set/dead-code/dead-code.yaml
packages/DeadCode/src/Rector/Plus/RemoveDeadZeroAndOneOperationRector.php
packages/DeadCode/tests/Rector/Plus/RemoveDeadZeroAndOneOperationRector/Fixture/assigns.php.inc
packages/DeadCode/tests/Rector/Plus/RemoveDeadZeroAndOneOperationRector/Fixture/fixture.php.inc
packages/DeadCode/tests/Rector/Plus/RemoveDeadZeroAndOneOperationRector/Fixture/multiple.php.inc
packages/DeadCode/tests/Rector/Plus/RemoveDeadZeroAndOneOperationRector/Fixture/skip_floats.php.inc
packages/DeadCode/tests/Rector/Plus/RemoveDeadZeroAndOneOperationRector/Fixture/skip_type_change.php.inc
packages/DeadCode/tests/Rector/Plus/RemoveDeadZeroAndOneOperationRector/RemoveDeadZeroAndOneOperationRectorTest.php
packages/NodeTypeResolver/src/NodeTypeResolver.php
src/Rector/ClassMethod/AddMethodParentCallRector.php

[DeadCode] Add RemoveDeadZeroAndOneOperationRector

---

packages/DeadCode/src/Rector/StaticCall/RemoveParentCallWithoutParentRector.php
packages/DeadCode/tests/Rector/ClassMethod/RemoveDelegatingParentCallRector/Fixture/in_trait.php.inc
packages/DeadCode/tests/Rector/ClassMethod/RemoveDelegatingParentCallRector/RemoveDelegatingParentCallRectorTest.php
packages/DeadCode/tests/Rector/StaticCall/RemoveParentCallWithoutParentRector/Fixture/skip_trait.php.inc
packages/DeadCode/tests/Rector/StaticCall/RemoveParentCallWithoutParentRector/RemoveParentCallWithoutParentRectorTest.php
packages/Php/tests/Rector/List_/ListSwapArrayOrderRector/ListSwapArrayOrderRectorTest.php

Skip traits in RemoveParentCallWithoutParentRector

---

config/set/dead-code/dead-code.yaml
packages/DeadCode/src/Rector/Instanceof_/RemoveDuplicatedInstanceOfRector.php
packages/DeadCode/tests/Rector/Instanceof_/RemoveDuplicatedInstanceOfRector/Fixture/fixture.php.inc
packages/DeadCode/tests/Rector/Instanceof_/RemoveDuplicatedInstanceOfRector/Fixture/jump_around_one.php.inc
packages/DeadCode/tests/Rector/Instanceof_/RemoveDuplicatedInstanceOfRector/Fixture/nested.php.inc
packages/DeadCode/tests/Rector/Instanceof_/RemoveDuplicatedInstanceOfRector/Fixture/skip_multiple_variables.php.inc
packages/DeadCode/tests/Rector/Instanceof_/RemoveDuplicatedInstanceOfRector/RemoveDuplicatedInstanceOfRectorTest.php

[DeadCode] Add RemoveDuplicatedInstanceOfRector

---

composer.json
config/set/elasticsearch-dsl/elasticsearch-dsl50.yaml
config/set/shopware/shopware56.yaml
packages/ElasticSearchDSL/config/config.yaml
packages/ElasticSearchDSL/src/Rector/MethodCall/MigrateFilterToQueryRector.php
packages/ElasticSearchDSL/tests/Rector/MethodCall/MigrateFilterToQueryRector/Fixture/fixture.php.inc
packages/ElasticSearchDSL/tests/Rector/MethodCall/MigrateFilterToQueryRector/MigrateFilterToQueryRectorTest.php

Project Page https://github.com/ongr-io/ElasticsearchDSL

Add ElasticSearchDSL package

---

packages/DeadCode/src/Rector/ClassMethod/RemoveDelegatingParentCallRector.php
packages/DeadCode/src/Rector/FunctionLike/RemoveCodeAfterReturnRector.php
packages/DeadCode/src/Rector/Instanceof_/RemoveDuplicatedInstanceOfRector.php
packages/DeadCode/tests/Rector/FunctionLike/RemoveCodeAfterReturnRector/Fixture/keep_comment.php.inc
packages/DeadCode/tests/Rector/FunctionLike/RemoveCodeAfterReturnRector/RemoveCodeAfterReturnRectorTest.php
packages/ElasticSearchDSL/src/Rector/MethodCall/MigrateFilterToQueryRector.php
packages/ElasticSearchDSL/tests/Rector/MethodCall/MigrateFilterToQueryRector/MigrateFilterToQueryRectorTest.php
packages/Php/src/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector.php
packages/Shopware/src/Rector/ClassConstFetch/ShopwareVersionConstsRector.php
packages/Shopware/src/Rector/MethodCall/ShopRegistrationServiceRector.php
packages/Shopware/tests/Rector/ClassConstFetch/ShopwareVersionConstsRector/ShopwareVersionConstsRectorTest.php
packages/Shopware/tests/Rector/MethodCall/ShopRegistrationServiceRector/ShopRegistrationServiceRectorTest.php

[DeadCode] Fix removed comment after return at RemoveCodeAfterReturnRector

---

composer.json
packages/Php/src/Rector/FuncCall/RemoveExtraParametersRector.php
packages/Php/tests/Rector/FuncCall/RemoveExtraParametersRector/Fixture/skip_call_user_func_array.php.inc
packages/Php/tests/Rector/FuncCall/RemoveExtraParametersRector/RemoveExtraParametersRectorTest.php

[PHP] Fix class signature over interface priority in RemoveExtraParametersRector

---

packages/CodeQuality/src/Rector/Class_/CompleteDynamicPropertiesRector.php
packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/CompleteDynamicPropertiesRectorTest.php
packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/Fixture/skip_magic.php.inc
packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/Fixture/skip_magic_parent.php.inc
packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/Source/MagicParent.php

[CodeQuality] Fix __set/__get case for CompleteDynamicPropertiesRector

---

packages/Php/src/Rector/FuncCall/StringifyStrNeedlesRector.php
packages/Php/tests/Rector/FuncCall/StringifyStrNeedlesRector/Fixture/skip_twice.php.inc
packages/Php/tests/Rector/FuncCall/StringifyStrNeedlesRector/StringifyStrNeedlesRectorTest.php

[PHP] Fix StringifyStrNeedlesRector duplicated change

---

packages/Php/src/Rector/FuncCall/JsonThrowOnErrorRector.php
packages/Php/tests/Rector/FuncCall/JsonThrowOnErrorRector/Fixture/fixture.php.inc

[PHP] Fix JsonThrowOnErrorRector inter-args

---

packages/DeadCode/tests/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/skip_anonymous_function.php.inc
packages/DeadCode/tests/Rector/Property/RemoveUnusedPrivatePropertyRector/RemoveUnusedPrivatePropertyRectorTest.php

Add test case for #1630

---

composer.json
config/set/symfony/symfony-phpunit.yaml
packages/SymfonyPHPUnit/src/Rector/Class_/MultipleServiceGetToSetUpMethodRector.php
packages/SymfonyPHPUnit/tests/Rector/Class_/MultipleServiceGetToSetUpMethodRector/Fixture/existing_setup.php.inc
packages/SymfonyPHPUnit/tests/Rector/Class_/MultipleServiceGetToSetUpMethodRector/Fixture/extends_parent_class_with_property.php.inc
packages/SymfonyPHPUnit/tests/Rector/Class_/MultipleServiceGetToSetUpMethodRector/Fixture/fixture.php.inc
packages/SymfonyPHPUnit/tests/Rector/Class_/MultipleServiceGetToSetUpMethodRector/Fixture/instant_call.php.inc
packages/SymfonyPHPUnit/tests/Rector/Class_/MultipleServiceGetToSetUpMethodRector/MultipleServiceGetToSetUpMethodRectorTest.php
packages/SymfonyPHPUnit/tests/Rector/Class_/MultipleServiceGetToSetUpMethodRector/Source/DummyKernelTestCase.php
packages/SymfonyPHPUnit/tests/Rector/Class_/MultipleServiceGetToSetUpMethodRector/Source/ParentClassWithPropertyKernelTestCase.php

[SymfonyPHPUnit] Add MultipleServiceGetToSetUpMethodRector

---

config/set/symfony/symfony42.yaml
packages/Symfony/src/Bridge/DefaultAnalyzedSymfonyApplicationContainer.php
packages/Symfony/src/Bridge/SymfonyKernelParameterGuard.php
src/Rector/Class_/RenameClassRector.php
tests/Rector/Class_/RenameClassRector/Fixture/name_insensitive.php.inc

[Symfony] Make set symfony42 refactor get(...) in former container aware commands

---

composer.json
packages/BetterPhpDocParser/src/PhpDocInfo/PhpDocInfoFactory.php
packages/BetterPhpDocParser/src/Printer/PhpDocInfoPrinter.php
packages/CodeQuality/src/Rector/Assign/CombinedAssignRector.php
packages/DeadCode/src/Rector/For_/RemoveDeadIfForeachForRector.php
packages/NodeTypeResolver/src/PHPStan/Type/TypeToStringResolver.php
packages/NodeTypeResolver/src/PerNodeTypeResolver/NameTypeResolver.php
packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/FqnNamePhpDocNodeDecorator.php
packages/PHPUnit/src/Rector/SpecificMethod/AssertFalseStrposToContainsRector.php
packages/PHPUnit/src/Rector/SpecificMethod/AssertPropertyExistsRector.php
packages/PhpSpecToPHPUnit/src/Rector/ClassMethod/PhpSpecMethodToPHPUnitMethodRector.php
packages/RemovingStatic/src/Rector/Class_/StaticTypeToSetterInjectionRector.php
packages/Symfony/src/Rector/Form/OptionNameRector.php
packages/Symfony/src/Rector/MethodCall/SimplifyWebTestCaseAssertionsRector.php
packages/SymfonyPHPUnit/src/Rector/Class_/MultipleServiceGetToSetUpMethodRector.php
phpstan.neon
src/Php/Regex/RegexPatternArgumentManipulator.php
src/PhpParser/NodeTransformer.php
src/Rector/Architecture/RepositoryAsService/ServiceLocatorToDIRector.php
src/Rector/MethodCall/RenameMethodCallRector.php
src/Reflection/FunctionReflectionResolver.php

Bump to phpstan 0.11.9
- https://github.com/phpstan/phpstan/tree/0.11.9

fix new phpstan reports

---

config/set/code-quality/code-quality.yaml
packages/CodeQuality/src/Rector/FuncCall/StrlenZeroToIdenticalEmptyStringRector.php
packages/CodeQuality/tests/Rector/FuncCall/StrlenZeroToIdenticalEmptyStringRector/Fixture/fixture.php.inc
packages/CodeQuality/tests/Rector/FuncCall/StrlenZeroToIdenticalEmptyStringRector/StrlenZeroToIdenticalEmptyStringRectorTest.php

[CodeQuality] Add StrlenZeroToIdenticalEmptyStringRector

---

composer.json
config/set/architecture/constructor-injectin-to-action-injection.yaml
ecs.yaml
packages/Architecture/config/config.yaml
packages/Architecture/src/Cleaner/ClassMethodCleaner.php
packages/Architecture/src/Rector/Class_/ConstructorInjectionToActionInjectionRector.php
packages/Architecture/tests/Rector/Class_/ConstructorInjectionToActionInjectionRector/ConstructorInjectionToActionInjectionRectorTest.php
packages/Architecture/tests/Rector/Class_/ConstructorInjectionToActionInjectionRector/Fixture/duplicate.php.inc
packages/Architecture/tests/Rector/Class_/ConstructorInjectionToActionInjectionRector/Fixture/fixture.php.inc
packages/Architecture/tests/Rector/Class_/ConstructorInjectionToActionInjectionRector/Fixture/manage_different_naming.php.inc
packages/Architecture/tests/Rector/Class_/ConstructorInjectionToActionInjectionRector/Fixture/skip_non_action_methods.php.inc
packages/Architecture/tests/Rector/Class_/ConstructorInjectionToActionInjectionRector/Fixture/skip_scalars.php.inc
src/PhpParser/Node/Manipulator/ClassManipulator.php

[Architecture] Add ConstructorInjectionToActionInjectionRector

---

packages/NodeTypeResolver/src/PerNodeTypeResolver/NameTypeResolver.php

It was broken on `master` branch.

Fix NameTypeResolver@resolveFullyQualifiedName return type

---

.travis.yml
composer.json
docs/AllRectorsOverview.md
docs/NodesOverview.md

Fixed wrong naming of docs script in composer.json

---

ecs.yaml
packages/CodeQuality/tests/Rector/If_/ExplicitBoolCompareRector/Fixture/string.php.inc
packages/DeadCode/src/Rector/ClassMethod/RemoveUnusedPrivateMethodRector.php
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/skip_array_callables.php.inc
packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/RemoveUnusedPrivateMethodRectorTest.php
src/NodeContainer/ParsedNodesByType.php

[DeadCode] Keep array method call in RemoveUnusedPrivateMethodRector

---

config/set/doctrine/doctrine-services.yaml
src/Rector/MethodCall/ServiceGetterToConstructorInjectionRector.php
tests/Rector/MethodCall/ServiceGetterToConstructorInjectionRector/Fixture/fixture.php.inc
tests/Rector/MethodCall/ServiceGetterToConstructorInjectionRector/ServiceGetterToConstructorInjectionRectorTest.php
tests/Rector/MethodCall/ServiceGetterToConstructorInjectionRector/Source/AnotherService.php
tests/Rector/MethodCall/ServiceGetterToConstructorInjectionRector/Source/FirstService.php

[Generic] Add ServiceGetterToConstructorInjectionRector

---

config/set/coding-style/coding-style.yaml
packages/CodingStyle/src/Rector/Encapsed/EncapsedStringsToSprintfRector.php
packages/CodingStyle/tests/Rector/Encapsed/EncapsedStringsToSprintfRector/EncapsedStringsToSprintfRectorTest.php
packages/CodingStyle/tests/Rector/Encapsed/EncapsedStringsToSprintfRector/Fixture/fixture.php.inc
packages/CodingStyle/tests/Rector/Encapsed/EncapsedStringsToSprintfRector/Fixture/numberz.php.inc

[CodingStyle] Add EncapsedStringsToSprintfRector

---

packages/CodeQuality/src/Rector/Class_/CompleteDynamicPropertiesRector.php
packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/CompleteDynamicPropertiesRectorTest.php
packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/Fixture/skip_laravel_closure_binding.php.inc
src/PhpParser/Node/BetterNodeFinder.php
src/Rector/AbstractRector/AbstractRectorTrait.php
src/Rector/MethodCall/ServiceGetterToConstructorInjectionRector.php

skip Illuminate\Support\Collection magic for CompleteDynamicPropertiesRector

---

.gitattributes

Tell GitHub to syntax highlight .neon files.

Colorify neon files

---

tests/Rector/Property/InjectAnnotationClassRector/Fixture/inject_from_var3.php.inc
tests/Rector/Property/InjectAnnotationClassRector/InjectAnnotationClassRectorTest.php

As reported in https://github.com/rectorphp/rector/issues/1729

Add failing test to demonstrate difference in import order

---

.travis.yml
packages/BetterPhpDocParser/src/Attributes/Attribute/Attribute.php
packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/FqnNamePhpDocNodeDecorator.php
packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/NamespaceAnalyzer.php
packages/Php/src/Rector/FuncCall/RemoveMissingCompactVariableRector.php
tests/Rector/Property/InjectAnnotationClassRector/Fixture/inject_from_var3.php.inc
tests/Rector/Property/InjectAnnotationClassRector/InjectAnnotationClassRectorTest.php

Fix InjectAnnotationClassRector with aliases

---

packages/BetterPhpDocParser/src/Attributes/Ast/AttributeAwareNodeFactory.php
packages/BetterPhpDocParser/src/Attributes/Ast/PhpDoc/AttributeAwareParamTagValueNode.php
packages/BetterPhpDocParser/src/PhpDocParser/BetterPhpDocParser.php

add reference support to ParamTypeDeclarationRector

---

packages/CodeQuality/src/Rector/Class_/CompleteDynamicPropertiesRector.php
packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/CompleteDynamicPropertiesRectorTest.php
packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/Fixture/skip_dynamic_properties.php.inc

[CodeQuality] Fix CompleteDynamicPropertiesRector for dynamic property fetch

---

config/set/code-quality/code-quality.yaml
ecs.yaml
packages/CodeQuality/src/Rector/Class_/CompleteDynamicPropertiesRector.php
packages/CodeQuality/src/Rector/If_/RemoveAlwaysTrueConditionSetInConstructorRector.php
packages/CodeQuality/tests/Rector/If_/RemoveAlwaysTrueConditionSetInConstructorRector/Fixture/fixture.php.inc
packages/CodeQuality/tests/Rector/If_/RemoveAlwaysTrueConditionSetInConstructorRector/Fixture/multiple_lines.php.inc
packages/CodeQuality/tests/Rector/If_/RemoveAlwaysTrueConditionSetInConstructorRector/Fixture/multiple_lines_in_callable.php.inc
packages/CodeQuality/tests/Rector/If_/RemoveAlwaysTrueConditionSetInConstructorRector/Fixture/multiple_lines_removed.php.inc
packages/CodeQuality/tests/Rector/If_/RemoveAlwaysTrueConditionSetInConstructorRector/Fixture/numbers.php.inc
packages/CodeQuality/tests/Rector/If_/RemoveAlwaysTrueConditionSetInConstructorRector/Fixture/skip_changed_value.php.inc
packages/CodeQuality/tests/Rector/If_/RemoveAlwaysTrueConditionSetInConstructorRector/Fixture/skip_optional_argument_value.php.inc
packages/CodeQuality/tests/Rector/If_/RemoveAlwaysTrueConditionSetInConstructorRector/Fixture/skip_scalars.php.inc
packages/CodeQuality/tests/Rector/If_/RemoveAlwaysTrueConditionSetInConstructorRector/Fixture/skip_unknown.php.inc
packages/CodeQuality/tests/Rector/If_/RemoveAlwaysTrueConditionSetInConstructorRector/Fixture/strings.php.inc
packages/CodeQuality/tests/Rector/If_/RemoveAlwaysTrueConditionSetInConstructorRector/Fixture/various_types.php.inc
packages/CodeQuality/tests/Rector/If_/RemoveAlwaysTrueConditionSetInConstructorRector/RemoveAlwaysTrueConditionSetInConstructorRectorTest.php
packages/CodingStyle/src/Rector/ClassConst/VarConstantCommentRector.php
packages/CodingStyle/src/Rector/Encapsed/EncapsedStringsToSprintfRector.php
packages/DeadCode/src/Rector/ClassMethod/RemoveUnusedParameterRector.php
packages/NodeTypeResolver/src/NodeTypeResolver.php
packages/NodeTypeResolver/src/PHPStan/Type/StaticTypeAnalyzer.php
packages/NodeTypeResolver/src/PHPStan/Type/StaticTypeToStringResolver.php
packages/NodeTypeResolver/src/PerNodeTypeResolver/VariableTypeResolver.php
packages/NodeTypeResolver/src/StaticTypeToStringResolver.php
rector.yaml
src/NodeContainer/ParsedNodesByType.php
src/PhpParser/Printer/BetterStandardPrinter.php

[CodeQuality] Add RemoveAlwaysTrueConditionSetInConstructorRector

---

config/set/dead-code/dead-code.yaml
packages/DeadCode/src/Rector/Switch_/RemoveDuplicatedCaseInSwitchRector.php
packages/DeadCode/tests/Rector/Switch_/RemoveDuplicatedCaseInSwitchRector/Fixture/fixture.php.inc
packages/DeadCode/tests/Rector/Switch_/RemoveDuplicatedCaseInSwitchRector/RemoveDuplicatedCaseInSwitchRectorTest.php

[DeadCode] Add RemoveDuplicatedCaseInSwitchRector

---

config/set/laravel/laravel53.yaml

fix laravel53 config

---

packages/CodingStyle/src/Rector/Switch_/BinarySwitchToIfElseRector.php
packages/CodingStyle/tests/Rector/Switch_/BinarySwitchToIfElseRector/BinarySwitchToIfElseRectorTest.php
packages/CodingStyle/tests/Rector/Switch_/BinarySwitchToIfElseRector/Fixture/extra_break.php.inc

[CodingStyle] remove extra break from BinarySwitchToIfElseRector

---

packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/Fixture/doctrine_relation.php.inc

Doctrine ToOne are nullable by default

failing testcase for PropertyTypeDeclarationRector

---

packages/TypeDeclaration/src/Rector/FunctionLike/ReturnTypeDeclarationRector.php
phpstan.neon
src/PhpParser/Node/Manipulator/FunctionLikeManipulator.php

add iterable return type for yield values in ReturnTypeDeclarationRector

---

packages/TypeDeclaration/src/PropertyTypeInferer/DoctrineRelationPropertyTypeInferer.php
packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/Fixture/doctrine_relation_target_entity_same_namespace.php.inc
packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/Fixture/doctrine_relation_to_many.php.inc
packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/Fixture/doctrine_relation_to_one.php.inc
packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/PropertyTypeDeclarationRectorTest.php

fix nullable for xToOne annotation by default

---

packages/TypeDeclaration/src/PropertyTypeInferer/ConstructorPropertyTypeInferer.php
packages/TypeDeclaration/src/PropertyTypeInferer/DoctrineRelationPropertyTypeInferer.php
packages/TypeDeclaration/src/PropertyTypeInferer/SingleMethodAssignedNodePropertyTypeInferer.php
packages/TypeDeclaration/src/Rector/Property/PropertyTypeDeclarationRector.php
packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/PropertyTypeDeclarationRectorTest.php

fix nullable array type param for PropertyTypeDeclarationRector

---

packages/TypeDeclaration/src/PropertyTypeInferer/DoctrineRelationPropertyTypeInferer.php
packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/Fixture/doctrine_relation_target_entity_same_namespace.php.inc
packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/PropertyTypeDeclarationRectorTest.php

resolve target entity from same namespace

---

config/set/nette/nette-utils-code-quality.yaml
packages/Nette/src/Rector/FuncCall/JsonDecodeEncodeToNetteUtilsJsonDecodeEncodeRector.php
packages/Nette/tests/Rector/FuncCall/JsonDecodeEncodeToNetteUtilsJsonDecodeEncodeRector/Fixture/json_decode.php.inc
packages/Nette/tests/Rector/FuncCall/JsonDecodeEncodeToNetteUtilsJsonDecodeEncodeRector/Fixture/json_encode.php.inc
packages/Nette/tests/Rector/FuncCall/JsonDecodeEncodeToNetteUtilsJsonDecodeEncodeRector/JsonDecodeEncodeToNetteUtilsJsonDecodeEncodeRectorTest.php

[Nette] Add JsonDecodeEncodeToNetteUtilsJsonDecodeEncodeRector

---

packages/TypeDeclaration/src/Rector/FunctionLike/ParamTypeDeclarationRector.php
packages/TypeDeclaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/Fixture/skip_nullable_resource.php.inc
packages/TypeDeclaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/ParamTypeDeclarationRectorTest.php

Follow up of https://github.com/rectorphp/rector/commit/34e1a8d46588bcaba90b419214f2318b367ff471 that also ignores resource when it's nullable

Ignores resource also when type is nullable

---

config/set/type-declaration/type-declaration.yaml
packages/NodeTypeResolver/src/NodeTypeResolver.php
packages/NodeTypeResolver/src/Php/AbstractTypeInfo.php
packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
packages/TypeDeclaration/src/Contract/ParamTypeInfererInterface.php
packages/TypeDeclaration/src/ParamTypeInferer/GetterNodeParamTypeInferer.php
packages/TypeDeclaration/src/ParamTypeInferer/PropertyNodeParamTypeInferer.php
packages/TypeDeclaration/src/PhpDocParser/ParamPhpDocNodeFactory.php
packages/TypeDeclaration/src/PropertyTypeInferer/AllAssignNodePropertyTypeInferer.php
packages/TypeDeclaration/src/PropertyTypeInferer/ConstructorPropertyTypeInferer.php
packages/TypeDeclaration/src/PropertyTypeInferer/DefaultValuePropertyTypeInferer.php
packages/TypeDeclaration/src/PropertyTypeInferer/GetterOrSetterPropertyTypeInferer.php
packages/TypeDeclaration/src/PropertyTypeInferer/SingleMethodAssignedNodePropertyTypeInferer.php
packages/TypeDeclaration/src/Rector/ClassMethod/AddArrayParamDocTypeRector.php
packages/TypeDeclaration/src/TypeInferer/AbstractTypeInferer.php
packages/TypeDeclaration/tests/Rector/ClassMethod/AddArrayParamDocTypeRector/AddArrayParamDocTypeRectorTest.php
packages/TypeDeclaration/tests/Rector/ClassMethod/AddArrayParamDocTypeRector/Fixture/from_getter.php.inc
packages/TypeDeclaration/tests/Rector/ClassMethod/AddArrayParamDocTypeRector/Fixture/from_property.php.inc
packages/TypeDeclaration/tests/Rector/ClassMethod/AddArrayParamDocTypeRector/Fixture/keep_filled.php.inc
packages/TypeDeclaration/tests/Rector/ClassMethod/AddArrayParamDocTypeRector/Fixture/keep_mixed.php.inc
src/PhpParser/Node/Manipulator/PropertyFetchManipulator.php

[TypeDeclaration] Add AddArrayParamDocTypeRector

---

composer.json
config/set/php/php74.yaml
packages/Php/src/Rector/LNumber/AddLiteralSeparatorToNumberRector.php
packages/Php/tests/Rector/LNumber/AddLiteralSeparatorToNumberRector/AddLiteralSeparatorToNumberRectorTest.php
packages/Php/tests/Rector/LNumber/AddLiteralSeparatorToNumberRector/Fixture/fixture.php.inc
packages/Php/tests/Rector/LNumber/AddLiteralSeparatorToNumberRector/Fixture/skip_hexadecimal.php.inc
packages/Php/tests/Rector/LNumber/AddLiteralSeparatorToNumberRector/Fixture/skip_non_dec_simple_float_numbers.php.inc
phpstan.neon
src/Php/PhpVersionProvider.php
src/PhpParser/Printer/BetterStandardPrinter.php

* https://wiki.php.net/rfc/numeric_literal_separator
* https://github.com/nikic/PHP-Parser/pull/615
```diff
-1000000000
+1_000_000_000
```

[PHP 7.4] Add literal thousand superator

---

composer.json
config/set/psr-4/psr-4.yaml
docs/AllRectorsOverview.md
packages/PSR4/config/config.yaml
packages/PSR4/src/Collector/RenamedClassesCollector.php
packages/PSR4/src/Composer/PSR4AutoloadPathsProvider.php
packages/PSR4/src/Extension/RenamedClassesReportExtension.php
packages/PSR4/src/Rector/Namespace_/NormalizeNamespaceByPSR4ComposerAutoloadRector.php

Changes namespaces based on `composer.json`:
```diff
{
"autoload": {
-        "classmap": "src" 
+        "psr-4": {
+            "App\\": "src/"
+        }
}
}
```
- `src/SomeFile/File.php`
```diff
-namespace Blabla;
+namespace App\SomeFile;
class File
{
}
```

[PSR4] Add NormalizeNamespaceByPSR4ComposerAutoloadRector

---

src/FileSystem/FilesFinder.php

Remove the default excluded file patterns, change for #1815

Remove default excluded file patterns (closes #1815)

---

src/Rector/Property/RemoveDeadInitializationRector.php
tests/Rector/Property/RemoveDeadInitializationRector/Fixture/fixture.php.inc
tests/Rector/Property/RemoveDeadInitializationRector/RemoveDeadInitializationRectorTest.php

[DeadCode] Remove null value from property

---

packages/Php/src/Rector/MethodCall/PreferThisOrSelfMethodCallRector.php
packages/Php/tests/Rector/MethodCall/PreferThisOrSelfMethodCallRector/Fixture/to_this.php.inc
packages/SOLID/src/Rector/ClassConst/PrivatizeLocalClassConstantRector.php

Fix missing args in PreferThisOrSelfMethodCallRector

---

config/set/cakephp/cakephp40.yaml

* Add removed method renames
* Add a handful of return typehints
This isn't a complete list but it is a start with more to come as I upgrade do an upgrade on a small application I have.

Start CakePHP 4.0 rectors

---

composer.json

Move Jetbrains PhpStorm stubs into dev dependencies

---

config/set/cakephp/cakephp40.yaml

More renames that can be handled by rector.

Add more rectors for CakePHP 4.0

---

packages/Architecture/src/Rector/Class_/ConstructorInjectionToActionInjectionRector.php
packages/DeadCode/src/Rector/Class_/RemoveUnusedDoctrineEntityMethodAndPropertyRector.php
packages/Doctrine/src/Rector/Class_/ManagerRegistryGetManagerToEntityManagerRector.php
packages/Legacy/src/Rector/ClassMethod/ChangeSingletonToServiceRector.php
packages/PhpSpecToPHPUnit/src/Rector/Class_/PhpSpecClassToPHPUnitClassRector.php
phpstan.neon
src/PhpParser/Node/Manipulator/ClassManipulator.php
src/Rector/AbstractRector/NodeCommandersTrait.php

add removeNodeFromStatements() method to remove statement without key easily

---

config/set/cakephp/cakephp40.yaml

Refs https://github.com/cakephp/cakephp/pull/13664

Add rules for renaming CakePHP's Router methods

---

config/set/doctrine/doctrine-id-to-uuid-step-3.yaml
config/set/symfony/symfony34.yaml
packages/BetterPhpDocParser/src/PhpDocParser/Ast/PhpDoc/AbstractTagValueNode.php
packages/NetteToSymfony/src/PhpDocParser/Ast/PhpDoc/SymfonyMethodTagValueNode.php
packages/NetteToSymfony/src/PhpDocParser/Ast/PhpDoc/SymfonyRouteTagValueNode.php
packages/NetteToSymfony/src/Rector/ClassMethod/RouterListToControllerAnnotationsRector.php
packages/Symfony/src/PhpDocParser/Extension/SymfonyPhpDocParserExtension.php
packages/Symfony/src/PhpDocParser/SymfonyPhpDocTagParser.php
packages/Symfony/src/Rector/ClassMethod/MergeMethodAnnotationToRouteAnnotationRector.php
packages/Symfony/tests/Rector/ClassMethod/MergeMethodAnnotationToRouteAnnotationRector/Fixture/fixture.php.inc
packages/Symfony/tests/Rector/ClassMethod/MergeMethodAnnotationToRouteAnnotationRector/MergeMethodAnnotationToRouteAnnotationRectorTest.php
packages/TypeDeclaration/tests/Rector/ClassMethod/AddArrayReturnDocTypeRector/AddArrayReturnDocTypeRectorTest.php
packages/TypeDeclaration/tests/Rector/ClassMethod/AddArrayReturnDocTypeRector/Fixture/return_uuid.php.inc
packages/TypeDeclaration/tests/Rector/ClassMethod/AddArrayReturnDocTypeRector/Source/EntityReturningUuid.php
packages/ZendToSymfony/src/Rector/ClassMethod/GetParamToClassMethodParameterAndRouteRector.php
packages/ZendToSymfony/src/ValueObject/RouteValueObject.php
stubs/Symfony/Bundle/FrameworkExtraBundle/Configuration/ConfigurationAnnotation.php
stubs/Symfony/Bundle/FrameworkExtraBundle/Configuration/Method.php

[Symfony] Add MergeMethodAnnotationToRouteAnnotationRector

---

packages/Php71/src/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector.php
packages/Php71/tests/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/BinaryOpBetweenNumberAndStringRectorTest.php
packages/Php71/tests/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/Fixture/edge_case.php.inc
packages/Php71/tests/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/Fixture/fixture.php.inc

[PHP71] Fix BinaryOpBetweenNumberAndStringRector for variables

---

packages/DeadCode/src/Rector/Property/RemoveUnusedPrivatePropertyRector.php
packages/DeadCode/tests/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/skip_magically_accessed.php.inc
packages/DeadCode/tests/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/skip_magically_accessed_fetch.php.inc
packages/DeadCode/tests/Rector/Property/RemoveUnusedPrivatePropertyRector/RemoveUnusedPrivatePropertyRectorTest.php

[DeadCode] Skip magic property RemoveUnusedPrivatePropertyRector

---

src/Rector/Typehint/ParentTypehintedArgumentRector.php

fix parent typehint for anonymous class

---

packages/Php71/src/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector.php
packages/Php71/tests/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/BinaryOpBetweenNumberAndStringRectorTest.php
packages/Php71/tests/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/Fixture/fixture.php.inc
packages/Php71/tests/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/Fixture/known_static_string.php.inc

Fix numeric string type in BinaryOpBetweenNumberAndStringRector

---

docs/AllRectorsOverview.md
src/Rector/Namespace_/PseudoNamespaceToNamespaceRector.php
tests/Rector/Namespace_/PseudoNamespaceToNamespaceRector/Fixture/use_statement.php.inc
tests/Rector/Namespace_/PseudoNamespaceToNamespaceRector/PseudoNamespaceToNamespaceRectorTest.php

Fix pseudo namespace to namespace with use statement

---

packages/BetterPhpDocParser/config/config.yaml
packages/BetterPhpDocParser/src/PhpDocParser/BetterPhpDocParser.php
packages/BetterPhpDocParser/src/Printer/OriginalSpacingRestorer.php
packages/BetterPhpDocParser/src/Printer/PhpDocInfoPrinter.php
packages/BetterPhpDocParser/src/ValueObject/StartEndInfo.php
src/PhpDoc/PhpDocClassRenamer.php
src/PhpParser/Printer/BetterStandardPrinter.php

Fix printing of tab-indented files

---

.phpstorm.meta.php
packages/Renaming/src/Rector/Class_/RenameClassRector.php
packages/Renaming/tests/Rector/Class_/RenameClassRector/Fixture/fqnize_namespaced.php.inc
packages/Renaming/tests/Rector/Class_/RenameClassRector/RenameClassRectorTest.php

[Renaming] fqnize freshly namespaced class

---

config/set/monolog/monolog20.yaml

[Monolog] Add 2.0 upgrade set

---

config/set/coding-style/coding-style.yaml
packages/CodingStyle/src/Rector/FuncCall/CallUserFuncCallToVariadicRector.php
packages/CodingStyle/tests/Rector/FuncCall/CallUserFuncCallToVariadicRector/CallUserFuncCallToVariadicRectorTest.php
packages/CodingStyle/tests/Rector/FuncCall/CallUserFuncCallToVariadicRector/Fixture/fixture.php.inc

[CodingStyle] Add CallUserFuncCallToVariadicRector

---

packages/Restoration/src/Rector/ClassConstFetch/MissingClassConstantReferenceToStringRector.php
packages/Restoration/tests/Rector/ClassConstFetch/MissingClassConstantReferenceToStringRector/Fixture/fixture.php.inc
packages/Restoration/tests/Rector/ClassConstFetch/MissingClassConstantReferenceToStringRector/MissingClassConstantReferenceToStringRectorTest.php

[Restoration] Add MissingClassConstantReferenceToStringRector

---

config/set/celebrity/celebrity.yaml
packages/Php72/src/Rector/Unset_/UnsetCastRector.php
packages/Php72/tests/Rector/Unset_/UnsetCastRector/Fixture/unset_expr.php.inc
packages/Php72/tests/Rector/Unset_/UnsetCastRector/UnsetCastRectorTest.php

Inspired at https://github.com/PHPCompatibility/PHPModernizer/issues/8
Closes #2005

[Php72] improve UnsetCastRector

---

docs/AllRectorsOverview.md
docs/NodesOverview.md
packages/CodingStyle/src/Rector/FuncCall/StrictArraySearchRector.php
packages/CodingStyle/tests/Rector/FuncCall/StrictArraySearchRector/Fixture/fixture.php.inc
packages/CodingStyle/tests/Rector/FuncCall/StrictArraySearchRector/StrictArraySearchRectorTest.php

First try for https://github.com/rectorphp/rector/issues/2009
Not sure why it added extra rectors inside docs/AllRectorsOverview.md.
What do you think about the code?
---
EDIT by @tomasVotruba Closes #2009

Added StrictArraySearchRector - Issue #2009

---

composer.json
docs/AllRectorsOverview.md
docs/NodesOverview.md
packages/CodingStyle/src/Rector/Use_/RemoveUnusedAliasRector.php
packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Fixture/skip_vich_annotation.php.inc
packages/Renaming/src/Rector/Class_/RenameClassRector.php
stubs/Symfony/Component/Validator/Constraints/Length.php
stubs/Symfony/Component/Validator/Constraints/NotBlank.php
stubs/Vich/UploaderBundle/Mapping/Annotation/Uploadable.php

[CodingStyle] Skip common annotation aliases in RemoveUnusedAliasRector

---

packages/BetterPhpDocParser/src/PhpDocParser/BetterPhpDocParser.php
packages/PHPUnit/tests/Rector/Class_/AddSeeTestAnnotationRector/AddSeeTestAnnotationRectorTest.php
packages/PHPUnit/tests/Rector/Class_/AddSeeTestAnnotationRector/Fixture/surrounded_doc.php.inc

fix @TODO malfforms

---

.phpstorm.meta.php
config/set/dead-code/dead-code.yaml
packages/BetterPhpDocParser/src/PhpDocParser/AnnotationContentResolver.php
packages/CodeQuality/src/Rector/FuncCall/RemoveSoleValueSprintfRector.php
packages/CodingStyle/src/Application/UseAddingCommander.php
packages/CodingStyle/src/Application/UseImportsAdder.php
packages/CodingStyle/src/Node/NameImporter.php
packages/CodingStyle/src/Rector/Use_/RemoveUnusedAliasRector.php
packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/bootstrap_names.php.inc
packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/ImportFullyQualifiedNamesRectorTest.php
packages/DeadCode/src/Rector/For_/RemoveDeadIfForeachForRector.php
packages/DeadCode/src/Rector/Property/RemoveUnusedPrivatePropertyRector.php
packages/DeadCode/src/Rector/Stmt/RemoveUnreachableStatementRector.php
packages/DeadCode/tests/Rector/Stmt/RemoveUnreachableStatementRector/Fixture/after_return.php.inc
packages/DeadCode/tests/Rector/Stmt/RemoveUnreachableStatementRector/Fixture/after_throws.php.inc
packages/DeadCode/tests/Rector/Stmt/RemoveUnreachableStatementRector/Fixture/keep_comment.php.inc
packages/DeadCode/tests/Rector/Stmt/RemoveUnreachableStatementRector/Fixture/keep_false_positive_always_true_if.php.inc
packages/DeadCode/tests/Rector/Stmt/RemoveUnreachableStatementRector/Fixture/skip_condition_before.php.inc
packages/DeadCode/tests/Rector/Stmt/RemoveUnreachableStatementRector/Fixture/skip_marked_skipped_test_file.php.inc
packages/DeadCode/tests/Rector/Stmt/RemoveUnreachableStatementRector/RemoveUnreachableStatementRectorTest.php
packages/Doctrine/src/PhpDocParser/DoctrineDocBlockResolver.php
packages/NodeTypeResolver/src/Node/AttributeKey.php
packages/NodeTypeResolver/src/PHPStan/Scope/NodeScopeResolver.php
packages/Php53/src/Rector/FuncCall/DirNameFileConstantToDirConstantRector.php
packages/Symfony/src/Rector/Form/FormIsValidRector.php
rector.yaml
src/PhpDoc/PhpDocClassRenamer.php
src/PhpParser/Node/Manipulator/ClassManipulator.php
src/PhpParser/Node/Manipulator/PropertyFetchManipulator.php
src/Rector/Argument/ArgumentAdderRector.php

[DeadCode] Add RemoveUnreachableStatementRector

---

packages/CodingStyle/src/Rector/Assign/UseIncrementAssignRector.php
packages/Php73/src/Rector/FuncCall/StringifyStrNeedlesRector.php

fix stringy str needless for return strings

---

packages/PHPUnit/tests/Rector/SpecificMethod/AssertComparisonToSpecificMethodRector/Fixture/fixture.php.inc

Fixes: https://github.com/rectorphp/rector/issues/1726

Add fixture for phpunit x>y to greaterThan refactoring

---

ecs.yaml
packages/NodeTypeResolver/src/NodeTypeResolver.php
packages/Php71/tests/Rector/FuncCall/CountOnNullRector/CountOnNullRectorTest.php
packages/Php71/tests/Rector/FuncCall/CountOnNullRector/Fixture/skip_simple_xml_element.php.inc

Fix countable for countable classes without countable

---

packages/CodingStyle/src/Rector/ClassMethod/ReturnArrayClassMethodToYieldRector.php

keep comments in ReturnArrayClassMethodToYieldRector

---

packages/DeadCode/src/Rector/ClassMethod/RemoveDelegatingParentCallRector.php
packages/DeadCode/tests/Rector/ClassMethod/RemoveDelegatingParentCallRector/Fixture/skip_required.php.inc
packages/DeadCode/tests/Rector/ClassMethod/RemoveDelegatingParentCallRector/RemoveDelegatingParentCallRectorTest.php
phpstan.neon

skip required in delegating parent call method

---

packages/BetterPhpDocParser/src/PhpDocNode/AbstractTagValueNode.php
packages/BetterPhpDocParser/src/PhpDocNode/Doctrine/Class_/TableTagValueNode.php
packages/BetterPhpDocParser/src/PhpDocNode/Doctrine/Property_/JoinTableTagValueNode.php
packages/BetterPhpDocParser/src/PhpDocNodeFactory/AbstractPhpDocNodeFactory.php
packages/BetterPhpDocParser/src/PhpDocNodeFactory/Doctrine/Class_/TablePhpDocNodeFactory.php
packages/BetterPhpDocParser/src/PhpDocNodeFactory/Doctrine/Property_/JoinTablePhpDocNodeFactory.php
packages/BetterPhpDocParser/src/PhpDocParser/BetterPhpDocParser.php
packages/BetterPhpDocParser/tests/PhpDocParser/OrmTagParser/Class_/Fixture/TableWithIndexes.php
packages/BetterPhpDocParser/tests/PhpDocParser/OrmTagParser/Class_/Fixture/expected_table_with_indexes.txt
packages/BetterPhpDocParser/tests/PhpDocParser/OrmTagParser/Class_/ParserClassTest.php
packages/BetterPhpDocParser/tests/PhpDocParser/OrmTagParser/Property_/Fixture/JoinTable.php
packages/BetterPhpDocParser/tests/PhpDocParser/OrmTagParser/Property_/Fixture/expected_join_table.txt
packages/BetterPhpDocParser/tests/PhpDocParser/OrmTagParser/Property_/OrmTagParserPropertyTest.php
packages/BetterPhpDocParser/tests/PhpDocParser/OrmTagParser/Property_/ParserPropertyTest.php

fix joinColumns always fallback

---

.github/ISSUE_TEMPLATE/1_Bug_report.md
packages/BetterPhpDocParser/src/PhpDocNode/Sensio/SensioTemplateTagValueNode.php
packages/Sensio/src/Helper/TemplateGuesser.php

Allow @Template to get nullable values

---

composer.json
config/set/code-quality/code-quality.yaml
ecs.yaml
packages/SOLID/src/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector.php
packages/SOLID/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector/Fixture/fixture.php.inc
packages/SOLID/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector/Fixture/prefer_first_parent_interface.php.inc
packages/SOLID/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector/Fixture/skip_class_that_implements_interface_with_multiple_children.php.inc
packages/SOLID/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector/Fixture/skip_interface.php.inc
packages/SOLID/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector/Fixture/skip_multiple_interfaces.php.inc
packages/SOLID/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector/Fixture/skip_simple_type.php.inc
packages/SOLID/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector/Fixture/skip_sole_class.php.inc
packages/SOLID/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector/Source/Apple.php
packages/SOLID/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector/Source/ClassThatImplementsInterfaceThatExtendsInterface.php
packages/SOLID/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector/Source/ClassThatImplementsMoreInterfaces.php
packages/SOLID/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector/Source/Fruit.php
packages/SOLID/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector/Source/InterfaceExtendingInterface.php
packages/SOLID/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector/Source/InterfaceOne.php
packages/SOLID/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector/Source/InterfaceThree.php
packages/SOLID/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector/Source/InterfaceTwo.php
packages/SOLID/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector/Source/Orange.php
packages/SOLID/tests/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector/UseInterfaceOverImplementationInConstructorRectorTest.php
phpstan.neon
rector.yaml
src/Rector/AbstractRector.php

[SOLID] Prefer interface if possible

---

packages/CodingStyle/src/Rector/Encapsed/EncapsedStringsToSprintfRector.php

Fix EncapsedStringsToSprintfRector for non-var exprs

---

ecs.yaml
sample/ScreenSample.php
src/Console/Command/ScreenFileCommand.php
src/PhpParser/Node/Commander/NodeAddingCommander.php

- What php part is what node in php-parser?
- What type/name is there?
- How do I find the right name?
```php
vendor/bin/rector screen-file sample/ScreenSample.php --output ShowMe.php
```
```php
<?php declare(strict_types=1);
namespace App;
final class ScreenSample
{
{
$this->mute();
}
public function mute()
{
}
}
```
```php
<?php
// node_type: "PhpParser\Node\Stmt\Declare_"
declare(strict_types=1);
// node_type: "PhpParser\Node\Stmt\Namespace_"
namespace App;
// class_name: "App\ScreenSample"
// node_type: "PhpParser\Node\Stmt\Class_"
final class ScreenSample
{
// node_type: "PhpParser\Node\Stmt\ClassMethod"
{
// method_variable_name - $this->isName($node->var, "X"): "this"
// method_call_method_name - $this->isName($node->name, "X"): "mute"
// …
```

Helpful printer - good for tranings

---

packages/PHPUnit/src/Rector/ClassMethod/EnsureDataProviderInDocBlockRector.php
packages/PHPUnit/tests/Rector/ClassMethod/EnsureDataProviderInDocBlockRector/EnsureDataProviderInDocBlockRectorTest.php
packages/PHPUnit/tests/Rector/ClassMethod/EnsureDataProviderInDocBlockRector/Fixture/fixture.php.inc
packages/PHPUnit/tests/Rector/ClassMethod/EnsureDataProviderInDocBlockRector/Fixture/multiple_comment.php.inc

[PHPUnit] [Doc] Add EnsureDataProviderInDocBlockRector

---

packages/PHPUnit/src/Rector/ClassMethod/FixDataProviderAnnotationTypoRector.php
packages/PHPUnit/tests/Rector/ClassMethod/FixDataProviderAnnotationTypoRector/FixDataProviderAnnotationTypoRectorTest.php
packages/PHPUnit/tests/Rector/ClassMethod/FixDataProviderAnnotationTypoRector/Fixture/fixture.php.inc

[PHPUnit] [Doc] Add FixDataProviderAnnotationTypoRector

---

packages/CodeQuality/tests/Rector/If_/RemoveAlwaysTrueConditionSetInConstructorRector/Fixture/skip_trait.php.inc
packages/CodeQuality/tests/Rector/If_/RemoveAlwaysTrueConditionSetInConstructorRector/RemoveAlwaysTrueConditionSetInConstructorRectorTest.php
src/PhpParser/Node/Manipulator/ClassManipulator.php

[code-quality] fixes processing of trait - RemoveAlwaysTrueConditionSetInConstructorRector  #2162

---

config/set/code-quality/code-quality.yaml
packages/CodeQuality/src/Rector/FuncCall/ArrayMergeOfNonArraysToSimpleArrayRector.php
packages/CodeQuality/tests/Rector/FuncCall/ArrayMergeOfNonArraysToSimpleArrayRector/ArrayMergeOfNonArraysToSimpleArrayRectorTest.php
packages/CodeQuality/tests/Rector/FuncCall/ArrayMergeOfNonArraysToSimpleArrayRector/Fixture/fixture.php.inc
packages/CodeQuality/tests/Rector/FuncCall/ArrayMergeOfNonArraysToSimpleArrayRector/Fixture/nested_arrays.php.inc
packages/CodeQuality/tests/Rector/FuncCall/ArrayMergeOfNonArraysToSimpleArrayRector/Fixture/skip_non_arrays.php.inc
packages/TypeDeclaration/src/TypeInferer/PropertyTypeInferer.php
rector.yaml
src/Rector/Psr4/MultipleClassFileToPsr4ClassesRector.php

[CodeQuality] Add ArrayMergeOfNonArraysToSimpleArrayRector

---

packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/Fixture/Version5/with_route_options.php.inc
packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/TemplateAnnotationVersion5RectorTest.php

Add test case for route annotation with optional parameters

---

config/set/phpunit/phpunit75.yaml
packages/NodeTypeResolver/src/NodeTypeResolver.php
packages/PHPUnit/src/Rector/MethodCall/WithConsecutiveArgToArrayRector.php
packages/PHPUnit/tests/Rector/MethodCall/WithConsecutiveArgToArrayRector/ClassWithMethodOfTwoArguments.php
packages/PHPUnit/tests/Rector/MethodCall/WithConsecutiveArgToArrayRector/Fixture/fixture.php.inc
packages/PHPUnit/tests/Rector/MethodCall/WithConsecutiveArgToArrayRector/Fixture/skip_already_array.php.inc
packages/PHPUnit/tests/Rector/MethodCall/WithConsecutiveArgToArrayRector/WithConsecutiveArgToArrayRectorTest.php
phpstan.neon
src/PhpParser/Node/Manipulator/MethodCallManipulator.php
src/PhpParser/Node/NodeFactory.php

[PHPUnit 7.5] Add WithConsecutiveArgToArrayRector

---

.dockerignore

Ignore not required files in docker build

---

.travis.yml
bin/container.php
bin/rector
ecs.yaml
src/Console/Application.php
src/Console/Command/AbstractCommand.php

Closes #2205
Solves #2214
Inspired by: https://github.com/phpstan/phpstan/commit/d437e70f929bf508569e3c0f55ecfee7f977bd01

Fix empty -c/--config value

---

packages/DeadCode/src/Analyzer/SetterOnlyMethodAnalyzer.php
packages/DeadCode/src/Rector/Assign/RemoveDoubleAssignRector.php
packages/DeadCode/src/Rector/Class_/RemoveSetterOnlyPropertyAndMethodCallRector.php
packages/DeadCode/tests/Rector/Class_/RemoveSetterOnlyPropertyAndMethodCallRector/Fixture/remove_dim_fetch.php.inc
packages/DeadCode/tests/Rector/Class_/RemoveSetterOnlyPropertyAndMethodCallRector/Fixture/remove_multiple_dim_fetch.php.inc
packages/DeadCode/tests/Rector/Class_/RemoveSetterOnlyPropertyAndMethodCallRector/RemoveSetterOnlyPropertyAndMethodCallRectorTest.php
src/PhpParser/Node/Manipulator/AssignManipulator.php
src/PhpParser/Node/Manipulator/ClassManipulator.php
src/PhpParser/Node/Manipulator/PropertyFetchManipulator.php

- Replaces #2232
- Closes #2208

Decouple PropertyFetchManipulator methods for array dim fetch

---

packages/CodingStyle/src/Imports/ShortNameResolver.php
packages/Renaming/tests/Rector/Class_/RenameClassRector/AutoImportNamesParameterTest.php
packages/Renaming/tests/Rector/Class_/RenameClassRector/Fixture/AutoImportNamesParameter/skip_parent_class_same_name.php.inc
packages/Renaming/tests/Rector/Class_/RenameClassRector/Source/SkipParentClassSameName.php

Fix importing parent that is identical in short to class name

---

src/Php/PhpVersionProvider.php

infer php version from composer.json

---

packages/DeadCode/src/Rector/Class_/RemoveSetterOnlyPropertyAndMethodCallRector.php
packages/DeadCode/tests/Rector/Class_/RemoveSetterOnlyPropertyAndMethodCallRector/Fixture/deal_with_property_fetches.php.inc
packages/DeadCode/tests/Rector/Class_/RemoveSetterOnlyPropertyAndMethodCallRector/Fixture/node_removal_on_non_expression.php.inc
packages/DeadCode/tests/Rector/Class_/RemoveSetterOnlyPropertyAndMethodCallRector/RemoveSetterOnlyPropertyAndMethodCallRectorTest.php
src/PhpParser/Node/Commander/NodeReplacingCommander.php
src/Rector/AbstractRector/NodeCommandersTrait.php

Fixed issue with property fetches

Fixed removal of non expressions

---

README.md
config/config.yaml
packages/Renaming/tests/Rector/Class_/RenameClassRector/AutoImportNamesParameterTest.php
rector-ci.yaml
rector.yaml
src/Testing/PHPUnit/AbstractRectorTestCase.php

Import default

---

packages/NodeTypeResolver/src/StaticTypeMapper.php
packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/nullable_property_scalar.php.inc

Fix StaticTypeMapper for nullables

---

packages/CodingStyle/tests/Rector/ClassMethod/ReturnArrayClassMethodToYieldRector/ReturnArrayClassMethodToYieldRectorTest.php

fix no-regular naming

---

.travis.yml
composer.json
docs/AllRectorsOverview.md
docs/NodesOverview.md

travis: change ENV matrix to jobs + add Windows OS

---

packages/Sensio/src/Rector/FrameworkExtraBundle/TemplateAnnotationRector.php

code fixes

---

bin/rector
src/Configuration/Option.php
src/DependencyInjection/CompilerPass/RemoveExcludedRectorsCompilerPass.php

[DX] report missing rules in exclude_rectors parameter

---

composer.json
docs/AllRectorsOverview.md
ecs.yaml
packages/CodingStyle/src/Imports/ImportSkipper.php
packages/CodingStyle/src/Naming/ClassNaming.php
packages/PHPUnit/src/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector.php
packages/Renaming/tests/Rector/Class_/RenameClassRector/AutoImportNamesParameterTest.php
packages/Renaming/tests/Rector/Class_/RenameClassRector/FixtureAutoImportNames/class_importing_same_name.php.inc
packages/Renaming/tests/Rector/Class_/RenameClassRector/FixtureAutoImportNames/exception_extends_exceptions.php.inc
packages/Renaming/tests/Rector/Class_/RenameClassRector/FixtureAutoImportNames/imports_extends_imports.php.inc
packages/Renaming/tests/Rector/Class_/RenameClassRector/Source/ClassImportingSameName.php
packages/Renaming/tests/Rector/Class_/RenameClassRector/Source/SomeInterface.php
phpstan.neon

Fix parent interface, extends, implements same name as short name

---

packages/CakePHP/src/Rector/MethodCall/ModalToGetSetRector.php

fix var type on method call

---

docs/AllRectorsOverview.md
packages/Php70/src/Rector/FuncCall/RandomFunctionRector.php

Closes #2366 PR from @berezuev

Fix: RandomFunctionRector typo fix + regenerated docs

---

packages/NodeTypeResolver/src/StaticTypeMapper.php

[TypeDeclaration] Object without class

---

packages/TypeDeclaration/src/Rector/FunctionLike/ReturnTypeDeclarationRector.php
packages/TypeDeclaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/issue2383.php.inc

prevent union sub-type nullable override

---

config/set/cakephp/cakephp40.yaml

Another upgrade that rector can take care of.

Add rector rule for EntityInterface::isNew()

---

config/set/phalcon/phalcon40.yaml

Did a small scan on the current Phalcon40 project. And noticed these missing changes

Added missing methods

---

config/config.yaml

when rector.yaml does not contain rector_recipe

Added default to prevent rector from breaking

---

packages/SOLID/src/Rector/ClassMethod/UseInterfaceOverImplementationInConstructorRector.php

Make sure array keys start at 0

Fix undefined offset in UseInterfaceOverImplementationInConstructorRector

---

src/Rector/New_/NewToStaticCallRector.php

Fix arguments documentation for `Rector\Rector\New_\NewToStaticCallRector`

Fix NewToStaticCallRector documentation

---

composer.json
config/set/phalcon/phalcon40.yaml
packages/CodeQuality/src/Rector/FuncCall/AddPregQuoteDelimiterRector.php
packages/NodeTypeResolver/src/NodeTypeResolver.php
packages/Phalcon/src/Rector/Assign/FlashWithCssClassesToExtraCallRector.php
packages/Phalcon/src/Rector/Assign/NewApplicationToToFactoryWithDefaultContainerRector.php
packages/Phalcon/src/Rector/MethodCall/AddRequestToHandleMethodCallRector.php
packages/Phalcon/tests/Rector/Assign/FlashWithCssClassesToExtraCallRector/Fixture/fixture.php.inc
packages/Phalcon/tests/Rector/Assign/FlashWithCssClassesToExtraCallRector/FlashWithCssClassesToExtraCallRectorTest.php
packages/Phalcon/tests/Rector/Assign/NewApplicationToToFactoryWithDefaultContainerRector/Fixture/fixture.php.inc
packages/Phalcon/tests/Rector/Assign/NewApplicationToToFactoryWithDefaultContainerRector/NewApplicationToToFactoryWithDefaultContainerRectorTest.php
packages/Phalcon/tests/Rector/MethodCall/AddRequestToHandleMethodCallRector/AddRequestToHandleMethodCallRectorTest.php
packages/Phalcon/tests/Rector/MethodCall/AddRequestToHandleMethodCallRector/Fixture/fixture.php.inc
packages/Php71/src/Rector/FuncCall/CountOnNullRector.php
rector.yaml
src/PhpParser/Node/NodeFactory.php

[Phalcon 4.0] Add FlashWithCssClassesToExtraCallRector

---

packages/Php72/src/Rector/ConstFetch/BarewordStringRector.php

Make BarewordStringRector skip missing file

---

packages/NodeTypeResolver/src/StaticTypeMapper.php

add intersection type support to StaticTypeMapper

---

README.md
config/config.yaml

For various *undesired* default feature complains, it will be better make this feature opt-in

disable imports by default

---

packages/Symfony/src/Rector/FrameworkBundle/GetParameterToConstructorInjectionRector.php
packages/Symfony/tests/Rector/FrameworkBundle/GetParameterToConstructorInjectionRector/Fixture/param_with_dot.php.inc

[Symfony] fix dot in GetParameterToConstructorInjectionRector
