rectorphp/rector

packages/Renaming/src/Rector/MethodCall/RenameMethodCallRector.php, src/Rector/AbstractRector/NodeTypeResolverTrait.php
- Closes #2440 
- Closes #2456
=> fix rename method call

src/DependencyInjection/Collector/RectorServiceArgumentCollector.php, src/DependencyInjection/CompilerPass/MergeImportedRectorServiceArgumentsCompilerPass.php, src/DependencyInjection/Loader/TolerantRectorYamlFileLoader.php, src/HttpKernel/RectorKernel.php, tests/Issues/Issue2451/Fixture/fixture2451.php.inc, tests/Issues/Issue2451/Issue2451Test.php
=> merge Rector arguments on import

composer.json, config/set/knplabs/doctrine-gedmo-to-knplabs.yaml, packages/BetterPhpDocParser/src/AnnotationReader/AnnotationReaderFactory.php, packages/BetterPhpDocParser/src/PhpDocInfo/PhpDocInfo.php, packages/BetterPhpDocParser/src/PhpDocNode/Gedmo/SlugTagValueNode.php, packages/BetterPhpDocParser/src/PhpDocNodeFactory/Gedmo/SlugPhpDocNodeFactory.php, packages/BetterPhpDocParser/src/PhpDocParser/BetterPhpDocParser.php, packages/BetterPhpDocParser/src/PhpDocParser/ClassAnnotationMatcher.php, packages/DoctrineGedmoToKnplabs/src/Rector/Class_/SluggableBehaviorRector.php, packages/DoctrineGedmoToKnplabs/src/Rector/Class_/TimestampableBehaviorRector.php, packages/DoctrineGedmoToKnplabs/tests/Rector/Class_/SluggableBehaviorRector/Fixture/fixture.php.inc, packages/DoctrineGedmoToKnplabs/tests/Rector/Class_/SluggableBehaviorRector/SluggableBehaviorRectorTest.php, packages/DoctrineGedmoToKnplabs/tests/Rector/Class_/TimestampableBehaviorRector/Fixture/fixture.php.inc, packages/DoctrineGedmoToKnplabs/tests/Rector/Class_/TimestampableBehaviorRector/TimestampableBehaviorRectorTest.php, src/PhpParser/Node/Manipulator/ClassManipulator.php, src/Rector/Class_/ParentClassToTraitsRector.php, stubs/Gedmo/Mapping/Annotation/Slug.php, stubs/Gedmo/Timestampable/Traits/TimestampableEntity.php
=> [DoctrineGedmoToKnplabs] init set

docs/AllRectorsOverview.md, packages/CodingStyle/src/Imports/UseImportsTraverser.php, packages/CodingStyle/src/Imports/UsedImportsResolver.php, packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/skip_grouped.php.inc, packages/Renaming/src/Rector/Function_/RenameFunctionRector.php, packages/Renaming/src/Rector/MethodCall/RenameMethodRector.php, src/Rector/Argument/ArgumentAdderRector.php
=> Fix grouped use statement import

packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php, packages/PHPStan/src/Type/AliasedObjectType.php, packages/TypeDeclaration/src/PHPStan/Type/ObjectTypeSpecifier.php, packages/TypeDeclaration/src/TypeInferer/PropertyTypeInferer/ConstructorPropertyTypeInferer.php, packages/TypeDeclaration/tests/Rector/Property/CompleteVarDocTypePropertyRector/Fixture/skip_already_used.php.inc
=> Fix alias object conflict with existing type

packages/Php71/src/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector.php, packages/Php71/tests/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/Fixture/skip_constant_value.php.inc
=> Skip non-variable non-scalars in BinaryOpBetweenNumberAndStringRector

packages/Php73/src/Rector/FuncCall/ArrayKeyFirstLastRector.php, packages/Php73/tests/Rector/FuncCall/ArrayKeyFirstLastRector/Fixture/skip_other_function_name.php.inc, src/ValueObject/PhpVersionFeature.php
=> Fix name resolution in ArrayKeyFirstLastRector

docs/AllRectorsOverview.md, packages/Nette/src/Rector/FuncCall/PregFunctionToNetteUtilsStringsRector.php, packages/Nette/tests/Rector/FuncCall/PregFunctionToNetteUtilsStringsRector/Fixture/preg_split_with_subpattern.php.inc
=> fix PREG_SPLIT_DELIM_CAPTURE for split Nette Utils

docs/AllRectorsOverview.md, packages/Nette/config/config.yaml, packages/Nette/src/NodeFactory/ActionRenderFactory.php, packages/Nette/src/Rector/ClassMethod/TemplateMagicAssignToExplicitVariableArrayRector.php, packages/Nette/src/TemplatePropertyAssignCollector.php, packages/Nette/src/ValueObject/MagicTemplatePropertyCalls.php, packages/Nette/tests/Rector/ClassMethod/TemplateMagicAssignToExplicitVariableArrayRector/Fixture/fixture.php.inc, packages/Nette/tests/Rector/ClassMethod/TemplateMagicAssignToExplicitVariableArrayRector/TemplateMagicAssignToExplicitVariableArrayRectorTest.php, packages/NetteToSymfony/src/Rector/Class_/NetteControlToSymfonyControllerRector.php, src/PhpParser/Node/NodeFactory.php
=> [Nette] Add magic template code quality

.travis.yml, packages/Php71/tests/Rector/FuncCall/RemoveExtraParametersRector/Fixture/redeclare_function.php.inc, src/PhpParser/Node/Resolver/NameResolver.php
=> Fix function override under namespace

ecs.yaml, packages/TypeDeclaration/src/PhpParserTypeAnalyzer.php, packages/TypeDeclaration/src/Rector/FunctionLike/AbstractTypeDeclarationRector.php, packages/TypeDeclaration/src/Rector/FunctionLike/ParamTypeDeclarationRector.php, packages/TypeDeclaration/src/Rector/FunctionLike/ReturnTypeDeclarationRector.php, packages/TypeDeclaration/src/VendorLock/VendorLockResolver.php, packages/TypeDeclaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/skip_parent_overriden_with_throws.php.inc, packages/TypeDeclaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Source/ParentObjectReturnInterface.php, packages/TypeDeclaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Source/RealReturnedClass.php, packages/TypeDeclaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Source/ReturnedClass.php, phpstan.neon, src/PhpParser/Node/Manipulator/ClassManipulator.php
=> Fix return override in case of parent vendor lock

packages/Laravel/src/Rector/FuncCall/HelperFunctionToConstructorInjectionRector.php, packages/Laravel/tests/Rector/FuncCall/HelperFunctionToConstructorInjectionRector/Fixture/skip_static_method.php.inc
=> Apply HelperFunctionToConstructorInjectionRector only in non-static class method scope

config/set/knplabs/doctrine-gedmo-to-knplabs.yaml, packages/BetterPhpDocParser/src/PhpDocInfo/PhpDocInfo.php, packages/BetterPhpDocParser/src/PhpDocNode/Doctrine/Class_/EntityTagValueNode.php, packages/BetterPhpDocParser/src/PhpDocNode/Gedmo/LocaleTagValueNode.php, packages/BetterPhpDocParser/src/PhpDocNode/Gedmo/TranslatableTagValueNode.php, packages/BetterPhpDocParser/src/PhpDocNodeFactory/Gedmo/LocalePhpDocNodeFactory.php, packages/BetterPhpDocParser/src/PhpDocNodeFactory/Gedmo/TranslatablePhpDocNodeFactory.php, packages/DeadCode/src/Rector/ClassMethod/RemoveUnusedParameterRector.php, packages/Doctrine/src/PhpDocParser/Ast/PhpDoc/PhpDocTagNodeFactory.php, packages/DoctrineGedmoToKnplabs/src/Rector/Class_/TranslationBehaviorRector.php, packages/DoctrineGedmoToKnplabs/tests/Rector/Class_/TranslationBehaviorRector/Fixture/fixture.php.inc, packages/DoctrineGedmoToKnplabs/tests/Rector/Class_/TranslationBehaviorRector/Source/ExpectedSomeClassTranslation.php, packages/DoctrineGedmoToKnplabs/tests/Rector/Class_/TranslationBehaviorRector/TranslationBehaviorRectorTest.php, packages/NetteToSymfony/src/Rector/Assign/FormControlToControllerAndFormTypeRector.php, packages/NetteToSymfony/tests/Rector/Assign/FormControlToControllerAndFormTypeRector/FormControlToControllerAndFormTypeRectorTest.php, packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php, src/PhpParser/Node/Manipulator/ClassManipulator.php, src/PhpParser/Node/NodeFactory.php, src/Rector/AbstractRector/BetterStandardPrinterTrait.php, stubs/Gedmo/Mapping/Annotation/Locale.php, stubs/Gedmo/Mapping/Annotation/Translatable.php, stubs/Gedmo/Timestampable/Traits/TimestampableEntity.php, stubs/Gedmo/Translatable/Translatable.php
=> [Gedmo to Knp] Add Translatable Behavior Rector

packages/NodeTypeResolver/src/StaticTypeMapper.php, packages/TypeDeclaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/Fixture/change_union_type_mutually_children.php.inc, packages/TypeDeclaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/Fixture/skip_union_type.php.inc
=> Fix param type union

config/set/code-quality/code-quality.yaml, packages/CodeQuality/src/Rector/FuncCall/IntvalToTypeCastRector.php, packages/CodeQuality/tests/Rector/FuncCall/IntvalToTypeCastRector/Fixture/fixture.php.inc, packages/CodeQuality/tests/Rector/FuncCall/IntvalToTypeCastRector/IntvalToTypeCastRectorTest.php, utils/RectorGenerator/src/TemplateVariablesFactory.php, utils/RectorGenerator/templates/packages/_Package_/src/Rector/_Category_/_Name_.php.inc
=> [CodeQuality] Add IntvalToTypeCastRector

packages/BetterPhpDocParser/src/PhpDocInfo/PhpDocInfoFactory.php, packages/BetterPhpDocParser/src/PhpDocParser/AnnotationContentResolver.php, packages/BetterPhpDocParser/src/PhpDocParser/BetterPhpDocParser.php, packages/CodingStyle/tests/Rector/ClassConst/VarConstantCommentRector/Fixture/skip_already_has.php.inc, packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php, packages/Renaming/src/Rector/Class_/RenameClassRector.php
- Closes #2305 
- Closes #2266
=> Fix single-line comment and constant scalar type match

config/set/doctrine/doctrine-dbal-210.yaml, config/set/doctrine/doctrine-dbal-30.yaml
=> [Doctrine/dbal] Add 2.10 and 3.0 sets

packages/NodeTypeResolver/src/StaticTypeMapper.php
=> add resource type to StaticTypeMapper

packages/CodingStyle/src/Rector/Identical/IdenticalFalseToBooleanNotRector.php, packages/CodingStyle/tests/Rector/Identical/IdenticalFalseToBooleanNotRector/Fixture/skip_null_false_again.php.inc
=> [CodingStyle] Fix IdenticalFalseToBooleanNotRector for null|bool

config/set/code-quality/code-quality.yaml, packages/CodeQuality/src/Rector/Include_/AbsolutizeRequireAndIncludePathRector.php, packages/CodeQuality/tests/Rector/Include_/AbsolutizeRequireAndIncludePathRector/AbsolutizeRequireAndIncludePathRectorTest.php, packages/CodeQuality/tests/Rector/Include_/AbsolutizeRequireAndIncludePathRector/Fixture/dots.php.inc, packages/CodeQuality/tests/Rector/Include_/AbsolutizeRequireAndIncludePathRector/Fixture/fixture.php.inc, packages/CodeQuality/tests/Rector/Include_/AbsolutizeRequireAndIncludePathRector/Fixture/vendor_phar.php.inc
=> [CodeQuality] Add AbsolutizeRequireAndIncludePathRector

packages/DeadCode/tests/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/write_only.php.inc
=> add test case for #1244

abz/UnderElse.php, config/set/dead-code/dead-code.yaml, packages/DeadCode/src/Rector/FunctionLike/RemoveUnusedElseForReturnedValueRector.php, packages/DeadCode/tests/Rector/FunctionLike/RemoveUnusedElseForReturnedValueRector/Fixture/fixture.php.inc, packages/DeadCode/tests/Rector/FunctionLike/RemoveUnusedElseForReturnedValueRector/Fixture/skip_non_first_level.php.inc, packages/DeadCode/tests/Rector/FunctionLike/RemoveUnusedElseForReturnedValueRector/Fixture/skip_not_only_else.php.inc, packages/DeadCode/tests/Rector/FunctionLike/RemoveUnusedElseForReturnedValueRector/RemoveUnusedElseForReturnedValueRectorTest.php, src/PhpParser/Node/Manipulator/IfManipulator.php
=> [DeadCode] RemoveUnusedElseForReturnedValueRector

packages/BetterPhpDocParser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php, packages/Restoration/src/Rector/Namespace_/CompleteImportForPartialAnnotationRector.php
=> fix function callback in assert callback

docs/AllRectorsOverview.md, packages/NodeTypeResolver/src/StaticTypeMapper.php, packages/NodeTypeResolver/tests/StaticTypeMapper/StaticTypeMapperTest.php, packages/TypeDeclaration/src/Rector/ClassMethod/AddArrayReturnDocTypeRector.php, packages/TypeDeclaration/tests/Rector/ClassMethod/AddArrayReturnDocTypeRector/Fixture/skip_iterable.php.inc
=> add IterableType to StaticTypeMapper::mapPHPStanTypeToPHPStanPhpDocType()

packages/NodeTypeResolver/src/DependencyInjection/PHPStanServicesFactory.php, phpstan.neon
=> allow loading bleedingEdge.neon config inside PHPStan phar

config/set/code-quality/code-quality.yaml, docs/AllRectorsOverview.md, packages/CodeQuality/src/Rector/FuncCall/ChangeArrayPushToArrayAssignRector.php, packages/CodeQuality/tests/Rector/FuncCall/ChangeArrayPushToArrayAssignRector/ChangeArrayPushToArrayAssignRectorTest.php, packages/CodeQuality/tests/Rector/FuncCall/ChangeArrayPushToArrayAssignRector/Fixture/fixture.php.inc
=> [CodeQuality] Add ChangeArrayPushToArrayAssignRector

packages/BetterPhpDocParser/src/PhpDocParser/BetterPhpDocParser.php, packages/NodeTypeResolver/config/phpstan/better-infer.neon, packages/NodeTypeResolver/src/DependencyInjection/PHPStanServicesFactory.php, packages/NodeTypeResolver/src/NodeTypeResolver.php, packages/Php71/src/Rector/FuncCall/CountOnNullRector.php, src/Configuration/CurrentNodeProvider.php
=> Improve 3rd party property type resolution

packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Fixture/keep_nette_symfony_finder.php.inc, packages/MinimalScope/tests/Rector/Class_/ChangeLocalPropertyToVariableRector/Fixture/skip_double_use.php.inc, packages/MinimalScope/tests/Rector/Class_/ChangeLocalPropertyToVariableRector/Fixture/skip_public.php.inc
=> Add test case for unused alias

config/set/code-quality/code-quality.yaml, packages/CodeQuality/src/Rector/Foreach_/ForeachItemsAssignToEmptyArrayToAssignRector.php, packages/CodeQuality/tests/Rector/Foreach_/ForeachItemsAssignToEmptyArrayToAssignRector/Fixture/fixture.php.inc, packages/CodeQuality/tests/Rector/Foreach_/ForeachItemsAssignToEmptyArrayToAssignRector/Fixture/skip_argument.php.inc, packages/CodeQuality/tests/Rector/Foreach_/ForeachItemsAssignToEmptyArrayToAssignRector/Fixture/skip_non_empty_array.php.inc, packages/CodeQuality/tests/Rector/Foreach_/ForeachItemsAssignToEmptyArrayToAssignRector/ForeachItemsAssignToEmptyArrayToAssignRectorTest.php
=> [CodingQuality] Add ForeachItemsAssignToEmptyArrayToAssignRector

packages/CodeQuality/src/Rector/For_/ForRepeatedCountToOwnVariableRector.php, packages/CodeQuality/tests/Rector/For_/ForRepeatedCountToOwnVariableRector/Fixture/already_existing_items_count.php.inc
Covers https://github.com/rectorphp/rector/pull/2559#discussion_r363036297
=> Prevent variable name override

ecs.yaml, packages/MinimalScope/src/Rector/Class_/ChangeLocalPropertyToVariableRector.php, packages/MinimalScope/tests/Rector/Class_/ChangeLocalPropertyToVariableRector/Fixture/skip_double_use_in_one_method.php.inc, packages/MinimalScope/tests/Rector/Class_/ChangeLocalPropertyToVariableRector/Fixture/skip_double_use_in_one_method_without_change.php.inc, phpstan.neon, src/PhpParser/Node/Manipulator/IfManipulator.php, src/PhpParser/Node/Manipulator/PropertyFetchManipulator.php
Improves https://github.com/rectorphp/rector/pull/2558#discussion_r363035639
=> prevent variable scope changing

.travis.yml
Reverts rectorphp/rector#2581
Reasons https://github.com/rectorphp/rector/pull/2581#issuecomment-571133453
=> Revert "Try pcov for code coverage"

packages/BetterPhpDocParser/src/Attributes/Ast/AttributeAwareNodeFactory.php, packages/BetterPhpDocParser/src/Attributes/Ast/PhpDoc/AttributeAwareExtendsTagValueNode.php, packages/BetterPhpDocParser/src/Attributes/Ast/PhpDoc/AttributeAwareImplementsTagValueNode.php
Fixes #2544
I've compiled the .phar locally and tested it on my codebase, it worked. :) Thanks for the help/clues!
=> Fix PHPStan 0.12+ @implements and @extends class annotations.

config/set/knplabs/doctrine-gedmo-to-knplabs.yaml, packages/BetterPhpDocParser/src/AnnotationReader/AnnotationReaderFactory.php, packages/BetterPhpDocParser/src/PhpDocNode/Gedmo/SoftDeleteableTagValueNode.php, packages/BetterPhpDocParser/src/PhpDocNodeFactory/Gedmo/SoftDeleteablePhpDocNodeFactory.php, packages/DoctrineGedmoToKnplabs/src/Rector/Class_/SoftDeletableBehaviorRector.php, packages/DoctrineGedmoToKnplabs/tests/Rector/Class_/SoftDeletableBehaviorRector/Fixture/fixture.php.inc, packages/DoctrineGedmoToKnplabs/tests/Rector/Class_/SoftDeletableBehaviorRector/SoftDeletableBehaviorRectorTest.php, stubs/Gedmo/Mapping/Annotation/SoftDeleteable.php
=> [DoctrineGedmoToKnpLabs] Add SoftDeletableBehaviorRector

config/set/knplabs/doctrine-gedmo-to-knplabs.yaml, packages/BetterPhpDocParser/src/AnnotationReader/AnnotationReaderFactory.php, packages/BetterPhpDocParser/src/PhpDocNode/Gedmo/BlameableTagValueNode.php, packages/BetterPhpDocParser/src/PhpDocNodeFactory/Gedmo/BlameablePhpDocNodeFactory.php, packages/DoctrineGedmoToKnplabs/src/Rector/Class_/BlameableBehaviorRector.php, packages/DoctrineGedmoToKnplabs/tests/Rector/Class_/BlameableBehaviorRector/BlameableBehaviorRectorTest.php, packages/DoctrineGedmoToKnplabs/tests/Rector/Class_/BlameableBehaviorRector/Fixture/fixture.php.inc, phpstan.neon, stubs/Gedmo/Mapping/Annotation/Blameable.php
=> [DoctrineGemoToKnplabs] Add BlameableBehaviorRector

packages/BetterPhpDocParser/src/PhpDocNode/Symfony/SymfonyRouteTagValueNode.php
=> [Symfony] fix process error of controller with Internationalized routing

config/set/knplabs/doctrine-gedmo-to-knplabs.yaml, packages/BetterPhpDocParser/src/AnnotationReader/AnnotationReaderFactory.php, packages/BetterPhpDocParser/src/PhpDocNode/Gedmo/LoggableTagValueNode.php, packages/BetterPhpDocParser/src/PhpDocNode/Gedmo/VersionedTagValueNode.php, packages/BetterPhpDocParser/src/PhpDocNodeFactory/Gedmo/LoggablePhpDocNodeFactory.php, packages/BetterPhpDocParser/src/PhpDocNodeFactory/Gedmo/VersionedPhpDocNodeFactory.php, packages/DoctrineGedmoToKnplabs/src/Rector/Class_/LoggableBehaviorRector.php, packages/DoctrineGedmoToKnplabs/src/Rector/Class_/SluggableBehaviorRector.php, packages/DoctrineGedmoToKnplabs/src/Rector/Class_/SoftDeletableBehaviorRector.php, packages/DoctrineGedmoToKnplabs/src/Rector/Class_/TimestampableBehaviorRector.php, packages/DoctrineGedmoToKnplabs/src/Rector/Class_/TranslationBehaviorRector.php, packages/DoctrineGedmoToKnplabs/src/Rector/Class_/TreeBehaviorRector.php, packages/DoctrineGedmoToKnplabs/tests/Rector/Class_/LoggableBehaviorRector/Fixture/fixture.php.inc, packages/DoctrineGedmoToKnplabs/tests/Rector/Class_/LoggableBehaviorRector/LoggableBehaviorRectorTest.php, stubs/Gedmo/Mapping/Annotation/Loggable.php, stubs/Gedmo/Mapping/Annotation/Versioned.php
=> [DoctrineGemoToKnplabs] Add LoggableBehaviorRector

packages/CodeQuality/src/Rector/Foreach_/ForeachItemsAssignToEmptyArrayToAssignRector.php, packages/CodeQuality/tests/Rector/Foreach_/ForeachItemsAssignToEmptyArrayToAssignRector/Fixture/skip_nested_foreach_edge_case.php.inc
Fixed https://github.com/Symplify/Symplify/pull/1733/checks?check_run_id=379368887
=> [CodeQuality] Fix nested foreach case in ForeachItemsAssignToEmptyArrayToAssignRector

README.md
As @staabm suggested yesterday in #2622
=> REAME changed URL to relative path

packages/CodingStyle/src/Application/UseAddingCommander.php, packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/FixtureNonNamespaced/skip_non_coumpond.php.inc
=> [CodingStyle] Prevent adding non-namespaced imports to non-namespaced class

packages/Renaming/tests/Rector/MethodCall/RenameMethodCallRector/Fixture/underscore_only.php.inc, packages/Renaming/tests/Rector/MethodCall/RenameMethodCallRector/RenameMethodCallRectorTest.php, packages/Renaming/tests/Rector/MethodCall/RenameMethodCallRector/Source/SomeTranslator.php, src/PhpParser/Node/Resolver/NameResolver.php
=> fix pattern miss matching

composer.json, config/set/cakephp/cakephp30.yaml, docs/AllRectorsOverview.md, packages/CakePHP/config/config.yaml, packages/CakePHP/src/FullyQualifiedClassNameResolver.php, packages/CakePHP/src/ImplicitNameResolver.php, packages/CakePHP/src/Rector/Name/ImplicitShortClassNameUseStatementRector.php, packages/CakePHP/src/Rector/StaticCall/AppUsesStaticCallToUseStatementRector.php, packages/CakePHP/tests/Rector/Name/ImplicitShortClassNameUseStatementRector/Fixture/cakephp_controller.php.inc, packages/CakePHP/tests/Rector/Name/ImplicitShortClassNameUseStatementRector/Fixture/fixture.php.inc, packages/CakePHP/tests/Rector/Name/ImplicitShortClassNameUseStatementRector/ImplicitShortClassNameUseStatementRectorTest.php, packages/CakePHP/tests/Rector/Name/ImplicitShortClassNameUseStatementRector/Source/AppController.php, packages/CakePHP/tests/Rector/Name/ImplicitShortClassNameUseStatementRector/Source/Controller.php, packages/CakePHP/tests/Rector/Name/ImplicitShortClassNameUseStatementRector/Source/TestFixture.php, packages/CakePHP/tests/Rector/StaticCall/AppUsesStaticCallToUseStatementRector/AppUsesStaticCallToUseStatementRectorTest.php, packages/CakePHP/tests/Rector/StaticCall/AppUsesStaticCallToUseStatementRector/Fixture/cakephp_controller.php.inc, packages/CakePHP/tests/Rector/StaticCall/AppUsesStaticCallToUseStatementRector/Fixture/cakephp_fixture.php.inc, packages/CakePHP/tests/Rector/StaticCall/AppUsesStaticCallToUseStatementRector/Fixture/cakephp_import_namespaces_up.php.inc, packages/CakePHP/tests/Rector/StaticCall/AppUsesStaticCallToUseStatementRector/Fixture/fixture.php.inc, packages/CakePHP/tests/Rector/StaticCall/AppUsesStaticCallToUseStatementRector/Source/App.php, packages/CakePHP/tests/Rector/StaticCall/AppUsesStaticCallToUseStatementRector/Source/Xml.php
Closes #2377
Inspired at https://github.com/cakephp/upgrade
=> [CakePHP 3.0] Add AppUsesStaticCallToUseStatementRector

packages/PHPUnit/src/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector.php
=> Extend AddDoesNotPerformAssertionToNonAssertingTestRector by catching more test messages

packages/CodingStyle/tests/Rector/ClassConst/VarConstantCommentRector/Fixture/union_nested_and_single_level_array_scalars.php.inc, packages/CodingStyle/tests/Rector/ClassConst/VarConstantCommentRector/Fixture/union_nested_array_scalars.php.inc, packages/NodeTypeResolver/src/StaticTypeMapper.php
=> Fix Union Array type StaticTypeMapper to string

.github/workflows/code_checks.yml, .github/workflows/test_with_doctrine.yml, composer.json
=> Test with Doctrine

config/set/doctrine/doctrine-common-20.yaml, helpers/extract_class_changes_from_diff.php
Closes #2642 
Covers https://github.com/doctrine/persistence/pull/71
=> [Doctrine 2.0] Add class rename set

packages/Polyfill/tests/Rector/If_/UnwrapFutureCompatibleIfFunctionExistsRector/Fixture/fixture.php.inc
added second test case to unittest
=> updated UnwrapFutureCompatibleIfRectorTest

.github/workflows/code_checks.yml, composer.json, config/set/cakephp-to-symfony/cakephp-24-to-symfony-50.yaml, docs/AllRectorsOverview.md, packages/CakePHPToSymfony/src/Rector/ClassMethod/CakePHPControllerRenderToSymfonyRector.php, packages/CakePHPToSymfony/src/Rector/Echo_/CakePHPTemplateLinkToTwigRector.php, packages/CakePHPToSymfony/src/Rector/Echo_/CakePHPTemplateTranslateToTwigRector.php, packages/CakePHPToSymfony/src/Rector/Template/TemplateMethodCallManipulator.php, packages/CakePHPToSymfony/src/RouteResolver.php, packages/CakePHPToSymfony/src/TemplatePathResolver.php, packages/CakePHPToSymfony/tests/Rector/Echo_/CakePHPTemplateLinkToTwigRector/CakePHPTemplateToTwigRectorTest.php, packages/CakePHPToSymfony/tests/Rector/Echo_/CakePHPTemplateLinkToTwigRector/Fixture/fixture.php.inc, packages/CakePHPToSymfony/tests/Rector/Echo_/CakePHPTemplateTranslateToTwigRector/CakePHPTemplateTranslateToTwigRectorTest.php, packages/CakePHPToSymfony/tests/Rector/Echo_/CakePHPTemplateTranslateToTwigRector/Fixture/fixture.php.inc, src/PhpParser/Printer/BetterStandardPrinter.php
=> [CakePHPToSymfony] Add CakePHPControllerRenderToSymfonyRector

.github/inactive_workflows/rector_phar.yml, composer.json, config/set/cakephp-to-symfony/cakephp-24-to-symfony-50.yaml, docs/AllRectorsOverview.md, packages/BetterPhpDocParser/src/PhpDocNode/Doctrine/Property_/JoinColumnTagValueNode.php, packages/BetterPhpDocParser/src/PhpDocNode/Doctrine/Property_/ManyToOneTagValueNode.php, packages/CakePHPToSymfony/src/Rector/Class_/CakePHPModelToDoctrineEntityRector.php, packages/CakePHPToSymfony/tests/Rector/Class_/CakePHPModelToDoctrineEntityRector/CakePHPModelToDoctrineEntityRectorTest.php, packages/CakePHPToSymfony/tests/Rector/Class_/CakePHPModelToDoctrineEntityRector/Fixture/fixture.php.inc, packages/CakePHPToSymfony/tests/Rector/Class_/CakePHPModelToDoctrineEntityRector/Source/AppModel.php, packages/CodingStyle/src/Application/UseAddingCommander.php, packages/CodingStyle/src/Application/UseImportsAdder.php, packages/PHPStan/src/Type/AliasedObjectType.php, packages/PHPStan/src/Type/FullyQualifiedObjectType.php, phpstan.neon, src/Rector/AbstractRector/NodeCommandersTrait.php
=> [CakePHPToSymfony] Add CakePHPModelToDoctrineEntityRector

composer.json, helpers/rector_dump_function.php
For reasier debug 
```php
/**
* @param Class_ $node
*/
public function refactor(Node $node): ?Node
{
rd($node);
die;
}
```
or same as
For reasier debug 
```php
/**
* @param Class_ $node
*/
public function refactor(Node $node): ?Node
{
rdd($node);
}
```
=> [DX] add rd() function mapping to tracy

ecs.yaml, packages/CakePHPToSymfony/src/Rector/NodeManipulator/DoctrineRepositoryClassMethodManipulator.php, packages/CakePHPToSymfony/tests/Rector/Class_/CakePHPModelToDoctrineRepositoryRector/CakePHPModelToDoctrineRepositoryRectorTest.php, packages/CakePHPToSymfony/tests/Rector/Class_/CakePHPModelToDoctrineRepositoryRector/Fixture/find_list.php.inc, packages/CakePHPToSymfony/tests/Rector/Class_/CakePHPModelToDoctrineRepositoryRector/Fixture/find_list_with_one_argument.php.inc, packages/CakePHPToSymfony/tests/Rector/Class_/CakePHPModelToDoctrineRepositoryRector/Source/ExpectedFindListRepository.php, packages/CakePHPToSymfony/tests/Rector/Class_/CakePHPModelToDoctrineRepositoryRector/Source/ExpectedFindListWithOneArgumentRepository.php
=> [CakePHPToSymfony] Add list to CakePHPModelToDoctrineRepositoryRector

config/set/phpunit/phpunit90.yaml, docs/AllRectorsOverview.md, packages/PHPUnit/src/Rector/MethodCall/ExplicitPhpErrorApiRector.php, packages/PHPUnit/tests/Rector/MethodCall/ExplicitPhpErrorApiRector/ExplicitPhpErrorApiRectorTest.php, packages/PHPUnit/tests/Rector/MethodCall/ExplicitPhpErrorApiRector/Fixture/php_deprecation.php.inc, packages/PHPUnit/tests/Rector/MethodCall/ExplicitPhpErrorApiRector/Fixture/php_error.php.inc, packages/PHPUnit/tests/Rector/MethodCall/ExplicitPhpErrorApiRector/Fixture/php_notice.php.inc, packages/PHPUnit/tests/Rector/MethodCall/ExplicitPhpErrorApiRector/Fixture/php_warning.php.inc
see: https://github.com/sebastianbergmann/phpunit/issues/3775
=> feature: add rule to refactor exception methods

packages/node-type-resolver/src/PerNodeTypeResolver/ScalarTypeResolver.php, packages/php-71/tests/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/Fixture/skip_enscaped.php.inc
=> Fix encapsed

.github/workflows/check_fixtures.yaml, .github/workflows/check_services.yaml, composer.json
see https://github.com/rectorphp/rector/pull/2784#issuecomment-580890319
=> add more checks to 'composer complete-check'

packages/attribute-aware-php-doc/src/Ast/Type/AttributeAwareCallableTypeNode.php
=> improve original format in CallableTypeNode

packages/TypeDeclaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/Fixture/respect_interface.php.inc
=> Failing test case for #2696.

packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureBasic/callable_mixed.txt, packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureBasic/callable_nullable_return.txt, packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureBasic/callable_param.txt, packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureBasic/callable_rich.txt
Falling tests for #2841
ping @TomasVotruba
=> Callable type falling tests

rules/php-74/src/Rector/Closure/ClosureToArrowFunctionRector.php, rules/php-74/tests/Rector/Closure/ClosureToArrowFunctionRector/Fixture/retain_static.php.inc
=> keep array function static

packages/node-type-resolver/src/NodeTypeResolver/ArrayDimFetchTypeResolver.php, rules/code-quality/tests/Rector/If_/ExplicitBoolCompareRector/Fixture/skip_nested_array_mixed.php.inc
=> fix nested array dim fetch resolving type

config/set/coding-style/coding-style.yaml, docs/AllRectorsOverview.md, rules/coding-style/src/Rector/Function_/CamelCaseFunctionNamingToUnderscoreRector.php, rules/coding-style/tests/Rector/Function_/CamelCaseFunctionNamingToUnderscoreRector/CamelCaseFunctionNamingToUnderscoreRectorTest.php, rules/coding-style/tests/Rector/Function_/CamelCaseFunctionNamingToUnderscoreRector/Fixture/fixture.php.inc, rules/coding-style/tests/Rector/Function_/CamelCaseFunctionNamingToUnderscoreRector/Fixture/skip_is_a.php.inc, src/Util/RectorStrings.php
=> [CodingStyle] Add CamelCaseFunctionNamingToUnderscoreRector

ecs.yaml, packages/better-php-doc-parser/src/PhpDocNode/AbstractTagValueNode.php, packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Class_/AbstractIndexTagValueNode.php, packages/better-php-doc-parser/src/PhpDocNodeFactory/AbstractPhpDocNodeFactory.php, packages/better-php-doc-parser/src/Printer/OriginalSpacingRestorer.php, packages/better-php-doc-parser/src/Printer/WhitespaceDetector.php, packages/better-php-doc-parser/tests/PhpDocParser/OrmTagParser/Class_/Fixture/FormattingDoctrineEntity.php, packages/better-php-doc-parser/tests/PhpDocParser/OrmTagParser/Class_/Fixture/expected_formatting.txt, packages/better-php-doc-parser/tests/PhpDocParser/OrmTagParser/Class_/ParserClassTest.php, rules/solid/src/Rector/ClassMethod/ChangeReadOnlyVariableWithDefaultValueToConstantRector.php
=> Fix incorrect regexes to preserve doc tags spacing

README.md, docs/AllRectorsOverview.md, rules/phpunit/src/Rector/Class_/AddSeeTestAnnotationRector.php, rules/phpunit/src/TestClassResolver/PHPUnitTestCaseClassesProvider.php, rules/phpunit/src/TestClassResolver/TestClassResolver.php, utils/documentation-generator/src/OutputFormatter/DumpRectors/MarkdownDumpRectorsOutputFormatter.php
- Closes #2793 
- Closes #2760
=> add links to each rule to docs

phpstan.neon, rules/php-70/src/EregToPcreTransformer.php, rules/php-70/src/Rector/FuncCall/EregToPregMatchRector.php
=> improve EregToPcreTransformer complexity

docs/AllRectorsOverview.md, rules/phalcon/src/Rector/MethodCall/DecoupleSaveMethodCallWithArgumentToAssignRector.php, rules/phalcon/tests/Rector/MethodCall/DecoupleSaveMethodCallWithArgumentToAssignRector/DecoupleSaveMethodCallWithArgumentToAssignRectorTest.php, rules/phalcon/tests/Rector/MethodCall/DecoupleSaveMethodCallWithArgumentToAssignRector/Fixture/fixture.php.inc, rules/php-70/src/EregToPcreTransformer.php
=> [Phalcon] Add DecoupleSaveMethodCallWithArgumentToAssignRector

composer.json, config/set/dead-code/dead-code.yaml, docs/AllRectorsOverview.md, rules/dead-code/src/Rector/Assign/RemoveUnusedVariableAssignRector.php, rules/dead-code/tests/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture/fixture.php.inc, rules/dead-code/tests/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture/skip_used.php.inc, rules/dead-code/tests/Rector/Assign/RemoveUnusedVariableAssignRector/RemoveUnusedVariableAssignRectorTest.php
=> [DeadCode] Add RemoveUnusedVariableAssignRector

config/set/database-migration/mysql-to-mysqli.yaml, docs/AllRectorsOverview.md, rules/mysql-to-mysqli/src/Rector/FuncCall/MysqlFuncCallToMysqliRector.php, rules/mysql-to-mysqli/src/Rector/FuncCall/MysqlQueryMysqlErrorWithLinkRector.php, rules/mysql-to-mysqli/tests/Rector/FuncCall/MysqlQueryMysqlErrorWithLinkRector/Fixture/fixture.php.inc, rules/mysql-to-mysqli/tests/Rector/FuncCall/MysqlQueryMysqlErrorWithLinkRector/Fixture/property_connection.php.inc, rules/mysql-to-mysqli/tests/Rector/FuncCall/MysqlQueryMysqlErrorWithLinkRector/Fixture/skip_missing_connection.php.inc, rules/mysql-to-mysqli/tests/Rector/FuncCall/MysqlQueryMysqlErrorWithLinkRector/MysqlQueryMysqlErrorWithLinkRectorTest.php
=> [MysqlToMysqli] Add MysqlQueryMysqlErrorWithLinkRector

rules/dead-code/tests/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/skip_trait_in_trait_user.php.inc, rules/dead-code/tests/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/skip_trait_used_property.php.inc
=> skip used property

config/set/codeigniter/codeigniter-40.yaml
Ref https://www.reddit.com/r/PHP/comments/f8nk0p/codeigniter_4/
=> [CodeIgniter] Add 4.0 set

rules/solid/tests/Rector/Class_/FinalizeClassesWithoutChildrenRector/Fixture/issue_1639.php.inc, stubs/Doctrine/ORM/Mapping/HasLifecycleCallbacks.php
=> add has lifecycle callbacks

rules/architecture/src/Rector/MethodCall/ServiceLocatorToDIRector.php, rules/architecture/tests/Rector/DoctrineRepositoryAsService/Fixture/issues_2930.php.inc
=> Fix prophecy mocking arg

rules/dead-code/src/Rector/Ternary/TernaryToBooleanOrFalseToBooleanAndRector.php, rules/dead-code/tests/Rector/Ternary/TernaryToBooleanOrFalseToBooleanAndRector/Fixture/skip_double_boolean.php.inc
=> Fix double boolean

.travis.yml, compiler/bin/compile, compiler/composer.json, compiler/config/config.yaml, compiler/src/Composer/ComposerJsonManipulator.php, compiler/src/Console/Command/CompileCommand.php, compiler/src/Console/RectorCompilerConsoleApplication.php, compiler/src/Debug/FileLister.php, compiler/src/Differ/ConsoleDiffer.php, compiler/src/Differ/ConsoleDifferFormatter.php, compiler/src/HttpKernel/RectorCompilerKernel.php, compiler/src/Renaming/JetbrainsStubsRenamer.php
- Closes #2936 
- Closes #2879
=> Make compiler own kernel app + add more debug info

src/PhpParser/Printer/BetterStandardPrinter.php
=> Let amount of usages decide whether whitespaces or tabs are used

config/set/dead-code/dead-code.yaml, docs/AllRectorsOverview.md, rules/dead-code/src/Rector/FunctionLike/RemoveDuplicatedIfReturnRector.php, rules/dead-code/tests/Rector/FunctionLike/RemoveDuplicatedIfReturnRector/Fixture/fixture.php.inc, rules/dead-code/tests/Rector/FunctionLike/RemoveDuplicatedIfReturnRector/Fixture/skip_modified_value.php.inc, rules/dead-code/tests/Rector/FunctionLike/RemoveDuplicatedIfReturnRector/Fixture/skip_this.php.inc, rules/dead-code/tests/Rector/FunctionLike/RemoveDuplicatedIfReturnRector/Fixture/skip_with_differnt_value.php.inc, rules/dead-code/tests/Rector/FunctionLike/RemoveDuplicatedIfReturnRector/RemoveDuplicatedIfReturnRectorTest.php, src/PhpParser/Node/Manipulator/IfManipulator.php, src/PhpParser/Printer/BetterStandardPrinter.php
=> [DeadCode] Add RemoveDuplicatedIfReturnRector

packages/node-type-resolver/src/NodeTypeResolver.php, rules/type-declaration/src/TypeInferer/ReturnTypeInferer/ReturnedNodesReturnTypeInferer.php
=> fix return dim array fetch

rules/phpunit/src/Rector/SpecificMethod/AssertRegExpRector.php
=> fix naming of non-func call

packages/better-php-doc-parser/src/Printer/PhpDocInfoPrinter.php
=> fix extra space in phpdoc

rules/dead-code/src/Rector/ClassMethod/RemoveUnusedParameterRector.php, rules/dead-code/tests/Rector/ClassMethod/RemoveUnusedParameterRector/FixtureOpenSource/skip_empty_method_to_be_overridden.php.inc
=> skip empty method on open-source

rules/dead-code/src/Rector/ClassMethod/RemoveUnusedParameterRector.php, rules/dead-code/tests/Rector/ClassMethod/RemoveUnusedParameterRector/FixtureOpenSource/skip_protected_method_of_passed_argument.php.inc, rules/restoration/src/Rector/Namespace_/CompleteImportForPartialAnnotationRector.php
=> Skip passed argument

packages/better-php-doc-parser/src/Printer/PhpDocInfoPrinter.php, packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureBasic/return_with_back_and_forth_slashes.txt, rules/dead-code/src/Rector/ClassMethod/RemoveUnusedParameterRector.php
=> Fix PhpDocInfoPrinter slash removal

packages/better-php-doc-parser/src/PhpDocNodeFactory/ParamPhpDocNodeFactory.php, packages/better-php-doc-parser/src/PhpDocParser/AnnotationContentResolver.php, packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureBasic/union_param_array.txt, packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureBasic/union_param_array_slashes.txt
=> fix union param

packages/better-php-doc-parser/src/PhpDocInfo/PhpDocInfo.php, packages/better-php-doc-parser/src/PhpDocInfo/PhpDocInfoFactory.php, rules/type-declaration/src/Rector/ClassMethod/AddArrayParamDocTypeRector.php, rules/type-declaration/tests/Rector/ClassMethod/AddArrayParamDocTypeRector/Fixture/param_double.php.inc, rules/type-declaration/tests/Rector/ClassMethod/AddArrayParamDocTypeRector/Fixture/param_no_double.php.inc
=> improve param array type for change type

packages/better-php-doc-parser/src/Printer/PhpDocInfoPrinter.php, packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureBasic/before_param_multi_indent.txt, packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/Source/Multiline/multiline3.txt, packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/Source/Multiline/multiline4.txt, packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/Source/Multiline/multiline5.txt
=> fix multiline with one space

.github/workflows/rector.yaml, .github/workflows/rector_ci.yaml, composer.json, src/DogFood/DogFoodClass.php
if you make technical debt and Rector can fix it, Rector bot will do it for you
=> Rector CI is now exclusive for non-fork pushes + PRs

rules/knp-labs/doctrine-behaviors-20.yaml
=> add DoctrineBehaviors 2.0

rules/code-quality/tests/Rector/For_/ForToForeachRector/Fixture/fixture.php.inc, rules/code-quality/tests/Rector/For_/ForToForeachRector/Fixture/other_use_of_loop_var.php.inc
=> ForToForeachRector fixture

rules/code-quality/src/Rector/For_/ForToForeachRector.php, rules/code-quality/tests/Rector/For_/ForToForeachRector/Fixture/other_use_of_loop_var.php.inc
=> Fix other loop

packages/better-php-doc-parser/src/PhpDocInfo/PhpDocInfo.php, packages/node-type-resolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
=> fix no-space change reprint in case of dual comment

rules/dead-code/src/Rector/FunctionLike/RemoveDuplicatedIfReturnRector.php, rules/dead-code/tests/Rector/FunctionLike/RemoveDuplicatedIfReturnRector/Fixture/skip_array_shifted_value.php.inc
=> [DeadCode] Skip shifted variable

rules/type-declaration/src/TypeAlreadyAddedChecker/ReturnTypeAlreadyAddedChecker.php, rules/type-declaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/skip_parent_and_child.php.inc
=> fix union type on ReturnTypeDeclarationRector

rules/php-70/src/Rector/List_/ListSwapArrayOrderRector.php, rules/php-70/tests/Rector/List_/ListSwapArrayOrderRector/Fixture/skip-array-dim.php
=> skip if not used with the `array []` operator fixes #3053

packages/better-php-doc-parser/src/PhpDocNode/AbstractTagValueNode.php, packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Property_/IdTagValueNode.php, packages/better-php-doc-parser/src/PhpDocNodeFactory/Doctrine/Property_/IdPhpDocNodeFactory.php, packages/phpstan-static-type-mapper/src/TypeMapper/IntersectionTypeMapper.php, rules/php-74/src/Rector/Property/TypedPropertyRector.php, rules/php-74/tests/Rector/Property/TypedPropertyRector/FixtureDoctrine/doctrine_collection_with_default_array.php.inc, rules/php-74/tests/Rector/Property/TypedPropertyRector/FixtureDoctrine/doctrine_id.php.inc, rules/type-declaration/src/TypeInferer/PropertyTypeInferer.php
=> [PHP 7.4] Add id tag support + remove array on collection property

rules/php-74/src/Rector/Property/TypedPropertyRector.php, rules/php-74/tests/Rector/Property/TypedPropertyRector/Fixture/add_null.php.inc, rules/php-74/tests/Rector/Property/TypedPropertyRector/Fixture/nullable_property.php.inc, rules/php-74/tests/Rector/Property/TypedPropertyRector/Fixture/nullable_property_scalar.php.inc
=> [PHP 7.4] Add default null type on properties

config/set/dead-code/dead-code.yaml, docs/AllRectorsOverview.md, rules/dead-code/src/Rector/Assign/RemoveAssignOfVoidReturnFunctionRector.php, rules/dead-code/tests/Rector/Assign/RemoveAssignOfVoidReturnFunctionRector/Fixture/fixture.php.inc, rules/dead-code/tests/Rector/Assign/RemoveAssignOfVoidReturnFunctionRector/Fixture/skip_returned_value.php.inc, rules/dead-code/tests/Rector/Assign/RemoveAssignOfVoidReturnFunctionRector/RemoveAssignOfVoidReturnFunctionRectorTest.php, src/Contract/PHPStan/Reflection/TypeToCallReflectionResolver/TypeToCallReflectionResolverInterface.php, src/PHPStan/Reflection/TypeToCallReflectionResolver/ClosureTypeToCallReflectionResolver.php, src/PHPStan/Reflection/TypeToCallReflectionResolver/ConstantArrayTypeToCallReflectionResolver.php, src/PHPStan/Reflection/TypeToCallReflectionResolver/ConstantStringTypeToCallReflectionResolver.php, src/PHPStan/Reflection/TypeToCallReflectionResolver/ObjectTypeToCallReflectionResolver.php, src/PHPStan/Reflection/TypeToCallReflectionResolver/TypeToCallReflectionResolverRegistry.php, src/Reflection/FunctionReflectionHelper.php
=> [DeadCode] Add RemoveAssignOfVoidReturnFunctionRector

packages/better-php-doc-parser/src/PhpDocNode/AbstractTagValueNode.php, packages/better-php-doc-parser/src/PhpDocNode/Symfony/SymfonyRouteTagValueNode.php
=> Fix Route separating key

docs/AllRectorsOverview.md, phpstan.neon, rules/php80/src/Rector/NotIdentical/StrContainsRector.php, rules/php80/tests/Rector/NotIdentical/StrContainsRector/Fixture/fixture.php.inc, rules/php80/tests/Rector/NotIdentical/StrContainsRector/Fixture/preg_match.php.inc, rules/php80/tests/Rector/NotIdentical/StrContainsRector/Fixture/preg_match_string.php.inc, rules/php80/tests/Rector/NotIdentical/StrContainsRector/Fixture/strstr.php.inc, rules/php80/tests/Rector/NotIdentical/StrContainsRector/StrContainsRectorTest.php, src/Rector/AbstractRector/NameResolverTrait.php
Ref #3025 
```diff
{
{
-        return strpos('abc', 'a') !== false;
+        return str_contains('abc', 'a');
}
}
```
=> [PHP 8.0] Add StrContainsRector

config/set/code-quality/code-quality.yaml, docs/AllRectorsOverview.md, rules/code-quality/src/Rector/FuncCall/ArrayKeysAndInArrayToIssetRector.php, rules/code-quality/tests/Rector/FuncCall/ArrayKeysAndInArrayToIssetRector/ArrayKeysAndInArrayToIssetRectorTest.php, rules/code-quality/tests/Rector/FuncCall/ArrayKeysAndInArrayToIssetRector/Fixture/fixture.php.inc, rules/code-quality/tests/Rector/FuncCall/ArrayKeysAndInArrayToIssetRector/Fixture/skip_over.php.inc
=> [CodeQuality] Add ArrayKeysAndInArrayToIssetRector

config/set/code-quality/code-quality.yaml, docs/AllRectorsOverview.md, rules/code-quality/src/Rector/FuncCall/ArrayKeysAndInArrayToArrayKeyExistsRector.php, rules/code-quality/tests/Rector/FuncCall/ArrayKeysAndInArrayToIssetRector/ArrayKeysAndInArrayToArrayKeyExistsRectorTest.php, rules/code-quality/tests/Rector/FuncCall/ArrayKeysAndInArrayToIssetRector/Fixture/fixture.php.inc
See https://twitter.com/PascalLandau/status/1243788859198095360
@paslandau Like this?
=> [CodeQuality] use array_key_exists instead of isset

docs/AllRectorsOverview.md, rules/code-quality/src/Rector/FuncCall/ArrayKeysAndInArrayToArrayKeyExistsRector.php, rules/code-quality/tests/Rector/FuncCall/ArrayKeysAndInArrayToArrayKeyExistsRector/ArrayKeysAndInArrayToArrayKeyExistsRectorTest.php, rules/code-quality/tests/Rector/FuncCall/ArrayKeysAndInArrayToArrayKeyExistsRector/Fixture/fixture.php.inc, rules/code-quality/tests/Rector/FuncCall/ArrayKeysAndInArrayToArrayKeyExistsRector/Fixture/skip_over.php.inc
- fixed typo in RectorDefinition code sample
- fixed argument order of array_key_exists
- renamed test folder from ArrayKeysAndInArrayToIssetRector
to ArrayKeysAndInArrayToArrayKeyExistsRector
=> Fix ArrayKeysAndInArrayToArrayKeyExistsRectorTest

config/set/privatization/privatization.yaml, docs/AllRectorsOverview.md, packages/changes-reporting/src/Application/ErrorAndDiffCollector.php, phpstan.neon, rector.yaml, rules/code-quality/src/Rector/Class_/CompleteDynamicPropertiesRector.php, rules/code-quality/src/Rector/For_/ForToForeachRector.php, rules/coding-style/src/Rector/Catch_/CatchExceptionNameMatchingTypeRector.php, rules/phpstan/src/Type/AliasedObjectType.php, rules/privatization/src/Rector/MethodCall/PrivatizeLocalGetterToPropertyRector.php, rules/privatization/tests/Rector/MethodCall/PrivatizeLocalGetterToPropertyRector/Fixture/fixture.php.inc, rules/privatization/tests/Rector/MethodCall/PrivatizeLocalGetterToPropertyRector/Fixture/skip_differnt_object_getter.php.inc, rules/privatization/tests/Rector/MethodCall/PrivatizeLocalGetterToPropertyRector/Fixture/skip_non_getter.php.inc, rules/privatization/tests/Rector/MethodCall/PrivatizeLocalGetterToPropertyRector/Fixture/skip_parent_class.php.inc, rules/privatization/tests/Rector/MethodCall/PrivatizeLocalGetterToPropertyRector/PrivatizeLocalGetterToPropertyRectorTest.php, rules/strict-code-quality/src/Rector/Stmt/VarInlineAnnotationToAssertRector.php, rules/symfony/src/Rector/HttpKernel/GetRequestRector.php, rules/symfony/src/Rector/New_/StringToArrayArgumentProcessRector.php, rules/zend-to-symfony/src/ValueObject/RouteValueObject.php, src/Rector/AbstractRector/NameResolverTrait.php
=> [Privatization] Add PrivatizeLocalGetterToPropertyRector

packages/better-php-doc-parser/src/PhpDocInfo/PhpDocInfo.php, packages/better-php-doc-parser/src/PhpDocNode/Symfony/SymfonyRouteTagValueNode.php, packages/better-php-doc-parser/src/PhpDocNodeFactory/Symfony/SymfonyRoutePhpDocNodeFactory.php, packages/better-php-doc-parser/src/PhpDocParser/ClassAnnotationMatcher.php, packages/better-php-doc-parser/src/Printer/PhpDocInfoPrinter.php, packages/better-php-doc-parser/tests/PhpDocParser/OrmTagParser/AbstractPhpDocInfoTest.php, packages/better-php-doc-parser/tests/PhpDocParser/OrmTagParser/Class_/ParserClassTest.php, packages/better-php-doc-parser/tests/PhpDocParser/OrmTagParser/Property_/ParserPropertyTest.php, packages/better-php-doc-parser/tests/PhpDocParser/SymfonyRouteTagParser/ClassMethodTest.php, packages/better-php-doc-parser/tests/PhpDocParser/SymfonyRouteTagParser/Fixture/expected_some_class_method.txt, packages/better-php-doc-parser/tests/PhpDocParser/SymfonyRouteTagParser/Source/SomeClassMethod.php, rules/cakephp-to-symfony/src/Rector/Class_/CakePHPImplicitRouteToExplicitRouteAnnotationRector.php, rules/nette-to-symfony/src/Rector/ClassMethod/RouterListToControllerAnnotationsRector.php
=> Fix @Route localized paths

config/set/privatization/privatization.yaml, docs/AllRectorsOverview.md, packages/better-php-doc-parser/src/PhpDocNode/Symfony/SymfonyRouteTagValueNode.php, packages/node-collector/src/NodeCollector/ParsedFunctionLikeNodeCollector.php, packages/node-collector/src/NodeCollector/ParsedPropertyFetchNodeCollector.php, packages/node-collector/src/NodeFinder/PropertyFetchParsedNodesFinder.php, packages/node-collector/src/NodeVisitor/NodeCollectorNodeVisitor.php, packages/vendor-locker/src/NodeVendorLocker/PropertyVisibilityVendorLockResolver.php, rules/cakephp/src/ImplicitNameResolver.php, rules/laravel/src/FunctionToServiceMap.php, rules/privatization/src/Rector/Property/PrivatizeLocalPropertyToPrivatePropertyRector.php, rules/privatization/tests/Rector/ClassMethod/PrivatizeLocalOnlyMethodRector/Fixture/skip_trait.php.inc, rules/privatization/tests/Rector/Property/PrivatizeLocalPropertyToPrivatePropertyRector/Fixture/fixture.php.inc, rules/privatization/tests/Rector/Property/PrivatizeLocalPropertyToPrivatePropertyRector/Fixture/skip_abstract.php.inc, rules/privatization/tests/Rector/Property/PrivatizeLocalPropertyToPrivatePropertyRector/Fixture/skip_anonymous_class.php.inc, rules/privatization/tests/Rector/Property/PrivatizeLocalPropertyToPrivatePropertyRector/Fixture/skip_child_property_usage.php.inc, rules/privatization/tests/Rector/Property/PrivatizeLocalPropertyToPrivatePropertyRector/Fixture/skip_class_extended.php.inc, rules/privatization/tests/Rector/Property/PrivatizeLocalPropertyToPrivatePropertyRector/Fixture/skip_external_fetch.php.inc, rules/privatization/tests/Rector/Property/PrivatizeLocalPropertyToPrivatePropertyRector/Fixture/skip_interface_implemented.php.inc, rules/privatization/tests/Rector/Property/PrivatizeLocalPropertyToPrivatePropertyRector/Fixture/skip_parent_class_protected.php.inc, rules/privatization/tests/Rector/Property/PrivatizeLocalPropertyToPrivatePropertyRector/Fixture/skip_trait.php.inc, rules/privatization/tests/Rector/Property/PrivatizeLocalPropertyToPrivatePropertyRector/Fixture/skip_used_in_trait.php.inc, rules/privatization/tests/Rector/Property/PrivatizeLocalPropertyToPrivatePropertyRector/PrivatizeLocalPropertyToPrivatePropertyRectorTest.php, utils/project-validator/src/Command/ValidateSetsCommand.php, utils/project-validator/src/Process/ParallelTaskRunner.php
=> [Privatization] Add PrivatizeLocalPropertyToPrivatePropertyRector

config/set/coding-style/coding-style.yaml, config/set/dead-code/dead-code.yaml, docs/AllRectorsOverview.md, packages/node-collector/src/NodeCollector/ParsedNodeCollector.php, packages/node-collector/src/NodeFinder/MethodCallParsedNodesFinder.php, rector.yaml, rules/coding-style/src/Application/NameImportingCommander.php, rules/coding-style/src/Rector/Namespace_/ImportFullyQualifiedNamesRector.php, rules/dead-code/src/NodeManipulator/ClassMethodAndCallMatcher.php, rules/dead-code/src/Rector/ClassMethod/RemoveDeadRecursiveClassMethodRector.php, rules/dead-code/src/Rector/ClassMethod/RemoveUnusedPrivateMethodRector.php, rules/dead-code/src/UnusedNodeResolver/UnusedClassResolver.php, rules/dead-code/tests/Rector/ClassMethod/RemoveDeadRecursiveClassMethodRector/Fixture/fixture.php.inc, rules/dead-code/tests/Rector/ClassMethod/RemoveDeadRecursiveClassMethodRector/Fixture/private_too.php.inc, rules/dead-code/tests/Rector/ClassMethod/RemoveDeadRecursiveClassMethodRector/Fixture/remove_file.inc, rules/dead-code/tests/Rector/ClassMethod/RemoveDeadRecursiveClassMethodRector/Fixture/skip_interface.php.inc, rules/dead-code/tests/Rector/ClassMethod/RemoveDeadRecursiveClassMethodRector/Fixture/skip_used.php.inc, rules/dead-code/tests/Rector/ClassMethod/RemoveDeadRecursiveClassMethodRector/Fixture/static_call.php.inc, rules/dead-code/tests/Rector/ClassMethod/RemoveDeadRecursiveClassMethodRector/RemoveDeadRecursiveClassMethodRectorTest.php, rules/privatization/src/Rector/ClassMethod/PrivatizeLocalOnlyMethodRector.php, rules/type-declaration/src/Rector/ClassMethod/AddMethodCallBasedParamTypeRector.php, src/Exclusion/ExclusionManager.php, src/PhpParser/Node/BetterNodeFinder.php, src/Rector/AbstractRector/ComplexRemovalTrait.php
=> [DeadCode] Add RemoveDeadRecursiveClassMethodRector

packages/better-php-doc-parser/src/PhpDocNode/Symfony/SymfonyRouteTagValueNode.php, packages/better-php-doc-parser/src/PhpDocNodeFactory/Symfony/SymfonyRoutePhpDocNodeFactory.php, packages/better-php-doc-parser/tests/PhpDocParser/SymfonyRouteTagParser/Fixture/expected_route_with_host.txt, packages/better-php-doc-parser/tests/PhpDocParser/SymfonyRouteTagParser/Source/RouteWithHost.php, packages/better-php-doc-parser/tests/PhpDocParser/SymfonyRouteTagParser/SymfonyRouteClassMethodTest.php
=> fix missing host at @Route annotation

rules/code-quality/src/Rector/FuncCall/ArrayMergeOfNonArraysToSimpleArrayRector.php, rules/code-quality/tests/Rector/FuncCall/ArrayMergeOfNonArraysToSimpleArrayRector/Fixture/with_keys.php.inc
=> Fix missing array key in ArrayMergeOfNonArraysToSimpleArrayRector

.docker/php/xdebug.ini, .dockerignore, Dockerfile
=> Copy .git directory into docker image

config/set/phpunit/phpunit91.yaml
=> [PHPUnit 9.1] Add assertFileNotExists() method rename

rules/code-quality/src/Rector/FuncCall/ChangeArrayPushToArrayAssignRector.php, rules/code-quality/tests/Rector/FuncCall/ChangeArrayPushToArrayAssignRector/Fixture/skip_spread_array.php.inc
=> [CodeQuality] Make ChangeArrayPushToArrayAssignRector skip spread

packages/better-php-doc-parser/src/PhpDocNode/AbstractTagValueNode.php, packages/better-php-doc-parser/src/PhpDocNode/Symfony/SymfonyRouteTagValueNode.php, packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php, packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertTypeTagValueNode.php, packages/better-php-doc-parser/src/PhpDocNodeFactory/Symfony/Validator/Constraints/AssertTypePhpDocNodeFactory.php, packages/better-php-doc-parser/src/Utils/ArrayItemStaticHelper.php, packages/better-php-doc-parser/tests/PhpDocParser/SymfonyValidation/Fixture/Choice/AssertChoiceNonQuoteValues.php, packages/better-php-doc-parser/tests/PhpDocParser/SymfonyValidation/Fixture/Choice/AssertChoiceQuoteValues.php, packages/better-php-doc-parser/tests/PhpDocParser/SymfonyValidation/Fixture/Choice/AssertQuoteChoice.php, packages/better-php-doc-parser/tests/PhpDocParser/SymfonyValidation/Fixture/Type/AssertArrayType.php, packages/better-php-doc-parser/tests/PhpDocParser/SymfonyValidation/Fixture/Type/AssertStringQuotedType.php, packages/better-php-doc-parser/tests/PhpDocParser/SymfonyValidation/Fixture/Type/AssertStringType.php, packages/better-php-doc-parser/tests/PhpDocParser/SymfonyValidation/Fixture/Type/AssertTypeWithMessage.php, rules/symfony/src/PhpDocParser/Ast/PhpDoc/AbstractConstraintTagValueNode.php, src/PhpDoc/PhpDocClassRenamer.php
=> Type and Choice fixes

rules/php73/tests/Rector/FuncCall/RegexDashEscapeRector/Fixture/slashes.php.inc, src/PhpParser/Printer/BetterStandardPrinter.php
=> [PHP 7.3] Fix regex slash escaping

packages/better-php-doc-parser/src/PhpDocNode/AbstractTagValueNode.php, packages/better-php-doc-parser/src/PhpDocNode/Symfony/SymfonyRouteTagValueNode.php, packages/better-php-doc-parser/src/PhpDocNodeFactory/Symfony/SymfonyRoutePhpDocNodeFactory.php, packages/better-php-doc-parser/src/Printer/OriginalSpacingRestorer.php, packages/better-php-doc-parser/src/Printer/PhpDocInfoPrinter.php, packages/better-php-doc-parser/src/Printer/WhitespaceDetector.php, packages/better-php-doc-parser/tests/PhpDocParser/DoctrineOrmTagParser/DoctrineOrmTagNodeTest.php, packages/better-php-doc-parser/tests/PhpDocParser/SymfonyRouteTagParser/Fixture/RouteWithCondition.php, packages/better-php-doc-parser/tests/PhpDocParser/SymfonyRouteTagParser/Fixture/RouteWithExtraNewline.php, src/PhpParser/Printer/BetterStandardPrinter.php
=> add condition test for @Route

docs/AllRectorsOverview.md, rules/phpunit/src/Rector/MethodCall/ReplaceAssertArraySubsetRector.php, rules/phpunit/tests/Rector/MethodCall/ReplaceAssertArraySubsetRector/Fixture/assert_same_assert_equal.php.inc, rules/phpunit/tests/Rector/MethodCall/ReplaceAssertArraySubsetRector/Fixture/fixture.php.inc, rules/phpunit/tests/Rector/MethodCall/ReplaceAssertArraySubsetRector/Fixture/issue_2069.php.inc, rules/phpunit/tests/Rector/MethodCall/ReplaceAssertArraySubsetRector/Fixture/issue_2237.php.inc, rules/phpunit/tests/Rector/MethodCall/ReplaceAssertArraySubsetRector/Fixture/issue_2279.php.inc, rules/phpunit/tests/Rector/MethodCall/ReplaceAssertArraySubsetRector/Fixture/multilevel_array.php.inc, rules/phpunit/tests/Rector/MethodCall/ReplaceAssertArraySubsetRector/Fixture/variable.php.inc
=> [PHPUnit] Add strict param to ReplaceAssertArraySubsetRector

config/set/code-quality/code-quality.yaml, docs/AllRectorsOverview.md, rules/code-quality/src/Rector/Assign/SplitListAssignToSeparateLineRector.php, rules/code-quality/tests/Rector/Assign/SplitListAssignToSeparateLineRector/Fixture/fixture.php.inc, rules/code-quality/tests/Rector/Assign/SplitListAssignToSeparateLineRector/Fixture/not_scalar.php.inc, rules/code-quality/tests/Rector/Assign/SplitListAssignToSeparateLineRector/Fixture/skip_split_of_array.php.inc, rules/code-quality/tests/Rector/Assign/SplitListAssignToSeparateLineRector/Fixture/skip_swap.php.inc, rules/code-quality/tests/Rector/Assign/SplitListAssignToSeparateLineRector/Fixture/with_list_function.php.inc, rules/code-quality/tests/Rector/Assign/SplitListAssignToSeparateLineRector/SplitListAssignToSeparateLineRectorTest.php, rules/php70/src/Rector/Ternary/TernaryToNullCoalescingRector.php
=> [CodeQuality] Add SplitListScalarAssignToSeparateLineRector

rules/phpunit/src/Rector/ExceptionAnnotationRector.php, rules/phpunit/tests/Rector/ExceptionAnnotationRector/Fixture/skip_method_with_null_php_doc.php.inc
=> [PHPUnit] Fix ExceptionAnnotationRector for null phpdoc

composer.json, docs/AllRectorsOverview.md, rules/restoration/src/Rector/Class_/RemoveFinalFromEntityRector.php, rules/restoration/tests/Rector/Class_/RemoveFinalFromEntityRector/Fixture/fixture.php.inc, rules/restoration/tests/Rector/Class_/RemoveFinalFromEntityRector/RemoveFinalFromEntityRectorTest.php, src/Rector/AbstractRector/AbstractRectorTrait.php
=> [Restoration] Add RemoveFinalFromEntityRector

packages/better-php-doc-parser/src/PhpDocNodeFactory/Symfony/SymfonyRoutePhpDocNodeFactory.php
Should not call getLocalizedPaths if method doesnt exists.
=> https://github.com/rectorphp/rector/issues/3223

compiler/build/scoper.inc.php
=> Compiler: Fix invalid changes in config/set neon files

config/set/php/php80.yaml, docs/AllRectorsOverview.md, rules/php80/src/Rector/Identical/StrEndsWithRector.php, rules/php80/tests/Rector/Identical/StrEndsWithRector/Fixture/fixture.php.inc, rules/php80/tests/Rector/Identical/StrEndsWithRector/Fixture/skip_substr_compare_not_zero.php.inc, rules/php80/tests/Rector/Identical/StrEndsWithRector/Fixture/substr_compare.php.inc, rules/php80/tests/Rector/Identical/StrEndsWithRector/Fixture/substr_other_way.php.inc, rules/php80/tests/Rector/Identical/StrEndsWithRector/StrEndsWithRectorTest.php
=> [PHP 8.0] Add str_ends_with()

packages/better-php-doc-parser/tests/PhpDocParser/TagValueNodeReprint/Fixture/SymfonyRoute/RouteWithPrefixAndEmptyName.php
=> Symfony route with prefix

README.md
Side note - you can do autoupdate like you do with `docs/AllRectorsOverview.md` page (the inside) when you add new rector. For example, update this counter on each 50 new rectors, i.e. 500/550/600/650
=> Update rector counter

config/set/php/php80.yaml, docs/AllRectorsOverview.md, rules/php80/src/Rector/Class_/StringableForToStringRector.php, rules/php80/tests/Rector/Class_/StringableForToStringRector/Fixture/fixture.php.inc, rules/php80/tests/Rector/Class_/StringableForToStringRector/StringableForToStringRectorTest.php
=> [PHP 8.0] Add Stringable

rules/type-declaration/src/TypeInferer/PropertyTypeInferer/DoctrineColumnPropertyTypeInferer.php, rules/type-declaration/src/TypeInferer/PropertyTypeInferer/DoctrineRelationPropertyTypeInferer.php
=> make Doctrine property inferer skip non doc

packages/better-php-doc-parser/tests/PhpDocParser/TagValueNodeReprint/Fixture/SymfonyRoute/RouteNameWithMethodAndClassConstant.php
=> add test case for #3271

config/set/php/php80.yaml, docs/AllRectorsOverview.md, rules/php80/src/Rector/Class_/AnnotationToAttributeRector.php, rules/php80/src/Rector/FuncCall/ClassOnObjectRector.php, rules/php80/tests/Rector/FuncCall/ClassOnObjectRector/ClassOnObjectRectorTest.php, rules/php80/tests/Rector/FuncCall/ClassOnObjectRector/Fixture/fixture.php.inc, src/ValueObject/PhpVersionFeature.php
=> [PHP 8.0] Add ClassOnObjectRector

config/set/php/php80.yaml, docs/AllRectorsOverview.md, rules/php80/src/Rector/Ternary/GetDebugTypeRector.php, rules/php80/tests/Rector/Ternary/GetDebugTypeRector/Fixture/fixture.php.inc, rules/php80/tests/Rector/Ternary/GetDebugTypeRector/GetDebugTypeRectorTest.php
=> [PHP 8.0] Add get_debug_type()

config/set/order/order.yaml, docs/rector_rules_overview.md, phpstan.neon, rules/order/config/config.yaml, rules/order/src/Rector/Class_/OrderPrivateMethodsByUseRector.php, rules/order/src/Rector/Class_/OrderPublicInterfaceMethodRector.php, rules/order/src/StmtOrder.php, rules/order/tests/Rector/Class_/OrderPublicInterfaceMethodRector/Fixture/fixture.php.inc, rules/order/tests/Rector/Class_/OrderPublicInterfaceMethodRector/OrderPublicInterfaceMethodRectorTest.php, rules/order/tests/Rector/Class_/OrderPublicInterfaceMethodRector/Source/FoodRecipeInterface.php
Mirror to https://github.com/symplify/coding-standard/blob/d170dd9979201c5ceb0748e1c2c17e888b438c98/src/Fixer/Order/MethodOrderByTypeFixer.php
=> [Order] Add OrderPublicInterfaceMethodRector

tests/Issues/Issue3291/Fixture/fixture3291_keep_private_property.php.inc
Closes #3291 
cc @tomasnorre This shows how test case is the most useful report.
With failing test, it was matter of 2 minutes to fix for me.
=> fix test case

.gitattributes
=> do not export compiler as part of package

packages/better-php-doc-parser/src/PhpDocNode/AbstractTagValueNode.php, rules/sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/FixtureVersion5/with_route_options.php.inc
Closes #3241
cc @stephanvierkant
=> add = for @Route options separator

.github/workflows/update_documentation.yaml, .github/workflows/validate_project.yaml
Inspiration https://github.com/sabbelasichon/typo3-rector/pull/1354﻿
=> workflow: generate documentation

.github/workflows/update_changelog.yaml
=> workflow: generate changelog

packages/better-php-doc-parser/src/PhpDocInfo/PhpDocInfoFactory.php, packages/node-type-resolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php, rules/dead-code/src/Rector/Stmt/RemoveDeadStmtRector.php, rules/doctrine-gedmo-to-knplabs/src/Rector/Class_/SluggableBehaviorRector.php, rules/doctrine-gedmo-to-knplabs/src/Rector/Class_/TranslationBehaviorRector.php, rules/phpstan/src/Rector/Assign/PHPStormVarAnnotationRector.php, rules/sensio/src/Rector/FrameworkExtraBundle/TemplateAnnotationRector.php, rules/solid/src/Rector/ClassMethod/ChangeReadOnlyVariableWithDefaultValueToConstantRector.php, rules/solid/tests/Rector/ClassMethod/ChangeReadOnlyVariableWithDefaultValueToConstantRector/Fixture/replace_in_args.php.inc, rules/symfony-code-quality/src/Rector/Class_/EventListenerToEventSubscriberRector.php, src/Rector/AbstractRector.php, tests/Issues/Issue3222/Fixture/fixture3222.php.inc, tests/Issues/Issue3222/Fixture/fixture3222_with_many_comments.php.inc, tests/Issues/Issue3222/Issue3222Test.php, tests/Issues/Issue3222/config3222.yaml
Replaces #3250 
Fixes #3222
Releated to switch of docblocks to PHPDocInfo - https://github.com/rectorphp/rector/pull/2775
=> Fix comment removing

bin/rector
Closes https://github.com/rectorphp/rector/issues/3330#issuecomment-625783407
=> Define `__RECTOR_RUNNING__` constant at analysis time

docs/rector_recipe.md
This change will suggest to use command given in the output of the vendor/bin/rector
=> Alter command name

config/set/coding-style/coding-style.yaml, docs/rector_rules_overview.md, rules/coding-style/src/Rector/Use_/SplitGroupedUseImportsRector.php, rules/coding-style/tests/Rector/Use_/SplitGroupedUseImportsRector/Fixture/fixture.php.inc, rules/coding-style/tests/Rector/Use_/SplitGroupedUseImportsRector/Fixture/trait_uses.php.inc, rules/coding-style/tests/Rector/Use_/SplitGroupedUseImportsRector/Source/FirstTrait.php, rules/coding-style/tests/Rector/Use_/SplitGroupedUseImportsRector/Source/SecondTrait.php, rules/coding-style/tests/Rector/Use_/SplitGroupedUseImportsRector/SplitGroupedUseImportsRectorTest.php, src/Testing/Finder/RectorsFinder.php
=> [CodingStyle] Add SplitGroupedUseImportsRector

rules/phpunit/src/Rector/MethodCall/CreateMockToCreateStubRector.php, rules/phpunit/tests/Rector/MethodCall/CreateMockToCreateStubRector/Fixture/skip_non_phpunit.php.inc, rules/phpunit/tests/Rector/MethodCall/CreateMockToCreateStubRector/Fixture/skip_sonata_expects.php.inc
=> [PHPUnit] Fix CreateMockToCreateStubRector outside PHPUnit test case

composer.json, config/services.yaml, packages/better-php-doc-parser/tests/PhpDocParser/Helper/TagValueToPhpParserNodeMap.php, src/HttpKernel/RectorKernel.php
Follow up to https://github.com/symplify/symplify/pull/1956
=> remove deprecated AutoReturnFactoryCompilerPass

.github/workflows/phpstan_compatibility_check.yaml, composer.json, packages/attribute-aware-php-doc/src/Ast/PhpDoc/AttributeAwareMixinTagValueNode.php, packages/attribute-aware-php-doc/src/Ast/Type/AttributeAwareConstTypeNode.php, packages/attribute-aware-php-doc/src/AttributeAwareNodeFactory/PhpDoc/AttributeAwareMixinTagValueNodeFactory.php, packages/attribute-aware-php-doc/src/AttributeAwareNodeFactory/Type/AttributeAwareConstTypeNodeFactory.php, utils/phpstan-attribute-type-syncer/src/NodeFactory/AttributeAwareClassFactoryFactory.php
Closes #3331
Waits on slevomat/coding-standard release
=> Add @mixin support from PHPStan

src/PhpParser/Printer/BetterStandardPrinter.php
This fixes [#3276](https://github.com/rectorphp/rector/issues/3276), exactly like [UFTimmy](https://github.com/UFTimmy) said.
=> Use Newline from Standard Printer

rules/coding-style/src/Rector/ClassMethod/NewlineBeforeNewAssignSetRector.php
=> Guard against ShouldNotHappenException

composer.json, config/set/nette/kdyby-events-to-contributte-event-dispatcher.yaml, docs/rector_rules_overview.md, rules/coding-style/src/Naming/ClassNaming.php, rules/nette-kdyby/config/config.yaml, rules/nette-kdyby/src/ContributeEventClassResolver.php, rules/nette-kdyby/src/NodeManipulator/GetSubscribedEventsArrayManipulator.php, rules/nette-kdyby/src/NodeManipulator/SubscriberMethodArgumentToContributteEventObjectManipulator.php, rules/nette-kdyby/src/NodeResolver/ListeningMethodsCollector.php, rules/nette-kdyby/src/Rector/Class_/KdybyEventSubscriberToContributteEventSubscriberRector.php, rules/nette-kdyby/src/ValueObject/NetteEventToContributeEventClass.php, rules/nette-kdyby/tests/Rector/Class_/KdybyEventSubscriberToContributteEventSubscriberRector/Fixture/application_on_shutdown.php.inc, rules/nette-kdyby/tests/Rector/Class_/KdybyEventSubscriberToContributteEventSubscriberRector/KdybyEventSubscriberToContributteEventSubscriberRectorTest.php, src/Testing/PHPUnit/AbstractRectorTestCase.php, stubs/Kdyby/Events/Subscriber.php
```diff
use Kdyby\Events\Subscriber;
use Nette\Application\Application;
class GetApplesSubscriber implements Subscriber
{
-    public function getSubscribedEvents()
+    public static function getSubscribedEvents()
{
return [
-            Application::class . '::onShutdown',
+            ShutdownEvent::class => 'onShutdown',
CustomService::class . '::onCopy' => 'onCustomCopy',
];
}
public function onShutdown()
{
}
public function onCustomCopy()
{
}
}
```
=> [Kdyby to Contributte] Migrate events

rules/privatization/src/Rector/Property/PrivatizeFinalClassPropertyRector.php, rules/privatization/tests/Rector/Property/PrivatizeFinalClassPropertyRector/Fixture/keep_used_public.php.inc
- Follow up to #3412 
- Closes #3409
=> skip public properties

config/set/symfony/symfony28.yaml, config/set/symfony/symfony31.yaml, config/set/symfony/symfony42.yaml, src/Rector/Argument/ArgumentDefaultValueReplacerRector.php, stubs/Symfony/Component/Routing/Generator/UrlGeneratorInterface.php, stubs/Symfony/Component/Routing/Router.php, stubs/Symfony/Component/Routing/RouterInterface.php, tests/Rector/Argument/ArgumentDefaultValueReplacerRector/ArgumentDefaultValueReplacerRectorTest.php, tests/Rector/Argument/ArgumentDefaultValueReplacerRector/Fixture/fixture.php.inc, tests/Rector/Argument/ArgumentDefaultValueReplacerRector/Fixture/fixture3.php.inc, tests/Rector/Argument/ArgumentDefaultValueReplacerRector/FixtureSymfony28/url_matcher_generate.php.inc, tests/Rector/Argument/ArgumentDefaultValueReplacerRector/Symfony28Test.php
Also cover https://github.com/symfony/symfony/commit/912fc4de8fd6de1e5397be4a94d39091423e5188 in Symfony 2.8
=> [Symfony 2.8] Fix ArgumentDefaultValueReplacerRector to work with bool values

rules/symfony/src/Rector/FrameworkBundle/GetToConstructorInjectionRector.php
=> fix prefixed GetToConstructorInjectionRector classes

composer.json, config/set/nette/nette-utils-code-quality.yaml, docs/rector_rules_overview.md, rules/nette-utils-code-quality/src/Rector/LNumber/ReplaceTimeNumberWithDateTimeConstantRector.php, rules/nette-utils-code-quality/tests/Rector/LNumber/ReplaceTimeNumberWithDateTimeConstantRector/Fixture/fixture.php.inc, rules/nette-utils-code-quality/tests/Rector/LNumber/ReplaceTimeNumberWithDateTimeConstantRector/ReplaceTimeNumberWithDateTimeConstantRectorTest.php
=> [NetteUtilsCodeQuality] Add ReplaceTimeNumberWithDateTimeConstantRector

packages/node-type-resolver/src/FileSystem/CurrentFileInfoProvider.php, rules/coding-style/src/Imports/ShortNameResolver.php, rules/php74/tests/Rector/Property/TypedPropertyRector/FixtureImported/conflicting_short_name_in_constuctor.php.inc, src/Application/FileProcessor.php
=> [PHP 7.4] Prevent already used property name

README.md
Just a small tweak to ensure there are no left over containers when running the respective Docker commands. 
Thanks for making / sharing Rector.
=> Update docker commands to remove container on exit

packages/attribute-aware-php-doc/src/Ast/PhpDoc/AttributeAwarePropertyTagValueNode.php, packages/better-php-doc-parser/src/Ast/PhpDocNodeTraverser.php, packages/node-type-resolver/src/PhpDoc/NodeAnalyzer/DocBlockClassRenamer.php, packages/node-type-resolver/src/PhpDoc/NodeAnalyzer/DocBlockNameImporter.php, rules/renaming/tests/Rector/Class_/RenameClassRector/Fixture/rename_property_read.php.inc
=> Add support for rename of @property

packages/better-php-doc-parser/src/PhpDocNode/AbstractTagValueNode.php, packages/node-name-resolver/src/NodeNameResolver.php, src/Rector/AbstractRector/NameResolverTrait.php
=> fix method call name

src/Contract/Rector/PhpRectorInterface.php
Update documentation link in `PhpRectorInterface`
=> Update documentation link in PhpRectorInterface

packages/post-rector/src/Rector/AbstractRector/NodeCommandersTrait.php, rules/phpunit/src/Rector/MethodCall/ExplicitPhpErrorApiRector.php, src/Rector/AbstractRector/ComplexRemovalTrait.php, src/Rector/AbstractRector/NameResolverTrait.php
See https://github.com/rectorphp/rector/issues/3515#issuecomment-643600252
=> Simplify ExplicitPhpErrorApiRector and remove replaceNode() use

rules/solid/tests/Rector/ClassMethod/ChangeReadOnlyVariableWithDefaultValueToConstantRector/Fixture/skip_double_assign.php.inc, src/PhpParser/Node/Manipulator/ClassMethodAssignManipulator.php
=> skip multi assign ChangeReadOnlyVariableWithDefaultValueToConstantRector

rules/solid/src/Rector/Foreach_/ChangeNestedForeachIfsToEarlyContinueRector.php, rules/solid/tests/Rector/Foreach_/ChangeNestedForeachIfsToEarlyContinueRector/Fixture/comment_inside_if_statement.php.inc
=> fix nested comment in nested foreach to if

packages/attribute-aware-php-doc/src/Ast/PhpDoc/AttributeAwareTemplateTagValueNode.php, packages/attribute-aware-php-doc/src/AttributeAwareNodeFactory/PhpDoc/AttributeAwareTemplateTagValueNodeFactory.php, packages/better-php-doc-parser/tests/PhpDocParser/Helper/TagValueToPhpParserNodeMap.php, packages/better-php-doc-parser/tests/PhpDocParser/TagValueNodeReprint/Fixture/Native/Template/TemplateTagAs.php, packages/better-php-doc-parser/tests/PhpDocParser/TagValueNodeReprint/Fixture/Native/Template/TemplateTagAsOf.php, packages/better-php-doc-parser/tests/PhpDocParser/TagValueNodeReprint/Fixture/Native/Template/TemplateTagOf.php, packages/better-php-doc-parser/tests/PhpDocParser/TagValueNodeReprint/TagValueNodeReprintTest.php
=> fix @template tag preposition

packages/static-type-mapper/src/PhpDocParser/NullableTypeMapper.php
=> add NullableTypeMapper

rules/solid/tests/Rector/ClassMethod/ChangeReadOnlyVariableWithDefaultValueToConstantRector/Fixture/skip_enscaped_string.php.inc, src/PhpParser/Node/Manipulator/VariableManipulator.php
=> skip encapsed string from constant extraction

packages/attribute-aware-php-doc/src/Ast/Type/AttributeAwareArrayTypeNode.php, packages/better-php-doc-parser/tests/PhpDocParser/Helper/TagValueToPhpParserNodeMap.php, packages/better-php-doc-parser/tests/PhpDocParser/TagValueNodeReprint/Fixture/Native/VarTag/ArrayType/ArrayCallableType.php, packages/better-php-doc-parser/tests/PhpDocParser/TagValueNodeReprint/TagValueNodeReprintTest.php, rector.yaml
=> Fix for array of callable print in phpdoc

config/set/phpunit/phpunit90.yaml
=> Add PHPUnit 9.0 regex method name changes

config/set/order/order.yaml, docs/rector_rules_overview.md, rules/order/src/Rector/Class_/OrderClassConstantsByIntegerValueRector.php, rules/order/tests/Rector/Class_/OrderClassConstantsByIntegerValueRector/Fixture/fixture.php.inc, rules/order/tests/Rector/Class_/OrderClassConstantsByIntegerValueRector/Fixture/from_zero.php.inc, rules/order/tests/Rector/Class_/OrderClassConstantsByIntegerValueRector/OrderClassConstantsByIntegerValueRectorTest.php
=> [Order] Add OrderClassConstantsByIntegerValueRector

packages/better-php-doc-parser/src/PartPhpDocTagPrinter/Behavior/ArrayPartPhpDocTagPrinterTrait.php, packages/better-php-doc-parser/src/PhpDocNode/AbstractTagValueNode.php, packages/better-php-doc-parser/src/PhpDocNode/PrintTagValueNodeTrait.php, packages/better-php-doc-parser/src/PhpDocNode/Symfony/SymfonyRouteTagValueNode.php, packages/better-php-doc-parser/src/ValueObject/TagValueNodeConfiguration.php, packages/better-php-doc-parser/src/ValueObjectFactory/TagValueNodeConfigurationFactory.php, packages/better-php-doc-parser/tests/PartPhpDocTagPrinter/Behavior/ArrayPartPhpDocTagPrinterTest.php, packages/better-php-doc-parser/tests/PartPhpDocTagPrinter/Behavior/Source/PhpDocTagNodeWithArrayPrinter.php, packages/better-php-doc-parser/tests/PhpDocParser/TagValueNodeReprint/TagValueNodeReprintTest.php, rules/sensio/src/Rector/ClassMethod/ReplaceSensioRouteAnnotationWithSymfonyRector.php
=> Fix quote in array values of phpdoc tags, decouple TagValueNodeConfiguration

README.md, rector.yaml, src/Application/RectorApplication.php, src/Configuration/Configuration.php, src/Configuration/OnlyRuleResolver.php, src/Configuration/Option.php, src/Configuration/RectorClassesProvider.php, src/Console/Command/ProcessCommand.php, src/DependencyInjection/CompilerPass/MakeRectorsPublicCompilerPass.php, src/Exception/Configuration/RectorRuleNotFoundException.php, src/HttpKernel/RectorKernel.php, tests/Configuration/OnlyRuleResolverTest.php, tests/Configuration/Source/CustomLocalRector.php, tests/Configuration/Source/config/some_config.yaml
Closes https://github.com/rectorphp/rector/issues/3342
=> Re-add --only option

composer.json
Closes https://github.com/rectorphp/rector/issues/3537
=> allow new phpstan

config/set/cakephp/cakephp41.yml
Add a newly deprecation method.
=> Expand CakePHP 4.1 standard

composer.json, packages/node-removal/config/config.yaml, packages/node-removal/src/BreakingRemovalGuard.php, packages/post-rector/src/Collector/NodesToRemoveCollector.php, phpstan.neon, rules/coding-style/src/Rector/ClassMethod/NewlineBeforeNewAssignSetRector.php, rules/coding-style/tests/Rector/ClassMethod/NewlineBeforeNewAssignSetRector/Fixture/skip_method_call_property_call.php.inc, src/Comments/CommentableNodeResolver.php, src/Rector/FuncCall/RemoveIniGetSetFuncCallRector.php, tests/Rector/FuncCall/RemoveIniGetSetFuncCallRector/Fixture/get_assign.php.inc
Closes https://github.com/afilina/custom-rectors/issues/33
=> Add @fixme, if ini_set/init_get removal breaks the code

rules/php70/src/Rector/MethodCall/ThisCallOnStaticMethodToStaticCallRector.php, rules/php70/tests/Rector/MethodCall/ThisCallOnStaticMethodToStaticCallRector/Fixture/fixture.php.inc
If a class could be inherited, "$this->"" needs to become "static::" instead of "self::"
=> "$this->"" needs to become "static::" instead of "self::"

rules/type-declaration/src/TypeInferer/ReturnTypeInferer.php, rules/type-declaration/src/TypeInferer/ReturnTypeInferer/ReturnedNodesReturnTypeInferer.php, rules/type-declaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/parent_override.php.inc
=> fix return type in abstract class

src/Rector/AbstractRector/NameResolverTrait.php
=> fix get name or static call

rector-ci.yaml, rules/coding-style/src/Rector/ClassMethod/ReturnArrayClassMethodToYieldRector.php, rules/coding-style/tests/Rector/ClassMethod/ReturnArrayClassMethodToYieldRector/Fixture/provide_data_multi_items.php.inc, rules/coding-style/tests/Rector/ClassMethod/ReturnArrayClassMethodToYieldRector/ReturnArrayClassMethodToYieldRectorTest.php, tests/Configuration/ComposerJsonParserTest.php, tests/Configuration/MinimalVersionCheckerTest.php
cc @dobryy We got it CI covered now :wink:
=> fix data provider to iterator

rules/coding-style/src/Node/NameImporter.php, rules/coding-style/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/skip_aliased_names.php.inc, rules/coding-style/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/skip_aliased_names_docblock.php.inc
Closes https://github.com/rectorphp/rector/issues/3336
=> [CodingStyle] Import classes only for Fully Qualified class names byt skipping all Qualified names

rules/legacy/src/Rector/Include_/RemoveIncludeRector.php, rules/legacy/tests/Rector/Include_/RemoveIncludeRector/Fixture/fixture.php.inc, rules/legacy/tests/Rector/Include_/RemoveIncludeRector/RemoveIncludeRectorTest.php
Add a Rector to remove all include statements.
=> [Legacy] RemoveIncludeRector

rules/mysql-to-mysqli/src/Rector/Assign/MysqlAssignToMysqliRector.php, rules/mysql-to-mysqli/src/Rector/FuncCall/MysqlFuncCallToMysqliRector.php, rules/mysql-to-mysqli/tests/Rector/Assign/MysqlAssignToMysqliRector/Fixture/fixture.php.inc, rules/mysql-to-mysqli/tests/Rector/Assign/MysqlAssignToMysqliRector/Fixture/fixture4.php.inc, rules/mysql-to-mysqli/tests/Rector/FuncCall/MysqlFuncCallToMysqliRector/Fixture/fixture.php.inc
=> [MysqlToMysqli] Mysql mysqli stackoverflow feedback

rules/symfony/src/Contract/Tag/TagInterface.php, rules/symfony/src/FormHelper/FormTypeStringToTypeProvider.php, rules/symfony/src/Rector/Form/StringFormTypeToClassRector.php, rules/symfony/src/ServiceMapProvider.php, rules/symfony/src/ValueObject/ServiceDefinition.php, rules/symfony/src/ValueObject/Tag.php, rules/symfony/src/ValueObject/Tag/EventListenerTag.php, rules/symfony/tests/Rector/Form/StringFormTypeToClassRector/Fixture/skip_already_added_type.php.inc, rules/symfony/tests/Rector/Form/StringFormTypeToClassRector/Fixture/skip_variable.php.inc, rules/symfony/tests/Rector/Form/StringFormTypeToClassRector/FixtureWithContainer/fixture.php.inc, rules/symfony/tests/Rector/Form/StringFormTypeToClassRector/Source/custom_container.xml, rules/symfony/tests/Rector/Form/StringFormTypeToClassRector/WithContainerTest.php
How to activate?
```yaml
parameters:
symfony_container_xml_path: 'app/temp/cache/dev/container.xml
```
=> [Symfony 3] Add custom xml to StringFormTypeToClassRector"

config/set/symfony/symfony30.yaml, rules/symfony/src/Rector/MethodCall/AbstractFormAddRector.php, rules/symfony/src/Rector/MethodCall/ChangeCollectionTypeOptionNameFromTypeToEntryTypeRector.php, rules/symfony/tests/Rector/MethodCall/ChangeCollectionTypeOptionNameFromTypeToEntryTypeRector/ChangeCollectionTypeOptionNameFromTypeToEntryTypeRectorTest.php, rules/symfony/tests/Rector/MethodCall/ChangeCollectionTypeOptionNameFromTypeToEntryTypeRector/Fixture/fixture.php.inc, rules/symfony/tests/Rector/MethodCall/ChangeCollectionTypeOptionNameFromTypeToEntryTypeRector/Fixture/skip_already_added.php.inc, rules/symfony/tests/Rector/MethodCall/ChangeCollectionTypeOptionNameFromTypeToEntryTypeRector/Fixture/skip_without_options.php.inc
=> [Symfony] Add ChangeCollectionTypeOptionNameFromTypeToEntryTypeRector

docs/rector_rules_overview.md, rules/symfony/src/NodeFactory/BuilderFormNodeFactory.php, rules/symfony/src/NodeFactory/ConfigureOptionsNodeFactory.php, rules/symfony/src/Rector/MethodCall/AbstractFormAddRector.php, rules/symfony/src/Rector/MethodCall/FormTypeInstanceToClassConstRector.php, rules/symfony/tests/Rector/MethodCall/FormTypeInstanceToClassConstRector/Fixture/create_form.php.inc, rules/symfony/tests/Rector/MethodCall/FormTypeInstanceToClassConstRector/Fixture/create_form_with_dependency.php.inc, rules/symfony/tests/Rector/MethodCall/FormTypeInstanceToClassConstRector/Fixture/form_add.php.inc, rules/symfony/tests/Rector/MethodCall/FormTypeInstanceToClassConstRector/Fixture/form_add_with_dependency.php.inc, rules/symfony/tests/Rector/MethodCall/FormTypeInstanceToClassConstRector/Source/TagType.php
Covers cases [like this](https://github.com/symfony/symfony-docs/pull/5909/files#diff-82b06b5128b61d824fc06df23cf0bd5eL129):
=> [Symfony] Update instance to class reference to collection types

config/set/cakephp/cakephp41.yml
@markstory follows https://github.com/cakephp/cakephp/pull/14761
=> Add Comparison to ComparisonExpression rename

rules/legacy/src/Rector/Include_/AddTopIncludeRector.php, rules/legacy/tests/Rector/Include_/AddTopIncludeRector/AddTopIncludeRectorTest.php, rules/legacy/tests/Rector/Include_/AddTopIncludeRector/Expected/fixture.php.inc, rules/legacy/tests/Rector/Include_/AddTopIncludeRector/Expected/has_class.php.inc, rules/legacy/tests/Rector/Include_/AddTopIncludeRector/Expected/has_include.php.inc, rules/legacy/tests/Rector/Include_/AddTopIncludeRector/Fixture/fixture.php.inc, rules/legacy/tests/Rector/Include_/AddTopIncludeRector/Fixture/has_class.php.inc, rules/legacy/tests/Rector/Include_/AddTopIncludeRector/Fixture/has_include.php.inc
Add AddTopIncludeRector squashed!
=> [Legacy] Add AddTopIncludeRector squash

config/set/cakephp/cakephp40.yaml
=> Add more refactorings for CakePHP 4.0

packages/changes-reporting/src/Output/ConsoleOutputFormatter.php
=> Improve grammar

config/set/phpunit-code-quality.php, rules/dead-code/src/NodeFinder/NextVariableUsageNodeFinder.php, rules/dead-code/tests/Rector/Assign/RemoveUnusedAssignVariableRector/Fixture/skip_assign_expression_class_use_variable.php.inc, rules/dead-code/tests/Rector/Assign/RemoveUnusedAssignVariableRector/Fixture/skip_assign_expression_closure_use_variable.php.inc, rules/dead-code/tests/Rector/Assign/RemoveUnusedAssignVariableRector/Fixture/skip_assign_expression_use_variable.php.inc, rules/dead-code/tests/Rector/Assign/RemoveUnusedAssignVariableRector/Fixture/skip_assign_expression_use_variable_as_function_param.php.inc, src/PhpParser/Node/BetterNodeFinder.php
Closes https://github.com/rectorphp/rector/issues/3726
=> [DeadCode] Fix variable usage detection

bin/rector, src/Bootstrap/RectorConfigsResolver.php, src/Set/SetResolver.php
=> [Config] Warn about YAML deprecation + load YAML sets

packages/better-php-doc-parser/src/PhpDocNodeFactory/AbstractPhpDocNodeFactory.php, rules/php74/tests/Rector/Property/TypedPropertyRector/FixtureDoctrine/doctrine_many_to_one_class_keyword.php.inc, rules/php74/tests/Rector/Property/TypedPropertyRector/FixtureDoctrine/doctrine_one_to_one_class_keyword.php.inc
Related: https://github.com/rectorphp/rector/issues/3716
=> [PHP7.4] Invalid type with class keyword in Doctrine ORM property

packages/better-php-doc-parser/src/PhpDocNodeFactory/AbstractPhpDocNodeFactory.php, rules/php74/tests/Rector/Property/TypedPropertyRector/FixtureDoctrine/doctrine_many_to_one_class_keyword_imported.php.inc
Follow up to #3770 
Closes #3716
=> [PHP 7.4] Add use imported FQN name

src/PhpParser/Printer/BetterStandardPrinter.php, tests/PhpParser/Printer/BetterStandardPrinterTest.php
=> fix removing of doc

composer.json, config/services.php, rules/code-quality/src/Rector/For_/ForToForeachRector.php
=> Update doctrine/inflector requirement from ^1.3 to ^1.4|^2.0

rules/code-quality/src/Rector/Name/FixClassCaseSensitivityNameRector.php, rules/code-quality/tests/Rector/Name/FixClassCaseSensitivityNameRector/Fixture/namespace_and_constants.php.inc
=> fix fixture content

README.md, docs/create_own_rule.md, docs/how_it_works.md, docs/rector_recipe.md
Closes https://github.com/rectorphp/rector/issues/3798
=> [DX] Update README and other docs files to use PHP syntax for configs

rules/php70/tests/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector/Fixture/keep_variable_method.php.inc
https://github.com/rectorphp/rector/issues/3824
=> Add failing test case for issue 3824

packages/rector-generator/src/FileSystem/TemplateFileSystem.php, rules/php70/src/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector.php, src/Testing/PHPUnit/AbstractGenericRectorTestCase.php, src/Testing/PHPUnit/AbstractRectorTestCase.php, utils/project-validator/src/Command/ValidateFixtureContentCommand.php
=> [PHP 7.0] Fix variable name on static call

rules/php56/tests/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/Fixture/skip_unset.php.inc
=> Add failing fixture for AddDefaultValueForUndefinedVariableRector

.kodiak.toml, rules/php56/src/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector.php, rules/php56/tests/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/Php74Test.php
=> [PHP 5.6] Fix foreach unset variable default

src/PhpParser/Node/Value/ValueResolver.php
=> Resolve " TypeError in ValueResolver::resolveClassConstFetch()"

docs/rector_rules_overview.md, rules/generic/src/Rector/MethodCall/MethodCallRemoverRector.php, rules/generic/tests/Rector/MethodCall/MethodCallRemoverRector/Fixture/fixture.php.inc, rules/generic/tests/Rector/MethodCall/MethodCallRemoverRector/MethodCallRemoverRectorTest.php, rules/generic/tests/Rector/MethodCall/MethodCallRemoverRector/Source/Car.php, rules/generic/tests/Rector/MethodCall/MethodCallRemoverRector/Source/CarType.php, src/PhpParser/Node/Manipulator/MethodCallManipulator.php
Closes #3843
As stated in issue I have no idea how to retrieve variable name.
=> method call remover rector

rules/solid/src/Rector/Property/ChangeReadOnlyPropertyWithDefaultValueToConstantRector.php, rules/solid/tests/Rector/Property/ChangeReadOnlyPropertyWithDefaultValueToConstantRector/Fixture/skip_end_function.php.inc, rules/solid/tests/Rector/Property/ChangeReadOnlyPropertyWithDefaultValueToConstantRector/Fixture/skip_trait.php.inc, src/PhpParser/Node/Manipulator/PropertyManipulator.php
=> [SOLID] Skip property that is being changed by func call

packages/file-system-rector/src/FileSystemFileProcessor.php, src/PhpParser/NodeTraverser/RectorNodeTraverser.php
=> skip configure unless in tests

config/set/order.php, packages/reporting/src/EventSubscriber/PrintReportCollectorEventSubscriber.php, rules/order/src/Rector/ClassLike/OrderMethodsByVisibilityRector.php, rules/order/src/Rector/Class_/OrderPrivateMethodsByUseRector.php, rules/order/src/StmtOrder.php, rules/order/tests/Rector/ClassLike/OrderMethodsByVisibilityRector/Fixture/abstact.php.inc, rules/order/tests/Rector/ClassLike/OrderMethodsByVisibilityRector/Fixture/fixture.php.inc, rules/order/tests/Rector/ClassLike/OrderMethodsByVisibilityRector/Fixture/magic_phpunit_preferred_order.php.inc, rules/order/tests/Rector/ClassLike/OrderMethodsByVisibilityRector/OrderMethodsByVisibilityRectorTest.php, rules/order/tests/StmtOrderTest.php, src/Rector/AbstractRector.php, src/Testing/PHPUnit/AbstractGenericRectorTestCase.php
=> [Order] Order class methods by visibility

config/set/order.php, docs/rector_rules_overview.md, rules/order/src/Rector/ClassLike/OrderMethodsByVisibilityRector.php, rules/order/src/Rector/ClassLike/OrderPropertiesByVisibilityRector.php, rules/order/src/StmtOrder.php, rules/order/tests/Rector/ClassLike/OrderPropertiesByVisibilityRector/Fixture/abstract.php.inc, rules/order/tests/Rector/ClassLike/OrderPropertiesByVisibilityRector/Fixture/fixture.php.inc, rules/order/tests/Rector/ClassLike/OrderPropertiesByVisibilityRector/Fixture/trait.php.inc, rules/order/tests/Rector/ClassLike/OrderPropertiesByVisibilityRector/OrderPropertiesByVisibilityRectorTest.php
Closes https://github.com/rectorphp/rector/issues/3891
=> [Order] Order properties by visibility

config/set/order.php, docs/rector_rules_overview.md, rules/cakephp/src/Rector/MethodCall/ArrayToFluentCallRector.php, rules/code-quality/src/Rector/Assign/SplitListAssignToSeparateLineRector.php, rules/code-quality/src/Rector/FuncCall/ArrayMergeOfNonArraysToSimpleArrayRector.php, rules/nette-kdyby/src/NodeManipulator/GetSubscribedEventsArrayManipulator.php, rules/nette-kdyby/src/Rector/ClassMethod/ChangeNetteEventNamesInGetSubscribedEventsRector.php, rules/nette-to-symfony/src/Rector/ClassMethod/RenameEventNamesInEventSubscriberRector.php, rules/nette-to-symfony/src/Rector/MethodCall/WrapTransParameterNameRector.php, rules/order/src/Rector/ClassLike/OrderConstantsByVisibilityRector.php, rules/order/src/StmtVisibilitySorter.php, rules/order/tests/Rector/ClassLike/OrderConstantsByVisibilityRector/Fixture/abstract.php.inc, rules/order/tests/Rector/ClassLike/OrderConstantsByVisibilityRector/Fixture/fixture.php.inc, rules/order/tests/Rector/ClassLike/OrderConstantsByVisibilityRector/OrderConstantsByVisibilityRectorTest.php, rules/php-spec-to-phpunit/src/MatchersManipulator.php, rules/phpunit/src/Rector/MethodCall/ReplaceAssertArraySubsetRector.php, rules/symfony/src/Rector/Form/OptionNameRector.php, rules/symfony/src/Rector/MethodCall/CascadeValidationFormBuilderRector.php, rules/symfony/src/Rector/MethodCall/ChangeCollectionTypeOptionNameFromTypeToEntryTypeRector.php, rules/symfony/src/Rector/MethodCall/ChangeCollectionTypeOptionTypeFromStringToClassReferenceRector.php, rules/symfony/src/Rector/MethodCall/FormTypeInstanceToClassConstRector.php, src/PhpParser/Node/Manipulator/ArrayManipulator.php, src/PhpParser/NodeTransformer.php
Closes: #3892 
This branch was created from #3933 that is why the target branch is not `master`
=> [Order] Order constants by visibility

rules/phpunit/src/Rector/MethodCall/AssertEqualsToSameRector.php, rules/phpunit/tests/Rector/MethodCall/AssertEqualsToSameRector/AssertEqualsToSameRectorTest.php, rules/phpunit/tests/Rector/MethodCall/AssertEqualsToSameRector/Fixture/fixture.php.inc, rules/phpunit/tests/Rector/MethodCall/AssertEqualsToSameRector/Fixture/skip.php.inc
Closes https://github.com/rectorphp/rector/issues/3742
EDIT by @TomasVotruba - added Github [closing keyword](https://docs.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords) so issue is closed by Github on merge
=> Add AssertEqualsToSameRector

rules/php70/tests/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector/Fixture/keep_variable_class_string.php.inc
Here is the pr with a failing testcase for #3981 as requested 👍 
Hope I did it correctly.
=> Add failing test case for #3981

rules/php70/src/Rector/StaticCall/StaticCallOnNonStaticToInstanceCallRector.php
=> fix class call

packages/node-type-resolver/src/NodeTypeResolver.php, packages/phpstan-static-type-mapper/src/TypeMapper/ArrayTypeMapper.php, rules/coding-style/tests/Rector/ClassConst/VarConstantCommentRector/Fixture/explicit_key_array.php.inc, rules/type-declaration/src/TypeInferer/ReturnTypeInferer.php, rules/type-declaration/tests/Rector/ClassMethod/AddArrayReturnDocTypeRector/Fixture/return_uuid.php.inc
@TomasVotruba, as agreed, creating pull-request with the smallest possible fixture being fixed, to let you take a look :)
=> [Type Declaration] The smallest possible fixture fixed ReturnUuid

src/Testing/PHPUnit/AbstractRectorTestCase.php
=> Fix typo in method name that breaks all tests

src/Testing/Finder/RectorsFinder.php
=> Fix dump rectors

packages/better-php-doc-parser/src/PhpDocManipulator/PhpDocTypeChanger.php
- Closes #4002 
- Closes #3995
=> report doc changes

packages/better-php-doc-parser/src/AnnotationReader/NodeAnnotationReader.php, packages/better-php-doc-parser/src/Printer/PhpDocInfoPrinter.php, packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureBasic/double_route.txt, rules/sensio/tests/Rector/ClassMethod/TemplateAnnotationToThisRenderRector/Fixture/double_route.php.inc
=> Add multiple annotation support on class

rules/type-declaration/src/TypeInferer/ReturnTypeInferer/YieldNodesReturnTypeInferer.php, rules/type-declaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/skip_explicit_generator_from.php.inc
=> Fix return infer type for "yield from"

rules/type-declaration/src/TypeInferer/ReturnTypeInferer/ReturnedNodesReturnTypeInferer.php, rules/type-declaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/double_return.php.inc, rules/type-declaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/skip_return_void.php.inc
=> [TypeDeclaration] Skip return void on non-root return

rules/coding-style/src/Rector/Use_/RemoveUnusedAliasRector.php, rules/coding-style/tests/Rector/Use_/RemoveUnusedAliasRector/Fixture/handle_static_cal.php.inc, rules/coding-style/tests/Rector/Use_/RemoveUnusedAliasRector/Source/AliasedStaticCall.php
=> Fix static class call

rules/coding-style/tests/Rector/ClassConst/VarConstantCommentRector/Fixture/override_non_array_mixed.php.inc
Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>
=> Typo fix: NESTED_STIRNGS to NESTED_STRINGS

README.md
Following comment: https://github.com/rectorphp/rector/pull/4099#issuecomment-684941304
=> Added "Rector Configuration" section

docs/rector_rules_overview.md, packages/documentation-generator/src/OutputFormatter/RectorPrinter.php
Fixes #3448
Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>
=> Fixes #3448 : Fixes relative path link on dump-rectors generate class link documentation

config/set/downgrade.php, rules/downgrade/src/Rector/Coalesce/DowngradeNullCoalescingOperatorRector.php, rules/downgrade/src/Rector/FunctionLike/AbstractDowngradeParamTypeDeclarationRector.php, rules/downgrade/src/Rector/FunctionLike/AbstractDowngradeReturnTypeDeclarationRector.php, rules/downgrade/src/Rector/Property/DowngradeTypedPropertyRector.php, rules/downgrade/tests/Rector/Coalesce/DowngradeNullCoalescingOperatorRector/DowngradeNullCoalescingOperatorRectorTest.php, rules/downgrade/tests/Rector/Coalesce/DowngradeNullCoalescingOperatorRector/Fixture/fixture.php.inc, src/ValueObject/PhpVersionFeature.php
=> Downgrade null coalescing operator

packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Property_/JoinTableTagValueNode.php, packages/node-collector/src/NodeAnalyzer/ArrayCallableMethodReferenceAnalyzer.php, packages/node-collector/src/NodeCollector/ParsedFunctionLikeNodeCollector.php, packages/node-type-resolver/src/NodeTypeCorrector/ParentClassLikeTypeCorrector.php, packages/node-type-resolver/src/NodeTypeResolver.php, phpstan.neon, rules/autodiscovery/tests/Rector/FileSystem/MoveInterfacesToContractNamespaceDirectoryRector/MoveInterfacesToContractNamespaceDirectoryRectorTest.php, rules/autodiscovery/tests/Rector/FileSystem/MoveInterfacesToContractNamespaceDirectoryRector/ValueObject/InputFilePathWithExpectedFile.php, rules/autodiscovery/tests/Rector/FileSystem/MoveServicesBySuffixToDirectoryRector/MutualRenameTest.php, rules/code-quality/src/Rector/Array_/ArrayThisCallToThisMethodCallRector.php, rules/nette-kdyby/src/DataProvider/EventAndListenerTreeProvider.php, rules/nette-kdyby/src/ValueObject/EventAndListenerTree.php, rules/nette-to-symfony/src/Collector/OnFormVariableMethodCallsCollector.php, rules/nette-to-symfony/src/Rector/ClassMethod/RouterListToControllerAnnotationsRector.php, rules/nette-to-symfony/src/Rector/Class_/FormControlToControllerAndFormTypeRector.php, rules/nette-to-symfony/src/Routing/ExplicitRouteAnnotationDecorator.php, rules/order/src/Rector/Class_/OrderPrivateMethodsByUseRector.php, rules/phpunit/src/Rector/MethodCall/AssertComparisonToSpecificMethodRector.php, rules/phpunit/src/ValueObject/BinaryOpWithAssertMethod.php, src/DependencyInjection/Collector/ConfigureCallValuesCollector.php, src/DependencyInjection/CompilerPass/MergeImportedRectorConfigureCallValuesCompilerPass.php, src/DependencyInjection/Loader/ConfigurableCallValuesCollectingPhpFileLoader.php, src/HttpKernel/RectorKernel.php, src/Testing/PHPUnit/AbstractFileSystemRectorTestCase.php, src/Util/StaticRectorStrings.php
Static fixes after big Symplify PHPStan ruleset update,
See https://github.com/symplify/symplify/compare/8.2.21...8.2.22
=> static fixes

src/FileSystem/FilesFinder.php
fixes https://github.com/rectorphp/rector/issues/4127
=> make EXCLUDE_PATHS work across different OSes

config/set/downgrade.php
I had forgotten to add the 3 new rules to the `downgrade` set in PR #4162
=> Added downgrade rules

config/set/downgrade-php72.php, config/set/downgrade-php74.php, config/set/downgrade-php80.php, packages/set/src/ValueObject/SetList.php
As requested in https://github.com/rectorphp/rector/pull/4172#discussion_r485041789
=> Split downgrade sets

rules/coding-style/src/Node/UseManipulator.php, rules/coding-style/src/Rector/Use_/RemoveUnusedAliasRector.php, rules/coding-style/src/ValueObject/NameAndParent.php, rules/naming/src/NamespaceMatcher.php, rules/phpunit/src/Rector/Class_/ArrayArgumentInTestToDataProviderRector.php, rules/phpunit/src/ValueObject/ParamAndArg.php, rules/renaming/src/Rector/Namespace_/RenameNamespaceRector.php, rules/type-declaration/src/TypeNormalizer.php, rules/type-declaration/src/ValueObject/NestedArrayType.php, src/Application/FileSystem/RemovedAndAddedFilesCollector.php, src/Application/FileSystem/RemovedAndAddedFilesProcessor.php, src/ValueObject/MovedClass.php, src/ValueObject/RenamedNamespace.php, utils/phpstan-extensions/config/phpstan-extensions.neon, utils/phpstan-extensions/src/Rule/ValueObjectHasNoValueObjectSuffixRule.php, utils/phpstan-extensions/tests/Rule/ValueObjectHasNoValueObjectSuffixRule/Fixture/SkipNoValueObjectInNamespace.php, utils/phpstan-extensions/tests/Rule/ValueObjectHasNoValueObjectSuffixRule/Fixture/ValueObject/MoneyValueObject.php, utils/phpstan-extensions/tests/Rule/ValueObjectHasNoValueObjectSuffixRule/Fixture/ValueObject/SkipValueObjectWithoutValueObjectSuffix.php, utils/phpstan-extensions/tests/Rule/ValueObjectHasNoValueObjectSuffixRule/ValueObjectHasNoValueObjectSuffixRuleTest.php
=> [DX] PHPStan rule to check, that value objects do not have value object suffix

utils/phpstan-extensions/config/phpstan-extensions.neon, utils/phpstan-extensions/src/Rule/CheckGetNodeTypesReturnPhpParserNodeRule.php, utils/phpstan-extensions/tests/Rule/CheckGetNodeTypesReturnPhpParserNodeRule/CheckGetNodeTypesReturnPhpParserNodeRuleTest.php, utils/phpstan-extensions/tests/Rule/CheckGetNodeTypesReturnPhpParserNodeRule/Fixture/IncorrectReturnRector.php, utils/phpstan-extensions/tests/Rule/CheckGetNodeTypesReturnPhpParserNodeRule/Fixture/SkipInterface.php, utils/phpstan-extensions/tests/Rule/CheckGetNodeTypesReturnPhpParserNodeRule/Fixture/SkipNoGetNodeTypes.php, utils/phpstan-extensions/tests/Rule/CheckGetNodeTypesReturnPhpParserNodeRule/Fixture/SomeRector.php, utils/phpstan-extensions/tests/Rule/CheckGetNodeTypesReturnPhpParserNodeRule/Source/ClassNotOfPhpParserNode.php
=> [DX] PHPStan rule to check getNodeTypes() return classes of `PhpParser\Node`

src/Bootstrap/RectorConfigsResolver.php
=> load rector-recipe.php only in case of GenerateCommand

docs/rector_rules_overview.md, packages/rector-generator/src/TemplateVariablesFactory.php, rector-recipe.php.dist, rules/downgrade-php71/tests/Rector/FunctionLike/DowngradeNullableTypeReturnDeclarationRector/Fixture/fixture.php.inc, rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeUnionTypeReturnDeclarationRector/Fixture/fixture.php.inc, rules/removing-static/src/NodeAnalyzer/StaticCallPresenceAnalyzer.php, rules/removing-static/src/Rector/Class_/SingleStaticServiceToDynamicRector.php, rules/removing-static/tests/Rector/Class_/SingleStaticServiceToDynamicRector/Fixture/another_class.php.inc, rules/removing-static/tests/Rector/Class_/SingleStaticServiceToDynamicRector/Fixture/another_class_static_properties.php.inc, rules/removing-static/tests/Rector/Class_/SingleStaticServiceToDynamicRector/Fixture/fixture.php.inc, rules/removing-static/tests/Rector/Class_/SingleStaticServiceToDynamicRector/Fixture/static_properties.php.inc, rules/removing-static/tests/Rector/Class_/SingleStaticServiceToDynamicRector/SingleStaticServiceToDynamicRectorTest.php, rules/removing-static/tests/Rector/Class_/SingleStaticServiceToDynamicRector/Source/ClassWithStaticProperties.php, rules/removing-static/tests/Rector/Class_/SingleStaticServiceToDynamicRector/Source/FirstStaticClass.php, src/PhpParser/Node/Manipulator/ClassInsertManipulator.php
=> [RemovingStatic] Add SingleStaticServiceToDynamicRector

rules/symfony-php-config/functions/functions.php
=> fix Symfony inline_function fallback

rules/magic-disclosure/src/NodeAnalyzer/ExprStringTypeResolver.php, rules/magic-disclosure/src/Rector/MethodCall/AbstractFluentChainMethodCallRector.php, rules/magic-disclosure/src/Rector/MethodCall/InArgFluentChainMethodCallToStandaloneMethodCallRector.php, rules/magic-disclosure/tests/Rector/MethodCall/InArgChainFluentMethodCallToStandaloneMethodCallRectorTest/Fixture/self_self.php.inc, rules/magic-disclosure/tests/Rector/MethodCall/InArgChainFluentMethodCallToStandaloneMethodCallRectorTest/Source/SetGetDateTime.php
=> [MagicDisclosure] Fix alised date time

rules/magic-disclosure/src/Rector/MethodCall/AbstractFluentChainMethodCallRector.php, rules/magic-disclosure/src/Rector/MethodCall/FluentChainMethodCallToNormalMethodCallRector.php, rules/magic-disclosure/tests/Rector/MethodCall/FluentChainMethodCallToNormalMethodCallRector/Fixture/skip_getter_response_header.php.inc, rules/magic-disclosure/tests/Rector/MethodCall/FluentChainMethodCallToNormalMethodCallRector/Source/SomeResponse.php, src/Rector/AbstractRector.php
=> [MagicDisclosure] Fix FluentChainMethodCallToNormalMethodCallRector fix

packages/node-name-resolver/src/NodeNameResolver.php, rules/php70/tests/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector/Fixture/keep_curly_braces.php.inc
=> node name resolver skip on identifier

rules/coding-style/tests/Rector/Encapsed/WrapEncapsedVariableInCurlyBracesRector/Fixture/some_variables_with_braces.php.inc, src/PhpParser/Node/BetterNodeFinder.php, utils/node-documentation-generator/src/Command/DumpNodesCommand.php, utils/node-documentation-generator/src/OutputFormatter/MarkdownDumpNodesOutputFormatter.php, utils/node-documentation-generator/src/RobotLoader/NodeClassProvider.php, utils/node-documentation-generator/src/ValueObject/NodeInfo.php, utils/node-documentation-generator/tests/RobotLoader/NodeClassProviderTest.php
Follow up to https://github.com/rectorphp/rector/pull/4241
=> [Docs] Fixup

rules/phpunit/src/TestClassResolver/TestClassResolver.php
Fixes docs generating in random order.
=> fix rector docs generator sorting issue

docs/nodes_overview.md, utils/node-documentation-generator/snippet/array_dim_fetch.php.inc, utils/node-documentation-generator/snippet/array_item.php.inc, utils/node-documentation-generator/snippet/assign.php.inc, utils/node-documentation-generator/snippet/assign_ref.php.inc, utils/node-documentation-generator/snippet/bitwise_not.php.inc, utils/node-documentation-generator/snippet/boolean_not.php.inc, utils/node-documentation-generator/snippet/clone.php.inc, utils/node-documentation-generator/snippet/empty.php.inc, utils/node-documentation-generator/snippet/error_suppress.php.inc, utils/node-documentation-generator/snippet/include.php.inc, utils/node-documentation-generator/snippet/instance_of.php.inc, utils/node-documentation-generator/snippet/isset.php.inc, utils/node-documentation-generator/snippet/list.php.inc, utils/node-documentation-generator/snippet/match.php.inc, utils/node-documentation-generator/snippet/method_call.php.inc, utils/node-documentation-generator/snippet/new.php.inc, utils/node-documentation-generator/snippet/new2.php.inc, utils/node-documentation-generator/snippet/null_safe_method_call.php.inc, utils/node-documentation-generator/snippet/null_safe_property_fetch.php.inc, utils/node-documentation-generator/snippet/value.php.inc, utils/node-documentation-generator/src/Command/DumpNodesCommand.php
=> [Docs] Update node docs with examples how to create them - part 2

rules/coding-style/tests/Rector/Variable/UnderscoreToCamelCaseVariableNameRector/Fixture/skip_underscored_reserved_names.php.inc, src/Php/ReservedKeywordAnalyzer.php
Re-create PR #4263 to this repo.
=> [CodingStyle]  Bug fix: ReservedKeywordAnalyzer should add _SESSION to NATIVE_VARIABLE_NAMES

composer.json
Update composer.json to pin to latest version of php-parser
=> Support latest php-parser

rules/php80/src/Rector/Class_/AnnotationToAttributeRector.php
from the `<<>>` interim style.
=> Update example to new-style php80 Attributes Fixes #4306

packages/better-php-doc-parser/src/PhpDocManipulator/PropertyDocBlockManipulator.php, rules/naming/src/ExpectedNameResolver/AbstractExpectedNameResolver.php, rules/naming/src/ExpectedNameResolver/BoolPropertyExpectedNameResolver.php, rules/naming/src/ExpectedNameResolver/ExpectedNameResolverInterface.php, rules/naming/src/ExpectedNameResolver/MatchParamTypeExpectedNameResolver.php, rules/naming/src/ExpectedNameResolver/MatchPropertyTypeExpectedNameResolver.php, rules/naming/src/ExpectedNameResolver/UnderscoreCamelCaseExpectedNameResolver.php, rules/naming/src/Guard/DateTimeAtNamingConventionGuard.php, rules/naming/src/Guard/NotPrivatePropertyGuard.php, rules/naming/src/Guard/PropertyConflictingNameGuard/AbstractPropertyConflictingNameGuard.php, rules/naming/src/Guard/RamseyUuidInterfaceGuard.php, rules/naming/src/ParamRenamer/AbstractParamRenamer.php, rules/naming/src/ParamRenamer/MatchTypeParamRenamer.php, rules/naming/src/ParamRenamer/UnderscoreCamelCaseParamRenamer.php, rules/naming/src/PropertyRenamer/AbstractPropertyRenamer.php, rules/naming/src/Rector/ClassMethod/RenameParamToMatchTypeRector.php, rules/naming/src/Rector/Variable/UnderscoreToCamelCaseVariableNameRector.php, rules/naming/src/RenamerInterface.php, rules/naming/src/ValueObject/ParamRename.php, rules/naming/src/ValueObject/PropertyRename.php, rules/naming/src/ValueObject/RenameParamValueObjectInterface.php, rules/naming/src/ValueObject/RenamePropertyValueObjectInterface.php, rules/naming/src/ValueObject/RenameValueObjectInterface.php, rules/naming/src/ValueObjectFactory/ParamRenameFactory.php, rules/naming/tests/ValueObjectFactory/PropertyRenameFactory/PropertyRenameFactoryTest.php
=> [Naming] Apply ParamRenamer without conflict resolution for Naming set

config/set/downgrade-php74.php, rules/downgrade-php74/src/Rector/LNumber/DowngradeNumericLiteralSeparatorRector.php, rules/downgrade-php74/tests/Rector/LNumber/DowngradeNumericLiteralSeparatorRector/DowngradeNumericLiteralSeparatorRectorTest.php, rules/downgrade-php74/tests/Rector/LNumber/DowngradeNumericLiteralSeparatorRector/Fixture/fixture.php.inc, rules/downgrade-php74/tests/Rector/LNumber/DowngradeNumericLiteralSeparatorRector/Fixture/no_change.php.inc, src/ValueObject/PhpVersionFeature.php
=> [Downgrade PHP 7.4] Numeric Literal Separator Rector

Dockerfile, README.md, rules/symfony/src/Rector/MethodCall/StringFormTypeToClassRector.php
=> Improved rector in docker autoloading

rules/generic/src/Rector/ClassMethod/ArgumentAdderRector.php, rules/generic/tests/Rector/ClassMethod/ArgumentAdderRector/ArgumentAdderRectorTest.php, rules/generic/tests/Rector/ClassMethod/ArgumentAdderRector/Fixture/skip_add_with_default_null.php.inc
Closes https://github.com/rectorphp/rector/issues/4267
=> [Generic] Add skip for ArgumentAdderRector

src/Error/ExceptionCorrector.php
...for the clueless copy-pasters...
=> Fix syntax error in ExceptionCorrector message

README.md
see https://github.com/rectorphp/rector/issues/2733 https://github.com/rectorphp/rector/pull/2735
=> README: mention the `rd` debugging helper function

UPGRADE_09.md
Ref https://github.com/rectorphp/rector/issues/4905#issuecomment-746399661
=> [UPGRADE] Add Rector 0.9 upgrade docs

src/PhpParser/Printer/BetterStandardPrinter.php, src/PhpParser/Printer/ContentPatcher.php, tests/Issues/Issue4191/DoNotDuplicateComment/DoNotDuplicateCommentTest.php, tests/Issues/Issue4191/DoNotDuplicateComment/Fixture/skip_duplicate_comment.php.inc, tests/Issues/Issue4191/DoNotDuplicateComment/config/some_config.php
=> [BetterStandardPrinter] Failing fixture to not duplicate comment

config/set/downgrade-php74.php, packages/static-type-mapper/src/PhpParser/NameNodeMapper.php, rules/downgrade-php74/src/Rector/ClassMethod/DowngradeReturnSelfTypeDeclarationRector.php, rules/downgrade-php74/tests/Rector/ClassMethod/DowngradeReturnSelfTypeDeclarationRector/DowngradeReturnSelfTypeDeclarationRectorTest.php, rules/downgrade-php74/tests/Rector/ClassMethod/DowngradeReturnSelfTypeDeclarationRector/Fixture/docblock_exists.php.inc, rules/downgrade-php74/tests/Rector/ClassMethod/DowngradeReturnSelfTypeDeclarationRector/Fixture/fixture.php.inc, rules/downgrade-php74/tests/Rector/ClassMethod/DowngradeReturnSelfTypeDeclarationRector/Fixture/interface.php.inc, rules/downgrade-php74/tests/Rector/ClassMethod/DowngradeReturnSelfTypeDeclarationRector/Fixture/nullable_type.php.inc, rules/downgrade-php74/tests/Rector/ClassMethod/DowngradeReturnSelfTypeDeclarationRector/Fixture/trait.php.inc
=> [Downgrade PHP 7.4] Remove self return type

rules/dead-code/src/Rector/ClassMethod/RemoveUnusedPublicMethodRector.php, rules/dead-code/tests/Rector/ClassMethod/RemoveUnusedPublicMethodRector/Fixture/dependency_injection.php.inc, rules/dead-code/tests/Rector/ClassMethod/RemoveUnusedPublicMethodRector/Fixture/fixture.php.inc, rules/dead-code/tests/Rector/ClassMethod/RemoveUnusedPublicMethodRector/Fixture/used_outside_class.php.inc, rules/dead-code/tests/Rector/ClassMethod/RemoveUnusedPublicMethodRector/RemoveUnusedPublicMethodRectorTest.php
=> [DeadCode] Add RemoveUnusedPublicMethodRector

rules/composer/src/Processor/ComposerProcessor.php
Closes https://github.com/rectorphp/rector/issues/4173
=> [Composer] Add check for existing compsore.json

composer.json, phpstan.neon
Ref https://github.com/rectorphp/rector/issues/5180#issuecomment-760009133
=> add missing astral package

Dockerfile
https://github.com/rectorphp/rector/issues/5180#issuecomment-760100459
=> Issue #5180 - add intl extension

README.md
=> [Typo] Fixed a typo in the README.md file

config/set/dead-code.php, src/Rector/AbstractRector/NodeTypeResolverTrait.php
=> [DeadCode] Register RemoveDeadConditionAboveReturnRector to dead-code config set

packages/phpstan-static-type-mapper/src/TypeAnalyzer/BoolUnionTypeAnalyzer.php, packages/phpstan-static-type-mapper/src/TypeAnalyzer/UnionTypeAnalyzer.php, packages/phpstan-static-type-mapper/src/TypeMapper/BooleanTypeMapper.php, packages/phpstan-static-type-mapper/src/TypeMapper/UnionTypeMapper.php, packages/static-type-mapper/src/Mapper/ScalarStringToTypeMapper.php, packages/static-type-mapper/src/PhpParser/NameNodeMapper.php, packages/static-type-mapper/src/ValueObject/Type/FalseBooleanType.php, rules/php80/tests/Rector/FunctionLike/UnionTypesRector/Fixture/false_pseudo_type.php.inc, rules/type-declaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/Fixture/bool_class.php.inc, rules/type-declaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/Fixture/nullable_false.php.inc, rules/type-declaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/false_true_union_type.php.inc, rules/type-declaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/known_false.php.inc
Closes https://github.com/rectorphp/rector/issues/5227
=> add FalseBooleanType and UnionType false support

packages/better-php-doc-parser/src/ValueObject/PhpDocNode/Doctrine/Property_/JoinTableTagValueNode.php
See https://github.com/rectorphp/rector-prefixed/pull/12
=> Fix parsing JoinTable without table name explicitly set

config/set/doctrine-code-quality.php
As discussed here https://github.com/rectorphp/rector/issues/5183#issuecomment-760530050
=> [DoctrineCodeQuality] replace `ASC`|`DESC` strings with constants

config/set/nette-31.php
- nette/forms 3.1 is out
- Small typo
=> ConfigSet: Update nette-31

.github/workflows/weekly_code_coverage.yaml
Fixes #5297 with change `${{ secrets.ACCESS_TOKEN }}` to `${{ secrets.GITHUB_TOKEN }}` like in other workflow.
=> [Code Coverage] Fixes weekly code coverage generation

config/set/symfony52.php, rules/symfony5/src/Rector/MethodCall/DefinitionAliasSetPrivateToSetPublicRector.php, rules/symfony5/src/Rector/MethodCall/DefinitionSetPrivateToSetPublicRector.php, rules/symfony5/tests/Rector/MethodCall/DefinitionAliasSetPrivateToSetPublicRector/DefinitionAliasSetPrivateToSetPublicRectorTest.php, rules/symfony5/tests/Rector/MethodCall/DefinitionAliasSetPrivateToSetPublicRector/Fixture/fixture.php.inc, rules/symfony5/tests/Rector/MethodCall/DefinitionAliasSetPrivateToSetPublicRector/Fixture/pass_variable.php.inc, rules/symfony5/tests/Rector/MethodCall/DefinitionAliasSetPrivateToSetPublicRector/Fixture/skip_not_definition_alias.php.inc, rules/symfony5/tests/Rector/MethodCall/DefinitionAliasSetPrivateToSetPublicRector/Fixture/skip_not_private_call.php.inc
=> [Symfony 5.2] Upgrade Definition/Alias::setPrivate to setPublic

config/set/symfony51.php, packages/rector-generator/src/NodeFactory/ConfigurationNodeFactory.php, rules/renaming/src/Rector/String_/RenameStringRector.php, rules/renaming/tests/Rector/String_/RenameStringRector/Fixture/some_class.php.inc, rules/renaming/tests/Rector/String_/RenameStringRector/RenameStringRectorTest.php
Ref https://github.com/rectorphp/rector/issues/4831
Covers cases like https://github.com/symfony/symfony/pull/35858
=> [Renaming] Add RenameStringRector

phpstan.neon
New symplify release 9.0.46 with this update message https://github.com/symplify/symplify/commit/0fd31c08d3a77abf78c69169463c80202f5d503b
=> [PHPStan] Typo fix: Refator -> Refactor

rules/php74/tests/Rector/Property/TypedPropertyFromStrictConstructorRector/Fixture/demo_file.php.inc, rules/php74/tests/Rector/Property/TypedPropertyFromStrictConstructorRector/Fixture/variadic_constructor_param.php.inc, rules/type-declaration/src/TypeInferer/PropertyTypeInferer/ConstructorPropertyTypeInferer.php
Based on https://getrector.org/demo/331db50e-de84-4ffc-99cb-ae299c427411
=> Support variadic constructor params in TypedPropertyFromStrictConstructorRector

packages/static-type-mapper/src/StaticTypeMapper.php, rules/generics/config/config.php, rules/generics/src/NodeType/ExtendsTemplateTypeMapFallbackFactory.php, rules/generics/src/NodeType/GenericTypeSpecifier.php, rules/generics/src/Rector/Class_/GenericsPHPStormMethodAnnotationRector.php, rules/generics/src/Reflection/GenericClassReflectionAnalyzer.php, rules/generics/src/ValueObject/GenericChildParentClassReflections.php, rules/generics/tests/Rector/Class_/GenericsPHPStormMethodAnnotationRector/Fixture/child_repository.php.inc, rules/generics/tests/Rector/Class_/GenericsPHPStormMethodAnnotationRector/Fixture/direct_pass_repository.php.inc, rules/generics/tests/Rector/Class_/GenericsPHPStormMethodAnnotationRector/Fixture/some_class.php.inc, rules/generics/tests/Rector/Class_/GenericsPHPStormMethodAnnotationRector/Source/AbstractGenericRepository.php
Follow up to https://github.com/rectorphp/rector/pull/5365
=> [Generics] Add GenericsPHPStormMethodAnnotationRector #2

rules/type-declaration/src/PHPStan/Type/ObjectTypeSpecifier.php, rules/type-declaration/tests/Rector/MethodCall/FormerNullableArgumentToScalarTypedRector/Fixture/aliased_class.php.inc
=> [TypeDeclaration] Handle alias usage on FormerNullableArgumentToScalarTypedRector

rules/renaming/src/NodeManipulator/ClassRenamer.php, rules/renaming/tests/Rector/Name/RenameClassRector/Fixture/do_not_implement_twice.php.inc, rules/renaming/tests/Rector/Name/RenameClassRector/RenameClassRectorTest.php, src/PhpParser/Printer/BetterStandardPrinter.php
=> [Renaming] Handle RenameClassRector to avoid duplicate interface definition

config/set/symfony52.php
part of https://github.com/rectorphp/rector/issues/4824
=> [Symfony 5.2] Change Param type declaration for Notifier and Channel

rules/early-return/src/Rector/If_/ChangeAndIfToEarlyReturnRector.php, rules/early-return/tests/Rector/If_/ChangeAndIfToEarlyReturnRector/Fixture/skip_has_next_stmt_after_if.php.inc
=> [EarlyReturn] Skip ChangeAndIfToEarlyReturnRector when parent if has next statement

phpstan.neon, rules/renaming/src/NodeManipulator/ClassRenamer.php, rules/renaming/tests/Rector/Name/RenameClassRector/Fixture/do_not_remove_existing_target_namespace.php.inc, rules/renaming/tests/Rector/Name/RenameClassRector/RenameClassRectorTest.php
=> [Renaming] Do not update target new namespace exists on RenameClassRector

rules/code-quality/src/Rector/For_/ForToForeachRector.php, rules/code-quality/tests/Rector/For_/ForToForeachRector/Fixture/add_single_prefix_singular.php.inc, rules/code-quality/tests/Rector/For_/ForToForeachRector/Fixture/not_add_single_prefix_singular_if_used_next.php.inc, rules/code-quality/tests/Rector/For_/ForToForeachRector/Fixture/skip_value_var_used.php.inc
=> [CodeQuality] Add "single" prefix for value var of Foreach on ForToForeachRector when singularize() got same name

config/set/symfony52.php
=> [Symfony 5.2] Change Param type declaration for Chat/Email/Sms NotificationInterface

.docker/php-blackfire/Dockerfile, .docker/php-blackfire/readme.md
Hi, im playing with profiling and trying to optimize performance for online demo. I use blackfire and run it in docker, i think it is worth publishing it directly in the repo - either it might serve someone for inspiration and either it might be useful if anyone wants to start profiling as well + i do not have to save it in separe repository 😄
=> Added Docker image for blackfire profiling

packages/vendor-locker/src/NodeVendorLocker/ClassMethodVisibilityVendorLockResolver.php, rules/privatization/src/NodeAnalyzer/ClassMethodExternalCallNodeAnalyzer.php, rules/privatization/src/Rector/ClassMethod/MakeOnlyUsedByChildrenProtectedRector.php, rules/privatization/tests/Rector/ClassMethod/MakeOnlyUsedByChildrenProtectedRector/Fixture/deep_child.php.inc, rules/privatization/tests/Rector/ClassMethod/MakeOnlyUsedByChildrenProtectedRector/Fixture/fixture.php.inc, rules/privatization/tests/Rector/ClassMethod/MakeOnlyUsedByChildrenProtectedRector/Fixture/skip_extended.php.inc, rules/privatization/tests/Rector/ClassMethod/MakeOnlyUsedByChildrenProtectedRector/Fixture/skip_not_has_children.php.inc, rules/privatization/tests/Rector/ClassMethod/MakeOnlyUsedByChildrenProtectedRector/Fixture/skip_not_public.php.inc, rules/privatization/tests/Rector/ClassMethod/MakeOnlyUsedByChildrenProtectedRector/Fixture/skip_trait.php.inc, rules/privatization/tests/Rector/ClassMethod/MakeOnlyUsedByChildrenProtectedRector/Fixture/skip_used_by_child_instance.php.inc, rules/privatization/tests/Rector/ClassMethod/MakeOnlyUsedByChildrenProtectedRector/Fixture/skip_used_by_external.php.inc, rules/privatization/tests/Rector/ClassMethod/MakeOnlyUsedByChildrenProtectedRector/Fixture/skip_used_by_external_in_closure.php.inc, rules/privatization/tests/Rector/ClassMethod/MakeOnlyUsedByChildrenProtectedRector/MakeOnlyUsedByChildrenProtectedRectorTest.php
=> [Privatization] Add MakeOnlyUsedByChildrenProtectedRector

docs/rector_rules_overview.md, packages/node-collector/src/NodeCollector/NodeRepository.php, packages/node-collector/src/NodeCollector/ParsedNodeCollector.php, rules/doctrine-code-quality/src/NodeAnalyzer/SetterClassMethodAnalyzer.php, rules/type-declaration/src/Rector/ClassMethod/ReturnTypeFromStrictTypedPropertyRector.php, rules/type-declaration/src/Rector/Property/TypedPropertyFromStrictConstructorRector.php, rules/type-declaration/tests/Rector/ClassMethod/ReturnTypeFromStrictTypedPropertyRector/Fixture/skip_doc_type.php.inc, rules/type-declaration/tests/Rector/ClassMethod/ReturnTypeFromStrictTypedPropertyRector/Fixture/skip_one_missing_type.php.inc, rules/type-declaration/tests/Rector/ClassMethod/ReturnTypeFromStrictTypedPropertyRector/Fixture/skip_single_void.php.inc, rules/type-declaration/tests/Rector/ClassMethod/ReturnTypeFromStrictTypedPropertyRector/Fixture/some_class.php.inc, rules/type-declaration/tests/Rector/ClassMethod/ReturnTypeFromStrictTypedPropertyRector/Fixture/two_returns_union_type.php.inc, rules/type-declaration/tests/Rector/ClassMethod/ReturnTypeFromStrictTypedPropertyRector/Fixture/union_type.php.inc, rules/type-declaration/tests/Rector/ClassMethod/ReturnTypeFromStrictTypedPropertyRector/ReturnTypeFromStrictTypedPropertyRectorTest.php, rules/type-declaration/tests/Rector/Property/TypedPropertyFromStrictConstructorRector/Fixture/iterable_interface_var_tag.php.inc, rules/type-declaration/tests/Rector/Property/TypedPropertyFromStrictConstructorRector/Fixture/skip_already_type.php.inc, rules/type-declaration/tests/Rector/Property/TypedPropertyFromStrictConstructorRector/Fixture/skip_doc.php.inc, rules/type-declaration/tests/Rector/Property/TypedPropertyFromStrictConstructorRector/Fixture/some_class.php.inc, rules/type-declaration/tests/Rector/Property/TypedPropertyFromStrictConstructorRector/Fixture/variadic_constructor_param.php.inc, rules/type-declaration/tests/Rector/Property/TypedPropertyFromStrictConstructorRector/TypedPropertyFromStrictConstructorRectorTest.php
Closes https://github.com/rectorphp/rector/issues/5435
=> [TypeDeclaratoin] Add ReturnTypeFromStrictTypedPropertyRector

config/set/action-injection-to-constructor-injection.php, packages/set/src/ValueObject/SetList.php, rules/dependency-injection/src/Collector/VariablesToPropertyFetchCollection.php, rules/dependency-injection/src/Rector/Class_/ActionInjectionToConstructorInjectionRector.php, rules/dependency-injection/src/Rector/Variable/ReplaceVariableByPropertyFetchRector.php, rules/dependency-injection/tests/Rector/Class_/ActionInjectionToConstructorInjectionRector/ActionInjectionToConstructorInjectionRectorTest.php, rules/dependency-injection/tests/Rector/Class_/ActionInjectionToConstructorInjectionRector/Fixture/fixture.php.inc, rules/dependency-injection/tests/Rector/Class_/ActionInjectionToConstructorInjectionRector/Fixture/fixture2.php.inc, rules/dependency-injection/tests/Rector/Class_/ActionInjectionToConstructorInjectionRector/Source/ProductRepository.php, rules/dependency-injection/tests/Rector/Class_/ActionInjectionToConstructorInjectionRector/Source/SomeProduct.php, rules/dependency-injection/tests/Rector/Class_/ActionInjectionToConstructorInjectionRector/Source/SomeRequest.php, rules/dependency-injection/tests/Rector/Class_/ActionInjectionToConstructorInjectionRector/config/configured_rule.php, rules/dependency-injection/tests/Rector/Class_/ActionInjectionToConstructorInjectionRector/xml/services.xml, rules/transform/tests/Rector/StaticCall/StaticCallToNewRector/config/configured_rule.php
Revert of https://github.com/rectorphp/rector/pull/5356
Needed for a post: https://getrector.org/blog/2021/02/01/how-to-instantly-refactor-symfony-action-injects-to-constructor-injection
=> [DependencyInjectoin] Add ActionInjectionToConstructorInjectionRector

.github/workflows/build_php71.yaml
refs https://github.com/rectorphp/rector-php71/pull/1#discussion_r573557883
=> [PHP 7.1 Scoped] remove `stubs` from excluded zip at build_php71.yaml

rules/renaming/src/Rector/MethodCall/RenameMethodRector.php, rules/renaming/tests/Rector/MethodCall/RenameMethodRector/Fixture/demo_file.php.inc, rules/renaming/tests/Rector/MethodCall/RenameMethodRector/config/configured_rule.php
=> [Renaming] Handle RenameMethodRector on new in caller class

rules/dead-code/src/Rector/Class_/RemoveUnusedClassesRector.php, rules/dead-code/tests/Rector/Class_/RemoveUnusedClassesRector/Fixture/skip_class_extend.php.inc
=> [DeadCode] Skip RemoveUnusedClassesRector on class has children

packages/post-rector/src/Application/PostFileProcessor.php
=> [PostRector] Allow skip parameters

rules/privatization/tests/Rector/Property/ChangeReadOnlyPropertyWithDefaultValueToConstantRector/Fixture/symfony_example.php.inc, src/NonPhpFile/NonPhpFileProcessor.php
Closes https://github.com/rectorphp/rector/issues/5342
=> [Privatization] Add test case to verify property privatization

packages/read-write/src/ReadNodeAnalyzer/AbstractReadNodeAnalyzer.php, rules/dead-code/tests/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/remove_magic_property.php.inc, src/NonPhpFile/NonPhpFileProcessor.php
Cherry picked - closes https://github.com/rectorphp/rector/pull/5505
Fixes https://github.com/rectorphp/rector/issues/5501
=> [DeadCode] Fix RemoveUnusedPrivatePropertyRector in foreach

rules/renaming/src/NodeManipulator/ClassRenamer.php, rules/renaming/tests/Rector/Name/RenameClassRector/Fixture/do_not_remove_existing_target_namespace.php.inc, rules/renaming/tests/Rector/Name/RenameClassRector/Fixture/name_insensitive.php.inc, rules/renaming/tests/Rector/Name/RenameClassRector/Fixture/rename_property_read.php.inc, rules/renaming/tests/Rector/Name/RenameClassRector/Fixture/skip_parent_class_if_final.php.inc, rules/renaming/tests/Rector/Name/RenameClassRector/FixtureAutoImportNames/class_to_new_with_post_import.php.inc, rules/renaming/tests/Rector/Name/RenameClassRector/FixtureDuplication/skip_duplicated_class.php.inc, rules/renaming/tests/Rector/Name/RenameClassRector/RenameClassRectorTest.php, rules/renaming/tests/Rector/Name/RenameClassRector/Source/SomeFinalClass.php, rules/renaming/tests/Rector/Name/RenameClassRector/Source/SomeNonFinalClass.php, rules/renaming/tests/Rector/Name/RenameClassRector/config/configured_rule.php
Closes https://github.com/rectorphp/rector/issues/5519
=> [Renaming] Skip parent class rename, if target class is final

.github/workflows/publish_docker_images.yaml
=> [CI][Docker] Push all Docker image tags at once

rules/dead-code/src/Rector/ClassMethod/RemoveUnusedConstructorParamRector.php, rules/dead-code/tests/Rector/ClassMethod/RemoveUnusedConstructorParamRector/FixturePhp80/skip_property_promotion.php.inc, rules/dead-code/tests/Rector/ClassMethod/RemoveUnusedConstructorParamRector/Php80Test.php, rules/nette-kdyby/src/NodeManipulator/ParamAnalyzer.php, rules/symfony/src/Rector/Class_/MakeCommandLazyRector.php
=> [DeadCode]  Skip RemoveUnusedConstructorParamRector on property promotion

Dockerfile
Closes https://github.com/rectorphp/getrector.org/issues/269
=> Raise php version in docker image to 8.0

packages/better-php-doc-parser/src/PhpDocParser/BetterPhpDocParser.php, packages/post-rector/src/Collector/NodesToAddCollector.php, rules/early-return/src/Rector/Foreach_/ReturnAfterToEarlyOnBreakRector.php, rules/early-return/tests/Rector/Foreach_/ReturnAfterToEarlyOnBreakRector/Fixture/fixture.php.inc, rules/early-return/tests/Rector/Foreach_/ReturnAfterToEarlyOnBreakRector/Fixture/skip_before_break_not_assign.php.inc, rules/early-return/tests/Rector/Foreach_/ReturnAfterToEarlyOnBreakRector/Fixture/skip_before_break_not_expression.php.inc, rules/early-return/tests/Rector/Foreach_/ReturnAfterToEarlyOnBreakRector/Fixture/skip_in_if.php.inc, rules/early-return/tests/Rector/Foreach_/ReturnAfterToEarlyOnBreakRector/Fixture/skip_multi_break.php.inc, rules/early-return/tests/Rector/Foreach_/ReturnAfterToEarlyOnBreakRector/Fixture/skip_no_break.php.inc, rules/early-return/tests/Rector/Foreach_/ReturnAfterToEarlyOnBreakRector/Fixture/skip_no_previous.php.inc, rules/early-return/tests/Rector/Foreach_/ReturnAfterToEarlyOnBreakRector/Fixture/skip_no_return_after_foreach.php.inc, rules/early-return/tests/Rector/Foreach_/ReturnAfterToEarlyOnBreakRector/Fixture/skip_var_used_multiple.php.inc, rules/early-return/tests/Rector/Foreach_/ReturnAfterToEarlyOnBreakRector/ReturnAfterToEarlyOnBreakRectorTest.php, src/Application/FileSystem/RemovedAndAddedFilesProcessor.php, src/NodeManipulator/ClassDependencyManipulator.php, src/PhpParser/Node/BetterNodeFinder.php
=> [EarlyReturn] Add ReturnAfterToEarlyBreakRector

rules/dead-code/tests/Rector/ClassMethod/RemoveUnusedConstructorParamRector/FixturePhp80/skip_property_promotion.php.inc, rules/php56/tests/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/FixturePhp74/arrow_function.php.inc, rules/symfony/tests/Rector/Class_/MakeCommandLazyRector/FixturePhp80/skip_property_promotion.php.inc, utils/project-validator/src/Finder/FixtureFinder.php
=> [FixtureFinder] Update FixtureFinder Regex to allow Fixture(Php\d+)? like FixturePhp80

src/NodeManipulator/ClassInsertManipulator.php
As https://github.com/nikic/PHP-Parser/pull/646 is tagged already.
=> Use `Class_::getProperty()`

.github/workflows/build_php71.yaml
=> Revert "[PHP 7.1 Scoped] Use PHP 7.1 for build php 7.1"

composer.json, rules/code-quality/tests/Rector/Class_/CompleteDynamicPropertiesRector/CompleteDynamicPropertiesRectorTest.php, rules/dead-code/tests/Rector/MethodCall/RemoveDefaultArgumentValueRector/RemoveDefaultArgumentValueRectorTest.php, rules/php56/tests/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/AddDefaultValueForUndefinedVariableRectorTest.php, tests/bootstrap.php
Closes https://github.com/phpstan/phpstan/issues/4541#issuecomment-779434916
=> include stubs in tests

.docker/php-xdebug/Dockerfile, .docker/php-xdebug/readme.md, .docker/php-xdebug/xdebug.ini, .docker/php/xdebug.ini
Similar as #5430 - prepared docker image for quickstart with debugging and guide how to.
=> Prepared xdebug Docker image with instructions

packages/node-collector/src/NodeCollector/NodeRepository.php, rules/dead-code/src/Rector/Class_/RemoveEmptyAbstractClassRector.php
ref https://github.com/rectorphp/rector/pull/5558#discussion_r577085820
=> [NodeCollector] Apply NodeRepository::collect() on Name node

Dockerfile
... to not rely on a possibly outdated local image.
=> Specify an explicit Composer version in the Dockerfile

rules/code-quality/src/Rector/ClassMethod/DateTimeToDateTimeInterfaceRector.php, rules/coding-style/src/Rector/ClassMethod/ReturnArrayClassMethodToYieldRector.php, rules/doctrine-code-quality/src/Rector/Class_/InitializeDefaultEntityCollectionRector.php, rules/doctrine/src/Rector/ClassMethod/ChangeGetIdTypeToUuidRector.php, rules/doctrine/src/Rector/ClassMethod/ChangeReturnTypeOfClassMethodWithGetIdRector.php, rules/doctrine/src/Rector/ClassMethod/ChangeSetIdTypeToUuidRector.php, rules/nette-to-symfony/src/NodeFactory/ActionWithFormProcessClassMethodFactory.php, rules/nette-to-symfony/src/Rector/Class_/NetteControlToSymfonyControllerRector.php, rules/phpunit/src/NodeFactory/DataProviderClassMethodFactory.php
=> Pass string to FullyQualified instead of ::class

rules/dead-code/src/Rector/For_/RemoveDeadLoopRector.php, rules/dead-code/tests/Rector/For_/RemoveDeadLoopRector/Fixture/do_.php.inc, rules/dead-code/tests/Rector/For_/RemoveDeadLoopRector/Fixture/fixture.php.inc, rules/dead-code/tests/Rector/For_/RemoveDeadLoopRector/Fixture/foreach_.php.inc, rules/dead-code/tests/Rector/For_/RemoveDeadLoopRector/Fixture/skip_has_stmt.php.inc, rules/dead-code/tests/Rector/For_/RemoveDeadLoopRector/Fixture/while_.php.inc, rules/dead-code/tests/Rector/For_/RemoveDeadLoopRector/RemoveDeadLoopRectorTest.php
=> [DeadCode] Add RemoveDeadLoopRector

rules/early-return/src/Rector/Return_/PreparedValueToEarlyReturnRector.php, rules/early-return/tests/Rector/Return_/PreparedValueToEarlyReturnRector/Fixture/fixture.php.inc, rules/early-return/tests/Rector/Return_/PreparedValueToEarlyReturnRector/Fixture/inside_if.php.inc, rules/early-return/tests/Rector/Return_/PreparedValueToEarlyReturnRector/Fixture/skip_no_if_before.php.inc, rules/early-return/tests/Rector/Return_/PreparedValueToEarlyReturnRector/Fixture/skip_previous_if_has_else.php.inc, rules/early-return/tests/Rector/Return_/PreparedValueToEarlyReturnRector/Fixture/skip_previous_if_has_else_if.php.inc, rules/early-return/tests/Rector/Return_/PreparedValueToEarlyReturnRector/Fixture/skip_previous_if_multi_stmt.php.inc, rules/early-return/tests/Rector/Return_/PreparedValueToEarlyReturnRector/Fixture/skip_previous_if_stmt_different_var.php.inc, rules/early-return/tests/Rector/Return_/PreparedValueToEarlyReturnRector/Fixture/skip_previous_if_stmt_not_assign.php.inc, rules/early-return/tests/Rector/Return_/PreparedValueToEarlyReturnRector/PreparedValueToEarlyReturnRectorTest.php
=> [EarlyReturn] Add PreparedValueToEarlyReturnRector

rules/code-quality/src/Rector/Catch_/ThrowWithPreviousExceptionRector.php, rules/code-quality/tests/Rector/Catch_/ThrowWithPreviousExceptionRector/Fixture/empty_brackets.php.inc, rules/dead-doc-block/src/TagRemover/VarTagRemover.php
- Closes https://github.com/rectorphp/rector/issues/5576
- Closes https://github.com/rectorphp/rector/pull/5578
=> [CodeQuality] Fix printing of fixed throws statement

packages/node-collector/src/NodeCollector/NodeRepository.php, rules/renaming/tests/Rector/MethodCall/RenameMethodRector/Fixture/skip_when_interface_and_wildcard.php.inc, rules/renaming/tests/Rector/MethodCall/RenameMethodRector/config/configured_rule.php, src/NodeManipulator/ClassManipulator.php
=> [Renaming] Skip RenameMethodRector on interface wildcard used

rules/php80/src/NodeAnalyzer/SwitchAnalyzer.php, rules/php80/tests/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/no_break_in_last.php.inc, rules/php80/tests/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_no_break_in_not_last_case.php.inc, rules/php80/tests/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_no_break_in_not_last_case_multiple.php.inc
=> [Php80] Skip ChangeSwitchToMatchRector on missed break

rules/php80/src/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector.php, rules/php80/tests/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector/Fixture/nullable_type.php.inc, rules/php80/tests/Rector/Class_/ClassPropertyAssignToConstructorPromotionRector/Fixture/nullable_type_2.php.inc
=> [Php80] Handle Nullable Type on ClassPropertyAssignToConstructorPromotionRector

rules/nette-to-symfony/src/NodeFactory/ActionWithFormProcessClassMethodFactory.php, rules/nette-to-symfony/src/Rector/Class_/NetteControlToSymfonyControllerRector.php, utils/doctrine-annotation-parser-syncer/src/Rector/Assign/AssignNewDocParserRector.php, utils/doctrine-annotation-parser-syncer/src/Rector/ClassMethod/ChangeOriginalTypeToCustomRector.php, utils/doctrine-annotation-parser-syncer/src/Rector/ClassMethod/LogIdentifierAndResolverValueInConstantClassMethodRector.php, utils/phpstan-extensions/config/rector-rules.neon
Closes https://github.com/rectorphp/rector/pull/5623
=> use RequireStringArgumentInConstructorRule

rules/privatization/src/Rector/ClassMethod/PrivatizeLocalOnlyMethodRector.php, rules/privatization/tests/Rector/ClassMethod/PrivatizeLocalOnlyMethodRector/Fixture/skip_symfony_route.php.inc, rules/type-declaration/src/TypeInferer/ParamTypeInferer/PHPUnitDataProviderParamTypeInferer.php
=> [Privatization] Skip PrivatizeLocalOnlyMethodRector on use of SymfonyRouteTagValueNode

rules/naming/src/Rector/Foreach_/RenameForeachValueVariableToMatchExprVariableRector.php, rules/naming/tests/Rector/Foreach_/RenameForeachValueVariableToMatchExprVariableRector/Fixture/fixture.php.inc, rules/naming/tests/Rector/Foreach_/RenameForeachValueVariableToMatchExprVariableRector/Fixture/not_variable_in_stmts.php.inc, rules/naming/tests/Rector/Foreach_/RenameForeachValueVariableToMatchExprVariableRector/Fixture/property_fetch.php.inc, rules/naming/tests/Rector/Foreach_/RenameForeachValueVariableToMatchExprVariableRector/Fixture/reference.php.inc, rules/naming/tests/Rector/Foreach_/RenameForeachValueVariableToMatchExprVariableRector/Fixture/single_prefix.php.inc, rules/naming/tests/Rector/Foreach_/RenameForeachValueVariableToMatchExprVariableRector/Fixture/skip_expr_call.php.inc, rules/naming/tests/Rector/Foreach_/RenameForeachValueVariableToMatchExprVariableRector/Fixture/skip_expr_not_variable.php.inc, rules/naming/tests/Rector/Foreach_/RenameForeachValueVariableToMatchExprVariableRector/Fixture/skip_used_in_key.php.inc, rules/naming/tests/Rector/Foreach_/RenameForeachValueVariableToMatchExprVariableRector/Fixture/skip_used_in_stmts.php.inc, rules/naming/tests/Rector/Foreach_/RenameForeachValueVariableToMatchExprVariableRector/Fixture/skip_used_next_foreach.php.inc, rules/naming/tests/Rector/Foreach_/RenameForeachValueVariableToMatchExprVariableRector/Fixture/skip_value_var_not_variable.php.inc, rules/naming/tests/Rector/Foreach_/RenameForeachValueVariableToMatchExprVariableRector/RenameForeachValueVariableToMatchExprVariableRectorTest.php
=> [Naming] Add RenameForeachValueVariableToMatchExprVariableRector

packages/node-type-resolver/src/NodeTypeResolver.php, rules/code-quality/tests/Rector/ClassMethod/DateTimeToDateTimeInterfaceRector/FixturePhp74/skip_arrow_function.php.inc, rules/code-quality/tests/Rector/ClassMethod/DateTimeToDateTimeInterfaceRector/FixturePhp74/skip_identifier_parameter.php.inc, rules/code-quality/tests/Rector/ClassMethod/DateTimeToDateTimeInterfaceRector/Php74Test.php
=> [NodeTypeResolver] Handle object type or nullable object type from Parameter as Identifier

rules/code-quality/src/Rector/Catch_/ThrowWithPreviousExceptionRector.php, rules/code-quality/tests/Rector/Catch_/ThrowWithPreviousExceptionRector/FixturePhp8/named_argument.php.inc, rules/code-quality/tests/Rector/Catch_/ThrowWithPreviousExceptionRector/Php8Test.php
=> [CodeQuality] Handle Named Argument in ThrowWithPreviousExceptionRector

rules/early-return/src/Rector/If_/ChangeAndIfToEarlyReturnRector.php, rules/early-return/tests/Rector/If_/ChangeAndIfToEarlyReturnRector/Fixture/always_return.php.inc
=> [EarlyReturn] Handle Always return on ChangeAndIfToEarlyReturnRector

rules/privatization/src/Rector/ClassMethod/PrivatizeLocalOnlyMethodRector.php, rules/privatization/tests/Rector/ClassMethod/PrivatizeLocalOnlyMethodRector/Fixture/skip_symfony_route_attribute.php.inc, rules/privatization/tests/Rector/ClassMethod/PrivatizeLocalOnlyMethodRector/FixturePhp8/skip_symfony_route_attribute.php.inc, rules/privatization/tests/Rector/ClassMethod/PrivatizeLocalOnlyMethodRector/Php8Test.php, rules/privatization/tests/Rector/ClassMethod/PrivatizeLocalOnlyMethodRector/config/configured_rule.php
=> [Privatization] Skip PrivatizeLocalOnlyMethodRector on use Symfony Route Attribute 

.github/workflows/publish_docker_images.yaml
=> [Docker] Support multiple CPU architectures - arm64 + amd64

.github/workflows/publish_docker_images.yaml
=> [Docker] Setup QEMU for multiarch Docker builds

rules/coding-style/src/Application/UseImportsAdder.php
Closes https://github.com/rectorphp/the-power-of-automated-refactoring/issues/67
=> [CodingStyle] Fix extra space on no extra import

rules/type-declaration/src/Rector/ClassMethod/ReturnTypeFromStrictTypedCallRector.php, rules/type-declaration/tests/Rector/ClassMethod/ReturnTypeFromStrictTypedCallRector/Fixture/return_self.php.inc, rules/type-declaration/tests/Rector/ClassMethod/ReturnTypeFromStrictTypedCallRector/Fixture/return_self_different_namespace.php.inc, rules/type-declaration/tests/Rector/ClassMethod/ReturnTypeFromStrictTypedCallRector/Fixture/return_self_different_namespace_nullable.php.inc, rules/type-declaration/tests/Rector/ClassMethod/ReturnTypeFromStrictTypedCallRector/Fixture/use_return_self.php.inc, rules/type-declaration/tests/Rector/ClassMethod/ReturnTypeFromStrictTypedCallRector/Fixture/use_return_self_nullable.php.inc, rules/type-declaration/tests/Rector/ClassMethod/ReturnTypeFromStrictTypedCallRector/Source/ReturnSelfFromSource.php, rules/type-declaration/tests/Rector/ClassMethod/ReturnTypeFromStrictTypedCallRector/Source/ReturnSelfFromSourceNullable.php
Fixees https://github.com/rectorphp/rector/issues/5770
=> [TypeDeclaration] Handle return self on ReturnTypeFromStrictTypedCallRector

packages/node-type-resolver/src/NodeTypeResolver/CastTypeResolver.php, packages/node-type-resolver/src/NodeTypeResolver/ClassConstFetchTypeResolver.php, packages/phpstan-static-type-mapper/src/PHPStanStaticTypeMapper.php, packages/phpstan-static-type-mapper/src/TypeMapper/NullTypeMapper.php, packages/phpstan-static-type-mapper/src/ValueObject/TypeKind.php, rules/php74/src/Rector/Property/TypedPropertyRector.php, rules/transform/src/Rector/Isset_/UnsetAndIssetToMethodCallRector.php, rules/transform/src/Rector/String_/ToStringToMethodCallRector.php, rules/type-declaration/src/Rector/FunctionLike/ParamTypeDeclarationRector.php, rules/type-declaration/src/Rector/FunctionLike/ReturnTypeDeclarationRector.php, rules/type-declaration/src/Rector/Property/TypedPropertyFromStrictConstructorRector.php, rules/type-declaration/tests/Rector/ClassMethod/AddParamTypeFromCallersRector/Fixture/skip_boolean_cast.php.inc, rules/type-declaration/tests/Rector/ClassMethod/AddParamTypeFromCallersRector/Fixture/skip_by_class_string.php.inc
Follow up to https://github.com/rectorphp/rector/pull/5782
=> [TypeDeclaration] Improve param by caller types

rules/code-quality-strict/src/Rector/Variable/MoveVariableDeclarationNearReferenceRector.php, rules/code-quality/src/Rector/ClassMethod/DateTimeToDateTimeInterfaceRector.php, rules/code-quality/src/Rector/If_/SimplifyIfReturnBoolRector.php, rules/coding-style/src/ClassNameImport/ClassNameImportSkipVoter/FullyQualifiedNameClassNameImportSkipVoter.php, rules/coding-style/src/ClassNameImport/ShortNameResolver.php, rules/coding-style/src/Node/NameImporter.php, rules/downgrade-php74/src/Rector/ClassMethod/DowngradeCovariantReturnTypeRector.php, rules/nette/src/NodeFactory/ActionRenderFactory.php, rules/php74/tests/Rector/Property/TypedPropertyRector/FixtureImported/already_imported_short_name.php.inc, rules/php80/src/Rector/If_/NullsafeOperatorRector.php, rules/phpunit/src/NodeFactory/ExpectExceptionCodeFactory.php
Closes https://github.com/rectorphp/rector/issues/5738
=> [TypedProperty] Fix short import on already existing docblock

packages/node-type-resolver/src/NodeTypeResolver.php, packages/node-type-resolver/src/NodeTypeResolver/ClassAndInterfaceTypeResolver.php, packages/node-type-resolver/src/NodeTypeResolver/StaticCallTypeResolver.php, packages/node-type-resolver/src/NodeTypeResolver/VariableTypeResolver.php, rules/code-quality/src/Rector/ClassMethod/DateTimeToDateTimeInterfaceRector.php, rules/dead-code/src/Rector/Assign/RemoveAssignOfVoidReturnFunctionRector.php, rules/dead-code/tests/Rector/Assign/RemoveAssignOfVoidReturnFunctionRector/Fixture/some_static_call.php.inc, rules/dead-code/tests/Rector/FunctionLike/RemoveOverriddenValuesRector/Fixture/keep_re_use.php.inc, rules/doctrine/src/Rector/MethodCall/ChangeSetIdToUuidValueRector.php, rules/doctrine/src/Rector/MethodCall/ReplaceParentRepositoryCallsByRepositoryPropertyRector.php, rules/nette-code-quality/src/NodeAnalyzer/ControlDimFetchAnalyzer.php, rules/nette-tester-to-phpunit/src/Rector/Class_/NetteTesterClassToPHPUnitClassRector.php, rules/nette-tester-to-phpunit/src/Rector/StaticCall/NetteAssertToPHPUnitAssertRector.php, rules/nette-tester-to-phpunit/tests/Rector/Class_/NetteTesterClassToPHPUnitClassRector/NetteTesterClassToPHPUnitClassRectorTest.php, rules/php-office/src/Rector/MethodCall/ChangeConditionalGetConditionRector.php, rules/php-office/src/Rector/StaticCall/AddRemovedDefaultValuesRector.php, rules/php-office/src/Rector/StaticCall/CellStaticToCoordinateRector.php, rules/php-office/tests/Rector/StaticCall/AddRemovedDefaultValuesRector/Fixture/some_static_call.php.inc, rules/php56/src/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector.php, rules/privatization/src/Rector/ClassMethod/MakeOnlyUsedByChildrenProtectedRector.php, rules/privatization/src/Rector/MethodCall/ReplaceStringWithClassConstantRector.php, rules/privatization/src/ValueObject/ReplaceStringWithClassConstant.php, rules/symfony/src/Rector/Class_/MakeCommandLazyRector.php, rules/symfony5/src/Rector/MethodCall/FormBuilderSetDataMapperRector.php, rules/type-declaration/src/Rector/ClassMethod/AddReturnTypeDeclarationRector.php, rules/type-declaration/src/ValueObject/AddReturnTypeDeclaration.php
Follow up to https://github.com/rectorphp/rector/pull/5787
=> [TypeDeclaration] Improve param by caller type #3

rules/phpunit/src/Rector/Class_/AddSeeTestAnnotationRector.php, rules/phpunit/tests/Rector/Class_/AddSeeTestAnnotationRector/Fixture/remove_non_existing_see.php.inc
Solves old rename duplications like  https://github.com/symplify/symplify/pull/3033/commits/7660984d1c1cd5a79b577c772ebdca462250f1c0
=> [PHPUnit] Remove old test case in AddSeeTestAnnotationRector

rules/renaming/src/NodeManipulator/ClassRenamer.php, rules/renaming/tests/Rector/Name/RenameClassRector/FixtureAutoImportNames/rename_class_with_same_name_but_different_namespace.php.inc, rules/renaming/tests/Rector/Name/RenameClassRector/Source/FirstNamespace/SomeServiceClass.php, rules/renaming/tests/Rector/Name/RenameClassRector/Source/SecondNamespace/SomeServiceClass.php, rules/renaming/tests/Rector/Name/RenameClassRector/config/auto_import_names.php
=> [Renaming] Handle RenameClassRector on auto import with same class name last namespace part

config/set/symfony51.php, ecs.php, phpstan-for-rector.neon, rules-tests/Symfony5/Rector/ClassMethod/RouteCollectionBuilderToRoutingConfiguratorRector/Fixture/some_class.php.inc, rules-tests/Symfony5/Rector/ClassMethod/RouteCollectionBuilderToRoutingConfiguratorRector/RouteCollectionBuilderToRoutingConfiguratorRectorTest.php, rules/Symfony5/Rector/ClassMethod/RouteCollectionBuilderToRoutingConfiguratorRector.php, stubs/Symfony/Bundle/FrameworkBundle/Kernel/MicroKernelTrait.php
Closes https://github.com/rectorphp/rector/issues/4831
=> [Symfony 5.1] Add RouteCollectionBuilderToRoutingConfiguratorRector

rules-tests/Php80/Rector/NotIdentical/StrContainsRector/Fixture/identical_false.php.inc, rules-tests/Php80/Rector/NotIdentical/StrContainsRector/Fixture/identical_strpos.php.inc, rules-tests/Php80/Rector/NotIdentical/StrContainsRector/Fixture/identical_strstr.php.inc, rules/Php80/Rector/NotIdentical/StrContainsRector.php
=> [Php80] Handle Identical false in StrContainsRector

rules-tests/CodeQuality/Rector/FuncCall/ChangeArrayPushToArrayAssignRector/Fixture/skip_array_push_not_in_expression.php.inc, rules/CodeQuality/Rector/FuncCall/ChangeArrayPushToArrayAssignRector.php
=> [CodeQuality] Skip ChangeArrayPushToArrayAssignRector not in expression

scoper.php
=> [Scoped] Fixes escape backslash regex on Scoper

packages/NodeCollector/NodeCollector/NodeRepository.php, rules-tests/DowngradePhp72/Rector/ClassMethod/DowngradeParameterTypeWideningRector/Fixture/parent_type_none.php.inc, rules-tests/DowngradePhp72/Rector/ClassMethod/DowngradeParameterTypeWideningRector/Source/SomeContainerInterface.php, rules/DowngradePhp72/NodeAnalyzer/ClassLikeParentResolver.php, rules/DowngradePhp72/NodeAnalyzer/NativeTypeClassTreeResolver.php, rules/DowngradePhp72/Rector/ClassMethod/DowngradeParameterTypeWideningRector.php
Closes https://github.com/rectorphp/rector/pull/5780#issuecomment-800288101
=> [Downgrade 7.2] Fix downgrade from parent native type

rules-tests/DowngradePhp73/Rector/String_/DowngradeFlexibleHeredocSyntaxRector/DowngradeFlexibleHeredocSyntaxRectorTest.php, rules-tests/DowngradePhp73/Rector/String_/DowngradeFlexibleHeredocSyntaxRector/Fixture/skip_correct_position.php.inc, rules-tests/DowngradePhp80/Rector/ClassMethod/DowngradeStaticTypeDeclarationRector/Fixture/also_trait.php.inc, rules/DowngradePhp71/Rector/String_/DowngradeNegativeStringOffsetToStrlenRector.php, rules/DowngradePhp71/Rector/TryCatch/DowngradePipeToMultiCatchExceptionRector.php, rules/DowngradePhp72/NodeAnalyzer/NativeTypeClassTreeResolver.php, rules/DowngradePhp73/Rector/String_/DowngradeFlexibleHeredocSyntaxRector.php, rules/DowngradePhp80/Rector/ClassMethod/DowngradeStaticTypeDeclarationRector.php, rules/Symfony5/Rector/MethodCall/ReflectionExtractorEnableMagicCallExtractorRector.php, rules/Symfony5/Rector/New_/PropertyAccessorCreationBooleanToFlagsRector.php
Cherry picks of https://github.com/rectorphp/rector/pull/5880
=> misc fixes

packages/NodeTypeResolver/PHPStan/Type/TypeFactory.php
Not sure how to test this currently as I still did not narrow
the issue down to some specific code or case (as I'm currently
encountering other issues that I'm investigating)
Fixes #5953
=> Fix Undefined offset in TypeFactory around flattenTypes calls

packages/ChangesReporting/Application/ErrorAndDiffCollector.php, src/Application/RectorApplication.php
Closes https://github.com/rectorphp/rector/issues/5966
=> Do not print files with fatal errors as the file format breaks completely

rules-tests/DeadCode/Rector/If_/RemoveDeadInstanceOfRector/Fixture/skip_trait.php.inc, rules/DeadCode/Rector/If_/RemoveDeadInstanceOfRector.php, rules/TypeDeclaration/Reflection/ReflectionTypeResolver.php
Closes https://github.com/rectorphp/rector/issues/5952
=> [DeadCode] Skip RemoveDeadInstanceOfRector for traits

packages/VendorLocker/NodeVendorLocker/PropertyTypeVendorLockResolver.php, rules-tests/Php74/Rector/Property/TypedPropertyRector/Fixture/skip_trait.php.inc
- Closes https://github.com/rectorphp/rector/issues/5955
- Closes https://github.com/rectorphp/rector/pull/5957
=> [TypedProperty] Skip trait property type as unable to resolve reliable

rules-tests/Php71/Rector/Assign/AssignArrayToStringRector/Fixture/skip_cast_undefined_var.php.inc, rules-tests/Php71/Rector/Assign/AssignArrayToStringRector/Fixture/skip_cast_undefined_var2.php.inc, rules-tests/Php71/Rector/Assign/AssignArrayToStringRector/Fixture/skip_cast_undefined_var3.php.inc, rules/Php71/Rector/Assign/AssignArrayToStringRector.php, src/PhpParser/Node/BetterNodeFinder.php
=> [Php71] Skip AssignArrayToStringRector on assign var not defined before

packages/NodeNameResolver/NodeNameResolver.php, rules-tests/CodeQuality/Rector/Class_/CompleteDynamicPropertiesRector/Fixture/skip_static_return_object.php.inc
=> [NodeNameResolver] Set return false on node is MethodCall/StaticCall on NodeNameResolver::isName()

rules-tests/DeadCode/Rector/MethodCall/RemoveDefaultArgumentValueRector/Fixture/not_last_argument.php.inc, rules-tests/DeadCode/Rector/MethodCall/RemoveDefaultArgumentValueRector/Fixture/not_last_argument2.php.inc, rules-tests/DeadCode/Rector/MethodCall/RemoveDefaultArgumentValueRector/Fixture/not_last_argument3.php.inc, rules-tests/DeadCode/Rector/MethodCall/RemoveDefaultArgumentValueRector/Fixture/skip_has_required_argument.php.inc, rules-tests/DeadCode/Rector/MethodCall/RemoveDefaultArgumentValueRector/Fixture/skip_no_argument.php.inc, rules-tests/DeadCode/Rector/MethodCall/RemoveDefaultArgumentValueRector/Fixture/skip_system_function.php.inc, rules/DeadCode/Rector/MethodCall/RemoveDefaultArgumentValueRector.php
=> [DeadCode] Handle RemoveDefaultArgumentValueRector on removal default argument on not last argument

.gitattributes
Based on https://github.com/rectorphp/rector/pull/5973#issuecomment-806228914
=> [GitAttributes] Add phpstan-for-rector.neon to .gitattributes

.github/workflows/build_scoped_rector.yaml
=> [Scoped] Add templates on build rector-prefixed-downgraded

scoper.php
=> [Scoped] Handle Cannot use RectorPrefix20210329parent as class name as it is reserved on Build docker image

scoper.php
Fixes #6010 for fix the build docker php 7.3 and 7.4
=> [Scoper] Remove namespace on polyfill symfony Stubs

rules-tests/CodeQuality/Rector/Array_/CallableThisArrayToAnonymousFunctionRector/Fixture/skip_forward_static_call.php.inc, rules/CodeQuality/Rector/Array_/CallableThisArrayToAnonymousFunctionRector.php
=> [CodeQuality] Skip CallableThisArrayToAnonymousFunctionRector on forward_static_call function

rules-tests/CodeQualityStrict/Rector/If_/MoveOutMethodCallInsideIfConditionRector/Fixture/string_arg_variable_colon.php.inc, rules/CodeQuality/Naming/MethodCallToVariableNameResolver.php
=> [CodeQuality] Handle colon in arg value for create variable or MoveOutMethodCallInsideIfConditionRector

rules-tests/Privatization/Rector/Property/ChangeReadOnlyPropertyWithDefaultValueToConstantRector/Fixture/skip_referenced.php.inc, rules-tests/Privatization/Rector/Property/ChangeReadOnlyPropertyWithDefaultValueToConstantRector/Fixture/skip_referenced2.php.inc, src/NodeManipulator/PropertyManipulator.php
=> [Privatization] Skip ChangeReadOnlyPropertyWithDefaultValueToConstantRector on by ref param method call

packages/StaticTypeMapper/ValueObject/Type/AliasedObjectType.php, rules-tests/Renaming/Rector/Name/RenameClassRector/FixtureAutoImportNames/rename_class_with_same_name_but_different_namespace.php.inc, rules/Php72/Rector/FuncCall/IsObjectOnIncompleteClassRector.php, rules/Php74/Rector/MethodCall/ChangeReflectionTypeToStringToGetNameRector.php, rules/Renaming/NodeManipulator/ClassRenamer.php, rules/Renaming/Rector/FuncCall/RenameFunctionRector.php, rules/Transform/Rector/Expression/MethodCallToReturnRector.php, src/PhpParser/Node/NodeFactory.php, src/PhpParser/Printer/BetterStandardPrinter.php, src/Rector/AbstractRector.php, tests/PhpParser/Printer/BetterStandardPrinterTest.php
Closes https://github.com/rectorphp/rector/issues/6039
=> Restore parent relations on new nodes

UPGRADE.md, composer.json, rules-tests/Arguments/Rector/MethodCall/ValueObjectWrapArgRector/Fixture/include_many.php.inc, rules-tests/Arguments/Rector/MethodCall/ValueObjectWrapArgRector/Fixture/skip_already_new.php.inc, rules-tests/Arguments/Rector/MethodCall/ValueObjectWrapArgRector/Fixture/some_class.php.inc, rules-tests/Arguments/Rector/MethodCall/ValueObjectWrapArgRector/ValueObjectWrapArgRectorTest.php, rules-tests/Arguments/Rector/MethodCall/ValueObjectWrapArgRector/config/configured_rule.php, rules/Arguments/Rector/MethodCall/ValueObjectWrapArgRector.php, rules/Arguments/ValueObject/ValueObjectWrapArg.php, upgrade/rector_010.php, utils/phpstan-extensions/src/ReturnTypeExtension/GetAttributeReturnTypeExtension.php
Inspired by manual upgrade of https://github.com/sabbelasichon/typo3-rector/pull/2141
This should be easier :)
=> Add upgrade path to Rector 0.10 - upgrade set included 

packages/BetterPhpDocParser/PhpDocInfo/PhpDocInfo.php, packages/BetterPhpDocParser/PhpDocManipulator/PhpDocTypeChanger.php, packages/Testing/PHPUnit/AbstractRectorTestCase.php, rules-tests/TypeDeclaration/Rector/ClassMethod/AddArrayReturnDocTypeRector/Fixture/skip_invalid_tag_double_doc.php.inc, rules/Composer/Processor/ComposerProcessorNonPhp.php, src/Console/Command/ProcessCommand.php, src/NonPhpFile/NonPhpFileProcessorService.php, tests/NonPhpFile/NonPhpFileProcessorServiceTest.php, tests/NonPhpFile/config/configured_rule.php
Closes https://github.com/rectorphp/rector/issues/5954
=> Workaround invalid tag value node on add return array

rules/LeagueEvent/Rector/MethodCall/DispatchStringToObjectRector.php
Ref https://github.com/rectorphp/rector/pull/6075#discussion_r611030217 /cc @lulco
=> [LeagueEvent] Remove unnecessary check instanceof StringType on DispatchStringToObjectRector

rules-tests/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture/skip_in_compact.php.inc, rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php, src/NodeAnalyzer/CompactFuncCallAnalyzer.php
=> [DeadCode] Skip RemoveUnusedVariableAssignRector on used in next compact function

config/set/downgrade-php70.php, rules-tests/DowngradePhp70/Rector/Declare_/DowngradeStrictTypeDeclarationRector/DowngradeStrictTypeDeclarationRectorTest.php, rules-tests/DowngradePhp70/Rector/Declare_/DowngradeStrictTypeDeclarationRector/Fixture/fixture.php.inc, rules-tests/DowngradePhp70/Rector/Declare_/DowngradeStrictTypeDeclarationRector/Fixture/skip_different_declare.php.inc, rules-tests/DowngradePhp70/Rector/Declare_/DowngradeStrictTypeDeclarationRector/config/php_70.php, rules/DowngradePhp70/Rector/Declare_/DowngradeStrictTypeDeclarationRector.php, rules/DowngradePhp70/Rector/FuncCall/DowngradeStrictTypeDeclarationRector.php
=> [DowngradePhp70] Add DowngradeStrictTypeDeclarationRector

packages/Testing/PHPUnit/AbstractRectorTestCase.php, packages/Testing/PHPUnit/Behavior/MovingFilesTrait.php, rules-tests/Autodiscovery/Rector/FileNode/MoveEntitiesToEntityDirectoryRector/MoveEntitiesToEntityDirectoryRectorTest.php, rules-tests/Autodiscovery/Rector/FileNode/MoveInterfacesToContractNamespaceDirectoryRector/MoveInterfacesToContractNamespaceDirectoryRectorTest.php, rules-tests/Autodiscovery/Rector/FileNode/MoveServicesBySuffixToDirectoryRector/MoveServicesBySuffixToDirectoryRectorTest.php, rules-tests/Autodiscovery/Rector/FileNode/MoveValueObjectsToValueObjectDirectoryRector/MoveValueObjectsToValueObjectDirectoryRectorTest.php, rules-tests/NetteTesterToPHPUnit/Rector/FileNode/RenameTesterTestToPHPUnitToTestFileRector/RenameTesterTestToPHPUnitToTestFileRectorTest.php, rules-tests/NetteToSymfony/Rector/Class_/FormControlToControllerAndFormTypeRector/FormControlToControllerAndFormTypeRectorTest.php, rules-tests/Restoration/Rector/ClassLike/UpdateFileNameByClassNameFileSystemRector/UpdateFileNameByClassNameFileSystemRectorTest.php, rules-tests/Transform/Rector/FileWithoutNamespace/FunctionToStaticMethodRector/FunctionToStaticMethodRectorTest.php
Follow up to https://github.com/rectorphp/rector/pull/6106/files
=> Standardize added file testing + remove doTestExtraFile() from AbstractRectorTestCase

src/NonPhpFile/NonPhpFileProcessor.php
=> Fix: use content from File not from SmartFileInfo

rules-tests/Downgrade73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector/DowngradeArrayKeyFirstLastRectorTest.php, rules-tests/Downgrade73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector/Fixture/array_key_last.php.inc, rules-tests/Downgrade73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector/Fixture/some_class.php.inc, rules-tests/Downgrade73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector/config/configured_rule.php, rules/Downgrade73/Rector/FuncCall/DowngradeArrayKeyFirstLastRector.php
Ref https://github.com/rectorphp/rector/issues/6126
=> [Downgrade 7.3] Add DowngradeArrayKeyFirstLastRector

.github/workflows/build_scoped_rector.yaml, build/build-rector-scoped.sh, build/config/config-downgrade.php, config/set/downgrade-php73.php
Ref https://github.com/rectorphp/rector/issues/6126
=> [prefixed] No polyfill on prefixed version

rules-tests/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture/skip_next_include_another_file.php.inc, rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php, src/PhpParser/Comparing/ConditionSearcher.php
Variable may be used in include file
=> [DeadCode] Skip RemoveUnusedVariableAssignRector on next expr Include_

phpstan.neon, src/Bootstrap/ExtensionConfigResolver.php, src/Bootstrap/RectorConfigsResolver.php
=> [TASK] Add ExtensionConfigResolver for rector/rector-installer

config/set/dead-code.php, packages/BetterPhpDocParser/PhpDocManipulator/PhpDocClassRenamer.php, rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodParameterRector/Fixture/in_between_parameter.php.inc, rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodParameterRector/Fixture/remove_last.php.inc, rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodParameterRector/Fixture/remove_php_doc.php.inc, rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodParameterRector/Fixture/skip_deep_nested_params.php.inc, rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodParameterRector/Fixture/skip_func_get_args.php.inc, rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodParameterRector/Fixture/skip_public_method.php.inc, rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodParameterRector/RemoveUnusedPrivateMethodParameterRectorTest.php, rules-tests/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodParameterRector/config/configured_rule.php, rules/DeadCode/NodeCollector/UnusedParameterResolver.php, rules/DeadCode/NodeManipulator/VariadicFunctionLikeDetector.php, rules/DeadCode/Rector/ClassMethod/RemoveUnusedPrivateMethodParameterRector.php, rules/Defluent/Rector/ClassMethod/NormalToFluentRector.php, rules/TypeDeclaration/Rector/FunctionLike/ParamTypeDeclarationRector.php, src/NodeManipulator/ClassMethodManipulator.php, src/PhpParser/Node/Value/ValueResolver.php
Reverts rectorphp/rector#5888 with 1 change - works only on private methods, where it's safe
=> [DeadCode] Add RemoveUnusedPrivateMethodParameterRector

rules/Renaming/Rector/Name/RenameClassRector.php, src/Configuration/RenamedClassesDataCollector.php
- If reusing the RenamedClassesDataCollector in another rector the additional classes get overridden
https://github.com/sabbelasichon/typo3-rector/pull/2190
=> [BUGFIX] Reusage of RenamedClassesDataCollector

packages/NodeTypeResolver/Node/AttributeKey.php, rules-tests/CodingStyle/Rector/Encapsed/WrapEncapsedVariableInCurlyBracesRector/Fixture/fixture.php.inc, rules/CodeQuality/Rector/Class_/CompleteDynamicPropertiesRector.php, rules/CodingStyle/Rector/Encapsed/WrapEncapsedVariableInCurlyBracesRector.php, rules/DeadCode/Rector/StaticCall/RemoveParentCallWithoutParentRector.php, rules/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector.php, rules/Privatization/Rector/Class_/ChangeLocalPropertyToVariableRector.php, rules/Privatization/Rector/Class_/FinalizeClassesWithoutChildrenRector.php, rules/Privatization/Rector/Property/PrivatizeLocalPropertyToPrivatePropertyRector.php, rules/Transform/Rector/Class_/ChangeSingletonToServiceRector.php, rules/Transform/Rector/Class_/ParentClassToTraitsRector.php, rules/Transform/Rector/MethodCall/ServiceGetterToConstructorInjectionRector.php, src/NodeAnalyzer/ChangedNodeAnalyzer.php, src/Rector/AbstractRector.php
Closes https://github.com/rectorphp/rector/issues/6169
=> Fix WrapEncapsedVariableInCurlyBracesRector reporting

rules-tests/Php80/Rector/Catch_/RemoveUnusedVariableInCatchRector/Fixture/skip_when_variable_is_used_outside_catch.php.inc, rules/Php80/Rector/Catch_/RemoveUnusedVariableInCatchRector.php
=> [Php80] Skip RemoveUnusedVariableInCatchRector when variable used next catch

rules-tests/Php80/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/add_default_case_when_variable_is_initialized.php.inc, rules/Php80/Rector/Switch_/ChangeSwitchToMatchRector.php
=> [Php80] Add default case when variable initialized on ChangeSwitchToMatchRector

packages/Testing/PHPUnit/AbstractRectorTestCase.php, rules/Php80/Rector/Switch_/ChangeSwitchToMatchRector.php, src/Autoloading/AdditionalAutoloader.php, src/Console/Command/ProcessCommand.php
Fixes https://github.com/rectorphp/rector/pull/6158
=> Fix AUTOLOAD_PATHS and BOOTSTRAP_FILES in tests

README.md, docs/init_command.md, phpstan.neon, src/Configuration/Option.php, src/Console/Command/InitCommand.php, src/Contract/Template/TemplateResolverInterface.php, src/Template/DefaultResolver.php, src/Template/TemplateTypeNotFound.php
=> [TASK] Add template type option for init command

rules/DependencyInjection/NodeManipulator/PropertyConstructorInjectionManipulator.php, rules/DependencyInjection/Rector/Property/AnnotatedPropertyInjectToConstructorInjectionRector.php
Ref https://github.com/rectorphp/rector/issues/6246
=> Decouple PropertyConstructorInjectionManipulator

packages/NodeTypeResolver/NodeTypeResolver.php, rules-tests/Renaming/Rector/Name/RenameClassRector/ComplexFixture/rename_class_then_rename_method.php.inc, rules-tests/Renaming/Rector/Name/RenameClassRector/ComplexRenameClassRectorTest.php, rules-tests/Renaming/Rector/Name/RenameClassRector/Source/NewClassWithNewMethod.php, rules-tests/Renaming/Rector/Name/RenameClassRector/Source/OldClassWithMethod.php, rules-tests/Renaming/Rector/Name/RenameClassRector/config/complex_rename.php, rules/PSR4/Collector/RenamedClassesCollector.php, rules/Renaming/Collector/MethodCallRenameCollector.php, rules/Renaming/Rector/MethodCall/RenameMethodRector.php, src/Configuration/RenamedClassesDataCollector.php, src/NodeManipulator/ClassManipulator.php
Closes https://github.com/rectorphp/rector/pull/6070
=> Failing test: Node type is not updated after executing rector

packages/PostRector/Collector/NodesToAddCollector.php, rules-tests/Downgrade72/Rector/FuncCall/DowngradeStreamIsattyRector/Fixture/return_or.php.inc, rules/Downgrade72/Rector/FuncCall/DowngradeStreamIsattyRector.php
Closes https://github.com/rectorphp/rector/issues/6264
=> [Downgrade 7.2] Fix DowngradeStreamIsattyRector with return

.github/workflows/build_scoped_rector_php70.yaml
ref https://github.com/rectorphp/rector/pull/6299#issuecomment-831113974
=> [Scoped] Copy rector-prefixed php 7.0 rector vendor to root vendor/rector

build/config/config-downgrade-php70.php
ref https://github.com/rectorphp/rector/pull/6300#issuecomment-831129216
=> [Scoped] Enable DowngradeNullableTypeDeclarationRector on config-downgrade-php70 config

rules-tests/DowngradePhp71/Rector/FunctionLike/DowngradeNullableTypeDeclarationRector/Fixture/nullable_return_on_closure.php.inc, rules-tests/DowngradePhp71/Rector/FunctionLike/DowngradeNullableTypeDeclarationRector/Fixture/nullable_return_on_closure_call.php.inc, rules/DowngradePhp71/Rector/FunctionLike/DowngradeNullableTypeDeclarationRector.php
ref https://github.com/rectorphp/rector/pull/6302#issuecomment-831158275
=> [DowngradePhp71] Nullable return on closure on DowngradeNullableTypeDeclarationRector

.github/workflows/build_scoped_rector_php70.yaml
ref https://github.com/rectorphp/rector/pull/6303#issuecomment-831171949
=> [Scoped] More exclude parallel lint php 7.0

.github/workflows/build_scoped_rector_php70.yaml
ref https://stackoverflow.com/questions/59954185/github-action-split-long-command-into-multiple-lines
=> [Scoped] Fixing multiline parallel lint exclude

utils/compiler/src/Command/DowngradePathsCommand.php
ref https://github.com/rectorphp/rector/pull/6312#issuecomment-831389943
=> [Scoped] Register config directory to be downgraded

config/set/code-quality.php, config/set/coding-style.php, rules-tests/CodingStyle/Rector/FuncCall/CallUserFuncArrayToVariadicRector/CallUserFuncArrayToVariadicRectorTest.php, rules-tests/CodingStyle/Rector/FuncCall/CallUserFuncArrayToVariadicRector/Fixture/array_local_method.php.inc, rules-tests/CodingStyle/Rector/FuncCall/CallUserFuncArrayToVariadicRector/Fixture/array_local_method_with_reference.php.inc, rules-tests/CodingStyle/Rector/FuncCall/CallUserFuncArrayToVariadicRector/Fixture/fixture.php.inc, rules-tests/CodingStyle/Rector/FuncCall/CallUserFuncArrayToVariadicRector/Fixture/skip_unknown_value.php.inc, rules-tests/CodingStyle/Rector/FuncCall/CallUserFuncArrayToVariadicRector/Source/Redirector.php, rules-tests/CodingStyle/Rector/FuncCall/CallUserFuncArrayToVariadicRector/config/configured_rule.php, rules-tests/CodingStyle/Rector/FuncCall/CallUserFuncToMethodCallRector/CallUserFuncToMethodCallRectorTest.php, rules-tests/CodingStyle/Rector/FuncCall/CallUserFuncToMethodCallRector/Fixture/skip_stringy_array.php.inc, rules-tests/CodingStyle/Rector/FuncCall/CallUserFuncToMethodCallRector/Fixture/some_class.php.inc, rules-tests/CodingStyle/Rector/FuncCall/CallUserFuncToMethodCallRector/config/configured_rule.php, rules-tests/DowngradePhp70/Rector/Spaceship/DowngradeSpaceshipRector/Fixture/func_call.php.inc, rules-tests/DowngradePhp71/Rector/String_/DowngradeNegativeStringOffsetToStrlenRector/Fixture/property_fetch.php.inc, rules/CodingStyle/NodeFactory/ArrayCallableToMethodCallFactory.php, rules/CodingStyle/Rector/FuncCall/CallUserFuncArrayToVariadicRector.php, rules/CodingStyle/Rector/FuncCall/CallUserFuncToMethodCallRector.php
Closes https://github.com/rectorphp/rector/issues/6321
=> [CodingStyle] Add CallUserFuncToMethodCallRector

.github/workflows/build_scoped_rector.yaml, build/build-rector-scoped.sh
Resolves #6268 
Honestly, I have no idea if this is the correct place where to add some directory to prefixed version of rector :) If not, please give me some hints :)
=> Added upgrade sets to rector-prefixed

.github/workflows/build_scoped_rector_php70.yaml, build/build-rector-scoped-php70.sh
ref https://github.com/rectorphp/rector/pull/6320
=> [Scoped] Sync scoped script to include "upgrade" directory

scoper-php70.php
ref https://github.com/rectorphp/rector/issues/6079#issuecomment-832510700
=> [Scoper] Use files-whitelist for vendor/composer/InstalledVersions.php

.github/workflows/build_scoped_rector_php70.yaml, composer.json
as phpstan/phpstan-src require composer/xdebug-handler": "^1.3.0"
=> [Scoper] Allow "composer/xdebug-handler": "^1.3.0 || ^2.0"

composer.json
ref https://github.com/rectorphp/rector/commit/19be81179615bd074e9cc7c304746a57a4ea32a9#r50427744
=> Rollback symfony/console version

packages/NodeNestingScope/ContextAnalyzer.php, rules-tests/EarlyReturn/Rector/If_/ChangeAndIfToEarlyReturnRector/Fixture/skip_assign_in_loop_with_indirect_return.php.inc, rules/EarlyReturn/Rector/If_/ChangeAndIfToEarlyReturnRector.php
Fixes https://github.com/rectorphp/rector/issues/6357
=> [EarlyReturn] Skip ChangeAndIfToEarlyReturnRector on has assign in loop with indirect return after loop

README.md, build/config/config-downgrade-php70.php, build/config/config-downgrade.php, docs/init_command.md, ecs.php, rector.php, src/Configuration/Option.php, src/Console/Command/ShowCommand.php, src/DependencyInjection/CompilerPass/DeprecationWarningCompilerPass.php, src/HttpKernel/RectorKernel.php, src/Reporting/MissingRectorRulesReporter.php, templates/rector.php.dist, tests/DependencyInjection/ConfigurableRectorImportConfigCallsMergeTest.php, tests/DependencyInjection/config/one_set.php, tests/DependencyInjection/config/one_set_with_own_rename.php, tests/DependencyInjection/config/two_sets.php, tests/DependencyInjection/config/two_sets_with_own_rename.php
Ref https://github.com/rectorphp/rector/pull/6362#issuecomment-833566199
cc @sabbelasichon I think this is what you suggested with configs. Let's make it happen :)
=> Move from SETS parameter to explicit import()
