rectorphp/rector

- README.md
- composer.json
- packages/NodeTypeResolver/README.md
- packages/NodeTypeResolver/src/NodeVisitor/ClassResolver.php
- packages/NodeTypeResolver/src/NodeVisitor/TypeResolver.php
- packages/TriggerExtractor/README.md
- packages/TriggerExtractor/src/Console/Command/ExtractCommand.php
- packages/TriggerExtractor/src/Deprecation/DeprecationCollector.php
- packages/TriggerExtractor/src/NodeVisitor/DeprecationDetector.php
- packages/TriggerExtractor/src/TriggerExtractor.php
- packages/TriggerExtractor/src/TriggerMessageResolver.php
- packages/TriggerExtractor/src/config/services.yml
- packages/TriggerExtractor/tests/TriggerExtractorSource/Definition.php
- packages/TriggerExtractor/tests/TriggerExtractorTest.php
- phpstan.neon
- src/Console/Command/ReconstructCommand.php
- src/NodeAnalyzer/ClassResolver.php
- src/NodeAnalyzer/MethodCallAnalyzer.php
- src/NodeFactory/NodeFactory.php
- src/Rector/AbstractChangeParentClassRector.php
- src/Rector/AbstractRector.php
- src/Rector/Contrib/Nette/FormSetRequiredRector.php
- src/Rector/Contrib/Nette/NetteObjectToSmartTraitRector.php
- src/Rector/Contrib/SymfonyExtra/CommandToConstructorInjectionRector.php
- src/Rector/Contrib/SymfonyExtra/GetterToPropertyRector.php
- src/config/services.yml
- tests/Rector/Contrib/Nette/FormSetRequiredRector/Correct/correct.php.inc
- tests/Rector/Contrib/Nette/FormSetRequiredRector/Test.php
- tests/Rector/Contrib/Nette/FormSetRequiredRector/Wrong/wrong.php.inc
Closes #27 
I really didn't get it from [the forum](https://forum.nette.org/cs/26672-missing-setrequired-true-false-on-field-abc-in-form), so at the moment it works like this:
Find on variable of `Nette\Application\UI\Form` type:
```php
->addCondition($form::FILLED)
```
and replace it by:
```php
->setRequired(false)
```
Could you confirm/help me with that @dg && @petrvacha?
> [Nette] forms setRequired(false)

- src/Rector/Contrib/Nette/Environment/NetteEnvironmentRector.php
- src/config/level/nette/nette09.yml
- tests/Rector/Contrib/Nette/Environment/NetteEnvironmentRector/Correct/correct.php.inc
- tests/Rector/Contrib/Nette/Environment/NetteEnvironmentRector/Test.php
- tests/Rector/Contrib/Nette/Environment/NetteEnvironmentRector/Wrong/wrong.php.inc
Rector convert from `Environment` class from Nette 0.9.x to 2.0.x
I added configuration for Nette 0.9.x too. :-)
> added rector for Environment in Nette 0.9

- easy-coding-standard.neon
- src/NodeAnalyzer/Contrib/Symfony/ContainerCallAnalyzer.php
- src/NodeAnalyzer/Contrib/Symfony/ControllerMethodAnalyzer.php
- src/Rector/Contrib/Symfony/Console/CommandToConstructorInjectionRector.php
- src/Rector/Contrib/Symfony/Form/FormTypeGetParentRector.php
- src/Rector/Contrib/Symfony/Form/Helper/FormTypeStringToTypeProvider.php
- src/Rector/Contrib/Symfony/Form/StringFormTypeToClassRector.php
- src/Rector/Contrib/Symfony/HttpKernel/GetRequestRector.php
- src/Rector/Contrib/Symfony/HttpKernel/GetterToPropertyRector.php
- tests/Rector/Contrib/Symfony/Form/FormTypeGetParentRector/Correct/correct2.php.inc
- tests/Rector/Contrib/Symfony/Form/FormTypeGetParentRector/Test.php
- tests/Rector/Contrib/Symfony/Form/FormTypeGetParentRector/Wrong/wrong2.php.inc
- tests/Rector/Contrib/Symfony/Form/StringFormTypeToClassRector/Correct/correct.php.inc
- tests/Rector/Contrib/Symfony/Form/StringFormTypeToClassRector/Wrong/wrong.php.inc
Covers: https://github.com/umpirsky/Symfony-Upgrade-Fixer/pull/38
- https://github.com/umpirsky/Symfony-Upgrade-Fixer/issues/16
> [Symfony] extend FormTypeGetParentRector with AbstractTypeExtension

- README.md
I read from top to bottom, meaning I first struggled to get the proper path to yml file for `--config` option working (the readme contained a wrong example - which I also fixed).
Only after I made it, I found on next line in the readme I could just use the shortcut 🙃 .
IMHO the shortcut for `--level` is more simpler usage, and the `--config` is meant for some specific use-cases, so I would first suggest using this one, which will IMHO work for most of people.
> Prefer level shortcuts insetad of config files in readme

- src/Rector/Dynamic/NamespaceReplacerRector.php
- tests/Rector/Dynamic/NamespaceReplacerRector/Test.php
- tests/Rector/Dynamic/NamespaceReplacerRector/config/rector.yml
- tests/Rector/Dynamic/NamespaceReplacerRector/correct/correct5.php.inc
- tests/Rector/Dynamic/NamespaceReplacerRector/wrong/wrong5.php.inc
Hey, this PR fixes bug, where namespace rector generated wrong class names. I was unable fix one test error, which was already present as it wants me to "Use service and constructor injection rather than instantiation", but service container is not instantiated yet. Have a nice day:)
> namespace rector fix

- README.md
- docs/HowUseWithOldPhp.md
It is part of my ideas for issue #133.
What do you mean about it? For now are installation steps in one place.
> docs - extract install for old PHP into docs folder

- easy-coding-standard.neon
- packages/NodeTypeResolver/tests/AbstractNodeTypeResolverTest.php
- packages/ReflectionDocBlock/src/NodeAnalyzer/DocBlockAnalyzer.php
- phpstan.neon
- src/Node/NodeFactory.php
- src/Rector/Contrib/PHPUnit/SpecificMethodBoolNullRector.php
- src/Rector/Contrib/PHPUnit/SpecificMethodCountRector.php
- src/Rector/Contrib/PHPUnit/SpecificMethodObjectAttributeRector.php
- src/config/level/phpunit/phpunit60.yml
- tests/Rector/Contrib/PHPUnit/SpecificMethodBoolNullRector/Correct/correct.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethodBoolNullRector/Test.php
- tests/Rector/Contrib/PHPUnit/SpecificMethodBoolNullRector/Wrong/wrong.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethodCountRector/Correct/correct.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethodCountRector/Test.php
- tests/Rector/Contrib/PHPUnit/SpecificMethodCountRector/Wrong/wrong.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethodObjectAttributeRector/Correct/correct.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethodObjectAttributeRector/Test.php
- tests/Rector/Contrib/PHPUnit/SpecificMethodObjectAttributeRector/Wrong/wrong.php.inc
Closes #187
- `assertCount` instead of `count` function;
- `assertTrue` instead of strict comparison with `true` keyword;
- `assertFalse` instead of strict comparison with `false` keyword;
- `assertNull` instead of strict comparison with `null` keyword;
- `assertObjectHasAttribute` and `assertObjectNotHasAttribute` instead of `isset` function.
Thaks @carusogabriel  for inspiration
> [PHPUnit] Add NarrowMethodsRector

- src/Rector/Contrib/PHPUnit/SpecificMethodCountRector.php
- tests/Rector/Contrib/PHPUnit/SpecificMethodCountRector/Correct/correct.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethodCountRector/Wrong/wrong.php.inc
I extended `SpecificMethodCountRector` and now we can work with `assertEquals`, `assertNotEquals` and `assertNotSame`. Also, `sizeof`, an alias to `count` is also detected now.
> Extend SpecificMethodCountRector

- src/NodeChanger/MethodNameChanger.php
- src/Rector/Contrib/PHPUnit/SpecificMethodCountRector.php
- src/Rector/Contrib/PHPUnit/SpecificMethodObjectAttributeRector.php
This resolves #201, creating a `NodeChanger\MethodNameChanger` to delegate the function or rename a Node method name. Implemented it in `SpecificMethodCountRector` for tests, but if @TomasVotruba agreed, let's constantly use in `Rector`s.
> [NodeChanger] Create MethodNameChanger

- src/Rector/Contrib/PHPUnit/SpecificMethodRector.php
- tests/Rector/Contrib/PHPUnit/SpecificMethodRector/Correct/correct.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethodRector/Wrong/wrong.php.inc
While refactoring tests, I discovery that `assertTrue(in_array('foo', $anything))` could be refactored to `assertContains('foo', $anything)`. Soo, why not have a `Rector` for that? :sweat_smile: 
@TomasVotruba May I have you opinions before stand this to also support `array_search`? :innocent:
> [PHPUnit] Add in_array and array_search to SpecificMethodRector

- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertSameBoolNullToSpecificMethodRector.php
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertSameBoolNullToSpecificMethodRector/Correct/correct.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertSameBoolNullToSpecificMethodRector/Wrong/wrong.php.inc
Sometimes we need to refactor the not variation of `assertSame`: `assertNotSame`. This PR adds this :smile_cat:
> [PHPUnit] Support assertNotSame in AssertSameBoolNullToSpecificMethodRector

- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertCompareToSpecificMethodRector.php
An easy refactor when checking instances. This assertion:
```php
$this->assertSame('Foo', get_class($foo));
```
Can became:
```php
$this->assertInstanceOf('Foo', $foo);
```
> [PHPUnit] Add get_class to AssertCompareToSpecificMethodRector

- composer.json
As the Contribute Guidelines [says](https://github.com/rectorphp/rector#how-to-contribute): `Tests, coding standard and` **`PHPStan`** `checks must pass`
> Add PHPStan to composer all command

- phpstan.neon
- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertComparisonToSpecificMethodRector.php
- src/config/level/phpunit/phpunit-specific-method.yml
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertComparisonToSpecificMethodRector/AssertComparisonToSpecificMethodRectorTest.php
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertComparisonToSpecificMethodRector/Correct/correct.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertComparisonToSpecificMethodRector/Wrong/wrong.php.inc
As suggested in #216, I've created a new `AssertComparisonToSpecificMethodRector`, so we can refactor comparisons to better `PHPUnit` assertion methods. 
I just need to add a new error to `ignoreErrors` section in `phpstan.neon`, because the `PhpParser\Node\Expr\BinaryOp::getOperatorSigil()` method [is abstract](https://github.com/nikic/PHP-Parser/blob/master/lib/PhpParser/Node/Expr/BinaryOp.php#L39), so, it raises this error. Otherwise, everything should be ready to go :mrs_claus:
> [PHPUnit] Create AssertComparisonToSpecificMethodRector

- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertCompareToSpecificMethodRector.php
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertCompareToSpecificMethodRector/Correct/correct.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertCompareToSpecificMethodRector/Wrong/wrong.php.inc
Most of the time, people already store what they expected in a `$variable`, and them pass it to the `PHPUnit` assert method. This PR adds support to this.
@TomasVotruba Should we create a method `resolveFirstArgument`, or `Variable`, `LNumber` and `String` have something in common that we could check? Maybe [`Cast`](https://github.com/nikic/PHP-Parser/tree/master/lib/PhpParser/Node/Expr/Cast)?
> [PHPUnit] Support variables as argument in AssertCompareToSpecificMethodRector

- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertSameBoolNullToSpecificMethodRector.php
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertSameBoolNullToSpecificMethodRector/Wrong/wrong.php.inc
As the purpose of `Rector` is to upgrade legacy apps, some of them do not follow the `PSR-2` recommendation to [define keywords in lowercase](http://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull). This PR fix some cases that we could face it :+1:
> [PHPUnit] Support keyword in uppercase at AssertSameBoolNullToSpecificMethodRector

- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertFalseStrposToContainsRector.php
- src/config/level/phpunit/phpunit-specific-method.yml
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertFalseStrposToContainsRector/AssertFalseStrposToContainsRectorTest.php
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertFalseStrposToContainsRector/Correct/correct.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertFalseStrposToContainsRector/Wrong/wrong.php.inc
We commonly assert for substring in `PHPUnit` with `strpos`:
```php
$this->assertTrue(strpos('foo', 'f') !== false);
```
But we can simplify this with `assertContains`, as [it handles it](https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/Constraint/StringContains.php#L82):
```php
$this->assertContains('f', 'foo');
```
As we already have `AssertComparisonToSpecificMethodRector`, that changes the first code to:
```php
$this->assertNotSame(false, strpos('foo', 'f'));
```
And `AssertSameBoolNullToSpecificMethodRector` that changes to:
```php
$this->assertNotFalse(strpos('foo', 'f'));
```
I've created `AssertFalseStrposToContainsRector` to finish this refaction :nerd_face:
> [PHPUnit] Create AssertFalseStrposToContainsRector

- README.md
- composer.json
I've renamed the `composer all` command to `composer complete-check`. As we have in [`Symplify`](https://github.com/Symplify/Symplify/blob/master/composer.json#L74), I guess suggests a better name for what this command does.
> Rename composer all to composer complete-check

- src/Application/FileProcessor.php
- src/Console/Command/ProcessCommand.php
- src/Console/ConsoleStyle.php
- src/Console/Output/ProcessCommandReporter.php
- src/Printer/FormatPerservingPrinter.php
I've made a little improvement to our `ProcessCommand`: report _how many_, and **what files**, were changed :tada:
- Now the `printToFile` and `processFile` methods in `FormatPerservingPrinter` and `FileProcessor` return the result of `file_put_contents`, and as this function [returns `false` in cause of failure](http://php.net/manual/en/function.file-put-contents.php#refsect1-function.file-put-contents-returnvalues), I've also added `return false` in case the file didn't get changed, so we can check it;
- I've used the [`listing` method](https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Console/Style/SymfonyStyle.php#L102-L111) from `SymfonyStyle`, to avoid `for` loops in our code. As suggested by @javiereguiluz in …
> [ProcessCommand] Improvement by reporting changed files

- src/Console/Command/ProcessCommand.php
- src/Console/Output/ProcessCommandReporter.php
As [foreseen](https://github.com/rectorphp/rector/pull/246#issuecomment-354471135) by @TomasVotruba in #246, the `--dry-run` option should also follow the process of collecting the changes, and them render.
Before:
After:
I've also added a title before the diffs: `X files with changes` :man_technologist:
> [ProcessCommand] Fix --dry-run option

- packages/NodeTypeResolver/src/PerNodeTypeResolver/MethodCallTypeResolver.php
- packages/NodeTypeResolver/tests/PerNodeTypeResolver/AssignTypeResolver/AssignTypeResolverTest.php
- packages/NodeTypeResolver/tests/PerNodeTypeResolver/AssignTypeResolver/Source/ClassConstant.php.inc
- packages/NodeTypeResolver/tests/PerNodeTypeResolver/AssignTypeResolver/Source/PropertyFetch.php.inc
One more bug discovered in #208:
```sh
PHP Recoverable fatal error:  Object of class PhpParser\Node\Scalar\MagicConst\Class_ could not be converted to string in /home/carusogabriel/.composer/vendor/rector/rector/packages/NodeTypeResolver/src/PerNodeTypeResolver/MethodCallTypeResolver.php on line 83
```
> [MethodCallTypeResolver] Extend method resolveMethodCallName

- packages/BetterReflection/src/Reflector/SmartClassReflector.php
- src/NodeAnalyzer/ClassLikeAnalyzer.php
- src/Rector/Contrib/PHPUnit/ExceptionAnnotationRector.php
- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertFalseStrposToContainsRector.php
- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertInstanceOfComparisonRector.php
- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertTrueFalseToSpecificMethodRector.php
- src/config/level/phpunit/phpunit-specific-method.yml
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertFalseStrposToContainsRector/Wrong/wrong.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertInstanceOfComparisonRector/AssertInstanceOfComparisonRectorTest.php
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertInstanceOfComparisonRector/Correct/correct.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertInstanceOfComparisonRector/Wrong/wrong.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertTrueFalseToSpecificMethodRector/Correct/correct.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertTrueFalseToSpecificMethodRector/Wrong/wrong.php.inc
I've expanded our PHPUnit `Rector`s to support more methods to refactory:
- `AssertFalseStrposToContainsRector` also converts `stripos` to `assertContains`;
- `AssertTrueFalseToSpecificMethodRector` supports `is_a` to `assertInstanceOf`;
- `AssertInstanceOfComparisonRector` is a new one to handle `instanceof` comparison to `assertInstanceOf` assertion.
Bonus: I use `array_map` in some places to clean up some code :man_technologist:
> [PHPUnit] Expand Rectors to support more methods

- phpstan.neon
- src/FileSystem/PhpFilesFinder.php
- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertCompareToSpecificMethodRector.php
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertCompareToSpecificMethodRector/Correct/correct.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertCompareToSpecificMethodRector/Wrong/wrong.php.inc
This fixes [#208](https://github.com/rectorphp/rector/issues/208#issuecomment-355059999) reported bug with complexes second arguments, such as `$something['property']()`.
I've tried to do not add a second if, to break function's cyclomatic allowed maximum of 5. So, an error must be added to `phpstan.neon`.
But, now we receive a PHP Notice during running Rector: `Undefined property: PhpParser\Node\Expr\ArrayDimFetch::$name`.
@TomasVotruba What should we do my friend?
> [AssertCompareToSpecificMethodRector] Fix bug with ArrayDimFetch Nodes

- packages/ReflectionDocBlock/src/NodeAnalyzer/DocBlockAnalyzer.php
In DocBlockAnalyzer line 88 we `count` the return of `getTagsByName`. [In PHP 7.2](https://travis-ci.org/rectorphp/rector/jobs/326743440#L607), if we try to count `null`, an error arises: 
```
count(): Parameter must be an array or an object that implements Countable
```
So, instead of null, just return an empty array.
> [DocBlockAnalyzer] Fix tests

- packages/NodeTypeResolver/src/PerNodeTypeResolver/MethodCallTypeResolver.php
- packages/NodeTypeResolver/tests/PerNodeTypeResolver/MethodCallTypeResolver/MethodCallSource/OnMagicClassCall.php.inc
- packages/NodeTypeResolver/tests/PerNodeTypeResolver/MethodCallTypeResolver/MethodCallTypeResolverTest.php
[As predicted](https://github.com/rectorphp/rector/pull/274#discussion_r160067629) in #274
> [Fix] Object of class PhpParser\Node\{} could not be converted to string

- bin/rector_bootstrap.php
This suppress #280, with a branch on Rector allowing local tests.
@TomasVotruba I'll test and see with position `vendor-bin` is better.
> Add vendor-bin to $possibleAutoloadPaths

- src/Rector/AbstractPHPUnitRector.php
- src/Rector/Contrib/PHPUnit/DelegateExceptionArgumentsRector.php
- src/Rector/Contrib/PHPUnit/ExceptionAnnotationRector.php
- src/Rector/Contrib/PHPUnit/GetMockRector.php
- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertCompareToSpecificMethodRector.php
- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertComparisonToSpecificMethodRector.php
- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertFalseStrposToContainsRector.php
- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertInstanceOfComparisonRector.php
- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertIssetToSpecificMethodRector.php
- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertSameBoolNullToSpecificMethodRector.php
- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertTrueFalseInternalTypeToSpecificMethodRector.php
- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertTrueFalseToSpecificMethodRector.php
This PR solves some problems with PHPUnit Rectors:
- Some assertions weren't being refactored if they extended a `BaseTestCase` class, not PHPUnit's;
- Unify how we candidate our classes to look up for assertions: end with `Test`, as it [is the standard in PHPUnit](https://phpunit.de/getting-started-with-phpunit.html). In the feature, we can remove this check, looking up just for the assertions, but only when improving the speed of Rector.
After that, a bug arises calling `toString` in FuncCall that are actually variables: `$method($argument)`, also fixed with this PR.
> [PHPUnit] Create AbstractPHPUnitRector

- src/Rector/Contrib/Symfony/Controller/RedirectToRouteRector.php
- src/config/level/symfony/symfony26.yml
- tests/Rector/Contrib/Symfony/Controller/RedirectToRouteRector/Correct/correct.php.inc
- tests/Rector/Contrib/Symfony/Controller/RedirectToRouteRector/Correct/correct2.php.inc
- tests/Rector/Contrib/Symfony/Controller/RedirectToRouteRector/Correct/correct3.php.inc
- tests/Rector/Contrib/Symfony/Controller/RedirectToRouteRector/RedirectToRouteRectorTest.php
- tests/Rector/Contrib/Symfony/Controller/RedirectToRouteRector/Wrong/wrong.php.inc
- tests/Rector/Contrib/Symfony/Controller/RedirectToRouteRector/Wrong/wrong2.php.inc
- tests/Rector/Contrib/Symfony/Controller/RedirectToRouteRector/Wrong/wrong3.php.inc
Hey added rector simplifying redirection to route. Helper method redirectToRoute was introduced in SF 2.6.
```php
/**
* Before:
* return $this->redirect($this->generateUrl("homepage"));
* After:
* return $this->redirectToRoute("homepage");
*/
```
> Redirect to route rector

- phpstan.neon
- src/NodeAnalyzer/ChainMethodCallAnalyzer.php
- src/Rector/Contrib/Symfony/Controller/AddFlashRector.php
- src/config/level/symfony/symfony26.yml
- tests/Rector/Contrib/Symfony/Controller/AddFlashRector/AddFlashRectorTest.php
- tests/Rector/Contrib/Symfony/Controller/AddFlashRector/Correct/correct.php.inc
- tests/Rector/Contrib/Symfony/Controller/AddFlashRector/Correct/correct2.php.inc
- tests/Rector/Contrib/Symfony/Controller/AddFlashRector/Wrong/wrong.php.inc
- tests/Rector/Contrib/Symfony/Controller/AddFlashRector/Wrong/wrong2.php.inc
Hey added rector simplifying adding flash messages. Helper method addFlash was introduced in SF 2.6.
```php
/**
* Before:
* $request->getSession()->getFlashBag()->add('success', 'something');
* After:
* $this->addflash('success', 'something');
*/
```
It is not finished, if you could help me out, It will be great. I added tests, config and I need help with finishing rector as i'm stuck with it now. Thx.
> [Symfony] AddFlashRector

- tests/Rector/Contrib/Nette/Utils/MagicMethodRector/MagicMethodRectorTest.php
- tests/Rector/Contrib/Nette/Utils/NetteObjectToSmartTraitRector/NetteObjectToSmartTraitRectorTest.php
> [Tests] Skip tests that require PHP 7.1 or lower

- easy-coding-standard.neon
- src/NodeValueResolver/ConstExprEvaluatorFactory.php
- src/Rector/AbstractPHPUnitRector.php
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertTrueFalseToSpecificMethodRector/Correct/correct.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertTrueFalseToSpecificMethodRector/Wrong/wrong.php.inc
The current logic checks if the TestCase ends with `Test`, but this isn't the safest way to do it. For example:
```php
<?php
class TestingCase extends \PHPUnit\Framework\TestCase {}
class MyTestCase extends TestingCase {}
```
> [PHPUnit] Safe way to check if a class is a Test class

- composer.json
As well this was causing a lot of messages like `"but these conflict with your requirements or minimum-stability"` :)
> Remove minimum stability "beta" as Symplify 4 was realeased

- bin/rector
After update to new Symplify `ConfigFileFinder::provide()` accepts array instead of string as second param.
> Fix default config from string to array

- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertComparisonToSpecificMethodRector.php
Remove the `===`, as `AssertComparisonToSpecificMethodRector` have many comparions
> Generalize AssertComparisonToSpecificMethodRector definition

- src/Rector/Contrib/PHPUnit/SpecificMethod/AssertComparisonToSpecificMethodRector.php
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertComparisonToSpecificMethodRector/Correct/correct.php.inc
- tests/Rector/Contrib/PHPUnit/SpecificMethod/AssertComparisonToSpecificMethodRector/Wrong/wrong.php.inc
Inspired by https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/3540
With this PR, I want to make `AssertComparisonToSpecificMethodRector` smarter, recognizing Yoda Comparisons and check what member has a `string`, number, const (`true`, `false` or `null`), as well variables starting with `exp` (from expected). This will result in more refactoring when passing to other Rectors :smile: 
TODO:
> Make AssertComparisonToSpecificMethodRector smarter

- docs/AllRectorsOverview.md
- src/Rector/Contrib/CodeQuality/UnnecessaryTernaryExpressionRector.php
- tests/Rector/Contrib/CodeQuality/UnnecessaryTernaryExpressionRector/Correct/correct.php.inc
- tests/Rector/Contrib/CodeQuality/UnnecessaryTernaryExpressionRector/UnnecessaryTernaryExpressionRectorTest.php
- tests/Rector/Contrib/CodeQuality/UnnecessaryTernaryExpressionRector/Wrong/wrong.php.inc
- tests/Rector/Contrib/CodeQuality/UnnecessaryTernaryExpressionRector/config.yml
Implements https://github.com/rectorphp/rector/issues/424#issuecomment-383398012
Roadmap:
```diff
-$foo === $bar ? false : true;
+$foo !== $bar;
```
> [CodeQuality] Create UnnecessaryTernaryExpressionRector

- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/TemplateAnnotationVersion3RectorTest.php
- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/TemplateAnnotationVersion5RectorTest.php
- packages/Symfony/tests/Rector/FrameworkBundle/GetToConstructorInjectionRector/GetToConstructorInjectionRectorTest.php
- src/Testing/PHPUnit/AbstractRectorTestCase.php
In total 98 containers are created during tests.
50 of them are dulicated - a nw containe is created, even if it was already created before with the same config.
**This reduces the number of created containers from 98 to 50.**
> Improve Test Performance

- .gitignore
- .travis.yml
- README.md
- bin/container.php
- composer.json
- packages/NodeTypeResolver/.travis.yml
- packages/NodeTypeResolver/composer.json
- packages/NodeTypeResolver/src/config/config.yml
- packages/Silverstripe/src/Rector/DefineConstantToStaticCallRector.php
- packages/Symfony/src/Rector/Controller/AddFlashRector.php
- packages/Utils/src/FilesystemTweaker.php
- packages/YamlRector/tests/AbstractYamlRectorTest.php
- phpstan.neon
- src/Autoloading/AdditionalAutoloader.php
- src/Console/Command/ProcessCommand.php
- src/DependencyInjection/ContainerFactory.php
- src/DependencyInjection/RectorKernel.php
- src/FileSystem/FilesFinder.php
- src/Testing/PHPUnit/AbstractRectorTestCase.php
- tests/AbstractConfigurableContainerAwareTestCase.php
Related #609 
Closes #613 
This allows to use fnmatch `*` for directories in path to process:
```
bin/rector process "src/Symfony/Component/*/Tests" --level symfony40 --dry-run
```
> FilesFinder - allow searching in asterisk

- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/AnnotatedPropertyInjectToConstructorInjectionRectorTest.php
- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Correct/correct2.php.inc
- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Correct/correct3.php.inc
- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Correct/correct4.php.inc
- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Correct/correct5.php.inc
- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Correct/correct6.php.inc
- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Source/SomeInterface.php
- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Source/SomeParent.php
- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Source/SomeProduct.php
- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Source/SomeProductWithInterface.php
- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Source/SomeProductWithParent.php
- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Source/SomeProductWithTrait.php
- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Source/SomeTrait.php
- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Wrong/wrong2.php.inc
- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Wrong/wrong3.php.inc
- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Wrong/wrong4.php.inc
- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Wrong/wrong5.php.inc
- tests/Rector/Architecture/DependencyInjection/AnnotatedPropertyInjectToConstructorInjectionRector/Wrong/wrong6.php.inc
Hey there,
First of all, thanks for the amazing project! It's been such a timesaver in upgrading some legacy code which doing manually would have been soul destroying.
I've been trying to use `AnnotatedPropertyInjectToConstructorInjectionRector` to clean up some uses of JMS DI in one of our projects. 
I've encountered a few issues which require manual cleanup after rector has run.
Hopefully these tests highlight the issues I'm facing, but if not, just shout.
I've not had time to look to see if I can fix these myself yet, but I'd imagine I wouldn't be able to do so quickly, so I just thought i get the ball rolling with some 'failing' tests.
Cheers!
> AnnotatedPropertyInjectToConstructorInjectionRector issues

- config/level/guzzle/guzzle50.yml
Unexpected characters (: 'getPath']) at line 18 (near "'GuzzleHttp\\get_path': ['GuzzleHttp\\Utils': 'getPath']").
> Fix guzzle50.yml syntax error

- packages/PHPUnit/src/Rector/SpecificMethod/AssertCompareToSpecificMethodRector.php
- packages/PHPUnit/tests/Rector/SpecificMethod/AssertCompareToSpecificMethodRector/Correct/correct.php.inc
- packages/PHPUnit/tests/Rector/SpecificMethod/AssertCompareToSpecificMethodRector/Wrong/wrong.php.inc
When a property, method or variable has one of the names to be
refactored, e.g. `count`, it gets wrong refactored
> [PHPUnit] Fix AssertCompareToSpecificMethodRector false positives

- config/level/php/php70.yml
For issue #745 : 
The rector name is actually for a method, not a function.
> use correct rector name

- ecs.yml
- packages/CodeQuality/src/Rector/Identical/SimplifyConditionsRector.php
- packages/CodeQuality/src/Rector/If_/SimplifyIfReturnBoolRector.php
- packages/CodeQuality/tests/Rector/If_/SimplifyIfReturnBoolRector/Correct/correct7.php.inc
- packages/CodeQuality/tests/Rector/If_/SimplifyIfReturnBoolRector/SimplifyIfReturnBoolRectorTest.php
- packages/CodeQuality/tests/Rector/If_/SimplifyIfReturnBoolRector/Wrong/wrong7.php.inc
- packages/Jms/src/Rector/Property/JmsInjectAnnotationRector.php
- src/Application/AppliedRectorCollector.php
- src/Application/Error.php
- src/Application/ErrorCollector.php
- src/Console/Command/ProcessCommand.php
- src/Console/Output/ProcessCommandReporter.php
- src/PhpParser/Node/AssignAndBinaryMap.php
- src/Rector/AbstractRector.php
- src/Reporting/FileDiff.php
```
[ERROR] Could not process "test.php" file, due to:   
"Class name must be a valid object or a string".                                                               
```
```
[ERROR] Could not process "test.php" file by "Rector\CodeQuality\Rector\Identical\SimplifyConditionsRector", due to:   
"Class name must be a valid object or a string".                                                               
```
---
```
--debug / -vvv
```
```
[ERROR] Message
```
Full stack trace
---
> show Rector class on caused error

- packages/PHPUnit/src/Rector/SpecificMethod/AssertCompareToSpecificMethodRector.php
- packages/PHPUnit/tests/Rector/SpecificMethod/AssertCompareToSpecificMethodRector/Correct/correct.php.inc
- packages/PHPUnit/tests/Rector/SpecificMethod/AssertCompareToSpecificMethodRector/Wrong/wrong.php.inc
[Since PHPUnit 4](https://github.com/sebastianbergmann/phpunit/blob/4.0/src/Framework/Constraint/Count.php#L105) this is supported.
[Example of usage](https://github.com/aws/aws-sdk-php/pull/1435/files#diff-fe0d42e9e0bbedd4b5770a1c7f74a8a8L379).
> [PHPUnit] Convert iterator_count into assertCount

- src/Console/Command/ProcessCommand.php
- src/PhpParser/Node/Commander/NodeAddingCommander.php
- src/PhpParser/Node/Commander/NodeRemovingCommander.php
- src/PhpParser/Node/Commander/PropertyAddingCommander.php
- src/PhpParser/NodeTraverser/CallableNodeTraverser.php
> Return error code on diff with dry-run option

- README.md
- docs/AllRectorsOverview.md
- packages/Php/src/Rector/MethodCall/PreferThisOrSelfMethodCallRector.php
- packages/Php/tests/Rector/MethodCall/PreferThisOrSelfMethodCallRector/Fixture/to_self.php.inc
- packages/Php/tests/Rector/MethodCall/PreferThisOrSelfMethodCallRector/Fixture/to_this.php.inc
- packages/Php/tests/Rector/MethodCall/PreferThisOrSelfMethodCallRector/PreferThisOrSelfMethodCallRectorTest.php
- packages/Php/tests/Rector/MethodCall/PreferThisOrSelfMethodCallRector/Source/AbstractTestCase.php
- packages/Php/tests/Rector/MethodCall/PreferThisOrSelfMethodCallRector/Source/BeLocalClass.php
Closes #863
```yaml
services:
Rector\Php\Rector\MethodCall\PreferThisOrSelfMethodCallRector:
PHPUnit\Framework\TestCase: 'this' # or 'self'
```
```diff
final class MyTestCase extends PHPUnit\Framework\TestCase
{
public function test()
{
-        self::assertNull();
+        $this->assertNull();
}
}
```
> [PHP] Add PreferThisOrSelfMethodCallRector

- README.md
- packages/ContributorTools/src/Command/GenerateDocsCommand.php
- src/Console/Command/LevelsCommand.php
- src/Console/Command/ProcessCommand.php
- src/DependencyInjection/CompilerPass/RemoveExcludedRectorsCompilerPass.php
- src/DependencyInjection/RectorKernel.php
- src/config/config.yml
- src/config/external-services.yml
Do you want to use whole set, except that one rule? Exclude it:
```yaml
parameters:
exclude_rectors:
- 'Rector\CodeQuality\Rector\If_\SimplifyIfReturnBoolRector'
```
> Add "exclude_rectors" parameters to skip selected rules

- config/level/php/php74.yml
- docs/AllRectorsOverview.md
- packages/Php/src/Rector/Assign/NullCoalescingOperatorRector.php
- packages/Php/tests/Rector/Assign/NullCoalescingOperatorRector/Fixture/fixture.php.inc
- packages/Php/tests/Rector/Assign/NullCoalescingOperatorRector/NullCoalescingOperatorRectorTest.php
- src/PhpParser/Printer/BetterStandardPrinter.php
Closes #974, `??=` is now part of PHP 7.4
Reverts https://github.com/php/php-src/pull/3747
> [Php] Add NullCoalescingOperatorRector

- docs/HowItWorks.md
Fix typo in `--config` option described in documentation.
> Fix docs typo

- src/Rector/Architecture/Factory/NewObjectToFactoryCreateRector.php
- tests/Rector/Architecture/Factory/NewObjectToFactoryCreateRector/Fixture/fixture.php.inc
- tests/Rector/Architecture/Factory/NewObjectToFactoryCreateRector/Fixture/fixture2.php.inc
- tests/Rector/Architecture/Factory/NewObjectToFactoryCreateRector/NewObjectToFactoryCreateRectorTest.php
- tests/Rector/Architecture/Factory/NewObjectToFactoryCreateRector/Source/MyClass.php
- tests/Rector/Architecture/Factory/NewObjectToFactoryCreateRector/Source/MyClassFactory.php
- tests/Rector/Architecture/Factory/NewObjectToFactoryCreateRector/config.yml
> NewObjectToFactoryCreateRector

- ecs.yml
- src/Rector/TypeAnalyzerTrait.php
- tests/Rector/MethodCall/MethodNameReplacerRector/Fixture/nette_to_symfony_presenter.php.inc
- tests/Rector/MethodCall/MethodNameReplacerRector/MethodNameReplacerRectorTest.php
> make MethodNameReplacerRector acccept fnmatch as well

- composer.json
- ecs.yml
- packages/CodeQuality/tests/Rector/If_/SimplifyIfReturnBoolRector/Fixture/fixture8.php.inc
- packages/Doctrine/src/Rector/AliasToClassRector.php
- packages/Doctrine/tests/Rector/AliasToClassRector/AliasToClassRectorTest.php
- packages/Doctrine/tests/Rector/AliasToClassRector/Fixture/fixture.php.inc
- packages/Doctrine/tests/Rector/AliasToClassRector/Source/DoctrineEntityManager.php
- packages/NetteToSymfony/src/Rector/MethodCall/FromHttpRequestGetHeaderToHeadersGetRector.php
- packages/NetteToSymfony/src/Rector/MethodCall/FromRequestGetParameterToAttributesGetRector.php
- packages/NetteToSymfony/tests/Rector/MethodCall/FromHttpRequestGetHeaderToHeadersGetRector/Fixture/fixture.php.inc
- packages/NetteToSymfony/tests/Rector/MethodCall/FromHttpRequestGetHeaderToHeadersGetRector/Fixture/missing_argument.php.inc
- packages/NetteToSymfony/tests/Rector/MethodCall/FromHttpRequestGetHeaderToHeadersGetRector/FromHttpRequestGetHeaderToHeadersGetRectorTest.php
- packages/NetteToSymfony/tests/Rector/MethodCall/FromHttpRequestGetHeaderToHeadersGetRector/Source/IrrelevantRequest.php
- packages/NetteToSymfony/tests/Rector/MethodCall/FromHttpRequestGetHeaderToHeadersGetRector/Source/NetteHttpRequest.php
- packages/NetteToSymfony/tests/Rector/MethodCall/FromRequestGetParameterToAttributesGetRector/Fixture/fixture.php.inc
- packages/NetteToSymfony/tests/Rector/MethodCall/FromRequestGetParameterToAttributesGetRector/FromRequestGetParameterToAttributesGetRectorTest.php
- packages/NetteToSymfony/tests/Rector/MethodCall/FromRequestGetParameterToAttributesGetRector/Source/NetteRequest.php
- packages/Sylius/src/Rector/Review/ReplaceCreateMethodWithoutReviewerRector.php
- packages/Sylius/tests/Rector/Review/Fixture/fixture.php.inc
- packages/Sylius/tests/Rector/Review/Fixture/fixture2.php.inc
- packages/Sylius/tests/Rector/Review/ReplaceCreateMethodWithoutReviewerRectorTest.php
- packages/Sylius/tests/Rector/Review/Source/ReviewFactoryInterface.php
- phpstan.neon
- tests/AbstractContainerAwareTestCase.php
```diff
final class SomeController
{
public static function someAction(NetteRequest $request)
{
-        $value = $request->getParameter('abz');
+        $value = $request->attributes->get('abz');
}
}
```
```diff
final class SomeController
{
private $httpRequest;
public function someAction(Request $request)
{
-        $header = $this->httpRequest->getHeader('x');
+        $header = $request->headers->get('x');
}
}
```
> Add FromRequestGetParameterToAttributesGetRector

- packages/Php/src/Rector/Assign/NullCoalescingOperatorRector.php
- src/PhpParser/Printer/BetterStandardPrinter.php
Custom token `??=` emulation is no more needed.
I've added support to php-parser in https://github.com/nikic/PHP-Parser/pull/575
> Use official coala assign

- packages/Php/src/Rector/ConstFetch/SensitiveConstantNameRector.php
case-sensitivity test of `defined()`: https://3v4l.org/DA23r
> SensitiveConstantNameRector: ignore existing contants

- src/Console/Command/ShowCommand.php
If you ever get lost and you want to know, what rector services are loaded, just use:
```bash
vendor/bin/rector show
```
<br><br>
> Add Show command to list loaded rectors

- config/level/code-quality/code-quality.yaml
- packages/CodeQuality/src/Rector/Ternary/SimplifyDuplicatedTernaryRector.php
- packages/CodeQuality/tests/Rector/Ternary/SimplifyDuplicatedTernaryRector/Fixture/fixture.php.inc
- packages/CodeQuality/tests/Rector/Ternary/SimplifyDuplicatedTernaryRector/SimplifyDuplicatedTernaryRectorTest.php
> [CodeQuality] Add SimplifyDuplicatedTernaryRector

- src/PhpParser/Node/Value/ValueResolver.php
Rector throws an exception when it has to inspect a constant with an integer value. See: #1127.
Signed-off-by: Kevin R <22906111+cgkkevinr@users.noreply.github.com>
> Change type hint for resolveClassConstFetch to mixed

- config/level/laravel/laravel-static-to-injection.yaml
- packages/Laravel/src/Rector/StaticCall/RequestStaticValidateToInjectRector.php
- packages/Laravel/tests/Rector/StaticCall/RequestStaticValidateToInjectRector/Fixture/fixture.php.inc
- packages/Laravel/tests/Rector/StaticCall/RequestStaticValidateToInjectRector/RequestStaticValidateToInjectRectorTest.php
- packages/NetteToSymfony/src/Rector/MethodCall/FromHttpRequestGetHeaderToHeadersGetRector.php
- packages/NodeTypeResolver/src/NodeTypeResolver.php
- packages/Php/tests/Rector/FuncCall/RegexDashEscapeRector/Fixture/method_call.php.inc
- src/PhpParser/Node/Manipulator/ClassMethodManipulator.php
- src/Rector/TypeAnalyzerTrait.php
Ref #1138 ,
ref #290
```diff
use Illuminate\Http\Request;
{
-     public function store()
+     public function store(\Illuminate\Http\Request $request)
{
-         $validatedData = Request::validate(['some_attribute' => 'required']);
+         $validatedData = $request->validate(['some_attribute' => 'required']);
}
}
```
> [Laravel] Add RequestStaticValidateToInjectRector

- src/PhpParser/Node/Manipulator/PropertyFetchManipulator.php
- src/Rector/MagicDisclosure/GetAndSetToMethodCallRector.php
- tests/Rector/MagicDisclosure/GetAndSetToMethodCallRector/Fixture/fixture3.php.inc
- tests/Rector/MagicDisclosure/GetAndSetToMethodCallRector/GetAndSetToMethodCallRectorTest.php
**Before the Fix**
Before
```php
class Enlight_View_Default
{
protected $engine;
public function __construct($engine)
{
$this->engine = $engine;
}
}
```
After
```php
class Enlight_View_Default
{
protected $engine;
public function __construct($engine)
{
$this->addService('engine', $engine);
}
}
```
> Fix GetAndSetToMethodCallRector in class itself

- config/level/laravel/laravel-static-to-injection.yaml
- ecs.yml
- packages/Laravel/src/Rector/FuncCall/HelperFunctionToConstructorInjectionRector.php
- packages/Laravel/tests/Rector/FuncCall/HelperFunctionToConstructorInjectionRector/Fixture/back.php.inc
- packages/Laravel/tests/Rector/FuncCall/HelperFunctionToConstructorInjectionRector/Fixture/broadcast.php.inc
- packages/Laravel/tests/Rector/FuncCall/HelperFunctionToConstructorInjectionRector/Fixture/route.php.inc
- packages/Laravel/tests/Rector/FuncCall/HelperFunctionToConstructorInjectionRector/Fixture/session.php.inc
- packages/Laravel/tests/Rector/FuncCall/HelperFunctionToConstructorInjectionRector/Fixture/view.php.inc
- packages/Laravel/tests/Rector/FuncCall/HelperFunctionToConstructorInjectionRector/HelperFunctionToConstructorInjectionRectorTest.php
Closes #1171
Instead of function helpers, use constructor injection of specific services
```php
class SomeController
{
public function action()
{
$template = view('template.blade');
$viewFactory = view();
}
}
```
```php
class SomeController
{
/**
* @var \Illuminate\Contracts\View\Factory
*/
private $viewFactory;
public function __construct(\Illuminate\Contracts\View\Factory $viewFactory)
{
$this->viewFactory = $viewFactory;
}
public function action()
{
$template = $this->viewFactory->make('template.blade');
$viewFactory = $this->viewFactory;
}
}
```
> [Laravel] Add HelperFunctionToConstructorInjectionRector

- packages/Laravel/src/Rector/StaticCall/RequestStaticValidateToInjectRector.php
- packages/Laravel/tests/Rector/StaticCall/RequestStaticValidateToInjectRector/Fixture/function.php.inc
- packages/Laravel/tests/Rector/StaticCall/RequestStaticValidateToInjectRector/Fixture/function2.php.inc
- packages/Laravel/tests/Rector/StaticCall/RequestStaticValidateToInjectRector/RequestStaticValidateToInjectRectorTest.php
```php
<?php
namespace App\Http\Controllers;
class WelcomeController extends Controller
{
public function index()
{
return view('welcome', [
'foo' => request()->get('foo'),
]);
}
}
```
```php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
class WelcomeController extends Controller
{
public function index(Request $request)
{
return view('welcome', [
'foo' => $request->get('foo'),
]);
}
}
```
cc @azdanov :)
> [Laravel] Add request() to injection

- composer.json
This pins the PHPStan version to 0.11.2 since the newer version breaks tests.
> Pin PHPStan version to 0.11.2

- Dockerfile
- README.md
This PR should make the image smaller, have a faster build time with `hirak/prestissimo` and simplify usage by exposing `bin/rector` directly to users.
Tried on my machine, seems to work. Need a little more testing.
```bash
docker run -t rector process packages/Symfony/ --level symfony40 --dry-run
Rector dev-master@d12d6ea
249/249 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
1 file with changes
```
Closes: #1181
> [Docker]: Optimize image

- packages/PHPUnit/src/Rector/MethodCall/SpecificAssertContainsRector.php
`assertIterableContains`/`assertIterableNotContains` were never implemented in phpunit.
https://github.com/rectorphp/rector/issues/1185#issuecomment-471768214
> remove incorrect docs

- config/level/phpunit/phpunit80.yaml
- packages/PHPUnit/src/Rector/MethodCall/ReplaceAssertArraySubsetRector.php
- packages/PHPUnit/tests/Rector/MethodCall/ReplaceAssertArraySubsetRector/Fixture/fixture.php.inc
- packages/PHPUnit/tests/Rector/MethodCall/ReplaceAssertArraySubsetRector/Fixture/issue_2069.php.inc
- packages/PHPUnit/tests/Rector/MethodCall/ReplaceAssertArraySubsetRector/Fixture/issue_2237.php.inc
- packages/PHPUnit/tests/Rector/MethodCall/ReplaceAssertArraySubsetRector/Fixture/variable.php.inc
- packages/PHPUnit/tests/Rector/MethodCall/ReplaceAssertArraySubsetRector/ReplaceAssertArraySubsetRectorTest.php
- phpstan.neon
- src/PhpParser/Node/Value/ValueResolver.php
- src/Rector/AbstractPHPUnitRector.php
Closes #1025 
Ref https://github.com/sebastianbergmann/phpunit/issues/3495
As this can have many different uses out in the wild and not all can be converted manually, this needs thorought testing.
0. Install local rector dev
```
composer require rector/rector:@dev --dev
```
1. Create `rector.yaml` local config
```yaml
services:
Rector\PHPUnit\Rector\MethodCall\ReplaceAssertArraySubsetRector: ~
```
2. Run Rector
```
vendor/bin/rector process src
```
3. Report anomalies
> [PHPUnit] Add ReplaceAssertArraySubsetRector

- packages/DeadCode/src/Rector/ClassMethod/RemoveEmptyClassMethodRector.php
- packages/DeadCode/tests/Rector/ClassMethod/RemoveEmptyClassMethodRector/Fixture/keep_abstract_method.php.inc
- packages/DeadCode/tests/Rector/ClassMethod/RemoveEmptyClassMethodRector/RemoveEmptyClassMethodRectorTest.php
found when running `dead-code` on my project.
> add failing test for RemoveEmptyClassMethodRectorTest

- composer.json
- config/level/shopware/shopware56.yaml
- packages/Shopware/src/Rector/MethodCall/ReplaceEnlightResponseWithSymfonyResponseRector.php
- packages/Shopware/tests/Rector/MethodCall/ReplaceEnlightResponseWithSymfonyResponseRector/Fixture/fixture.php.inc
- packages/Shopware/tests/Rector/MethodCall/ReplaceEnlightResponseWithSymfonyResponseRector/ReplaceEnlightResponseWithSymfonyResponseRectorTest.php
We are switching in Shopware 5.6 Request and Response objects to HttpFoundation. After this one follows a Rector for Request object :)
> Add rector to transform EnlightResponse to SymfonyResponse

- packages/DeadCode/src/Rector/ClassMethod/RemoveUnusedPrivateMethodRector.php
- packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/private_constructor.php.inc
- packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/RemoveUnusedPrivateMethodRectorTest.php
Here's a bug I found when running `dead-code` level on my project
> add failing test for RemoveUnusedPrivateMethodRector

- config/level/phpunit/phpunit90.yaml
- packages/PHPUnit/src/Rector/Class_/TestListenerToHooksRector.php
- packages/PHPUnit/tests/Rector/Class_/TestListenerToHooksRector/Fixture/before_list_hook.php.inc
- packages/PHPUnit/tests/Rector/Class_/TestListenerToHooksRector/Fixture/clear_it_all.php.inc
- packages/PHPUnit/tests/Rector/Class_/TestListenerToHooksRector/TestListenerToHooksRectorTest.php
Closes #1266 
Migration path for https://github.com/sebastianbergmann/phpunit/issues/3389
```bash
composer require rector/rector --dev
vendor/bin/rector process tests --level phpunit90
```
```diff
<?php
namespace App\Tests;
-use PHPUnit\Framework\TestListener;
-
-final class BeforeListHook implements TestListener
+final class BeforeListHook implements \PHPUnit\Runner\BeforeTestHook, \PHPUnit\Runner\AfterTestHook
{
-    public function addError(Test $test, \Throwable $t, float $time): void
-    {
-    }
-
-    public function addWarning(Test $test, Warning $e, float $time): void
-    {
-    }
-
-    public function addFailure(Test $test, AssertionFailedError $e, float $time): void
-    {
-    }
-
-    public function addIncompleteTest(Test $test, \Throwable $t, float $time): void
-    {
- …
```
> [PHPUnit 9.0] Add TestListenerToHooksRector

- config/level/code-quality/code-quality.yaml
- docs/AllRectorsOverview.md
- docs/NodesOverview.md
- packages/CodeQuality/src/Rector/FuncCall/SimplifyRegexPatternRector.php
- packages/CodeQuality/tests/Rector/FuncCall/SimplifyRegexPatternRector/Fixture/fixture.php.inc
- packages/CodeQuality/tests/Rector/FuncCall/SimplifyRegexPatternRector/Fixture/pattern_in_constant.php.inc
- packages/CodeQuality/tests/Rector/FuncCall/SimplifyRegexPatternRector/SimplifyRegexPatternRectorTest.php
- packages/PHPUnit/tests/Rector/Class_/TestListenerToHooksRector/Fixture/clear_it_all.php.inc
- packages/Php/src/Rector/FuncCall/RegexDashEscapeRector.php
- packages/Php/tests/Rector/FuncCall/RegexDashEscapeRector/RegexDashEscapeRectorTest.php
- src/Php/Regex/RegexPatternArgumentManipulator.php
Use `\d` and `\w` when it shortens the expression
```diff
-preg_match('#[0-9]+#', $value);
+preg_match('#\d+#', $value);
```
```diff
-Nette\Utils\Strings::match($value,'#[A-Za-z0-9_]+#');
+Nette\Utils\Strings::match($value,'#\w+#');
```
> [CodeQuality] Simplify Regex patterns

- README.md
- composer.json
- config/level/nette/nette-utils-code-quality.yaml
- packages/Nette/src/Rector/FuncCall/SubstrStrlenFunctionToNetteUtilsStringsRector.php
- packages/Nette/src/Rector/Identical/EndsWithFunctionToNetteUtilsStringsRector.php
- packages/Nette/src/Rector/Identical/StartsWithFunctionToNetteUtilsStringsRector.php
- packages/Nette/src/Rector/NotIdentical/StrposToStringsContainsRector.php
- packages/Nette/tests/Rector/FuncCall/SubstrStrlenFunctionToNetteUtilsStringsRector/Fixture/strlen.php.inc
- packages/Nette/tests/Rector/FuncCall/SubstrStrlenFunctionToNetteUtilsStringsRector/Fixture/substr.php.inc
- packages/Nette/tests/Rector/FuncCall/SubstrStrlenFunctionToNetteUtilsStringsRector/SubstrStrlenFunctionToNetteUtilsStringsRectorTest.php
- packages/Nette/tests/Rector/Identical/EndsWithFunctionToNetteUtilsStringsRector/EndsWithFunctionToNetteUtilsStringsRectorTest.php
- packages/Nette/tests/Rector/Identical/EndsWithFunctionToNetteUtilsStringsRector/Fixture/fixture.php.inc
- packages/Nette/tests/Rector/Identical/StartsWithFunctionToNetteUtilsStringsRector/Fixture/fixture.php.inc
- packages/Nette/tests/Rector/Identical/StartsWithFunctionToNetteUtilsStringsRector/StartsWithFunctionToNetteUtilsStringsRectorTest.php
- packages/Nette/tests/Rector/NotIdentical/StrposToStringsContainsRector/Fixture/fixture.php.inc
- packages/Nette/tests/Rector/NotIdentical/StrposToStringsContainsRector/Fixture/keep.php.inc
- packages/Nette/tests/Rector/NotIdentical/StrposToStringsContainsRector/StrposToStringsContainsRectorTest.php
- packages/NetteToSymfony/src/Rector/Class_/NetteControlToSymfonyControllerRector.php
- packages/NetteToSymfony/src/Rector/Class_/NetteFormToSymfonyFormRector.php
- packages/Php/src/Rector/MethodCall/PreferThisOrSelfMethodCallRector.php
- packages/Php/src/Rector/MethodCall/ThisCallOnStaticMethodToStaticCallRector.php
- packages/PhpSpecToPHPUnit/src/Rector/MethodCall/PhpSpecMocksToPHPUnitMocksRector.php
- packages/PhpSpecToPHPUnit/src/Rector/MethodCall/PhpSpecPromisesToPHPUnitAssertRector.php
- packages/Silverstripe/src/Rector/ConstantToStaticCallRector.php
- packages/Silverstripe/src/Rector/DefineConstantToStaticCallRector.php
- phpstan.neon
- src/Rector/Function_/FunctionToStaticCallRector.php
- src/Rector/New_/NewToStaticCallRector.php
- src/Rector/NodeFactoryTrait.php
Closes #1276 
See [Hidden Gems of PHP Packages: Nette\Utils](https://www.tomasvotruba.cz/blog/2018/07/30/hidden-gems-of-php-packages-nette-utils/)
```diff
-file_get_contents($file);
+Nette\Utils\FileSystem::read($file);
-json_encode($json);
+Nette\Utils\Json::encode($json);
-strpos($content, 'hi') !=== false
+Nette\Utils\Strings::contains($content, 'hi);
```
> [Nette] Add nette-utils-code-quality level

- config/level/phpunit/phpunit-code-quality.yaml
- packages/PHPUnit/src/Rector/MethodCall/RemoveExpectAnyFromMockRector.php
- packages/PHPUnit/tests/Rector/MethodCall/RemoveExpectAnyFromMockRector/Fixture/fixture.php.inc
- packages/PHPUnit/tests/Rector/MethodCall/RemoveExpectAnyFromMockRector/Fixture/keep.php.inc
- packages/PHPUnit/tests/Rector/MethodCall/RemoveExpectAnyFromMockRector/RemoveExpectAnyFromMockRectorTest.php
Closes #1298
```diff
use PHPUnit\Framework\TestCase;
class SomeClass extends TestCase
{
public function test()
{
$translator = $this->getMock('SomeClass');
-       $translator->expects($this->any())
+       $translator
->method('trans')
->willReturn('translated max {{ max }}!');
}
}
```
> [PHPUnit] Add RemoveExpectAnyFromMockRector

- CHANGELOG.md
- changelog-linker.yaml
- composer.json
> Add Changelog

- config/level/cakephp/cakephp37.yaml
Sorry, I made a mistake! 🙇 
In #1252, I added incorrect service name.
Lacking  of `~Rector` suffix, `--level  cakephp37` is  interrupted.
> [CakePHP]FIx rule for cakephp37

- composer.json
- src/NodeContainer/ParsedNodesByType.php
I wanted to test this tool, but I require Nette 3.0. 
By the way, Is it normal that your PHPUnit coverage tests require more than 25 minutes on travis ci?
> allow Nette 3.0

- packages/DeadCode/src/Rector/ClassMethod/RemoveUnusedParameterRector.php
- packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedParameterRector/Fixture/keep_magic_methods_param.php.inc
- packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedParameterRector/RemoveUnusedParameterRectorTest.php
> [DeadCode] Skip magic methods in RemoveUnusedParameterRector

- composer.json
- config/level/coding-style/coding-style.yaml
- packages/CodingStyle/src/Rector/String_/SplitStringClassConstantToClassConstFetchRector.php
- packages/CodingStyle/tests/Rector/String_/SplitStringClassConstantToClassConstFetchRector/Fixture/fixture.php.inc
- packages/CodingStyle/tests/Rector/String_/SplitStringClassConstantToClassConstFetchRector/SplitStringClassConstantToClassConstFetchRectorTest.php
```diff
{
const HI = true;
}
class AnotherClass
{
public function get()
{
-       return 'SomeClass::HI';
+       return SomeClass::class . '::HI';
}
}
> [CodingStyle] Add SplitStringClassConstantToClassConstFetchRector

- config/level/solid/solid.yaml
> Add PrivatizeLocalClassConstantRector to SOLID

- packages/Laravel/src/Rector/StaticCall/MinutesToSecondsInCacheRector.php
- packages/Laravel/tests/Rector/StaticCall/MinutesToSecondsInCacheRector/Fixture/skip_call.php.inc
- packages/Laravel/tests/Rector/StaticCall/MinutesToSecondsInCacheRector/MinutesToSecondsInCacheRectorTest.php
- packages/RemovingStatic/src/Rector/Class_/PassFactoryToUniqueObjectRector.php
- packages/RemovingStatic/src/UniqueObjectOrServiceDetector.php
> [Laravel] Fix MinutesToSecondsInCacheRector DateTimeInterface argument

- docs/AllRectorsOverview.md
- docs/NodesOverview.md
- packages/CodingStyle/src/Rector/Namespace_/ImportFullyQualifiedNamesRector.php
- packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/import_function.php.inc
- packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/import_function_no_class.php.inc
- packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/ImportFullyQualifiedNamesRectorTest.php
> Add function support to ImportFullyQualifiedNamesRector

- packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedParameterRector/Fixture/anonymous_classes.php.inc
- packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedParameterRector/RemoveUnusedParameterRectorTest.php
- packages/NodeTypeResolver/src/NodeVisitor/ClassAndMethodNodeVisitor.php
I found this while running the dead code level on a code base. I don't have a fix for it yet, but thought I'd open a PR so long with a failing test case while I investigate further (and maybe get some pointers to the right solution)
When instantiating an anonymous class that implements an interface, and the methods in the class is empty, then all the parameters in the method signature is removed. The signature that comes from the interface isn't respected. When running the test case in the PR, I get the following failure:
```diff
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
{
$class = new class implements Foo
{
-                public function bar($value1)
+                public function bar()
{
}
};\n
```
but I expect the test to pass, since the function …
> [DeadCode] Anonymous class implementing an interface doesn't respect interface signature

- composer.json
- config/level/dead-code/dead-code.yaml
- packages/DeadCode/src/Rector/MethodCall/RemoveDefaultArgumentValueRector.php
- packages/DeadCode/tests/Rector/MethodCall/RemoveDefaultArgumentValueRector/Fixture/fixture.php.inc
- packages/DeadCode/tests/Rector/MethodCall/RemoveDefaultArgumentValueRector/Fixture/function.php.inc
- packages/DeadCode/tests/Rector/MethodCall/RemoveDefaultArgumentValueRector/Fixture/skip_previous_order.php.inc
- packages/DeadCode/tests/Rector/MethodCall/RemoveDefaultArgumentValueRector/Fixture/system_function.php.inc
- packages/DeadCode/tests/Rector/MethodCall/RemoveDefaultArgumentValueRector/Fixture/user_vendor_function.php.inc
- packages/DeadCode/tests/Rector/MethodCall/RemoveDefaultArgumentValueRector/RemoveDefaultArgumentValueRectorTest.php
- packages/DeadCode/tests/Rector/MethodCall/RemoveDefaultArgumentValueRector/Source/UserDefined.php
- packages/NodeTypeResolver/src/NodeVisitor/ClassAndMethodNodeVisitor.php
- src/PhpParser/Node/Value/ValueResolver.php
- src/Reflection/FunctionReflectionResolver.php
> [DeadCode] Add RemoveDefaultArgumentValueRector

- src/PhpParser/Printer/FormatPerservingPrinter.php
- tests/PhpParser/Printer/FormatPerservingPrinterTest.php
The change of permissions is not explicitely requested by the user
and is not shown in the dry-run. It makes Rector harder to use when
the sources of a project has some executable scripts.
> Preserve file permissions when updating a file

- packages/CodingStyle/src/Naming/ClassNaming.php
- src/Rector/Class_/RenameClassRector.php
- src/Testing/PHPUnit/AbstractRectorTestCase.php
- tests/Rector/Class_/RenameClassRector/Fixture/rename_class.php.inc
- tests/Rector/Class_/RenameClassRector/Fixture/rename_class_to_class_without_namespace.php.inc
- tests/Rector/Class_/RenameClassRector/Fixture/rename_class_without_namespace.php.inc
- tests/Rector/Class_/RenameClassRector/Fixture/rename_class_without_namespace_to_class_without_namespace.php.inc
- tests/Rector/Class_/RenameClassRector/Fixture/rename_interface.php.inc
- tests/Rector/Class_/RenameClassRector/Fixture/rename_trait.php.inc
- tests/Rector/Class_/RenameClassRector/RenameClassRectorTest.php
> Add support to rename classes and it's namespace

- packages/CodingStyle/src/Rector/Namespace_/ImportFullyQualifiedNamesRector.php
> [ImportFullyQualifiedNamesRector] Allow to opt-out from doc block modification

- composer.json
- config/level/php/php74.yaml
- packages/ContributorTools/src/Command/DumpNodesCommand.php
- packages/Php/src/Rector/Closure/ClosureToArrowFunctionRector.php
- packages/Php/tests/Rector/Closure/ClosureToArrowFunctionRector/ClosureToArrowFunctionRectorTest.php
- packages/Php/tests/Rector/Closure/ClosureToArrowFunctionRector/Fixture/fixture.php.inc
- packages/Php/tests/Rector/Closure/ClosureToArrowFunctionRector/Fixture/referenced_but_not_used.php.inc
- packages/Php/tests/Rector/Closure/ClosureToArrowFunctionRector/Fixture/skip_no_return.php.inc
- packages/Php/tests/Rector/Closure/ClosureToArrowFunctionRector/Fixture/skip_referenced_value.php.inc
- packages/Php/tests/Rector/Function_/ReservedFnFunctionRector/ReservedFnFunctionRectorTest.php
- packages/TypeDeclaration/src/Rector/Closure/AddClosureReturnTypeRector.php
- rector.yaml
Closes #1405
```diff
-return array_filter($meetups, function (Meetup $meetups) {
+return array_filter($meetups, fn(Meetup $meetup) => is_object($meetup));
-   return is_object($meetup);
-);
```
> [PHP 7.4] Add ClosureToArrowFunctionRector

- config/services.yaml
- packages/NodeTypeResolver/src/NodeTypeResolver.php
- packages/NodeTypeResolver/src/PHPStan/Scope/NodeScopeResolver.php
- packages/NodeTypeResolver/src/PHPStan/Scope/Stub/ClassReflectionForUnusedTrait.php
- packages/Php/src/Rector/FuncCall/StringifyStrNeedlesRector.php
- packages/Php/tests/Rector/FuncCall/StringifyStrNeedlesRector/Fixture/trait.php.inc
- packages/Php/tests/Rector/FuncCall/StringifyStrNeedlesRector/StringifyStrNeedlesRectorTest.php
> Add trait analysis without class dependency

- composer.json
- config/level/php/php74.yaml
- packages/Php/src/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector.php
- packages/Php/tests/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/ArraySpreadInsteadOfArrayMergeRectorTest.php
- packages/Php/tests/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/Fixture/fixture.php.inc
- packages/Php/tests/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/Fixture/iterator_to_array.php.inc
- packages/Php/tests/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/Fixture/simple_array_merge.php.inc
- phpstan.neon
- src/Rector/Psr4/MultipleClassFileToPsr4ClassesRector.php
- tests/Rector/Psr4/MultipleClassFileToPsr4ClassesRector/MultipleClassFileToPsr4ClassesRectorTest.php
> [PHP 7.4] Spread array

- src/Console/Application.php
- src/Console/Command/ProcessCommand.php
- src/Rector/Psr4/MultipleClassFileToPsr4ClassesRector.php
- tests/Rector/Psr4/MultipleClassFileToPsr4ClassesRector/MultipleClassFileToPsr4ClassesRectorTest.php
New command-line utility option:
-d, --working-dir=WORKING-DIR
If specified, use the given directory as working directory.
Follows same syntax as Composer (quick port from there).
> Add working directory option

- composer.json
- config/level/code-quality/code-quality.yaml
- packages/CodeQuality/src/Rector/For_/ForToForeachRector.php
- packages/CodeQuality/tests/Rector/For_/ForToForeachRector/Fixture/fixture.php.inc
- packages/CodeQuality/tests/Rector/For_/ForToForeachRector/Fixture/for_with_count.php.inc
- packages/CodeQuality/tests/Rector/For_/ForToForeachRector/Fixture/for_with_switched_compare.php.inc
- packages/CodeQuality/tests/Rector/For_/ForToForeachRector/ForToForeachRectorTest.php
- packages/ContributorTools/src/Command/DumpNodesCommand.php
- packages/ContributorTools/src/Configuration/ConfigurationFactory.php
- packages/NodeTypeResolver/src/NodeTypeResolver.php
- packages/Php/tests/Rector/Closure/ClosureToArrowFunctionRector/ClosureToArrowFunctionRectorTest.php
- packages/Php/tests/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/ArraySpreadInsteadOfArrayMergeRectorTest.php
- phpstan.neon
- rector.yaml
Closes #1402
```diff
-for ($i = 0, $c = count($tokens); $i < $c; ++$i) {
+foreach ($tokens as $i => $token) {
}
```
```diff
-for ($i = 0; $i < count($tokens); ++$i) {
+foreach ($tokens as $i => $token) {
}
```
> [CodeQuality] Add For to foreach

- config/level/code-quality/code-quality.yaml
- docs/AllRectorsOverview.md
- packages/CodeQuality/src/Rector/FuncCall/CompactToVariablesRector.php
- packages/CodeQuality/tests/Rector/FuncCall/CompactToVariablesRector/CompactToVariablesRectorTest.php
- packages/CodeQuality/tests/Rector/FuncCall/CompactToVariablesRector/Fixture/fixture.php.inc
Closes #1379
```diff
$checkout = checkout();
$form     = $this->createForm(DeliveryType::class, DeliveryData::createFrom($checkout))->createView();
-return $this->render('@FrontendBundle/checkout/delivery.html.twig', compact('checkout', 'form'));
+return $this->render('@FrontendBundle/checkout/delivery.html.twig', [
+    'checkout' => $checkout,
+    'form' => $form,
+]);
```
> [CodeQuality] Add CompactToVariablesRector

- .travis.yml
- packages/Php/src/Rector/Name/ReservedObjectRector.php
- packages/Php/tests/Rector/Name/ReservedObjectRector/Fixture/skip_type_declaration_object.php
- packages/Php/tests/Rector/Name/ReservedObjectRector/ReservedObjectRectorTest.php
> fix ReservedObjectRector for lowercased object

- phpstan.neon
- rector.yaml
- src/Rector/Psr4/MultipleClassFileToPsr4ClassesRector.php
- tests/Rector/Psr4/MultipleClassFileToPsr4ClassesRector/Expected/JustOneExceptionWithoutNamespace.php
- tests/Rector/Psr4/MultipleClassFileToPsr4ClassesRector/Expected/JustTwoExceptionWithoutNamespace.php
- tests/Rector/Psr4/MultipleClassFileToPsr4ClassesRector/MultipleClassFileToPsr4ClassesRectorTest.php
- tests/Rector/Psr4/MultipleClassFileToPsr4ClassesRector/Source/exceptions-without-namespace.php
> [Psr4] Add supprot for namespace less MultipleClassFileToPsr4ClassesRector

- packages/FileSystemRector/src/Rector/AbstractFileSystemRector.php
- src/Rector/Psr4/MultipleClassFileToPsr4ClassesRector.php
- tests/Rector/Psr4/MultipleClassFileToPsr4ClassesRector/Expected/JustOneException.php
- tests/Rector/Psr4/MultipleClassFileToPsr4ClassesRector/Expected/UnknownImageFileException.php
- tests/Rector/Psr4/MultipleClassFileToPsr4ClassesRector/MultipleClassFileToPsr4ClassesRectorTest.php
Closes #1467
Note: the `MultipleClassFileToPsr4ClassesRector` now only works if there are 2+ classes. It doesn't rename the file itself. It should be work of another rector, that only hooks to `ClassLike`
> fix deleting file that matches class name

- config/level/coding-style/coding-style.yaml
- packages/CodingStyle/src/Rector/FuncCall/ConsistentPregDelimiterRector.php
- packages/CodingStyle/tests/Rector/FuncCall/ConsistentPregDelimiterRector/ConsistentPregDelimiterRectorTest.php
- packages/CodingStyle/tests/Rector/FuncCall/ConsistentPregDelimiterRector/Fixture/fixture.php.inc
- packages/CodingStyle/tests/Rector/FuncCall/ConsistentPregDelimiterRector/Fixture/skip_concat.php.inc
- packages/CodingStyle/tests/Rector/FuncCall/ConsistentPregDelimiterRector/Fixture/static_call.php.inc
Ref #1466
- Configurable :wrench: 
```yaml
services:
Rector\CodingStyle\Rector\FuncCall\ConsistentPregDelimiterRector:
delimiter: '_' # "#" by default
```
Inspired by https://github.com/Symplify/CodingStandard/blob/master/src/Fixer/ControlStructure/PregDelimiterFixer.php
> [CodingStyle] Add ConsistentPregDelimiterRector

- config/level/coding-style/coding-style.yaml
- packages/CodingStyle/src/Rector/Include_/FollowRequireByDirRector.php
- packages/CodingStyle/tests/Rector/Include_/FollowRequireByDirRector/Fixture/extra_dot.php.inc
- packages/CodingStyle/tests/Rector/Include_/FollowRequireByDirRector/Fixture/fixture.php.inc
- packages/CodingStyle/tests/Rector/Include_/FollowRequireByDirRector/Fixture/phar.php.inc
- packages/CodingStyle/tests/Rector/Include_/FollowRequireByDirRector/FollowRequireByDirRectorTest.php
Ref #1466
```diff
-require '/relativePath';
+require __DIR__ . '/relativePath';
```
> [CodingStyle] Add FollowRequireByDirRector

- config/level/coding-style/coding-style.yaml
- packages/CodingStyle/src/Rector/Assign/SplitDoubleAssignRector.php
- packages/CodingStyle/tests/Rector/Assign/SplitDoubleAssignRector/Fixture/fixture.php.inc
- packages/CodingStyle/tests/Rector/Assign/SplitDoubleAssignRector/SplitDoubleAssignRectorTest.php
Close #1466
```diff
-$one, $two = 1;
+$one = 1;
+$two = 1;
```
> [CodingStyle] Add SplitDoubleAssignRector

- config/level/coding-style/coding-style.yaml
- packages/CodingStyle/src/Rector/ClassConst/CompleteVarDocTypeConstantRector.php
- packages/CodingStyle/src/Rector/ClassConst/VarConstantCommentRector.php
- packages/CodingStyle/tests/Rector/ClassConst/VarConstantCommentRector/Fixture/arrays.php.inc
- packages/CodingStyle/tests/Rector/ClassConst/VarConstantCommentRector/Fixture/correct_invalid.php.inc
- packages/CodingStyle/tests/Rector/ClassConst/VarConstantCommentRector/Fixture/fixture.php.inc
- packages/CodingStyle/tests/Rector/ClassConst/VarConstantCommentRector/VarConstantCommentRectorTest.php
- packages/NodeTypeResolver/src/PHPStan/Type/TypeToStringResolver.php
- packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
- packages/Php/src/Rector/Property/CompleteVarDocTypePropertyRector.php
- packages/RemovingStatic/src/Rector/Class_/StaticTypeToSetterInjectionRector.php
- packages/RemovingStatic/src/UniqueObjectFactoryFactory.php
- src/Rector/Property/InjectAnnotationClassRector.php
Ref #1466
```diff
+   /**
+    * @var string[]
+    */
public const NAME = ['Papa', 'Mama'];
```
> [CodingStyle] Add VarConstantCommentRector

- config/level/solid/solid.yaml
- docs/AllRectorsOverview.md
- docs/NodesOverview.md
- packages/CodingStyle/src/Rector/Assign/SplitDoubleAssignRector.php
- packages/CodingStyle/src/Rector/Catch_/CatchExceptionNameMatchingTypeRector.php
- packages/CodingStyle/src/Rector/Include_/FollowRequireByDirRector.php
- packages/CodingStyle/src/Rector/Property/ArrayPropertyDefaultValueRector.php
- packages/NodeTypeResolver/src/PHPStan/Type/TypeToStringResolver.php
- packages/SOLID/src/Rector/Class_/MakeUnusedClassesWithChildrenAbstractRector.php
- packages/SOLID/tests/Rector/Class_/MakeUnusedClassesWithChildrenAbstractRector/Fixture/fixture.php.inc
- packages/SOLID/tests/Rector/Class_/MakeUnusedClassesWithChildrenAbstractRector/Fixture/skip_method_call.php.inc
- packages/SOLID/tests/Rector/Class_/MakeUnusedClassesWithChildrenAbstractRector/Fixture/skip_new.php.inc
- packages/SOLID/tests/Rector/Class_/MakeUnusedClassesWithChildrenAbstractRector/Fixture/skip_static_call.php.inc
- packages/SOLID/tests/Rector/Class_/MakeUnusedClassesWithChildrenAbstractRector/MakeUnusedClassesWithChildrenAbstractRectorTest.php
- phpstan.neon
- rector.yaml
- src/NodeContainer/ParsedNodesByType.php
- src/PhpParser/Node/Manipulator/PropertyManipulator.php
- src/PhpParser/Node/Manipulator/VisibilityManipulator.php
- src/Rector/VisibilityTrait.php
Closes #1466
Classes that are never used, only inherited from, are `abstract`
```diff
class SomeClass extends PossibleAbstractClass
{
}
-class PossibleAbstractClass
+abstract class PossibleAbstractClass
{
}
function run()
{
return new SomeClass();
}
```
> [SOLID] Add AbstractChildlessUnusedClassesRector

- composer.json
- docs/AllRectorsOverview.md
- ecs.yaml
- packages/ContributorTools/src/Command/CreateRectorCommand.php
- packages/Legacy/config/config.yaml
- packages/Legacy/src/NodeAnalyzer/SingletonClassMethodAnalyzer.php
- packages/Legacy/src/Rector/ClassMethod/ChangeSingletonToServiceRector.php
- packages/Legacy/tests/Rector/ClassMethod/ChangeSingletonToServiceRector/ChangeSingletonToServiceRectorTest.php
- packages/Legacy/tests/Rector/ClassMethod/ChangeSingletonToServiceRector/Fixture/fixture.php.inc
- packages/Legacy/tests/Rector/ClassMethod/ChangeSingletonToServiceRector/Fixture/non_empty_protected_construct.php.inc
- packages/Legacy/tests/Rector/ClassMethod/ChangeSingletonToServiceRector/Fixture/protected_construct.php.inc
- packages/Legacy/tests/Rector/ClassMethod/ChangeSingletonToServiceRector/Fixture/static_variable.php.inc
- packages/TypeDeclaration/src/Rector/FunctionLike/ReturnTypeDeclarationRector.php
- phpstan.neon
- rector.yaml
> [Legacy] Remove singleton

- packages/ConsoleDiffer/src/DifferAndFormatter.php
- rector.yaml
- src/Application/ErrorAndDiffCollector.php
- src/Application/RectorApplication.php
- src/Configuration/Configuration.php
- src/Console/Application.php
- src/Console/Command/ProcessCommand.php
- src/Console/Output/ConsoleOutputFormatter.php
- src/Console/Output/JsonOutputFormatter.php
- src/Contract/Console/Output/OutputFormatterInterface.php
- src/Reporting/FileDiff.php
Closes #1455 
```bash
bin/rector p src/Console/Output -n -o json
```
(`-n` = `--dry-run`, `-o` = `--output-format`)
```json
{
"meta": {
"version": "0.5.x-dev@adba626",
"config": "/var/www/rector/rector.yaml"
},
"totals": {
"changed_files": 1,
"removed_and_added_files_count": 0,
"errors": 0
},
"file_diffs": [
{
"file": "/var/www/rector/src/Console/Output/JsonOutputFormatter.php",
"diff": "--- Original\n+++ New\n@@ -25,7 +25,7 @@\n      */\n     private $configuration;\n \n-    public function __construct(\\Symfony\\Component\\Console\\Style\\SymfonyStyle $symfonyStyle, Configuration $configuration)\n+    public function __construct(SymfonyStyle $symfonyStyle, Configuration $configuration)\n     {\n         $this->symfonyStyle = $symfonyStyle;\n         $this->configuration = …
```
> add JsonOutputFormatter

- packages/Php/tests/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/BinaryOpBetweenNumberAndStringRectorTest.php
- packages/Php/tests/Rector/BinaryOp/BinaryOpBetweenNumberAndStringRector/Fixture/ignore_concatenation_dot.php.inc
Ensure that if a concatenation is made between a `string` and an `int`, Rector will not change anything, leaving the code as is.
https://github.com/rectorphp/rector/issues/1501
> Test concatenation dot is ignored.

- packages/CodeQuality/tests/Rector/Array_/CallableThisArrayToAnonymousFunctionRector/CallableThisArrayToAnonymousFunctionRectorTest.php
- packages/CodeQuality/tests/Rector/Array_/CallableThisArrayToAnonymousFunctionRector/Fixture/no_return_for_void.php.inc
Failing test for https://github.com/rectorphp/rector/issues/1499
> Test `void` methods doesn't have the `return` statement added.

- packages/CodeQuality/src/Rector/Array_/CallableThisArrayToAnonymousFunctionRector.php
> [CodeQuality] Fix unneeded return in CallableThisArrayToAnonymousFunctionRector

- packages/Php/src/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector.php
> [PHP] Fix AddDefaultValueForUndefinedVariableRector for static variable

- packages/CodeQuality/tests/Rector/Foreach_/ForeachToInArrayRector/Fixture/ignore_collections.php.inc
- packages/CodeQuality/tests/Rector/Foreach_/ForeachToInArrayRector/ForeachToInArrayRectorTest.php
- packages/CodeQuality/tests/Rector/Foreach_/ForeachToInArrayRector/Source/Collection.php
> Ensure Doctrine's `Collection`-like arrays are ignored.

- composer.json
> Widen `PHPStan` version constraint to `~0.11.6`.

- ecs.yaml
- packages/Symfony/src/Rector/Class_/MakeCommandLazyRector.php
- packages/Symfony/tests/Rector/Class_/MakeCommandLazyRector/Fixture/set_name_fluent.php.inc
- packages/Symfony/tests/Rector/Class_/MakeCommandLazyRector/Fixture/skip_non_string_param_construct.php.inc
- packages/Symfony/tests/Rector/Class_/MakeCommandLazyRector/Fixture/static_in_execute.php.inc
- packages/Symfony/tests/Rector/Class_/MakeCommandLazyRector/MakeCommandLazyRectorTest.php
- src/PhpParser/Node/Commander/NodeRemovingCommander.php
Closes #1497
What do you think @stloyd ?
> [Symfony] Add MakeCommandLazyRector

- packages/BetterPhpDocParser/tests/PhpDocInfo/PhpDocInfoPrinterSource/doc15.txt
- packages/BetterPhpDocParser/tests/PhpDocInfo/PhpDocInfoPrinterTest.php
- packages/Php/src/Exception/BreakScopeException.php
- packages/Php/src/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector.php
> Fix scope overflow in AddDefaultValueForUndefinedVariableRector

- src/EventDispatcher/AutowiredEventDispatcher.php
Signed-off-by: Kevin R <22906111+cgkkevinr@users.noreply.github.com>
> Do not call parent constructor of AutowiredEventDispatcher unless it exists

- packages/CodingStyle/src/Imports/ShortNameResolver.php
- packages/CodingStyle/src/Rector/Use_/RemoveUnusedAliasRector.php
- packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/Fixture/skip_different_namespaces_same_name.php.inc
- packages/CodingStyle/tests/Rector/Use_/RemoveUnusedAliasRector/RemoveUnusedAliasRectorTest.php
- packages/Php/src/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector.php
- phpstan.neon
- src/EventDispatcher/AutowiredEventDispatcher.php
> make RemoveUnusedAliasRector take into account aliases that keep 2 classes with same short name explicit

- config/level/symfony/symfony43.yaml
As described in https://github.com/symfony/symfony/blob/4.4/UPGRADE-4.3.md#httpkernel the new name for the FilterControllerEvent is ControllerEvent
> Fix classname change for FilterControllerEvent

- config/level/symfony/symfony43.yaml
- packages/CodingStyle/tests/Rector/FuncCall/ConsistentPregDelimiterRector/ConsistentPregDelimiterRectorTest.php
- packages/CodingStyle/tests/Rector/FuncCall/ConsistentPregDelimiterRector/Fixture/escape_nette_static_call.php.inc
- packages/FileSystemRector/src/Rector/AbstractFileSystemRector.php
- src/Rector/AbstractRector.php
- src/Rector/AbstractRector/AbstractRectorTrait.php
- src/Rector/AbstractRector/AppliedRectorCollectorTrait.php
- src/Rector/AbstractRector/BetterStandardPrinterTrait.php
- src/Rector/AbstractRector/CallableNodeTraverserTrait.php
- src/Rector/AbstractRector/ConstFetchAnalyzerTrait.php
- src/Rector/AbstractRector/NameResolverTrait.php
- src/Rector/AbstractRector/NodeCommandersTrait.php
- src/Rector/AbstractRector/NodeFactoryTrait.php
- src/Rector/AbstractRector/NodeTypeResolverTrait.php
- src/Rector/AbstractRector/ValueResolverTrait.php
- src/Rector/AbstractRector/VisibilityTrait.php
- src/Rector/ClassMethod/AddMethodParentCallRector.php
- tests/Rector/ClassMethod/AddMethodParentCallRector/AddMethodParentCallRectorTest.php
- tests/Rector/ClassMethod/AddMethodParentCallRector/Fixture/fixture.php.inc
- tests/Rector/ClassMethod/AddMethodParentCallRector/Fixture/skip_already_has.php.inc
- tests/Rector/ClassMethod/AddMethodParentCallRector/Source/ParentClassWithNewConstructor.php
> [Symfony 4.3] Add parent::__construct to EventDispatcher

- packages/CodingStyle/tests/Rector/Catch_/CatchExceptionNameMatchingTypeRector/CatchExceptionNameMatchingTypeRectorTest.php
- packages/CodingStyle/tests/Rector/Catch_/CatchExceptionNameMatchingTypeRector/Fixture/nested_call.php.inc
- packages/Php/src/Rector/FuncCall/CountOnNullRector.php
- packages/Symfony/src/Rector/Class_/MakeCommandLazyRector.php
- packages/Symfony/src/Rector/MethodCall/MakeDispatchFirstArgumentEventRector.php
- packages/Symfony/tests/Rector/MethodCall/MakeDispatchFirstArgumentEventRector/Fixture/event_class_constant.php.inc
- packages/Symfony/tests/Rector/MethodCall/MakeDispatchFirstArgumentEventRector/Fixture/keep_string_event_constant.php.inc
- packages/Symfony/tests/Rector/MethodCall/MakeDispatchFirstArgumentEventRector/MakeDispatchFirstArgumentEventRectorTest.php
- packages/Symfony/tests/Rector/MethodCall/MakeDispatchFirstArgumentEventRector/Source/CustomEvent.php
- src/Rector/AbstractRector.php
> Fix reporting of changed nodes

- config/level/dead-code/dead-code.yaml
- packages/DeadCode/src/Rector/Concat/RemoveConcatAutocastRector.php
- packages/DeadCode/tests/Rector/Concat/RemoveConcatAutocastRector/Fixture/fixture.php.inc
- packages/DeadCode/tests/Rector/Concat/RemoveConcatAutocastRector/RemoveConcatAutocastRectorTest.php
> [DeadCode] Add RemoveConcatAutocastRector

- .github/ISSUE_TEMPLATE/1_Bug_report.md
- .github/ISSUE_TEMPLATE/2_Feature_request.md
- .github/ISSUE_TEMPLATE/3_Support_question.md
You can merge it and see how it works. In future you can add or modify these templates.
> #1469 prototype github issue template

- config/set/dead-code/dead-code.yaml
- packages/DeadCode/src/Rector/ClassMethod/RemoveDelegatingParentCallRector.php
- packages/DeadCode/src/Rector/Plus/RemoveZeroAndOneBinaryRector.php
- packages/DeadCode/tests/Rector/ClassMethod/RemoveDelegatingParentCallRector/Fixture/fixture.php.inc
- packages/DeadCode/tests/Rector/ClassMethod/RemoveDelegatingParentCallRector/Fixture/skip_changed_arguments.php.inc
- packages/DeadCode/tests/Rector/ClassMethod/RemoveDelegatingParentCallRector/Fixture/skip_different_method_name.php.inc
- packages/DeadCode/tests/Rector/ClassMethod/RemoveDelegatingParentCallRector/Fixture/skip_extra_content.php.inc
- packages/DeadCode/tests/Rector/ClassMethod/RemoveDelegatingParentCallRector/RemoveDelegatingParentCallRectorTest.php
- packages/DeadCode/tests/Rector/Plus/RemoveZeroAndOneBinaryRector/Fixture/assigns.php.inc
- packages/DeadCode/tests/Rector/Plus/RemoveZeroAndOneBinaryRector/Fixture/fixture.php.inc
- packages/DeadCode/tests/Rector/Plus/RemoveZeroAndOneBinaryRector/Fixture/skip_floats.php.inc
- packages/DeadCode/tests/Rector/Plus/RemoveZeroAndOneBinaryRector/Fixture/skip_type_change.php.inc
- packages/DeadCode/tests/Rector/Plus/RemoveZeroAndOneBinaryRector/RemoveZeroAndOneBinaryRectorTest.php
- phpstan.neon
> [DeadCode] Add RemoveDelegatingParentCallRector

- config/set/laravel/laravel57.yaml
> [Laravel] Fix missing method name in 5.7

- .github/FUNDING.yml
This fixes the `FUNDING.yml` file to use the correct Open Collective id.
Currently the Sponsor button shows the following error notice:
> Unknown funding platform 'opencollective'.
> Fix Open Collective link for FUNDING.yml

- config/set/shopware/shopware55.yaml
- config/set/shopware/shopware56.yaml
- packages/Shopware/src/Rector/ClassConstFetch/ShopwareVersionConstsRector.php
- packages/Shopware/tests/Rector/ClassConstFetch/ShopwareVersionConstsRector/Fixture/fixture.php.inc
- packages/Shopware/tests/Rector/ClassConstFetch/ShopwareVersionConstsRector/ShopwareVersionConstsRectorTest.php
> Add shopware version const rector

- config/set/shopware/shopware56.yaml
- packages/Shopware/src/Rector/MethodCall/ShopRegistrationServiceRector.php
- packages/Shopware/tests/Rector/MethodCall/ShopRegistrationServiceRector/Fixture/fixture.php.inc
- packages/Shopware/tests/Rector/MethodCall/ShopRegistrationServiceRector/ShopRegistrationServiceRectorTest.php
Deprecated today https://github.com/shopware/shopware/commit/840fd02880d38032cf092bd9a28a52b017cc50d2 😅
> Add rector for ShopRegistration

- packages/Symfony/src/Rector/HttpKernel/GetRequestRector.php
- packages/Symfony/tests/Rector/HttpKernel/GetRequestRector/Fixture/skip_event_subscriber.php.inc
- packages/Symfony/tests/Rector/HttpKernel/GetRequestRector/GetRequestRectorTest.php
> [Symfony] Fix GetRequestRector overlap to non-controllers

- ecs.yaml
- packages/Php/tests/Rector/FuncCall/RemoveExtraParametersRector/Fixture/skip_invoke.php.inc
- packages/Php/tests/Rector/FuncCall/RemoveExtraParametersRector/RemoveExtraParametersRectorTest.php
- src/PhpParser/Node/Manipulator/CallManipulator.php
> [PHP] Fix missed variadic on ReflectionMethod::invoke() [closes #1625]

- phpstan.neon
- src/Rector/Property/InjectAnnotationClassRector.php
- tests/Rector/Property/InjectAnnotationClassRector/Fixture/inject_from_var.php.inc
- tests/Rector/Property/InjectAnnotationClassRector/InjectAnnotationClassRectorTest.php
> Fix InjectAnnotationClassRector for @var case

- packages/Php/src/IsArrayAndDualCheckToAble.php
- packages/Php/src/Rector/BinaryOp/IsCountableRector.php
- packages/Php/src/Rector/BinaryOp/IsIterableRector.php
- packages/Php/src/Rector/FuncCall/ArrayKeyFirstLastRector.php
- packages/Php/tests/Rector/BinaryOp/IsIterableRector/Fixture/polyfil_function.php.inc
- packages/Php/tests/Rector/BinaryOp/IsIterableRector/PolyfillRectorTest.php
- src/Configuration/Option.php
- src/Php/PhpVersionProvider.php
- tests/Rector/Property/InjectAnnotationClassRector/InjectAnnotationClassRectorTest.php
> Add Polyfil function support

- config/set/symfony/symfony42.yaml
- src/Rector/Argument/ArgumentAdderRector.php
- tests/Rector/Argument/ArgumentAdderRector/ArgumentAdderRectorTest.php
- tests/Rector/Argument/ArgumentAdderRector/Fixture/scoped.php.inc
- tests/Rector/Argument/ArgumentAdderRector/Source/SomeParentClient.php
- Closes #1662
- Replaces #1627
> [PHP] Add scope limitation to ArgumentAdderRector for 3party non-existing params

- packages/TypeDeclaration/src/Rector/FunctionLike/ParamTypeDeclarationRector.php
- packages/TypeDeclaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/Fixture/resource.php.inc
- packages/TypeDeclaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/ParamTypeDeclarationRectorTest.php
> [Bugfix] PHPDoc type-hint `resource` should not be used as PHP type-hint

- packages/Symfony/src/Bridge/DefaultAnalyzedSymfonyApplicationContainer.php
Allow to set custom ones via configuration:
```yaml
services:
Rector\Symfony\Bridge\DefaultAnalyzedSymfonyApplicationContainer:
autowire: true
arguments:
$commonNamesToTypes:
'doctrine.orm.other_entity_manager': Doctrine\ORM\EntityManagerInterface
'pseudo.buggy.service_name': App\Some\ServiceClass
> [Symfony] Set few default common service names for Symfony App Analyzer

- config/set/code-quality/code-quality.yaml
- packages/CodeQuality/src/Rector/FuncCall/IsAWithStringWithThirdArgumentRector.php
- packages/CodeQuality/tests/Rector/FuncCall/IsAWithStringWithThirdArgumentRector/Fixture/fixture.php.inc
- packages/CodeQuality/tests/Rector/FuncCall/IsAWithStringWithThirdArgumentRector/IsAWithStringWithThirdArgumentRectorTest.php
> [CodeQuality] Add is_a with string true

- config/set/architecture/doctrine-repository-as-service.yaml
- packages/Architecture/src/Rector/Class_/RemoveRepositoryFromEntityAnnotationRector.php
- packages/Architecture/tests/Rector/Class_/RemoveRepositoryFromEntityAnnotationRector/Fixture/fixture.php.inc
- packages/Architecture/tests/Rector/Class_/RemoveRepositoryFromEntityAnnotationRector/Fixture/skip_done.php.inc
- packages/Architecture/tests/Rector/Class_/RemoveRepositoryFromEntityAnnotationRector/RemoveRepositoryFromEntityAnnotationRectorTest.php
- packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
> [Doctrine] Add RemoveRepositoryFromEntityAnnotationRector

- config/set/phpstan/phpstan.yaml
- ecs.yaml
- packages/Architecture/src/Rector/Class_/RemoveRepositoryFromEntityAnnotationRector.php
- packages/Architecture/tests/Rector/Class_/RemoveRepositoryFromEntityAnnotationRector/RemoveRepositoryFromEntityAnnotationRectorTest.php
- packages/CodeQuality/src/Rector/FuncCall/IsAWithStringWithThirdArgumentRector.php
- packages/CodeQuality/src/Rector/FuncCall/StrlenZeroToIdenticalEmptyStringRector.php
- packages/ContributorTools/src/Command/DumpNodesCommand.php
- packages/ContributorTools/templates/packages/_Package_/src/Rector/_Category_/_Name_.php.inc
- packages/NodeTypeResolver/src/PerNodeTypeResolver/NameTypeResolver.php
- packages/PHPStan/src/Rector/Node/RemoveNonExistingVarAnnotationRector.php
- packages/PHPStan/tests/Rector/Node/RemoveNonExistingVarAnnotationRector/Fixture/fixture.php.inc
- packages/PHPStan/tests/Rector/Node/RemoveNonExistingVarAnnotationRector/Fixture/if_case.php.inc
- packages/PHPStan/tests/Rector/Node/RemoveNonExistingVarAnnotationRector/Fixture/keep.php.inc
- packages/PHPStan/tests/Rector/Node/RemoveNonExistingVarAnnotationRector/Fixture/subcontent.php.inc
- packages/PHPStan/tests/Rector/Node/RemoveNonExistingVarAnnotationRector/RemoveNonExistingVarAnnotationRectorTest.php
- packages/Php/src/Rector/FuncCall/RenameMktimeWithoutArgsToTimeRector.php
- packages/TypeDeclaration/src/Rector/FunctionLike/ParamTypeDeclarationRector.php
- rector.yaml
- src/PhpParser/Node/Manipulator/ClassManipulator.php
> [PHPStan] Add RemoveNonExistingVarAnnotationRector

- packages/DeadCode/tests/Rector/ClassConst/RemoveUnusedPrivateConstantRector/Fixture/keep_static_constant.php.inc
- packages/DeadCode/tests/Rector/ClassConst/RemoveUnusedPrivateConstantRector/RemoveUnusedPrivateConstantRectorTest.php
- src/PhpParser/Node/Manipulator/ClassConstManipulator.php
Basically there were false positives regarding private constant uses when called with `static::` instead of `self::`
**Note**: `phpstan` is failing [on master too](https://github.com/rectorphp/rector/commits/master). I've fixed it on #1698
> [DeadCode] Allow static constant call on RemoveUnusedPrivateConstantRector

- composer.json
There was a call to `@update-docs` but the script is called `@docs`.
**Note**: `phpstan` is failing [on master too](https://github.com/rectorphp/rector/commits/master). I've fixed it on #1698
> Update composer scripts

- .dockerignore
Context: 
I'm trying to use the Rector docker image to upgrade a testsuite from PHPUnit 6 to PHPUnit 8.
Symptom: 
Rector refuses to process files in a directory named `tests`. It only finds these files if I create an 'empty' `rector.yaml` configuration file in my project and specify it on the command line using the `-c` flag.
Analysis:
It turns out that when no config file is specified as a command line option, Rector looks for one in its current working directory. In the docker image, this is `/rector`, the directory containing the source files of Rector itself. Among these is `rector.yaml`, which is the Rector configuration file for developing on rector itself (at least I think so). This file contains an exclude pattern for `/tests/`, which is useful when working on Rector itself, but …
> Add rector.yaml to .dockerignore

- packages/DeadCode/src/Rector/Plus/RemoveZeroAndOneBinaryRector.php
- packages/DeadCode/tests/Rector/Plus/RemoveZeroAndOneBinaryRector/Fixture/assigns.php.inc
- packages/DeadCode/tests/Rector/Plus/RemoveZeroAndOneBinaryRector/Fixture/fixture.php.inc
- packages/DeadCode/tests/Rector/Plus/RemoveZeroAndOneBinaryRector/Fixture/no_unintended.php.inc
- packages/DeadCode/tests/Rector/Plus/RemoveZeroAndOneBinaryRector/RemoveZeroAndOneBinaryRectorTest.php
- src/PhpParser/Node/Value/ValueResolver.php
- tests/PhpParser/Node/Value/ValueResolverTest.php
Fixed issue where '1 / x' is considered to be equal to 'x'
Fixed issue where '($var + 1)' inside another expression is considered to be equal to '1'
Expanded unit test for ValueResolver
> Fixed some issues for RemoveZeroAndOneBinaryRector

- packages/BetterPhpDocParser/src/Printer/PhpDocInfoPrinter.php
- packages/CodingStyle/src/Rector/ClassConst/VarConstantCommentRector.php
- packages/CodingStyle/tests/Rector/ClassConst/VarConstantCommentRector/Fixture/correct_invalid.php.inc
- packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
Previously, this code:
```php
/**
* My comment.
*
* @var array
*/
public const CONST = [
'string'
];
```
would become:
```php
/**
* My comment.
* @var string[]
*/
public const CONST = [
'string'
];
```
messing with code standards/style (removing the line between comment and `@var`).
Now it stays as is:
```php
/**
* My comment.
*
* @var string[]
*/
public const CONST = [
'string'
];
```
(without breaking anything else)
> Don't mess with lines between docblock comment and var type.

- packages/PHPUnit/tests/Rector/MethodCall/ReplaceAssertArraySubsetRector/Fixture/multilevel_array.php.inc
- packages/PHPUnit/tests/Rector/MethodCall/ReplaceAssertArraySubsetRector/ReplaceAssertArraySubsetRectorTest.php
- src/PhpParser/Node/Value/ValueResolver.php
When multi-level arrays were used, an error was thrown:
```
Error: Call to undefined method PHPStan\Type\Constant\ConstantArrayType::getValue()
/rector/src/PhpParser/Node/Value/ValueResolver.php:181
/rector/src/PhpParser/Node/Value/ValueResolver.php:75
/rector/src/Rector/AbstractRector/ValueResolverTrait.php:32
/rector/packages/PHPUnit/src/Rector/MethodCall/ReplaceAssertArraySubsetRector.php:174
/rector/packages/PHPUnit/src/Rector/MethodCall/ReplaceAssertArraySubsetRector.php:89
```
> [MethodCall] Fix multilevel array subsets

- composer.json
- packages/NodeTypeResolver/src/PerNodeTypeResolver/NameTypeResolver.php
- packages/PHPUnitSymfony/src/Rector/StaticCall/AddMessageToEqualsResponseCodeRector.php
- packages/PHPUnitSymfony/tests/Rector/StaticCall/AddMessageToEqualsResponseCodeRector/AddMessageToEqualsResponseCodeRectorTest.php
- packages/PHPUnitSymfony/tests/Rector/StaticCall/AddMessageToEqualsResponseCodeRector/Fixture/fixture.php.inc
- packages/PHPUnitSymfony/tests/Rector/StaticCall/AddMessageToEqualsResponseCodeRector/Fixture/method_call.php.inc
> [PHPUnit][Symfony] Add AddMessageToEqualsResponseCodeRector

- src/Rector/Property/InjectAnnotationClassRector.php
- tests/Rector/Property/InjectAnnotationClassRector/Fixture/fixture4.php.inc
- tests/Rector/Property/InjectAnnotationClassRector/Fixture/inject_from_var2.php.inc
- tests/Rector/Property/InjectAnnotationClassRector/InjectAnnotationClassRectorTest.php
As suggested in https://github.com/rectorphp/rector/issues/1400#issuecomment-508336071
> Do not mark injected properties as private when moved to constructor

- packages/Php/src/Rector/FuncCall/ParseStrWithResultArgumentRector.php
- packages/Php/tests/Rector/FuncCall/ParseStrWithResultArgumentRector/Fixture/already_set.php.inc
- packages/Php/tests/Rector/FuncCall/ParseStrWithResultArgumentRector/ParseStrWithResultArgumentRectorTest.php
Before this fix, `parse_str($query, $data);` would turn into `parse_str($query, $result);` by no reason, breaking valid code.
> [FuncCall] Don't add $result to parse_str if second parameter is already set

- packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/skip_array_callables_fqn.php.inc
- packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/skip_array_callables_self.php.inc
- packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/skip_array_callables_static.php.inc
- packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/Fixture/skip_array_callables_this.php.inc
- packages/DeadCode/tests/Rector/ClassMethod/RemoveUnusedPrivateMethodRector/RemoveUnusedPrivateMethodRectorTest.php
- src/NodeContainer/ParsedNodesByType.php
> [DeadCode] Add static, self and FQN type to RemoveUnusedPrivateMethodRector

- .github/FUNDING.yml
- packages/DeadCode/src/Rector/Property/RemoveUnusedPrivatePropertyRector.php
- packages/DeadCode/tests/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/skip_anonymous_function.php.inc
- packages/DeadCode/tests/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/skip_nested_closure.php.inc
- packages/DeadCode/tests/Rector/Property/RemoveUnusedPrivatePropertyRector/RemoveUnusedPrivatePropertyRectorTest.php
- packages/NodeTypeResolver/src/PHPStan/Scope/NodeVisitor/RemoveDeepChainMethodCallNodeVisitor.php
- rector.yaml
- src/PhpParser/Node/Manipulator/PropertyManipulator.php
> [DeadCode] Fix too deep nesting in dead private property

- packages/NodeTypeResolver/src/NodeTypeResolver.php
- packages/NodeTypeResolver/src/StaticTypeToStringResolver.php
- packages/TypeDeclaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/a_new_class.php.inc
- packages/TypeDeclaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/ReturnTypeDeclarationRectorTest.php
> Resolve anonymous class return type to object

- config/set/php/php74.yaml
As reported  in https://github.com/rectorphp/rector/issues/1724
> is_real() is deprecated instead of is_float()

- packages/TypeDeclaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/Fixture/reference_symbol_in_docblock.php.inc
- packages/TypeDeclaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/ParamTypeDeclarationRectorTest.php
Linked to #1734 
The idea here would be to ignore the `&` during parsing. Unfortunately in this case, rector depends on phpstan doc parser which maintainers decided not to support this type of documenting: https://github.com/phpstan/phpstan/issues/699
I've dug a little and found that adding this line:
```php
$tokens->tryConsumeTokenType(Lexer::TOKEN_REFERENCE);
```
After this line: 
https://github.com/phpstan/phpdoc-parser/blob/master/src/Parser/PhpDocParser.php#L166
Would effectively ignore it and make the test green.
I'm wondering if there could be any workaround that can be put in rector code directly.
> Consider reference symbol in docblock for param type declaration rector

- config/set/coding-style/coding-style.yaml
- packages/CodingStyle/src/Rector/ClassMethod/NewlineBeforeNewAssignSetRector.php
- packages/CodingStyle/tests/Rector/ClassMethod/NewlineBeforeNewAssignSetRector/Fixture/fixture.php.inc
- packages/CodingStyle/tests/Rector/ClassMethod/NewlineBeforeNewAssignSetRector/NewlineBeforeNewAssignSetRectorTest.php
- src/PhpParser/Printer/BetterStandardPrinter.php
> [CodeStyle] Newline before assign

- packages/DeadCode/src/Rector/ClassMethod/RemoveDeadConstructorRector.php
- packages/DeadCode/tests/Rector/ClassMethod/RemoveDeadConstructorRector/Fixture/skip_private.php.inc
- packages/DeadCode/tests/Rector/ClassMethod/RemoveDeadConstructorRector/RemoveDeadConstructorRectorTest.php
> [DeadCode] Rector `RemoveDeadConstructorRector` should skip `private` method

- config/config.yaml
- packages/Symfony/config/config.yaml
- packages/Symfony/src/Bridge/DefaultAnalyzedSymfonyApplicationContainer.php
- packages/Symfony/src/Bridge/DependencyInjection/SymfonyContainerFactory.php
- packages/Symfony/src/Bridge/SymfonyKernelParameterGuard.php
- src/Bridge/Contract/AnalyzedApplicationContainerInterface.php
- src/Configuration/Option.php
```yaml
paramters:
kernel_environment: "test"
```
> make SymfonyContainer factory configurable with "kernel_environment" parameter in rector.yaml

- composer.json
- config/set/symfony/symfony-code-quality.yaml
- packages/SymfonyCodeQuality/src/Rector/Class_/EventListenerToEventSubscriberRector.php
- packages/SymfonyCodeQuality/tests/Rector/Class_/EventListenerToEventSubscriberRector/EventListenerToEventSubscriberRectorTest.php
- packages/SymfonyCodeQuality/tests/Rector/Class_/EventListenerToEventSubscriberRector/Fixture/fixture.php.inc
- packages/SymfonyCodeQuality/tests/Rector/Class_/EventListenerToEventSubscriberRector/Source/ListenersKernel.php
- phpstan.neon
```php
<?php
class SomeListener
{
public function methodToBeCalled()
{
}
}
```
```yaml
services:
SomeListener:
tags:
- { name: kernel.event_listener, event: 'some_event', method: 'methodToBeCalled' }
```
```php
<?php
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
class SomeEventSubscriber implements EventSubscriberInterface
{
/**
* @return mixed[]
*/
public static function getSubscribedEvents(): array
{
return ['some_event' => 'methodToBeCalled'];  
}
public function methodToBeCalled()
{
}
}
```
> [SymfonyCodeQuality] From listener to subscriber

- config/set/code-quality/code-quality.yaml
- packages/CodeQuality/src/Rector/Catch_/ThrowWithPreviousExceptionRector.php
- packages/CodeQuality/tests/Rector/Catch_/ThrowWithPreviousExceptionRector/Fixture/fixture.php.inc
- packages/CodeQuality/tests/Rector/Catch_/ThrowWithPreviousExceptionRector/ThrowWithPreviousExceptionRectorTest.php
> [CodeQuality] Add ThrowWithPreviousExceptionRector

- config/set/coding-style/coding-style.yaml
- ecs.yaml
- packages/CodingStyle/src/Node/ConcatJoiner.php
- packages/CodingStyle/src/Node/ConcatManipulator.php
- packages/CodingStyle/src/Rector/String_/ManualJsonStringToJsonEncodeArrayRector.php
- packages/CodingStyle/src/ValueObject/ConcatExpressionJoinData.php
- packages/CodingStyle/tests/Rector/String_/ManualJsonStringToJsonEncodeArrayRector/Fixture/assign_with_concat.php.inc
- packages/CodingStyle/tests/Rector/String_/ManualJsonStringToJsonEncodeArrayRector/Fixture/concat_json.php.inc
- packages/CodingStyle/tests/Rector/String_/ManualJsonStringToJsonEncodeArrayRector/Fixture/fixture.php.inc
- packages/CodingStyle/tests/Rector/String_/ManualJsonStringToJsonEncodeArrayRector/Fixture/multiline_concat_json.php.inc
- packages/CodingStyle/tests/Rector/String_/ManualJsonStringToJsonEncodeArrayRector/Fixture/tripleline_multiline_concat_json.php.inc
- packages/CodingStyle/tests/Rector/String_/ManualJsonStringToJsonEncodeArrayRector/ManualJsonStringToJsonEncodeArrayRectorTest.php
- packages/Nette/src/Rector/Identical/EndsWithFunctionToNetteUtilsStringsRector.php
- packages/Nette/src/Rector/Identical/StartsWithFunctionToNetteUtilsStringsRector.php
- packages/Php/src/Rector/FuncCall/ArrayKeyFirstLastRector.php
- packages/Silverstripe/src/Rector/ConstantToStaticCallRector.php
- phpstan.neon
- src/PhpParser/Node/Commander/NodeAddingCommander.php
- src/PhpParser/Node/NodeFactory.php
- src/Rector/AbstractRector.php
- src/Rector/AbstractRector/NodeCommandersTrait.php
- src/Rector/AbstractRector/NodeFactoryTrait.php
- tests/PhpParser/Node/NodeFactoryTest.php
```diff
-$someJsonAsString = '{"role_name":"admin","numberz":{"id":"10"}}';
+$data = [
+    'role_name' => 'admin',
+    'numberz' => ['id' => '10']
+];
+$someJsonAsString = json_encode($data);
```
> [CodingStyle] Add ManualJsonStringToJsonEncodeArrayRector

- packages/Symfony/src/Bridge/DefaultAnalyzedSymfonyApplicationContainer.php
Autowire is using `Symfony\Bridge\Doctrine\RegistryInterface` not the Doctrine one.
> [Symfony] Use Symfony bridge interface for `doctrine` service

- composer.json
- packages/NodeTypeResolver/src/DependencyInjection/PHPStanServicesFactory.php
- packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
- packages/NodeTypeResolver/src/StaticTypeToStringResolver.php
Now `$stub` returns both `Mock|Request` compared to only `Mock` before
```php
$stub = $this->getMockBuilder(Request::class)
->disableOriginalConstructor()
->getMock();
```
> [NodeTypeResolver] Add phpunit extension

- packages/TypeDeclaration/config/config.yaml
- packages/TypeDeclaration/src/Contract/PropertyTypeInfererInterface.php
- packages/TypeDeclaration/src/PropertyTypeInferer/AbstractPropertyTypeInferer.php
- packages/TypeDeclaration/src/PropertyTypeInferer/AllAssignNodePropertyTypeInferer.php
- packages/TypeDeclaration/src/PropertyTypeInferer/ConstructorPropertyTypeInferer.php
- packages/TypeDeclaration/src/PropertyTypeInferer/DefaultValuePropertyTypeInferer.php
- packages/TypeDeclaration/src/PropertyTypeInferer/DoctrineColumnPropertyTypeInferer.php
- packages/TypeDeclaration/src/PropertyTypeInferer/DoctrineRelationPropertyTypeInferer.php
- packages/TypeDeclaration/src/PropertyTypeInferer/GetterOrSetterPropertyTypeInferer.php
- packages/TypeDeclaration/src/PropertyTypeInferer/SingleMethodAssignedNodePropertyTypeInferer.php
- packages/TypeDeclaration/src/Rector/Property/PropertyTypeDeclarationRector.php
- packages/TypeDeclaration/src/TypeAsStringNormalizer.php
- packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/Fixture/constructor_assign.php.inc
- packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/Fixture/constructor_param.php.inc
- packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/Fixture/constructor_param_with_nullable.php.inc
- packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/Fixture/default_value.php.inc
- packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/Fixture/doctrine_column.php.inc
- packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/Fixture/doctrine_relation.php.inc
- packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/Fixture/phpunit_setup.php.inc
- packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/Fixture/skip_multi_vars.php.inc
- packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/PropertyTypeDeclarationRectorTest.php
> [TypeDeclaration] Add PropertyTypeDeclarationRector

- packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/Fixture/doctrine_relation.php.inc
Doctrine allow to define relation in same namespace without FQDN. However after rector process namespace is broken.
> Break class name in @var when relation is defined in same namespace

- ecs.yaml
- packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
- packages/TypeDeclaration/config/config.yaml
- packages/TypeDeclaration/src/Contract/PropertyTypeInfererInterface.php
- packages/TypeDeclaration/src/PropertyTypeInferer/ConstructorPropertyTypeInferer.php
- packages/TypeDeclaration/src/PropertyTypeInferer/DoctrineRelationPropertyTypeInferer.php
- packages/TypeDeclaration/src/Rector/Property/PropertyTypeDeclarationRector.php
- packages/TypeDeclaration/src/ValueObject/IdentifierValueObject.php
- packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/Fixture/constructor_param_with_aliased_param.php.inc
- packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/Source/ObjectToBeAliased.php
> add alias support to PropertyTypeDeclarationRector

- config/set/dead-code/dead-code.yaml
- packages/Architecture/src/Cleaner/ClassMethodCleaner.php
- packages/BetterPhpDocParser/src/Attributes/Attribute/Attribute.php
- packages/CodeQuality/src/Rector/Foreach_/ForeachToInArrayRector.php
- packages/CodingStyle/src/Node/ConcatManipulator.php
- packages/CodingStyle/src/Rector/String_/ManualJsonStringToJsonEncodeArrayRector.php
- packages/CodingStyle/src/Rector/Use_/RemoveUnusedAliasRector.php
- packages/DeadCode/src/Rector/Class_/RemoveSetterOnlyPropertyAndMethodCallRector.php
- packages/DeadCode/src/Rector/Class_/RemoveUnusedDoctrineEntityMethodAndPropertyRector.php
- packages/DeadCode/tests/Rector/Class_/RemoveSetterOnlyPropertyAndMethodCallRector/Fixture/fixture.php.inc
- packages/DeadCode/tests/Rector/Class_/RemoveSetterOnlyPropertyAndMethodCallRector/Fixture/in_constructor.php.inc
- packages/DeadCode/tests/Rector/Class_/RemoveSetterOnlyPropertyAndMethodCallRector/Fixture/keep_public_property.php.inc
- packages/DeadCode/tests/Rector/Class_/RemoveSetterOnlyPropertyAndMethodCallRector/Fixture/keep_serializable_object.php.inc
- packages/DeadCode/tests/Rector/Class_/RemoveSetterOnlyPropertyAndMethodCallRector/Fixture/keep_static_property.php.inc
- packages/DeadCode/tests/Rector/Class_/RemoveSetterOnlyPropertyAndMethodCallRector/RemoveSetterOnlyPropertyAndMethodCallRectorTest.php
- packages/Php/src/Rector/FuncCall/ParseStrWithResultArgumentRector.php
- packages/Php/src/Rector/FuncCall/PregReplaceEModifierRector.php
- packages/PhpSpecToPHPUnit/src/PhpSpecMockCollector.php
- packages/Twig/src/Rector/SimpleFunctionAndFilterRector.php
- packages/TypeDeclaration/src/Rector/Property/PropertyTypeDeclarationRector.php
- phpstan.neon
- src/Configuration/Configuration.php
- src/Console/Command/AbstractCommand.php
- src/PhpParser/Node/BetterNodeFinder.php
- src/PhpParser/Node/Commander/NodeRemovingCommander.php
- src/PhpParser/Node/Manipulator/ClassManipulator.php
- src/PhpParser/NodeTraverser/CallableNodeTraverser.php
- src/Rector/AbstractRector/CallableNodeTraverserTrait.php
- src/Rector/AbstractRector/NodeCommandersTrait.php
```diff
{
-    private $name;
-
-    public function setName($name)
-    {
-        $this->name = $name;
-    }
}
class ActiveOnlySetter
{
{
$someClass = new SomeClass();
-        $someClass->setName('Tom');
}
}
```
<br>
This rule would not be possible without @spaceflow-app sponsor, thank you :heart:
> [DeadCode] Add RemoveSetterOnlyPropertyAndMethodCallRector

- packages/SOLID/src/Rector/ClassConst/PrivatizeLocalClassConstantRector.php
- packages/SOLID/tests/Rector/ClassConst/PrivatizeLocalClassConstantRector/Fixture/in_interface.php.inc
Constants declared in an interface have to be `public`, having `private` or `protected` constants in interfaces is not supported by the language. PHP will error with `PHP Fatal error:  Access type for interface constant SomeInterface::CONSTANT must be public`.
So whenever a constant is defined in an interface, we can just make it `public`.
> Constants declared in interfaces have to be public

- packages/Laravel/src/Rector/FuncCall/HelperFunctionToConstructorInjectionRector.php
- packages/Laravel/tests/Rector/FuncCall/HelperFunctionToConstructorInjectionRector/Fixture/back.php.inc
- packages/Laravel/tests/Rector/FuncCall/HelperFunctionToConstructorInjectionRector/Fixture/config.php.inc
- packages/Laravel/tests/Rector/FuncCall/HelperFunctionToConstructorInjectionRector/HelperFunctionToConstructorInjectionRectorTest.php
Create new parameter `method_if_no_args`, fix transforming `back()` function, add `back` file to test cases
https://github.com/rectorphp/rector/issues/1824
The file [back.php.inc](https://github.com/rectorphp/rector/blob/master/packages/Laravel/tests/Rector/FuncCall/HelperFunctionToConstructorInjectionRector/Fixture/back.php.inc) was not added to test cases, and its template was either deprecated or invalid, because `back()` function doesn't relay to UrlGenerator (as was expected in this file), it is a call of [Illuminate\Routing\Redirector@back()](https://github.com/laravel/framework/blob/5.8/src/Illuminate/Foundation/helpers.php#L169).
I've created a little customization when there are no args in usage.
> HelperFunctionToDependencyInjectionRector fix

- src/Rector/MethodBody/FluentReplaceRector.php
- tests/Rector/MethodBody/FluentReplaceRector/Fixture/multiple_some_command.php.inc
- tests/Rector/MethodBody/FluentReplaceRector/Fixture/some_command.php.inc
- tests/Rector/MethodBody/FluentReplaceRector/FluentReplaceRectorTest.php
```yaml
services:
Rector\Rector\MethodBody\FluentReplaceRector:
$classesToDefluent:
- FluentInterfaceClass
- "*Command"
```
> Fix FluentReplaceRector for more than 2 calls + add * matching support

- packages/SOLID/config/config.yaml
- packages/SOLID/src/Analyzer/ClassConstantFetchAnalyzer.php
- packages/SOLID/src/Rector/ClassConst/PrivatizeLocalClassConstantRector.php
- packages/SOLID/tests/Rector/ClassConst/PrivatizeLocalClassConstantRector/Fixture/keep_public_parsing_order.php.inc
- packages/SOLID/tests/Rector/ClassConst/PrivatizeLocalClassConstantRector/PrivatizeLocalClassConstantRectorTest.php
- src/NodeContainer/ParsedNodesByType.php
Test case to demonstrate issue #1816.
1) The constant usages must be parsed before the class declaring the constant.
2) The class declaring the constant must be a subclass.
rector is then forced find the declaring class from the class hierarchy, which it can't when the declaring class and its superclasses haven't been parsed yet.
> Add test for #1816: Resolving constant fetches is unsafe 

- packages/SOLID/src/Rector/ClassConst/PrivatizeLocalClassConstantRector.php
- packages/SOLID/tests/Rector/ClassConst/PrivatizeLocalClassConstantRector/Fixture/override_protected_constant.php.inc
- packages/SOLID/tests/Rector/ClassConst/PrivatizeLocalClassConstantRector/Fixture/override_public_constant.php.inc
- packages/SOLID/tests/Rector/ClassConst/PrivatizeLocalClassConstantRector/PrivatizeLocalClassConstantRectorTest.php
When a constant is overridden in a subclass, it must have at least the access level of the superclass' constant. E.g. when the parent declares the constant `public`, the subclass _must_ also declare it as `public`, regardless if it's used or not.
It is possible to weaken the access level of a constant in a subclass, e.g. the superclass declares it as `private`, then the subclass can declare it `protected` or `public`. It's not allowed to have a more restrictive access level in a subclass tough.
If the access level of an overriding constant is not allowed, the PHP parser errors with:
`PHP Fatal error:  Access level to Subclass::OVERRIDDEN_CONSTANT must be [private|protected] (as in class Superclass::OVERRIDDEN_CONSTANT) or weaker in ... on line ...`
So what does that mean for rector: …
> Overriding constants require at least the parent's visibility

- packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
- src/Rector/Class_/RenameClassRector.php
- tests/Rector/Class_/RenameClassRector/Fixture/class_annotations.php.inc
- tests/Rector/Class_/RenameClassRector/RenameClassRectorTest.php
> [RenameClassRector] Include @ORM, @Assert, @Serializer etc annotations

- packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/SharedShortName.php
- packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/same_namespaced_class.php.inc
- packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/skip_same_namespaced_used_class.php.inc
- packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/ImportFullyQualifiedNamesRectorTest.php
- packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Source/SharedShortName.php
- packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
- rector.yaml
> [CodingStyle] Make import ImportFullyQualifiedNamesRector include same short class in same namespace

- packages/SOLID/src/Rector/ClassConst/PrivatizeLocalClassConstantRector.php
- packages/SOLID/tests/Rector/ClassConst/PrivatizeLocalClassConstantRector/Fixture/override_public_constant.php.inc
After my recent improvements on the `PrivatizeLocalClassConstantRector`, I've executed it on our big PHP project. Found out that the parent constant visibility is not detected correctly, when the constant is declared in the parent's parent or futher up the class hierarchy. This PR fixes the issue.
Worth mentioning: I've executed it on a project with 50k PHP files, did an almost perfect job. This issue was only a handful of cases. So :thumbsup: for rector!
> Parent constant visibility when it is declared in a super-superclass

- packages/CodingStyle/src/Imports/AliasUsesResolver.php
- packages/CodingStyle/src/Rector/Namespace_/ImportFullyQualifiedNamesRector.php
- packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/keep_aliased.php.inc
- packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/ImportFullyQualifiedNamesRectorTest.php
> [CodingStyle] Fix ImportFullyQualifiedNamesRector for imported namespace

- config/set/cakephp/cakephp36.yaml
- config/set/cakephp/cakephp37.yaml
- config/set/cakephp/cakephp38.yaml
- src/Rector/MethodCall/MethodCallToAnotherMethodCallWithArgumentsRector.php
There was only one rectorable deprecation in CakePHP 3.8
> Add cakephp3.8 target and fix a typo

- packages/NetteTesterToPHPUnit/src/Rector/Class_/NetteTesterClassToPHPUnitClassRector.php
- packages/NetteToSymfony/src/Route/RouteInfoFactory.php
- packages/PHPUnit/src/Rector/MethodCall/UseSpecificWillMethodRector.php
- packages/Php/src/Rector/ConstFetch/RenameConstantRector.php
- packages/Php/src/Rector/FunctionLike/Php4ConstructorRector.php
- src/PhpParser/Node/Resolver/NameResolver.php
- src/Rector/AbstractPHPUnitRector.php
- src/Rector/AbstractRector/NameResolverTrait.php
- src/Rector/Constant/RenameClassConstantRector.php
- src/Rector/Function_/RenameFunctionRector.php
- src/Rector/MethodCall/RenameMethodCallRector.php
- src/Rector/MethodCall/RenameMethodRector.php
- src/Rector/MethodCall/RenameStaticMethodRector.php
- src/Rector/Property/RenamePropertyRector.php
When working with legacy code, from technical point of view all names are insesntive:
```php
public function setUp() {}
```
is the same as:
```php
public function setup() {}
```
Saying that, all `*Name*` methods work will match both names
> merge isName and isNameInsensitive

- packages/DeadCode/src/Rector/If_/RemoveAlwaysTrueIfConditionRector.php
- packages/DeadCode/tests/Rector/If_/RemoveAlwaysTrueIfConditionRector/Fixture/fixture.php.inc
- packages/DeadCode/tests/Rector/If_/RemoveAlwaysTrueIfConditionRector/RemoveAlwaysTrueIfConditionRectorTest.php
> [DeadCode] Add RemoveAlwaysTrueIfConditionRector

- packages/TypeDeclaration/src/Contract/TypeInferer/ReturnTypeInfererInterface.php
- packages/TypeDeclaration/src/Rector/ClassMethod/AddArrayParamDocTypeRector.php
- packages/TypeDeclaration/src/Rector/ClassMethod/AddArrayReturnDocTypeRector.php
- packages/TypeDeclaration/src/Rector/FunctionLike/ReturnTypeDeclarationRector.php
- packages/TypeDeclaration/src/Rector/Property/PropertyTypeDeclarationRector.php
- packages/TypeDeclaration/src/TypeInferer/ParamTypeInferer.php
- packages/TypeDeclaration/src/TypeInferer/PropertyTypeInferer.php
- packages/TypeDeclaration/src/TypeInferer/ReturnTypeInferer.php
- packages/TypeDeclaration/src/TypeInferer/ReturnTypeInferer/ReturnedNodeReturnTypeInferer.php
- packages/TypeDeclaration/src/TypeInferer/ReturnTypeInferer/ReturnedPropertyReturnTypeInferer.php
- packages/TypeDeclaration/src/TypeInferer/ReturnTypeInferer/SetterNodeReturnTypeInferer.php
- packages/TypeDeclaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/CorrectionTest.php
- packages/TypeDeclaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/Correction/constructor_property_assign_over_getter.php.inc
```diff
{
private $decodedContents;
public function __construct(?array $decodedContents)
{
$this->decodedContents = $decodedContents;
}
-    public function getDecodedContents(): array
+    public function getDecodedContents(): ?array
{
return $this->decodedContents;
}
}
```
> [TypeDeclaration] Extend ReturnTypeDeclarationRector with incorrect types override

- config/set/phpunit/phpunit-code-quality.yaml
- ecs.yaml
- packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
- packages/NodeTypeResolver/src/StaticTypeMapper.php
- packages/NodeTypeResolver/src/StaticTypeToStringResolver.php
- packages/NodeTypeResolver/tests/PhpDoc/NodeAnalyzer/DocBlockManipulator/RemoveTest.php
- packages/NodeTypeResolver/tests/PhpDoc/NodeAnalyzer/DocBlockManipulatorTest.php
- packages/PHPUnit/config/config.yaml
- packages/PHPUnit/src/NodeFactory/DataProviderClassMethodFactory.php
- packages/PHPUnit/src/Rector/Class_/ArrayArgumentInTestToDataProviderRector.php
- packages/PHPUnit/src/ValueObject/DataProviderClassMethodRecipe.php
- packages/PHPUnit/src/ValueObject/ParamAndArgValueObject.php
- packages/PHPUnit/tests/Rector/Class_/AddSeeTestAnnotationRector/Fixture/skip_existing.php.inc
- packages/PHPUnit/tests/Rector/Class_/ArrayArgumentInTestToDataProviderRector/ArrayArgumentInTestToDataProviderRectorTest.php
- packages/PHPUnit/tests/Rector/Class_/ArrayArgumentInTestToDataProviderRector/Fixture/fixture.php.inc
- packages/PHPUnit/tests/Rector/Class_/ArrayArgumentInTestToDataProviderRector/Fixture/two_arguments.php.inc
- packages/PHPUnit/tests/Rector/Class_/ArrayArgumentInTestToDataProviderRector/Fixture/various_types.php.inc
- rector.yaml
Closes #1381
```php
class SomeServiceTest extends \PHPUnit\Framework\TestCase
{
public function test()
{
$this->doTestMultiple([1, 2, 3]);
}
}
```
```php
class SomeServiceTest extends \PHPUnit\Framework\TestCase
{
/**
* @dataProvider provideDataForTest()
*/
public function test(int $value)
{
$this->doTestSingle($value);
}
/**
* @return int[]
*/
public function provideDataForTest(): iterable
{
yield 1;
yield 2;
yield 3;
}
}
```
> [PHPUnit] Add array call to data provider

- packages/Doctrine/src/Rector/Class_/AddUuidMirrorForRelationPropertyRector.php
- packages/Doctrine/tests/Rector/Class_/AddUuidMirrorForRelationPropertyRector/AddUuidMirrorForRelationPropertyRectorTest.php
- packages/Doctrine/tests/Rector/Class_/AddUuidMirrorForRelationPropertyRector/Fixture/skip_one_to_one_mapped_by.php.inc
> add skip of one to one relations with mapped by

- packages/TypeDeclaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/CovarianceTest.php
- packages/TypeDeclaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/nikic/inheritance_covariance_order.php.inc
This test case shows how the order in which files are parsed & refactored can lead to incompatible method signatures on the return type. The rector does `populateChildren`, but the implementation implicity relies on the superclass being processed before its subclasses to ensure return type compatibility. This in combination with the subtype logic leads to this result.
(Note: Actually I have to say I don't really understand why this subtype logic is there, since [return type variance is only supported from PHP 7.4 on](https://wiki.php.net/rfc/covariant-returns-and-contravariant-parameters). Earlier versions support [type variance for the "iterable" type](https://www.php.net/manual/de/language.types.iterable.php#language.types.iterable.variance) which is there as the test case, but I have …
> Refactoring order creates incompatible return types

- packages/Doctrine/src/Rector/Class_/AlwaysInitializeUuidInEntityRector.php
- packages/Doctrine/tests/Rector/Class_/AlwaysInitializeUuidInEntityRector/AlwaysInitializeUuidInEntityRectorTest.php
- packages/Doctrine/tests/Rector/Class_/AlwaysInitializeUuidInEntityRector/Fixture/add_uuid_init.php.inc
- packages/Doctrine/tests/Rector/Class_/AlwaysInitializeUuidInEntityRector/Fixture/add_uuid_init_to_construct.php.inc
- packages/Doctrine/tests/Rector/Class_/AlwaysInitializeUuidInEntityRector/Fixture/skip_already_added.php.inc
- packages/Doctrine/tests/Rector/Class_/AlwaysInitializeUuidInEntityRector/Source/UuidInterface.php
```diff
/**
* @ORM\Id
* @var UuidInterface
*/
private $id;
+public function __construct()
+{
+    $this->id = \Ramsey\Uuid\Uuid::uuid4();
+}
```
> [Doctrine] Add AlwaysInitializeUuidInEntityRector

- docs/AllRectorsOverview.md
- packages/CodingStyle/src/Rector/ClassMethod/ReturnArrayClassMethodToYieldRector.php
- packages/Doctrine/src/NodeFactory/EntityUuidNodeFactory.php
- packages/PHPUnit/src/Rector/SpecificMethod/AssertCompareToSpecificMethodRector.php
- packages/PHPUnit/src/Rector/SpecificMethod/AssertIssetToSpecificMethodRector.php
- packages/Php/src/Rector/FuncCall/GetCalledClassToStaticClassRector.php
Noticed some typos in certain code samples so I fixed them. I also updated the docs.
> Code sample fixes

- config/set/doctrine/doctrine-id-to-uuid-step-3.yaml
- ecs.yaml
- packages/NodeTypeResolver/src/NodeTypeResolver.php
- packages/NodeTypeResolver/src/StaticTypeMapper.php
- packages/TypeDeclaration/src/Rector/ClassMethod/AddMethodCallBasedParamTypeRector.php
- packages/TypeDeclaration/tests/Rector/ClassMethod/AddMethodCallBasedParamTypeRector/AddMethodCallBasedParamTypeRectorTest.php
- packages/TypeDeclaration/tests/Rector/ClassMethod/AddMethodCallBasedParamTypeRector/Fixture/assigned_variable.php.inc
- packages/TypeDeclaration/tests/Rector/ClassMethod/AddMethodCallBasedParamTypeRector/Fixture/instant_class_call.php.inc
- packages/TypeDeclaration/tests/Rector/ClassMethod/AddMethodCallBasedParamTypeRector/Fixture/override.php.inc
- packages/TypeDeclaration/tests/Rector/ClassMethod/AddMethodCallBasedParamTypeRector/Fixture/second_position.php.inc
- packages/TypeDeclaration/tests/Rector/ClassMethod/AddMethodCallBasedParamTypeRector/Fixture/skip_already_completed.php.inc
- packages/TypeDeclaration/tests/Rector/ClassMethod/AddMethodCallBasedParamTypeRector/Fixture/skip_mixed.php.inc
- packages/TypeDeclaration/tests/Rector/ClassMethod/AddMethodCallBasedParamTypeRector/Fixture/static_call.php.inc
- packages/TypeDeclaration/tests/Rector/ClassMethod/AddMethodCallBasedParamTypeRector/Fixture/unioned_double_calls.php.inc
- packages/TypeDeclaration/tests/Rector/ClassMethod/AddMethodCallBasedParamTypeRector/Source/Apple.php
Closes #1887
```diff
class CallerClassForSecondPosition
{
{
$building = new Apple();
$someClass = new SecondPosition();
$someClass->process('hi', $building->getId());
}
}
class SecondPosition
{
-    public function process($name, $id)
+    public function process(string $name, \Ramsey\Uuid\UuidInterface $id)
{
}
}
```
> [TypeDeclaration] Add AddMethodCallBasedParamTypeRector

- config/set/php/php54.yaml
- packages/Php54/src/Rector/Break_/RemoveZeroBreakContinueRector.php
- packages/Php54/tests/Rector/Break_/RemoveZeroBreakContinueRector/Fixture/fixture.php.inc
- packages/Php54/tests/Rector/Break_/RemoveZeroBreakContinueRector/RemoveZeroBreakContinueRectorTest.php
Inspired https://github.com/PHPCompatibility/PHPModernizer/issues/1
> [Rector] Add RemoveZeroBreakContinueRector

- .travis.yml
- bin/run_all_sets.php
- config/set/celebrity/celebrity.yaml
- config/set/easy-corp/easy-admin-bundle20.yaml
- config/set/framework-migration/nette-to-symfony.yaml
- packages/NetteTesterToPHPUnit/src/Rector/RenameTesterTestToPHPUnitToTestFileRector.php
- packages/NodeTypeResolver/src/NodeTypeResolver.php
- src/Console/Command/SetsCommand.php
- src/DependencyInjection/Loader/RectorServiceParametersShifter.php
- src/DependencyInjection/Loader/TolerantRectorYamlFileLoader.php
- src/Set/SetProvider.php
Will prevent issues like: #2041
Closes #2042
> [CI] run all sets check

- config/set/code-quality/code-quality.yaml
- packages/CodeQuality/src/Rector/FuncCall/RemoveSoleValueSprintfRector.php
- packages/CodeQuality/tests/Rector/FuncCall/RemoveSoleValueSprintfRector/Fixture/fixture.php.inc
- packages/CodeQuality/tests/Rector/FuncCall/RemoveSoleValueSprintfRector/RemoveSoleValueSprintfRectorTest.php
> [CodeQuality] Add RemoveSoleValueSprintfRector

- bin/run_all_sets.php
- packages/Symfony/src/Rector/MethodCall/MakeDispatchFirstArgumentEventRector.php
- packages/Symfony/tests/Rector/MethodCall/MakeDispatchFirstArgumentEventRector/Fixture/get_class.php.inc
- packages/Symfony/tests/Rector/MethodCall/MakeDispatchFirstArgumentEventRector/MakeDispatchFirstArgumentEventRectorTest.php
> [Symfony] Make MakeDispatchFirstArgumentEventRector work with get_class

- packages/Php71/src/Rector/FuncCall/RemoveExtraParametersRector.php
- packages/Php71/tests/Rector/FuncCall/RemoveExtraParametersRector/Fixture/skip_values_passed_from_parent.php.inc
- packages/Php71/tests/Rector/FuncCall/RemoveExtraParametersRector/RemoveExtraParametersRectorTest.php
> [PHP 7.1] Skip extra argument removal for parent static call

- packages/CakePHP/src/Rector/MethodCall/RenameMethodCallBasedOnParameterRector.php
- packages/CakePHP/tests/Rector/MethodCall/RenameMethodCallBasedOnParameterRector/Fixture/fixture.php.inc
- packages/CakePHP/tests/Rector/MethodCall/RenameMethodCallBasedOnParameterRector/Fixture/fixture2.php.inc
- packages/CakePHP/tests/Rector/MethodCall/RenameMethodCallBasedOnParameterRector/RenameMethodCallBasedOnParameterRectorTest.php
- packages/CakePHP/tests/Rector/MethodCall/RenameMethodCallBasedOnParameterRector/Source/SomeModelType.php
We have a few renames in CakePHP that are parameter dependent. This rector lets a method be renamed based on the first parameter value. I've only supported string values as that is the current requirements.
> Add conditional method renaming rector

- packages/CodingStyle/src/Rector/ClassMethod/MakeInheritedMethodVisibilitySameAsParentRector.php
- packages/CodingStyle/tests/Rector/ClassMethod/MakeInheritedMethodVisibilitySameAsParentRector/Fixture/skip_static_ctor.php.inc
- packages/CodingStyle/tests/Rector/ClassMethod/MakeInheritedMethodVisibilitySameAsParentRector/SkipParentConstructOverrideInPHP72Test.php
> [CodingStyle] Allow private ctor override for static factory

- packages/CodingStyle/src/Rector/Use_/RemoveUnusedAliasRector.php
- packages/Symfony/src/Rector/Form/FormIsValidRector.php
- packages/Symfony/tests/Rector/Form/FormIsValidRector/Fixture/skip_negative_if.php.inc
- packages/Symfony/tests/Rector/Form/FormIsValidRector/Fixture/skip_nested_if.php.inc
> [Symfony] Fix is submitted

- packages/NodeTypeResolver/src/NodeTypeResolver.php
- packages/Symfony/src/Rector/New_/StringToArrayArgumentProcessRector.php
- phpstan.neon
> Fix type resolution for traversable

- docs/AllRectorsOverview.md
- packages/Symfony/src/Rector/VarDumper/VarDumperTestTraitMethodArgsRector.php
- packages/Symfony/tests/Rector/VarDumper/VarDumperTestTraitMethodArgsRector/Fixture/fixture.php.inc
In VarDumperTestTrait's asserts the third argument is called `$filter` and by default it should be equal to 0.
Right now it's called `$context` or `$format` and is set to null. Also `$data` argument is called `$format` sometimes.
`public function assertDumpEquals($expected, $data, $filter = 0, $message = '')`
`public function assertDumpMatchesFormat($expected, $data, $filter = 0, $message = '')` - 
https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/VarDumper/Test/VarDumperTestTrait.php
> Fixed the third argument in VarDumperTestTrait.

- packages/CodingStyle/src/Rector/ClassMethod/MakeInheritedMethodVisibilitySameAsParentRector.php
- packages/CodingStyle/tests/Rector/ClassMethod/MakeInheritedMethodVisibilitySameAsParentRector/Fixture/ParentWithPublicConstructor.php
- packages/CodingStyle/tests/Rector/ClassMethod/MakeInheritedMethodVisibilitySameAsParentRector/Fixture/skip_self_ctor.php.inc
- packages/CodingStyle/tests/Rector/ClassMethod/MakeInheritedMethodVisibilitySameAsParentRector/Fixture/skip_static_ctor.php.inc
- packages/CodingStyle/tests/Rector/ClassMethod/MakeInheritedMethodVisibilitySameAsParentRector/SkipParentConstructOverrideInPHP72Test.php
- packages/CodingStyle/tests/Rector/ClassMethod/MakeInheritedMethodVisibilitySameAsParentRector/Source/ParentWithPublicConstructor.php
`return new self();` was correctly handled, while `return new static();` was not. Now both are.
Fixes #2057
> Fixing 'return new static()' not being covered by MakeInheritedMethodVisibilitySameAsParentRector

- packages/CodingStyle/src/Rector/Namespace_/ImportFullyQualifiedNamesRector.php
- packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/import_root_namespace_classes_disabled.php.inc
- packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/import_root_namespace_classes_enabled.php.inc
- packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/ImportFullyQualifiedNamesRectorTest.php
- packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/ImportRootNamespaceClassesDisabledTest.php
- packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
- packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockNameImporter.php
Trying to fix https://github.com/rectorphp/rector/issues/1911#issuecomment-525642537
```yaml
services:
Rector\CodingStyle\Rector\Namespace_\ImportFullyQualifiedNamesRector:
$shouldImportRootNamespaceClasses: false
```
I still need to prevent changing DocBlock annotations like `@var \DateTime`... which seems way harder, looking at the code.
> Add an option to skip importing root namespace classes (like \DateTime)

- docs/AllRectorsOverview.md
- docs/NodesOverview.md
- packages/CodingStyle/src/Rector/Namespace_/ImportFullyQualifiedNamesRector.php
And update the docs while we're at it.
> Add documentation for ImportFullyQualifiedNamesRector new argument

- docs/AllRectorsOverview.md
- docs/NodesOverview.md
- packages/BetterPhpDocParser/src/AnnotationReader/NodeAnnotationReader.php
- packages/BetterPhpDocParser/src/PhpDocNodeFactory/JMS/SerializerTypePhpDocNodeFactory.php
- packages/BetterPhpDocParser/tests/PhpDocInfo/PhpDocInfoPrinter/MultilineTest.php
- packages/CodeQuality/src/Rector/If_/ShortenElseIfRector.php
- packages/Php55/src/Rector/FuncCall/PregReplaceEModifierRector.php
- phpstan.neon
- utils/DocumentationGenerator/src/Command/DumpNodesCommand.php
> Fix virtual property

- composer.json
- packages/CodingStyle/src/Rector/FuncCall/FunctionCallToConstantRector.php
- packages/CodingStyle/src/Rector/FuncCall/VersionCompareFuncCallToConstantRector.php
- packages/CodingStyle/tests/Rector/FuncCall/FunctionCallToConstantRector/FunctionCallToConstantRectorTest.php
- packages/CodingStyle/tests/Rector/FuncCall/VersionCompareFuncCallToConstantRector/VersionCompareFuncCallToConstantRectorTest.php
- packages/StrictCodeQuality/src/Rector/Stmt/VarInlineAnnotationToAssertRector.php
- packages/StrictCodeQuality/tests/Rector/Stmt/VarInlineAnnotationToAssertRector/Fixture/fixture.php.inc
- packages/StrictCodeQuality/tests/Rector/Stmt/VarInlineAnnotationToAssertRector/Fixture/scalar.php.inc
- packages/StrictCodeQuality/tests/Rector/Stmt/VarInlineAnnotationToAssertRector/VarInlineAnnotationToAssertRectorTest.php
- phpstan.neon
> [StrictCodeQuality] Add VarInlineAnnotationToAssertRector

- packages/CodingStyle/tests/Rector/ClassMethod/ReturnArrayClassMethodToYieldRector/Fixture/should_not_remove_comments.php.inc
- packages/CodingStyle/tests/Rector/ClassMethod/ReturnArrayClassMethodToYieldRector/Fixture/should_not_remove_doc_blocks.php.inc
- packages/CodingStyle/tests/Rector/ClassMethod/ReturnArrayClassMethodToYieldRector/ReturnArrayClassMethodToYieldRectorTest.php
See https://github.com/rectorphp/rector/issues/1846#issuecomment-537026517
> Add failing test case for ReturnArrayClassMethodToYieldRector (removing comments)

- packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/should_keep_all_doc_blocks_annotations_parameters.php.inc
- packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/ImportFullyQualifiedNamesRectorTest.php
I've finally been able to add `ImportFullyQualifiedNamesRector` to our project thanks to the new "skip root namespace" option. And I've noticed 3 nasty bugs in there (losing `@ORM\Table` argument, de-doubling of `@ORM\InheritanceType` argument, removing `@Route` arguments).
So I've added a test case with all these annotations, which resulted in : 
```diff
1) Rector\CodingStyle\Tests\Rector\Namespace_\ImportFullyQualifiedNamesRector\ImportFullyQualifiedNamesRectorTest::test with data set #22 ('/home/gnutix/dev/oss/rectorph...hp.inc')
Caused by /home/gnutix/dev/oss/rectorphp/rector/packages/CodingStyle/tests/Rector/Namespace_/ImportFullyQualifiedNamesRector/Fixture/should_keep_all_doc_blocks_annotations_parameters.php.inc
Failed asserting that string matches format description.
--- Expected …
```
> ImportFullyQualifiedNamesRector : add a failing test about modified annotations that shouldn't be

- packages/TypeDeclaration/src/TypeInferer/PropertyTypeInferer/AllAssignNodePropertyTypeInferer.php
- packages/TypeDeclaration/src/TypeInferer/PropertyTypeInferer/ConstructorPropertyTypeInferer.php
- packages/TypeDeclaration/src/TypeInferer/PropertyTypeInferer/GetterPropertyTypeInferer.php
- packages/TypeDeclaration/src/TypeInferer/PropertyTypeInferer/GetterTypeDeclarationPropertyTypeInferer.php
- packages/TypeDeclaration/src/TypeInferer/PropertyTypeInferer/SingleMethodAssignedNodePropertyTypeInferer.php
- packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/Fixture/skip_anonymous_class.php.inc
- packages/TypeDeclaration/tests/Rector/Property/PropertyTypeDeclarationRector/PropertyTypeDeclarationRectorTest.php
> skip var type in anonymous class for PropertyTypeDeclarationRector

- config/set/dead-code/dead-code.yaml
- packages/DeadCode/src/Rector/If_/SimplifyIfElseWithSameContentRector.php
- packages/DeadCode/tests/Rector/If_/SimplifyIfElseWithSameContentRector/Fixture/fixture.php.inc
- packages/DeadCode/tests/Rector/If_/SimplifyIfElseWithSameContentRector/Fixture/skip_different_content.php.inc
- packages/DeadCode/tests/Rector/If_/SimplifyIfElseWithSameContentRector/Fixture/skip_else_with_no_return.php.inc
- packages/DeadCode/tests/Rector/If_/SimplifyIfElseWithSameContentRector/Fixture/skip_missing_else.php.inc
- packages/DeadCode/tests/Rector/If_/SimplifyIfElseWithSameContentRector/Fixture/skip_more_than_return.php.inc
- packages/DeadCode/tests/Rector/If_/SimplifyIfElseWithSameContentRector/Fixture/with_else_ifs.php.inc
- packages/DeadCode/tests/Rector/If_/SimplifyIfElseWithSameContentRector/SimplifyIfElseWithSameContentRectorTest.php
- src/PhpParser/Node/Commander/NodeAddingCommander.php
> [DeadCode] Add SimplifyIfElseWithSameContentRector

- packages/StrictCodeQuality/src/Rector/Stmt/VarInlineAnnotationToAssertRector.php
- packages/StrictCodeQuality/tests/Rector/Stmt/VarInlineAnnotationToAssertRector/Fixture/assign_fresh_var.php.inc
- packages/StrictCodeQuality/tests/Rector/Stmt/VarInlineAnnotationToAssertRector/Fixture/skip_missing_variable.php.inc
- packages/StrictCodeQuality/tests/Rector/Stmt/VarInlineAnnotationToAssertRector/Fixture/skip_property.php.inc
- packages/StrictCodeQuality/tests/Rector/Stmt/VarInlineAnnotationToAssertRector/VarInlineAnnotationToAssertRectorTest.php
- phpstan.neon
Closes #2118
```diff
-/** @var int $value */
$int = $some->get();
+assert(is_int($value));
```
> [StrictCodeQuality] Add freshly created node support to var inline assert

- packages/CodingStyle/tests/Rector/Encapsed/EncapsedStringsToSprintfRector/EncapsedStringsToSprintfRectorTest.php
- packages/CodingStyle/tests/Rector/Encapsed/EncapsedStringsToSprintfRector/Fixture/fixture2.php.inc
```
vendor/bin/phpunit packages/CodingStyle/tests/Rector/Encapsed/EncapsedStringsToSprintfRector/EncapsedStringsToSprintfRectorTest.php
PHPUnit 7.5.0 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.3.9-1+ubuntu18.04.1+deb.sury.org+1
Configuration: /home/gnutix/dev/oss/rectorphp/rector/phpunit.xml
.F.                                                                 3 / 3 (100%)
Time: 1.49 seconds, Memory: 56.50MB
There was 1 failure:
1) Rector\CodingStyle\Tests\Rector\Encapsed\EncapsedStringsToSprintfRector\EncapsedStringsToSprintfRectorTest::test with data set #1 ('/home/gnutix/dev/oss/rectorph...hp.inc')
Caused by /home/gnutix/dev/oss/rectorphp/rector/packages/CodingStyle/tests/Rector/Encapsed/EncapsedStringsToSprintfRector/Fixture/fixture2.php.inc
Failed asserting that …
```
> EncapsedStringsToSprintfRector fails when using class properties

- config/set/phpunit/phpunit70.yaml
- packages/PHPUnit/src/Rector/Class_/RemoveDataProviderTestPrefixRector.php
- packages/PHPUnit/tests/Rector/Class_/RemoveDataProviderTestPrefixRector/Fixture/fixture.php.inc
- packages/PHPUnit/tests/Rector/Class_/RemoveDataProviderTestPrefixRector/Fixture/multiple_data_providers.php.inc
- packages/PHPUnit/tests/Rector/Class_/RemoveDataProviderTestPrefixRector/Fixture/with_test_annotation.php.inc
- packages/PHPUnit/tests/Rector/Class_/RemoveDataProviderTestPrefixRector/RemoveDataProviderTestPrefixRectorTest.php
Closes #2136
```diff
<?php
namespace App\Tests;
class SomeClass extends \PHPUnit\Framework\TestCase
{
/**
-      * @dataProvider testProvideData()
+      * @dataProvider provideData()
*/
public function test()
{
$nothing = 5;
}
-     public function testProvideData()
+     public function provideData()
{
return ['123'];
}
}
```
*Made with: https://www.quickdiff.com/*
> [PHPUnit] Add RemoveDataProviderTestPrefixRector

- packages/DeadCode/src/Rector/MethodCall/RemoveDefaultArgumentValueRector.php
- packages/DeadCode/tests/Rector/MethodCall/RemoveDefaultArgumentValueRector/Fixture/skip_system_function.php.inc
- packages/DeadCode/tests/Rector/MethodCall/RemoveDefaultArgumentValueRector/RemoveDefaultArgumentValueRectorTest.php
- packages/NodeTypeResolver/config/config.yaml
- packages/NodeTypeResolver/src/DependencyInjection/PHPStanServicesFactory.php
- src/Reflection/FunctionReflectionResolver.php
That prevents full-PHP-stub loading to get that their default value
> [DeadCode] Make RemoveDefaultArgumentValueRector skip native functions

- composer.json
- config/services.yaml
- docs/AllRectorsOverview.md
- src/Application/RectorApplication.php
This should prevent CI floods per line like these:
Now 20 steps are set
> Prevent CI floods with progress bar

- config/set/cakephp/cakephp40.yaml
This method is getting a split get/set which can be handled by rector.
> Add rules for ConsoleIo::styles()

- packages/Php73/src/Rector/FuncCall/RegexDashEscapeRector.php
- packages/Php73/tests/Rector/FuncCall/RegexDashEscapeRector/Fixture/false_positive.php.inc
- packages/Php73/tests/Rector/FuncCall/RegexDashEscapeRector/RegexDashEscapeRectorTest.php
This patch fixes this issue. But I suspect that there will be more edge cases which will not be fixed with this small patch. Perhaps it will be better to assure, that the escaping will only executed on hyphen in character classes.
> Fix for Issue2173

- config/set/code-quality/code-quality.yaml
- packages/Autodiscovery/src/Rector/FileSystem/MoveServicesBySuffixToDirectoryRector.php
- packages/BetterPhpDocParser/src/PhpDocParser/ClassAnnotationMatcher.php
- packages/CodeQuality/src/Rector/FuncCall/AddPregQuoteDelimiterRector.php
- packages/CodeQuality/tests/Rector/FuncCall/AddPregQuoteDelimiterRector/AddPregQuoteDelimiterRectorTest.php
- packages/CodeQuality/tests/Rector/FuncCall/AddPregQuoteDelimiterRector/Fixture/fixture.php.inc
- packages/CodeQuality/tests/Rector/FuncCall/AddPregQuoteDelimiterRector/Fixture/skip.php.inc
- packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockNameImporter.php
- packages/PHPUnit/src/Rector/Class_/ArrayArgumentInTestToDataProviderRector.php
- packages/PHPUnit/src/Rector/TryCatchToExpectExceptionRector.php
- rector.yaml
> [CodeQuality] Add AddPregQuoteDelimiterRector

- packages/NodeTypeResolver/src/DependencyInjection/PHPStanServicesFactory.php
In order to allow other libraries to provide a custom phpstan.neon configuration.
> [FEATURE] Possibility to add custom phpstan.neon configuration

- bin/bootstrap.php
- bin/container.php
- composer.json
- ecs.yaml
- src/Console/Option/SetOptionResolver.php
- src/DependencyInjection/RectorContainerFactory.php
- src/Set/Set.php
- src/Set/SetProvider.php
- src/Standalone/RectorStandaloneRunner.php
- src/Standalone/RectorStandaloneRunnerStaticFactory.php
- tests/DependencyInjection/RectorContainerFactoryTest.php
- tests/Standalone/RectorStandaloneRunnerTest.php
- tests/Standalone/Source/LowQualityFile.php
- utils/RectorGenerator/src/Configuration/ConfigurationFactory.php
This allows to use Rector as part of PHP scripts
> add Standalone Runner

- packages/Symfony/tests/Rector/Console/ConsoleExecuteReturnIntRector/ConsoleExecuteReturnIntRectorTest.php
- packages/Symfony/tests/Rector/Console/ConsoleExecuteReturnIntRector/Fixture/non-console-command.php.inc
When using `ConsoleExecuteReturnIntRector` on a class with an `execute` method that not extends from `Command` it adds the `return 0` and adds `: int`.
> Add test to ConsoleExecuteReturnIntRector for a not command class

- README.md
Hey there, this PR makes some (opinionated) changes to the grammar in the README, and standardizes casing in the section headings using traditional title case.
> Update grammar in the README for clarity

- packages/Symfony/src/Rector/Console/ConsoleExecuteReturnIntRector.php
- packages/Symfony/tests/Rector/Console/ConsoleExecuteReturnIntRector/ConsoleExecuteReturnIntRectorTest.php
- packages/Symfony/tests/Rector/Console/ConsoleExecuteReturnIntRector/Fixture/extends-command-not-directly.php.inc
Fixes: https://github.com/rectorphp/rector/pull/2200#issuecomment-546327783
> Fix ConsoleExecuteReturnIntRector if target class not directly extends Command

- packages/PHPUnit/src/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector.php
- packages/PHPUnit/tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/Fixture/keep_expected_exception.php.inc
Fix bug where rector added @doesNotPerformAssertion when using `setExpectedException`
> FIX AddDoesNotPerformAssertionToNonAssertingTest

- packages/Sensio/src/Rector/FrameworkExtraBundle/TemplateAnnotationRector.php
- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/Fixture/Version3/fixture.php.inc
- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/Fixture/Version3/fixture2.php.inc
- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/Fixture/Version3/fixture3.php.inc
- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/Fixture/Version3/fixture4.php.inc
- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/Fixture/Version3/skip_just_template.php.inc
- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/Fixture/Version5/fixture.php.inc
- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/Fixture/Version5/fixture2.php.inc
- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/Fixture/Version5/fixture3.php.inc
- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/Fixture/Version5/fixture4.php.inc
- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/Fixture/Version5/fixture5.php.inc
- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/Fixture/Version5/skip_without_template.php.inc
- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/Fixture/Version5/with_route_options.php.inc
- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/Fixture/Version5/without_base_class.php.inc
- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/TemplateAnnotationVersion5RectorTest.php
This is a first draft to fix #2215.
It seems to work, but I get an error from PHPStan which I don't understand.
Maybe you can help me with that?
> Add AbstractController as base class if no one exists

- src/Console/Command/ScreenFileCommand.php
```bash
vendor/bin/rector screen src/File.php
```
> make screen generate file by default

- packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
- packages/TypeDeclaration/tests/Rector/Property/CompleteVarDocTypePropertyRector/CompleteVarDocTypePropertyRectorTest.php
- packages/TypeDeclaration/tests/Rector/Property/CompleteVarDocTypePropertyRector/Fixture/skip_more_specific.php.inc
- packages/TypeDeclaration/tests/Rector/Property/CompleteVarDocTypePropertyRector/Source/SomeService.php
> [TypeDeclaration] Fix CompleteVarDocTypePropertyRector for mixed[] override

- packages/Doctrine/tests/Rector/Property/AddUuidAnnotationsToIdPropertyRector/Fixture/fixture.php.inc
- packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockClassRenamer.php
- packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
- packages/NodeTypeResolver/src/StaticTypeMapper.php
- packages/TypeDeclaration/tests/Rector/Property/CompleteVarDocTypePropertyRector/CompleteVarDocTypePropertyRectorTest.php
- packages/TypeDeclaration/tests/Rector/Property/CompleteVarDocTypePropertyRector/Fixture/keep_comment.php.inc
> keep comment on type change

- packages/Sensio/src/Rector/FrameworkExtraBundle/TemplateAnnotationRector.php
- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/Fixture/Version3/resolve_another_method_call.php.inc
- packages/Sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/TemplateAnnotationVersion3RectorTest.php
> add template nested

- ecs.yaml
- packages/DeadCode/src/Rector/ClassMethod/RemoveUnusedParameterRector.php
- packages/DeadCode/src/Rector/ClassMethod/RemoveUnusedPrivateMethodRector.php
- packages/DeadCode/src/Rector/Property/RemoveUnusedPrivatePropertyRector.php
- packages/DeadCode/src/Rector/StaticCall/RemoveParentCallWithoutParentRector.php
- packages/DeadCode/tests/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/no_usage_in_anonymous_class.php.inc
- packages/DeadCode/tests/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/no_usage_outside_anonymous_class.php.inc
- packages/DeadCode/tests/Rector/Property/RemoveUnusedPrivatePropertyRector/RemoveUnusedPrivatePropertyRectorTest.php
- packages/DeadCode/tests/Rector/StaticCall/RemoveParentCallWithoutParentRector/Fixture/anonymous_class_with_parent.php.inc
- packages/DeadCode/tests/Rector/StaticCall/RemoveParentCallWithoutParentRector/Fixture/anonymous_class_without_parent.php.inc
- packages/DeadCode/tests/Rector/StaticCall/RemoveParentCallWithoutParentRector/RemoveParentCallWithoutParentRectorTest.php
- packages/NodeTypeResolver/src/NodeVisitor/FunctionMethodAndClassNodeVisitor.php
- packages/NodeTypeResolver/tests/NodeVisitor/FunctionMethodAndClassNodeVisitor/FunctionMethodAndClassNodeVisitorTest.php
- packages/NodeTypeResolver/tests/NodeVisitor/FunctionMethodAndClassNodeVisitor/fixtures/anonymousClass.php.inc
- packages/NodeTypeResolver/tests/NodeVisitor/FunctionMethodAndClassNodeVisitor/fixtures/simple.php.inc
- src/PhpParser/BetterNodeDumper.php
- src/PhpParser/Node/Manipulator/PropertyManipulator.php
- src/Testing/PHPUnit/AbstractNodeVisitorTestCase.php
Also added test for nodeVisitors
I got a bit carried away while fixing a couple of issues that were caused by incorrect handling of anonymous classes.
> Better anonymous class handling

- ecs.yaml
I added a line feed parameter to ecs.yaml to enforce \n as line feed. It fixes the LineEndingFixer issue on windows.
> Fix ECS for windows

- README.md
- composer.json
- config/config.yaml
- rector-ci.yaml
- src/Console/Command/ProcessCommand.php
> [DX] add "paths" parameter

- packages/CodeQuality/src/Rector/Catch_/ThrowWithPreviousExceptionRector.php
- packages/CodeQuality/src/Rector/If_/ShortenElseIfRector.php
- packages/CodeQuality/tests/Rector/Catch_/ThrowWithPreviousExceptionRector/Fixture/skip_filled_exception_with_different_location.php.inc
- packages/CodeQuality/tests/Rector/Catch_/ThrowWithPreviousExceptionRector/Fixture/skip_missing_locatoin.php.inc
- packages/CodeQuality/tests/Rector/If_/ShortenElseIfRector/Fixture/skip_empty_else.php.inc
> improve stmt count check

- .travis.yml
- composer.json
- config/set/nette/nette-utils-code-quality.yaml
- packages/DynamicTypeAnalysis/config/config.yaml
- packages/DynamicTypeAnalysis/src/Probe/ProbeStaticStorage.php
- packages/DynamicTypeAnalysis/src/Probe/TypeStaticProbe.php
- packages/DynamicTypeAnalysis/src/Rector/ClassMethod/AbstractArgumentProbeRector.php
- packages/DynamicTypeAnalysis/src/Rector/ClassMethod/AddArgumentTypeWithProbeDataRector.php
- packages/DynamicTypeAnalysis/src/Rector/ClassMethod/DecorateMethodWithArgumentTypeProbeRector.php
- packages/DynamicTypeAnalysis/src/Rector/StaticCall/RemoveArgumentTypeProbeRector.php
- packages/DynamicTypeAnalysis/tests/Probe/TypeStaticProbeTest.php
- packages/DynamicTypeAnalysis/tests/Rector/ClassMethod/AddArgumentTypeWithProbeDataRector/AddArgumentTypeWithProbeDataRectorTest.php
- packages/DynamicTypeAnalysis/tests/Rector/ClassMethod/AddArgumentTypeWithProbeDataRector/Fixture/fixture.php.inc
- packages/DynamicTypeAnalysis/tests/Rector/ClassMethod/DecorateMethodWithArgumentTypeProbeRector/DecorateMethodWithArgumentTypeProbeRectorTest.php
- packages/DynamicTypeAnalysis/tests/Rector/ClassMethod/DecorateMethodWithArgumentTypeProbeRector/Fixture/fixture.php.inc
- packages/DynamicTypeAnalysis/tests/Rector/ClassMethod/DecorateMethodWithArgumentTypeProbeRector/Fixture/skip_non_public.php.inc
- packages/DynamicTypeAnalysis/tests/Rector/StaticCall/RemoveArgumentTypeProbeRector/Fixture/fixture.php.inc
- packages/DynamicTypeAnalysis/tests/Rector/StaticCall/RemoveArgumentTypeProbeRector/RemoveArgumentTypeProbeRectorTest.php
- packages/Nette/src/Rector/FuncCall/FilePutContentsToFileSystemWriteRector.php
- packages/Nette/tests/Rector/FuncCall/FilePutContentsToFileSystemWriteRector/FilePutContentsToFileSystemWriteRectorTest.php
- packages/Nette/tests/Rector/FuncCall/FilePutContentsToFileSystemWriteRector/Fixture/fixture.php.inc
- packages/NetteToSymfony/config/config.yaml
- phpstan.neon
- src/PhpParser/Node/Commander/NodeRemovingCommander.php
- utils/RectorGenerator/src/Command/CreateRectorCommand.php
cc @DaveLiddament I finally got to the idea we talked about in Venice :tada: 
Ref https://github.com/TomasVotruba/tomasvotruba.cz/issues/854
> [DynamicTypeAnalysis] Add Dynamic type infering

- ci/clean_trailing_spaces.sh
- composer.json
on macOs the -E option was taken as the argument of the -i option causing backups to be made with the addional extension -E.
also the backslash of the \s needed additional escaping
> Fixed issue with sed command:

- config/set/phpunit/phpunit80-dms.yaml
- packages/PHPUnit/src/Rector/MethodCall/ReplaceAssertArraySubsetWithDmsPolyfillRector.php
- packages/PHPUnit/tests/Rector/MethodCall/ReplaceAssertArraySubsetWithDmsPolyfillRector/Fixture/fixture.php.inc
- packages/PHPUnit/tests/Rector/MethodCall/ReplaceAssertArraySubsetWithDmsPolyfillRector/ReplaceAssertArraySubsetWithDmsPolyfillRectorTest.php
Closes #2138 
We got you covered:
```bash
composer require --dev dms/phpunit-arraysubset-asserts
vendor/bin/rector process tests --set phpunit80-dms
```
```diff
<?php
use PHPUnit\Framework\TestCase;
+use DMS\PHPUnitExtensions\ArraySubset\Assert;
final class SomeTest extends TestCase
{
public function testPreviouslyStaticCall(): void
{
-        $this->assertArraySubset(['bar' => 0], ['bar' => '0'], true);
+        Assert::assertArraySubset(['bar' => 0], ['bar' => '0'], true);
}
}
```
:+1:
> [PHPUnit 8.0] Add ReplaceAssertArraySubsetWithDmsPolyfillRector

- composer.json
- packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/FixtureUnionTypes/multiple_types.php.inc
- packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/UnionTypeCompleteDynamicPropertiesRectorTest.php
- packages/NodeTypeResolver/src/StaticTypeMapper.php
- packages/Php74/src/Rector/Property/TypedPropertyRector.php
- packages/Php74/tests/Rector/Property/TypedPropertyRector/FixtureUnionTypes/two_types.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/UnionTypedPropertyRectorTest.php
- packages/Php80/src/Rector/FunctionLike/UnionTypesRector.php
- packages/Php80/tests/Rector/FunctionLike/UnionTypesRector/Fixture/fixture.php.inc
- packages/Php80/tests/Rector/FunctionLike/UnionTypesRector/UnionTypesRectorTest.php
- packages/TypeDeclaration/src/Rector/FunctionLike/AbstractTypeDeclarationRector.php
- packages/TypeDeclaration/tests/Rector/ClassMethod/AddMethodCallBasedParamTypeRector/AddMethodCallBasedParamTypeRectorTest.php
- packages/TypeDeclaration/tests/Rector/Closure/AddClosureReturnTypeRector/AddClosureReturnTypeRectorTest.php
- packages/TypeDeclaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/Fixture/undesired.php.inc
- packages/TypeDeclaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/FixtureUnionType/undesired.php.inc
- packages/TypeDeclaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/UnionTypeParamTypeDeclarationRectorTest.php
- packages/TypeDeclaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/CorrectionTest.php
- packages/TypeDeclaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/ReturnTypeDeclarationRectorTest.php
- phpstan.neon
- src/ValueObject/PhpVersionFeature.php
- utils/RectorGenerator/src/Configuration/ConfigurationFactory.php
Closes #2290
```diff
<?php
{
-    /**
-     * @param array|int $number
-     * @return bool|float
-     */
-    public function go($number)
+    public function go(array|int $number): bool|float
{
}
}
```
> [PHP 8.0] Add union types

- config/set/phpunit/phpunit-injector.yaml
- packages/CodeQuality/src/Rector/Class_/CompleteDynamicPropertiesRector.php
- packages/CodeQuality/tests/Rector/Class_/CompleteDynamicPropertiesRector/CompleteDynamicPropertiesRectorTest.php
- packages/PHPUnit/src/Manipulator/OnContainerGetCallManipulator.php
- packages/PHPUnit/src/Rector/Class_/SelfContainerGetMethodCallFromTestToInjectPropertyRector.php
- packages/PHPUnit/tests/Rector/Class_/SelfContainerGetMethodCallFromTestToInjectPropertyRector/Fixture/another_case_test.php.inc
- packages/PHPUnit/tests/Rector/Class_/SelfContainerGetMethodCallFromTestToInjectPropertyRector/Fixture/fixture.php.inc
- packages/PHPUnit/tests/Rector/Class_/SelfContainerGetMethodCallFromTestToInjectPropertyRector/Fixture/from_set_up_to_inject.php.inc
- packages/PHPUnit/tests/Rector/Class_/SelfContainerGetMethodCallFromTestToInjectPropertyRector/SelfContainerGetMethodCallFromTestToInjectPropertyRectorTest.php
- packages/PHPUnit/tests/Rector/Class_/SelfContainerGetMethodCallFromTestToInjectPropertyRector/Source/RandomElasticClient.php
- packages/PHPUnit/tests/Rector/Class_/SelfContainerGetMethodCallFromTestToInjectPropertyRector/Source/TestCaseWithGetContainer.php
- packages/Php71/src/Rector/FuncCall/CountOnNullRector.php
- packages/Php74/src/Rector/Assign/NullCoalescingOperatorRector.php
- packages/Php74/src/Rector/Closure/ClosureToArrowFunctionRector.php
- packages/Php74/src/Rector/LNumber/AddLiteralSeparatorToNumberRector.php
- packages/Php74/src/Rector/Property/TypedPropertyRector.php
- packages/SymfonyPHPUnit/src/Node/KernelTestCaseNodeAnalyzer.php
- packages/SymfonyPHPUnit/src/Rector/Class_/SelfContainerGetMethodCallFromTestToSetUpMethodRector.php
- packages/SymfonyPHPUnit/src/SelfContainerMethodCallCollector.php
- packages/SymfonyPHPUnit/tests/Rector/Class_/SelfContainerGetMethodCallFromTestToSetUpMethodRector/Fixture/existing_setup.php.inc
- packages/TypeDeclaration/tests/Rector/ClassMethod/AddMethodCallBasedParamTypeRector/AddMethodCallBasedParamTypeRectorTest.php
- packages/TypeDeclaration/tests/Rector/Closure/AddClosureReturnTypeRector/AddClosureReturnTypeRectorTest.php
- packages/TypeDeclaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/ParamTypeDeclarationRectorTest.php
- packages/TypeDeclaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/ReturnTypeDeclarationRectorTest.php
- src/Naming/PropertyNaming.php
- src/PhpParser/Node/Manipulator/ClassManipulator.php
- src/ValueObject/PhpVersionFeature.php
- stubs/Symfony/Bundle/FrameworkBundle/Test/KernelTestCase.php
- stubs/Symfony/Bundle/FrameworkBundle/Test/WebTestCase.php
Closes #2296 
Migration on `$container->get(x)` to https://github.com/jakzal/phpunit-injector
```bash
composer require zalas/phpunit-injector --dev
vendor/bin/rector process tests --set phpunit-injector
```
> [PHPUnit][Symfony] Add jakzal-injetor Rector

- packages/Php52/src/Rector/Switch_/ContinueToBreakInSwitchRector.php
- packages/Php52/tests/Rector/Switch_/ContinueToBreakInSwitchRector/Fixture/skip_continue_with_argument.php.inc
Closes https://github.com/rectorphp/rector/issues/2345
>  [PHP] ContinueToBreakInSwitchRector skip continue with argument >1

- README.md
- src/Configuration/Configuration.php
- src/Configuration/Option.php
- src/Console/Command/ProcessCommand.php
- src/FileSystem/FilesFinder.php
- tests/FileSystem/FilesFinder/FilesFinderTest.php
This pull request adds the option `--must-match-git-diff` to the process command, this is useful for both local and CI execution.
It should be compatible with the rest of the configuration because creates an intersection with the `git diff` output.
> Add diff based execution

- .gitignore
- packages/Symfony/src/Rector/Console/ConsoleExecuteReturnIntRector.php
- packages/Symfony/tests/Rector/Console/ConsoleExecuteReturnIntRector/Fixture/skip_function_nested_return.php.inc
- packages/Symfony/tests/Rector/Console/ConsoleExecuteReturnIntRector/Fixture/skip_nested_return.php.inc
> [Symfony] Fix ConsoleExecuteReturnInt for nested functions

- Dockerfile
This PR uses PHP 7..4 in the docker image. Otherwise after using (for example) `Rector\Php74\Rector\Closure\ClosureToArrowFunctionRector`, rector will be unable to process the changed files.
```
[ERROR] Could not process
"/project/MyClass.php" file, due to:
"Analyze error: "ParseError (syntax error, unexpected '=>'
(T_DOUBLE_ARROW), expecting ')') thrown while autoloading class
MyClass.". Include your files in
"parameters > autoload_paths".
See https://github.com/rectorphp/rector#extra-autoloading".
```
> chore: use php 7.4 cli

- packages/CodingStyle/src/Rector/MethodCall/PreferThisOrSelfMethodCallRector.php
- packages/DeadCode/src/Rector/StaticCall/RemoveParentCallWithoutParentRector.php
- packages/Php71/src/Rector/FuncCall/RemoveExtraParametersRector.php
- packages/Php74/src/Rector/StaticCall/ExportToReflectionFunctionRector.php
- packages/Symfony/src/Rector/Process/ProcessBuilderInstanceRector.php
- src/FileSystem/FilesFinder.php
- src/PhpParser/Node/Resolver/NameResolver.php
- src/Rector/Argument/ArgumentAdderRector.php
- src/Rector/ClassMethod/AddMethodParentCallRector.php
> Make sure name is passed to getName(), instead of expr

- .gitattributes
- src/PhpParser/Node/Manipulator/PropertyManipulator.php
- src/Stubs/StubLoader.php
Closes #1899
cc @gnutix
In the end, I come to conclussion it's better to have PHPStorm 100 % working and one PHPUnit migration with extra class, rather then the other way.
Thanks for your feedback
> Exludes stubs on package install to prevent PHPStorm confussion

- .travis.yml
- packages/CodeQuality/src/Rector/Class_/CompleteDynamicPropertiesRector.php
- packages/Doctrine/src/NodeFactory/EntityUuidNodeFactory.php
- packages/RemovingStatic/src/Rector/Class_/StaticTypeToSetterInjectionRector.php
- packages/RemovingStatic/src/UniqueObjectFactoryFactory.php
- packages/Symfony/src/Rector/Class_/MakeCommandLazyRector.php
- src/PhpParser/Node/NodeFactory.php
> Fix CompleteDynamicPropertiesRector to add parent property

- src/PhpParser/Node/Resolver/NameResolver.php
> return false on MethodCall name to prevent expr errors

- src/ValueObject/PhpVersionFeature.php
Iterable type hint was introduced in PHP 7.1
https://www.php.net/manual/en/language.types.iterable.php
> Fix - iterable type introduced in PHP 7.1

- config/set/phalcon/phalcon40.yaml
- packages/CodeQuality/src/Rector/FuncCall/AddPregQuoteDelimiterRector.php
- phpstan.neon
- rector.yaml
- src/Rector/StaticCall/SwapClassMethodArgumentsRector.php
- tests/Rector/StaticCall/SwapClassMethodArgumentsRector/Fixture/fixture.php.inc
- tests/Rector/StaticCall/SwapClassMethodArgumentsRector/SwapClassMethodArgumentsRectorTest.php
- utils/RectorGenerator/config/config.yaml
> [Phalcon 4] Add SwapClassMethodArgumentsRector rule

- packages/Php53/tests/Rector/Ternary/TernaryToElvisRector/Fixture/parenthesis.php.inc
- src/Rector/New_/NewToStaticCallRector.php
Add test case for removing paranthesis when replacing ternary operator with elvis operator
> Add test case for removing paranthesis in TernaryToElvisRector

- composer.json
- packages/BetterPhpDocParser/src/Printer/OriginalSpacingRestorer.php
- packages/CodingStyle/src/Rector/FuncCall/CallUserFuncCallToVariadicRector.php
- packages/CodingStyle/tests/Rector/FuncCall/CallUserFuncCallToVariadicRector/Fixture/skip_unknown_value.php.inc
- packages/NodeTypeResolver/src/NodeTypeResolver.php
- packages/NodeTypeResolver/src/StaticTypeMapper.php
- packages/PHPUnit/src/Rector/MethodCall/WithConsecutiveArgToArrayRector.php
- packages/PHPUnit/src/Rector/TryCatchToExpectExceptionRector.php
- packages/PSR4/src/Rector/Namespace_/NormalizeNamespaceByPSR4ComposerAutoloadRector.php
- packages/Php53/src/Rector/Ternary/TernaryToElvisRector.php
- packages/Php53/tests/Rector/Ternary/TernaryToElvisRector/Fixture/fixture.php.inc
- packages/Php53/tests/Rector/Ternary/TernaryToElvisRector/Fixture/parenthesis.php.inc
- packages/Php53/tests/Rector/Ternary/TernaryToElvisRector/Fixture/yolo.php.inc
- packages/Php56/src/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector.php
- packages/Php56/tests/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/Fixture/skip_this_assign.php.inc
- packages/Php71/src/Rector/FuncCall/CountOnNullRector.php
- phpstan.neon
- rector.yaml
- src/Rector/Argument/ArgumentDefaultValueReplacerRector.php
- Closes #2422
- Closes #2421 
- Ref #2432
- Closes #2425 
- Closes #2430 
- Closes #2419
> Various fixes

- packages/PHPUnit/src/Rector/SpecificMethod/AssertCompareToSpecificMethodRector.php
- packages/PHPUnit/tests/Rector/SpecificMethod/AssertCompareToSpecificMethodRector/Fixture/count.php.inc
- packages/PHPUnit/tests/Rector/SpecificMethod/AssertCompareToSpecificMethodRector/Fixture/fixture.php.inc
- packages/PHPUnit/tests/Rector/SpecificMethod/AssertCompareToSpecificMethodRector/Fixture/get_class.php.inc
- packages/Php72/src/Rector/ConstFetch/BarewordStringRector.php
- rector.yaml
> [PHPUnit] Add get_class double sided to AssertCompareToSpecificMethodRector

- packages/Php74/src/Rector/Property/TypedPropertyRector.php
This rector does not remove the PHPDoc.
> Fix codesample in TypedPropertyRector

- docs/AllRectorsOverview.md
This rector does not remove the PHPDoc.
> [docs] Fix codesample in TypedPropertyRector

- config/set/dead-code/dead-code.yaml
- packages/DeadCode/src/Rector/Ternary/TernaryToBooleanOrFalseToBooleanAndRector.php
- packages/DeadCode/tests/Rector/Ternary/TernaryToBooleanOrFalseToBooleanAndRector/Fixture/fixture.php.inc
- packages/DeadCode/tests/Rector/Ternary/TernaryToBooleanOrFalseToBooleanAndRector/TernaryToBooleanOrFalseToBooleanAndRectorTest.php
> [DeadCode] Add TernaryToBooleanOrFalseToBooleanAndRector

- packages/Php53/src/Rector/FuncCall/DirNameFileConstantToDirConstantRector.php
- packages/Php53/src/Rector/Ternary/TernaryToElvisRector.php
- packages/Php55/src/Rector/String_/StringClassNameToClassConstantRector.php
- packages/Php56/src/Rector/FuncCall/PowToExpRector.php
- packages/Php70/src/Rector/FuncCall/MultiDirnameRector.php
- packages/Php70/src/Rector/FuncCall/RandomFunctionRector.php
- packages/Php70/src/Rector/FunctionLike/ExceptionHandlerTypehintRector.php
- packages/Php70/src/Rector/If_/IfToSpaceshipRector.php
- packages/Php70/src/Rector/List_/ListSwapArrayOrderRector.php
- packages/Php71/src/Rector/ClassConst/PublicConstantVisibilityRector.php
- packages/Php71/src/Rector/List_/ListToArrayDestructRector.php
- packages/Php71/src/Rector/TryCatch/MultiExceptionCatchRector.php
- packages/Php73/src/Rector/FuncCall/JsonThrowOnErrorRector.php
- packages/Php74/src/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector.php
- packages/Php74/src/Rector/FuncCall/GetCalledClassToStaticClassRector.php
- packages/Php74/src/Rector/MagicConstClass/ClassConstantToSelfClassRector.php
- src/ValueObject/PhpVersionFeature.php
This PR adds more PHP version checks to the PHP rectors.
> [PHP] add PHP version feature checks

- packages/NodeTypeResolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
- packages/NodeTypeResolver/src/StaticTypeMapper.php
- packages/TypeDeclaration/tests/Rector/ClassMethod/AddArrayReturnDocTypeRector/Fixture/with_comment.php.inc
> Fix AddArrayReturnDocTypeRector for existing comment

- packages/Php74/src/Rector/Property/TypedPropertyRector.php
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/parent_has_untyped_property.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/parent_of_parent_has_untyped_property.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Source/SomeParent.php
- packages/Php74/tests/Rector/Property/TypedPropertyRector/TypedPropertyRectorTest.php
- packages/TypeDeclaration/src/VendorLock/VendorLockResolver.php
When the property is defined in vendored code, it doesn't make sense to suggest typed properties on classes that extend from it.
Fixes https://github.com/rectorphp/rector/issues/2506
> Do not suggest typed property when defined in vendored parent

- config/set/code-quality/code-quality.yaml
- packages/CodeQuality/src/Rector/Foreach_/SimplifyForeachToCoalescingRector.php
- packages/CodeQuality/src/Rector/Ternary/ArrayKeyExistsTernaryThenValueToCoalescingRector.php
- packages/CodeQuality/tests/Rector/Ternary/ArrayKeyExistsTernaryThenValueToCoalescingRector/ArrayKeyExistsTernaryThenValueToCoalescingRectorTest.php
- packages/CodeQuality/tests/Rector/Ternary/ArrayKeyExistsTernaryThenValueToCoalescingRector/Fixture/fixture.php.inc
- packages/CodeQuality/tests/Rector/Ternary/ArrayKeyExistsTernaryThenValueToCoalescingRector/Fixture/skip_mismatch.php.inc
> [CodeQuality] Add ArrayKeyExistsTernaryThenValueToCoalescingRector

- packages/NodeTypeResolver/src/StaticTypeMapper.php
- packages/Php74/src/Rector/Property/TypedPropertyRector.php
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/bool_property.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/class_property.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/complex_array.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/default_values.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/default_values_for_nullable_iterables.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/match_types.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/match_types_parent.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/non_array_generic_types.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/nullable_property.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/nullable_property_scalar.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/parent_has_untyped_property.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/parent_of_parent_has_untyped_property.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/property.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/simple_array.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/static_property.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/FixturePhp74/parent_has_untyped_property.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/FixturePhp74/parent_of_parent_has_untyped_property.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/FixtureUnionTypes/two_types.php.inc
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Source/SomeParent.php
- packages/Php74/tests/Rector/Property/TypedPropertyRector/TypedPropertyRectorTest.php
Closes #2367 propperly
```diff
/**
* @var int
*/
-public $count;
+public int $count;
```
```diff
-/**
- * @var int
- */
-public $count;
+public int $count;
```
/cc @brendt @enumag @collapso @mallardduck @ruudk
> [PHP 7.4] Add @var removal to TypedPropertyRector

- packages/NodeTypeResolver/src/StaticTypeMapper.php
- packages/NodeTypeResolver/tests/StaticTypeMapper/StaticTypeMapperTest.php
- phpstan.neon
@enumag Apperently, only edge-case is generic `array`, that needs to be converted to array. It's treated as object without that, e.g. FQN by default `\array` and other problems.
Maybe there is more space for improvement. What do you think?
> improve generic type conversion

- packages/Php71/tests/Rector/FuncCall/CountOnNullRector/Fixture/skip_countable_local_property.php.inc
- packages/Php71/tests/Rector/FuncCall/CountOnNullRector/Fixture/skip_countable_remote_property.php.inc
- packages/Php71/tests/Rector/FuncCall/CountOnNullRector/Source/ClassWithCountableProperty.php
Managed to create a failing test for https://github.com/rectorphp/rector/issues/2474
> [Php71] Add failing test case for CountOnNullRector

- composer.json
- packages/MinimalScope/src/Rector/Class_/ChangeLocalPropertyToVariableRector.php
- packages/MinimalScope/tests/Rector/Class_/ChangeLocalPropertyToVariableRector/ChangeLocalPropertyToVariableRectorTest.php
- packages/MinimalScope/tests/Rector/Class_/ChangeLocalPropertyToVariableRector/Fixture/fixture.php.inc
> [MinimalScope] Add ChangeLocalPropertyToVariableRector

- config/set/code-quality/code-quality.yaml
- packages/CodeQuality/src/Rector/For_/ForRepeatedCountToOwnVariableRector.php
- packages/CodeQuality/tests/Rector/For_/ForRepeatedCountToOwnVariableRector/Fixture/fallback_for_complex.php.inc
- packages/CodeQuality/tests/Rector/For_/ForRepeatedCountToOwnVariableRector/Fixture/fixture.php.inc
- packages/CodeQuality/tests/Rector/For_/ForRepeatedCountToOwnVariableRector/Fixture/method_call_count.php.inc
- packages/CodeQuality/tests/Rector/For_/ForRepeatedCountToOwnVariableRector/ForRepeatedCountToOwnVariableRectorTest.php
> [CodeQuality] Add ForRepeatedCountToOwnVariableRector

- config/config.yaml
- packages/NodeTypeResolver/src/PHPStan/Scope/NodeVisitor/RemoveDeepChainMethodCallNodeVisitor.php
> make nested chain call remove configurable

- config/set/symfony/symfony50-types.yaml
- config/set/symfony/symfony50.yaml
Closes #2446 
Covers: https://symfony.com/blog/symfony-type-declarations-return-types-and-phpunit-compatibility
```bash
vendor/bin/rector process src --set symfony50-types
```
> [Symfony 5] Add param types

- .travis.yml
- phpunit.xml
Inspired by https://kizu514.com/blog/phpdbg-is-much-faster-than-xdebug-for-code-coverage/
> travis: try phpdbg

- composer.json
- config/set/polyfill/unwrap-compat.yaml
- packages/Polyfill/config/config.yaml
- packages/Polyfill/src/FeatureSupport/FunctionSupportResolver.php
- packages/Polyfill/src/Rector/If_/UnwrapFutureCompatibleIfRector.php
- packages/Polyfill/tests/Rector/If_/UnwrapFutureCompatibleIfRector/Fixture/fixture.php.inc
- packages/Polyfill/tests/Rector/If_/UnwrapFutureCompatibleIfRector/UnwrapFutureCompatibleIfRectorTest.php
- src/PhpParser/Node/Manipulator/IfManipulator.php
> [Polyfill] Add UnwrapFutureCompatibleIfRector

- .travis.yml
Similar to https://github.com/rectorphp/rector/pull/2576
Related article from the same source.. lets try
https://kizu514.com/blog/pcov-is-better-than-phpdbg-and-xdebug-for-code-coverage/
https://github.com/krakjoe/pcov
> Try pcov for code coverage

- compiler/build/scoper.inc.php
- compiler/composer.json
- composer.json
- docs/AllRectorsOverview.md
- packages/NetteToSymfony/src/Rector/MethodCall/FromHttpRequestGetHeaderToHeadersGetRector.php
- packages/NetteToSymfony/tests/Rector/ClassMethod/RouterListToControllerAnnotationsRetor/Fixture/with_parameter.php.inc
- packages/NetteToSymfony/tests/Rector/Class_/NetteFormToSymfonyFormRector/Source/NettePresenter.php
- packages/NetteToSymfony/tests/Rector/MethodCall/FromHttpRequestGetHeaderToHeadersGetRector/Fixture/fixture.php.inc
- phpstan.neon
- src/HttpKernel/RectorKernel.php
- stubs/Nette/Forms/Form.php
- tests/DependencyInjection/RectorContainerFactoryTest.php
This might need to automate in the future. Something like merge PHPStan's `scoper.php.inc` with Rector's or unpack/pack PHSPtan phar.
See conversation https://github.com/rectorphp/rector/pull/2575#issuecomment-571133000
> Update compiler with PHPStan 0.12.4 workflow change

- .github/workflows/push.yml
- .travis.yml
parallize more jobs to speedup the overall CI build time.
In GithubActions we can get up to 8 parallel workers, while on travis its limited to 4.
current overall build time is ~17-18 min. distribution of the jobs should make it faster.
> Transition some travis checks to GithubActions

- .github/workflows/push.yml
- .travis.yml
You should configure the new checks to be required in case those were required before (in github branch protection).
In case it is essentiell that the „compile phar“ travis job only runs after all (including those beeing removed with this PR) previous jobs went green/successfull we should think about the job design.. (I guess travis ci does not know about status of single github actions and vice versa)
> Remove travis-CI jobs which were moved to GithubAction

- packages/DeadCode/src/Rector/FunctionLike/RemoveDeadReturnRector.php
This is a more reliable way of getting the last array element (preserving the internal pointer), especially when the keys of the stmt gets scrambled by unsetting items.
> more reliable way getting last stmt

- compiler/build/box.json
- compiler/build/scoper.inc.php
> Remove stubs/ from rector.phar

- packages/DeadCode/src/Rector/ClassMethod/RemoveDelegatingParentCallRector.php
The key values are not reliable, this problem is caused by unsetting the values in the stmts array of a node without resetting them. It's not only in this rector file and might need a bigger fix, but this one was bugging me whole day.
> More reliable way getting first stmt item

- packages/PHPUnit/src/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector.php
- packages/PHPUnit/tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/Fixture/skip_existing_annotation.php.inc
> [AddDoesNotPerformAssertionToNonAssertingTestRector] fix skipping if annotation already exists (fixes infinite loop too)

- config/set/php/php70.yaml
- docs/AllRectorsOverview.md
- packages/CodeQuality/src/Rector/For_/ForRepeatedCountToOwnVariableRector.php
- packages/Php70/config/config.yaml
- packages/Php70/src/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector.php
- packages/Php70/src/Reflection/CallReflection.php
- packages/Php70/src/ValueObject/VariableAssignPair.php
- packages/Php70/tests/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector/Fixture/assignment.php.inc
- packages/Php70/tests/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector/Fixture/binary_op.php.inc
- packages/Php70/tests/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector/Fixture/func_calls.php.inc
- packages/Php70/tests/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector/Fixture/keep_array_dim_fetch.php.inc
- packages/Php70/tests/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector/Fixture/keep_property_fetch.php.inc
- packages/Php70/tests/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector/Fixture/keep_static_property_fetch.php.inc
- packages/Php70/tests/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector/Fixture/keep_variable.php.inc
- packages/Php70/tests/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector/Fixture/method_call_as_argument.php.inc
- packages/Php70/tests/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector/Fixture/method_calls.php.inc
- packages/Php70/tests/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector/Fixture/new.php.inc
- packages/Php70/tests/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector/Fixture/skip_optional_parameter.php.inc
- packages/Php70/tests/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector/NonVariableToVariableOnFunctionCallRectorTest.php
- phpstan.neon
- src/Rector/AbstractRector.php
Still WIP.
Creating it to gather first reviews.
> [Php70] add a rector to pass only variables as arguments by reference

- packages/NodeTypeResolver/src/NodeTypeResolver.php
> [CountOnNullRector] fix Rector applying on properties with phpdocs array

- packages/PHPUnit/tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/Fixture/skip_prophecy_assertions.php.inc
- packages/PHPUnit/tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/Source/Denormalizer.php
- packages/PHPUnit/tests/Rector/ClassMethod/AddDoesNotPerformAssertionToNonAssertingTestRector/Source/DenormalizerInterface.php
> [gnutix] Is this Rector developed with other testing framework than PHPUnit in mind ? (like Prophecy)
> [Tomas] Sure, whatever real case this rule should cover.
(from https://github.com/rectorphp/rector/issues/2634)
Here's a failing test case for this (currently it adds the annotation to the method yet it should not).
However, I'm not interested in implementing a fix myself, as it's ignored from my project anyway and I already wasted way too much time on this one : I'd rather focus on other issues (or take a break :smile: ). I could upgrade this Rector's documentation to state that it currently does not support Prophecy and any help in implementing it is welcome though.
> [AddDoesNotPerformAssertionToNonAssertingTestRector] Add failing test for Prophecy assertions.

- composer.json
- ecs.yaml
- packages/NodeTypeResolver/config/config.yaml
- packages/NodeTypeResolver/src/DependencyInjection/PHPStanServicesFactory.php
- packages/NodeTypeResolver/src/Finder/PHPStanTypeClassFinder.php
- packages/NodeTypeResolver/src/StaticTypeMapper.php
- packages/NodeTypeResolver/tests/StaticTypeMapper/StaticTypeMapperTest.php
- packages/PHPStanStaticTypeMapper/config/config.yaml
- packages/PHPStanStaticTypeMapper/src/PHPStanStaticTypeMapper.php
- packages/TypeDeclaration/tests/Rector/Property/CompleteVarDocTypePropertyRector/Fixture/symfony_console_helper_set.php.inc
- rector.yaml
- stubs/Symfony/Component/Console/Helper/HelperSet.php
Follow up to design cleanup in https://github.com/rectorphp/rector/pull/2649
Moving from god classes to collector pattern and CI checked compatbility with PHPStan types
Closes #2614
> Decouple PHPStanStaticTypeMapper

- .github/workflows/rector_phar.yml
In combination with https://github.com/rectorphp/rector-prefixed/pull/7
> Fix sync releases with rector-prefixed

- docs/AllRectorsOverview.md
- src/Rector/Visibility/ChangeMethodVisibilityRector.php
The example config resulted in an invalid yaml file with the current rector version.
`The configuration key "FrameworkClass" is unsupported for definition`
> Changed ChangeMethodVisibilityRector yaml config

- config/services.yaml
- src/Console/Command/ProcessCommand.php
- src/Exception/Linter/LintingException.php
- src/Linter/Linter.php
> Add PHP Linter

- .dockerignore
- .gitattributes
- .travis.yml
Partial revert of https://github.com/rectorphp/rector/pull/2641
Github Actions are now unable to release tagged version of rector-prefixed. It lead to 2 weeks of blackground on tags.
Travis can, so we're getting it back.
If Github Actions start to work, `.travis.yml` can be removed.
> add .travis.yml with tag release

- README.md
- packages/BetterPhpDocParser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php
- packages/BetterPhpDocParser/src/PhpDocNodeFactory/Symfony/Validator/Constraints/AssertChoicePhpDocNodeFactory.php
- packages/Php74/tests/Rector/Property/TypedPropertyRector/Fixture/assert_choice.php.inc
- src/BetterPhpDocParser/Utils/ArrayItemStaticHelper.php
> Fix AssertChoide with choices

- docs/AllRectorsOverview.md
- packages/Php73/src/Rector/FuncCall/SetcookieRector.php
- packages/Php73/tests/Rector/FuncCall/SetcookieRector/Fixture/no_modified.php.inc
- packages/Php73/tests/Rector/FuncCall/SetcookieRector/Fixture/options_specified.php.inc
- packages/Php73/tests/Rector/FuncCall/SetcookieRector/SetcookieRectorTest.php
- src/ValueObject/PhpVersionFeature.php
Convert to [`setcookie()`](https://www.php.net/setcookie) options array introduced in PHP 7.3.
This Rector just breaks backward compatibility with less than PHP 7.3 since PHP 7.3 actually supports old arguments. However, since the option array is required to set the `samesite` attribute, the changes are highlighted.
> Add SetcookieRector

- .docker/php/security.ini
- .github/workflows/publish_docker_images.yml
- Dockerfile
After merging this PR, we can disable autobuild images on hub.docker.com, this way it way docker images will be deployed faster
> Docker build secured image for online demo

- .github/workflows/test_with_doctrine.yaml
- config/set/cakephp-to-symfony/cakephp-24-to-symfony-51.yaml
- docs/AllRectorsOverview.md
- ecs.yaml
- packages/CakePHPToSymfony/src/Rector/Class_/CakePHPControllerComponentToSymfonyRector.php
- packages/CakePHPToSymfony/src/Rector/Class_/CakePHPModelToDoctrineRepositoryRector.php
- packages/CakePHPToSymfony/src/Rector/NodeFactory/DoctrineNodeFactory.php
- packages/CakePHPToSymfony/src/Rector/NodeFactory/DoctrineRepositoryClassMethodFactory.php
- packages/CakePHPToSymfony/tests/Rector/Class_/CakePHPModelToDoctrineRepositoryRector/CakePHPModelToDoctrineRepositoryRectorTest.php
- packages/CakePHPToSymfony/tests/Rector/Class_/CakePHPModelToDoctrineRepositoryRector/Fixture/fixture.php.inc
- packages/CakePHPToSymfony/tests/Rector/Class_/CakePHPModelToDoctrineRepositoryRector/Source/ExpectedActivityRepository.php
- packages/CodingStyle/src/Rector/Catch_/CatchExceptionNameMatchingTypeRector.php
- packages/CodingStyle/src/Rector/Use_/RemoveUnusedAliasRector.php
- packages/Php70/src/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector.php
- packages/Renaming/src/Rector/Class_/RenameClassRector.php
- phpstan.neon
- src/Rector/AbstractRector/BetterStandardPrinterTrait.php
- src/Rector/AbstractRector/NameResolverTrait.php
- src/Rector/Psr4/MultipleClassFileToPsr4ClassesRector.php
> [CakePHPToSymfony] Add CakePHPModelToDoctrineRepositoryRector

- .github/workflows/tests.yaml
- phpunit.xml
Similar to https://github.com/rectorphp/rector/pull/2756 this will enable reporting of phpunit test failures into the files-changed PR tab
> Added phpunit problem matcher

- README.md
`--config` parameter was nowhere metioned. Therefore I complemented it at a useful place.
Further I suggest a dedicated chapter for all possible parameters in the future because they are nowhere explained. Other params like the `-n` as synonym for `-dry-run` is also not mentioned and could lead to confusion
> added --config parameter to README

- config/set/cakephp/cakephp40.yaml
I got this wrong last time. Refs cakephp/cakephp#14250
> Fix replacement for Table::buildRules()

- packages/php-74/src/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector.php
- packages/php-74/tests/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/Fixture/skip_parse_url.php.inc
> [PHP 74] Fix ArraySpreadInsteadOfArrayMergeRector for non-constant string keys

- docs/AllRectorsOverview.md
- packages/doctrine-code-quality/src/Rector/Class_/ChangeQuerySetParametersMethodParameterFromArrayToArrayCollectionRector.php
- packages/doctrine-code-quality/tests/Rector/Class_/ChangeQuerySetParametersMethodParameterFromArrayToArrayCollection/ChangeQuerySetParametersMethodParameterFromArrayToArrayCollectionTest.php
- packages/doctrine-code-quality/tests/Rector/Class_/ChangeQuerySetParametersMethodParameterFromArrayToArrayCollection/Fixture/extends_entity_repository.php.inc
close #2796
implemented basic of moving from array to ArrayCollection in setParameters method.
Only works in case  if you extend basic EntityRepository, but for all types
(Doctrine\ORM\Query, Doctrine\ORM\NativeQuery, Doctrine\ORM\QueryBuilder).
Other types of this refactoring will do in other PR (not promising).
Other types include
- using entity repository externally (in some controller for example, or when you do composition over inheritance in you repositories)
- just creating new instance of query/query builder and doing it on your own
> rector for doctrine setParameters method

- src/Testing/PHPUnit/FixtureSplitter.php
We had issues with running tests on Windows. After short investigation we fixed this by providing the PHP_EOL constant.
> [BUGFIX] Add cross platform compatible newline character

- .github/workflows/code_coverage.yaml
1. Replace the Coveralls repo token in YAML with an environment variable.
2. Re-generate the token in Coveralls settings, since this one is already leaked online.
3. TODO: Set the new token as a `COVERALLS_REPO_TOKEN` variable in GitHub Actions Settings in the repository.
> Inject the coveralls token as a secret

- config/set/oxid/oxid60.yaml
We created this initially in https://github.com/OXID-eSales/oxideshop_ce/pull/758, but I think this is useful for module developers as well. We plan to create a few other rectors in the future.
> add first OXID rector

- config/set/dead-code/dead-code.yaml
- docs/AllRectorsOverview.md
- packages/rector-generator/src/Configuration/ConfigurationFactory.php
- packages/rector-generator/src/TemplateVariablesFactory.php
- rules/dead-code/src/Rector/TryCatch/RemoveDeadTryCatchRector.php
- rules/dead-code/tests/Rector/TryCatch/RemoveDeadTryCatchRector/Fixture/fixture.php.inc
- rules/dead-code/tests/Rector/TryCatch/RemoveDeadTryCatchRector/Fixture/multi_lines.php.inc
- rules/dead-code/tests/Rector/TryCatch/RemoveDeadTryCatchRector/Fixture/skip_catch_else.php.inc
- rules/dead-code/tests/Rector/TryCatch/RemoveDeadTryCatchRector/RemoveDeadTryCatchRectorTest.php
> [DeadCode] Add RemoveDeadTryCatchRector

- config/set/solid/solid.yaml
- docs/AllRectorsOverview.md
- rules/solid/src/Rector/Property/ChangeReadOnlyPropertyWithDefaultValueToConstantRector.php
- rules/solid/tests/Rector/Property/ChangeReadOnlyPropertyWithDefaultValueToConstantRector/ChangeReadOnlyPropertyWithDefaultValueToConstantRectorTest.php
- rules/solid/tests/Rector/Property/ChangeReadOnlyPropertyWithDefaultValueToConstantRector/Fixture/fixture.php.inc
- rules/solid/tests/Rector/Property/ChangeReadOnlyPropertyWithDefaultValueToConstantRector/Fixture/skip_multiple_properties.php.inc
- rules/solid/tests/Rector/Property/ChangeReadOnlyPropertyWithDefaultValueToConstantRector/Fixture/skip_overriden.php.inc
- src/PhpParser/Node/Manipulator/PropertyManipulator.php
> [SOLID] Add ChangeReadOnlyPropertyWithDefaultValueToConstantRector

- packages/Php71/tests/Rector/FuncCall/CountOnNullRector/Fixture/property_within_trait_method.php.inc
- packages/Php71/tests/Rector/FuncCall/CountOnNullRector/Fixture/variable_within_trait_method.php.inc
This PR adds two fixtures relating to `trait` handling by `CountOnNullRector`. Currently : 
* `PropertyWithinTraitMethod` : passes :+1:
* `VariableWithinTraitMethod` : fails :-1: 
If I change the Fixture from a `trait` to a `class` they both pass, so this is related to how a variable within a trait is handled.
I spent some time digging and tried to use `\Rector\NodeTypeResolver\PerNodeTypeResolver\VariableTypeResolver::resolve()` that seems to be written to handle resolution of variables (though it's used nowhere in Rector's code, only in its own Test file :thinking: ) by calling : 
* `resolveTypesFromScope($node)`, which calls...
* `resolveNodeScope($node)`, which calls on `\Rector\NodeTypeResolver\PHPStan\Collector\TraitNodeScopeCollector`...
* `getScopeForTraitAndNode($traitName, …
> [CountOnNullRector] Should understand array/countable variable in trait method

- rules/solid/tests/Rector/If_/RemoveAlwaysElseRector/Fixture/for_continue.php.inc
- rules/solid/tests/Rector/If_/RemoveAlwaysElseRector/Fixture/function_foreach_continue.php.inc
With a foreach within an anonymous function.
Issue: https://github.com/rectorphp/rector/issues/2842
> Adding failing test for RemoveAlwaysElseRector

- rules/solid/src/Rector/If_/RemoveAlwaysElseRector.php
- rules/solid/tests/Rector/If_/RemoveAlwaysElseRector/Fixture/function_foreach_continue.php.inc
- src/PhpParser/Node/Commander/NodeAddingCommander.php
> fix remove alwasy else for anonymous function jump

- rules/php-74/src/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector.php
- rules/php-74/tests/Rector/FuncCall/ArraySpreadInsteadOfArrayMergeRector/Fixture/skip_spread_array_merge.php.inc
> Skip unpackaged args in ArraySpreadInsteadOfArrayMergeRector

- rules/php-70/src/Rector/Ternary/TernaryToSpaceshipRector.php
- rules/php-70/tests/Rector/Ternary/TernaryToSpaceshipRector/Fixture/skip_non_binary_op_in_nested_ternary.php.inc
Fixes generated PHP notice `Notice: Undefined property: PhpParser\Node\Expr\Isset_::$left in /home/fsok/src/rector/rules/php-70/src/Rector/Ternary/TernaryToSpaceshipRector.php on line 88`
> Fix PHP notice in ternary to spaceship rector

- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Property_/ColumnTagValueNode.php
- src/PhpParser/Printer/BetterStandardPrinter.php
> fix tab indent

- rules/coding-style/src/Rector/Throw_/AnnotateThrowablesRector.php
- rules/coding-style/tests/Rector/Throw_/AnnotateThrowablesRector/Fixture/factory_static_method_with_return_dockblock.php.inc
- rules/coding-style/tests/Rector/Throw_/AnnotateThrowablesRector/Source/ExceptionsFactoryStaticMethodWithReturnDocblock.php
#2889 (general discussion: #2861).
```php
function throwThroughStaticMethod()
{
throw ExcetionFactory::createException();
}
```
See the test case here: https://github.com/rectorphp/rector/blob/71ad810c8c777def532af6ff22be6d4d900b3bdd/rules/coding-style/tests/Rector/Throw_/AnnotateThrowablesRector/Fixture/factory_static_method_with_return_dockblock.php.inc
The problem is to read the Docblock of the invoked method.
One approach, as suggested in #2861  (https://github.com/rectorphp/rector/issues/2861#issuecomment-586970207) is to use the reflection.
Currently it is possible to obtain the Docblock using reflection, but the docblock is obtained as a simple string and it cannot be parsed.
Obtaining a simple string is useless, as it makes impossible to know which classes are actually returned. …
> #2861: Support throw of static methods

- rules/dead-code/src/Rector/Switch_/RemoveDuplicatedCaseInSwitchRector.php
- rules/dead-code/tests/Rector/Switch_/RemoveDuplicatedCaseInSwitchRector/Fixture/skip_no_break.php.inc
> fix duplicate switch without break

- .github/ISSUE_TEMPLATE/1_Bug_report.md
- .github/ISSUE_TEMPLATE/2_Feature_request.md
- .github/ISSUE_TEMPLATE/3_Support_question.md
- .github/mergeable.yaml
> add mergeable

- config/set/code-quality/code-quality.yaml
- docs/AllRectorsOverview.md
- rules/code-quality/src/Rector/BinaryOp/InlineIfToExplicitIfRector.php
- rules/code-quality/tests/Rector/BinaryOp/InlineIfToExplicitIfRector/Fixture/fixture.php.inc
- rules/code-quality/tests/Rector/BinaryOp/InlineIfToExplicitIfRector/InlineIfToExplicitIfRectorTest.php
> [CodeQuality] Add InlineIfToExplicitIfRector

- config/set/solid/solid.yaml
- docs/AllRectorsOverview.md
- rules/solid/src/NodeTransformer/ConditionInverter.php
- rules/solid/src/Rector/Foreach_/ChangeNestedForeachIfsToEarlyContinueRector.php
- rules/solid/tests/Rector/Foreach_/ChangeNestedForeachIfsToEarlyContinueRector/ChangeNestedForeachIfsToEarlyContinueRectorTest.php
- rules/solid/tests/Rector/Foreach_/ChangeNestedForeachIfsToEarlyContinueRector/Fixture/fixture.php.inc
- rules/solid/tests/Rector/Foreach_/ChangeNestedForeachIfsToEarlyContinueRector/Fixture/multi_exprs.php.inc
- rules/solid/tests/Rector/Foreach_/ChangeNestedForeachIfsToEarlyContinueRector/Fixture/skip_text.php.inc
- src/PhpParser/Node/Manipulator/IfManipulator.php
> [SOLID] Add ChangeNestedForeachIfsToEarlyContinueRector

- composer.json
- docs/AllRectorsOverview.md
- packages/better-php-doc-parser/src/PhpDocNode/JMS/JMSInjectParamsTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/JMS/JMSServiceValueNode.php
- packages/better-php-doc-parser/src/PhpDocNodeFactory/JMS/JMSInjectParamsPhpDocNodeFactory.php
- packages/better-php-doc-parser/src/PhpDocNodeFactory/JMS/JMSServicePhpDocNodeFactory.php
- packages/rector-generator/src/Composer/ComposerPackageAutoloadUpdater.php
- packages/rector-generator/src/ValueObject/Configuration.php
- phpstan.neon
- rules/jms/src/Rector/ClassMethod/RemoveJmsInjectParamsAnnotationRector.php
- rules/jms/src/Rector/Class_/RemoveJmsInjectServiceAnnotationRector.php
- rules/jms/tests/Rector/ClassMethod/RemoveJmsInjectParamsAnnotationRector/Fixture/fixture.php.inc
- rules/jms/tests/Rector/ClassMethod/RemoveJmsInjectParamsAnnotationRector/RemoveJmsInjectParamsAnnotationRectorTest.php
- rules/jms/tests/Rector/Class_/RemoveJmsInjectServiceAnnotationRector/Fixture/fixture.php.inc
- rules/jms/tests/Rector/Class_/RemoveJmsInjectServiceAnnotationRector/RemoveJmsInjectServiceAnnotationRectorTest.php
- stubs/JMS/JMSDiExtraBundle/Annotation/InjectParams.php
- stubs/JMS/JMSDiExtraBundle/Annotation/Service.php
> [JMS] Add RemoveJmsInjectParamsAnnotationRector and RemoveJmsServiceAnnotationRector

- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Class_/EmbeddableTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNodeFactory/Doctrine/Class_/EmbeddablePhpDocNodeFactory.php
- phpstan.neon
- rules/doctrine/src/PhpDocParser/DoctrineDocBlockResolver.php
- rules/solid/tests/Rector/Class_/FinalizeClassesWithoutChildrenRector/Fixture/skip_embedable.php.inc
- rules/solid/tests/Rector/Class_/FinalizeClassesWithoutChildrenRector/Fixture/skip_entity.php.inc
- stubs/Doctrine/ORM/Mapping/Embeddable.php
> Fix FinalizeClassesWithoutChildrenRector for embedable

- config/config.yaml
- rules/dead-code/src/Rector/ClassMethod/RemoveUnusedParameterRector.php
- rules/dead-code/tests/Rector/ClassMethod/RemoveUnusedParameterRector/Fixture/change_when_not_using_in_children.php.inc
- rules/dead-code/tests/Rector/ClassMethod/RemoveUnusedParameterRector/FixtureOpenSource/skip_abstract.php.inc
- rules/dead-code/tests/Rector/ClassMethod/RemoveUnusedParameterRector/OpenSourceRectorTest.php
- src/Configuration/Option.php
- src/Testing/PHPUnit/AbstractRectorTestCase.php
Ref #2743 
```yaml
parameters:
project_type: "proprietary" # = only you use it (default)
```
or more opened, e.g. allow use of public constants
```yaml
parameters:
project_type: "open-source" # = other people use it
```
> add project_type

- rules/type-declaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Fixture/skip_array_index.php.inc
I'm not sure exactly what's happening here ; might have to do with the fact that we access an array index using `[0]` ?
But I'm pretty sure it shouldn't replace `): \stdClass` by `): array` as it will break the code (PS: in my real code it's not \stdClass but some domain object).
> ReturnTypeDeclarationRector: add broken test on array indexes (?)

- rules/phpunit/tests/Rector/SpecificMethod/AssertRegExpRector/Fixture/fixture_2.php.inc
Could not reproduce in a demo set however ('guessing because there's no real PHPUnit in there) : https://getrector.org/demo/011085dd-1266-4a33-a8a9-44e355f9f709#result
Fails with error : 
```                                  
[ERROR] Could not process "File.php" file, due to:     
"Pick more specific node than "PhpParser\Node\Expr\StaticCall"".                                                                        
```
I had the exact same error happen from these Rectors on my code base : 
* `Rector\PHPUnit\Rector\SpecificMethod\AssertTrueFalseToSpecificMethodRector`
* `Rector\PHPUnit\Rector\SpecificMethod\AssertFalseStrposToContainsRector`
* `Rector\PHPUnit\Rector\SpecificMethod\AssertPropertyExistsRector`
I guess the issue is the same, so I won't try to add tests for them all. We'll see …
> AssertRegExpRectorTest: add broken test on static method call

- rules/dead-code/tests/Rector/MethodCall/RemoveDefaultArgumentValueRector/Fixture/skip_static_method_call.php.inc
Might be related to https://github.com/rectorphp/rector/pull/2953 as it's the same error, but it might not (as the Rector is quite different).
Fails with error : 
```                                  
[ERROR] Could not process "File.php" file, due to:     
"Pick more specific node than "PhpParser\Node\Expr\StaticCall"".                                                                        
```
> RemoveDefaultArgumentValueRector: add broken test on static method call.

- rules/phpunit/tests/Rector/Class_/AddSeeTestAnnotationRector/Fixture/skip_simple_class_comment.php.inc
- rules/phpunit/tests/Rector/Class_/AddSeeTestAnnotationRector/Source/SkipSimpleClassCommentTest.php
I was not able to reproduce in the demo however (where it adds the `@see` annotation even on the simple comment...) https://getrector.org/demo/9890b876-ff9e-4bd4-bff1-ad1598d41f42#result
In local I get an error block like : 
```
[ERROR] Could not process "File.php" file by                           
"Rector\PHPUnit\Rector\Class_\AddSeeTestAnnotationRector", due to:                                             
"Call to a member function getTagsByName() on null".                                                                                                                                                                                 
```
> AddSeeTestAnnotationRectorTest: add broken test for simple comment.

- rules/dead-code/tests/Rector/MethodCall/RemoveDefaultArgumentValueRector/Fixture/skip_static_method_call.php.inc
- rules/phpunit/tests/Rector/SpecificMethod/AssertTrueFalseInternalTypeToSpecificMethodRector/Fixture/fixture_2.php.inc
Might be related to #2954 and #2955. They all come from `Rector\NodeNameResolver\NodeNameResolver->getName()`. I won't open any more issues like this one for now as to not spam you if it all comes from the same source ; this should give you enough of a sample to work with. ;) 
Fails with error : 
```
[ERROR] Could not process "File.php" file, due to:     
"Pick more specific node than "PhpParser\Node\Expr\MethodCall"".     
```
> AssertTrueFalseInternalTypeToSpecificMethodRector: add broken test method call

- rules/php-72/tests/Rector/FuncCall/GetClassOnNullRector/Fixture/skip_return_before_method_call.php.inc
https://getrector.org/demo/10a00600-21ac-4ca7-9f72-1cce72977b0f#result
It should detect the check `if (null === $object) { return null; }` and not process the statement `get_class($object)` (this demo is simplified as much as possible, compared to my real code).
> [GetClassOnNullRector] Add failing test in trait.

- rules/php-72/src/Rector/FuncCall/GetClassOnNullRector.php
> fix get class on trait

- rules/dead-code/src/NodeCollector/ModifiedVariableNamesCollector.php
- rules/dead-code/src/NodeManipulator/MagicMethodDetector.php
- rules/dead-code/src/NodeManipulator/VariadicFunctionLikeDetector.php
- rules/dead-code/src/Rector/ClassMethod/RemoveUnusedParameterRector.php
- rules/dead-code/src/Rector/FunctionLike/RemoveDuplicatedIfReturnRector.php
- rules/dead-code/tests/Rector/ClassMethod/RemoveUnusedParameterRector/Fixture/skip_func_get_args.php.inc
- rules/dead-code/tests/Rector/FunctionLike/RemoveDuplicatedIfReturnRector/Fixture/skip_referenced.php.inc
- src/PhpParser/Node/Manipulator/ClassMethodManipulator.php
- src/PhpParser/Node/Manipulator/FuncCallManipulator.php
> [DeadCode] Fix shifted value

- packages/attribute-aware-php-doc/src/Ast/Type/AttributeAwareArrayShapeItemNode.php
- packages/attribute-aware-php-doc/src/AttributeAwareNodeFactory/Type/AttributeAwareArrayShapeItemNodeFactory.php
- packages/attribute-aware-php-doc/src/AttributeAwareNodeFactory/Type/AttributeAwareArrayShapeNodeFactory.php
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureBasic/var_array.txt
> fix spacing for array shape item

- packages/attribute-aware-php-doc/src/Ast/Type/AttributeAwareArrayShapeItemNode.php
- packages/better-php-doc-parser/src/PhpDocParser/AnnotationContentResolver.php
- packages/better-php-doc-parser/src/PhpDocParser/BetterPhpDocParser.php
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureBasic/psalm_return_array_shape.txt
> improve array shape double collon spacing

- packages/attribute-aware-php-doc/src/Ast/PhpDoc/AttributeAwareParamTagValueNode.php
- packages/better-php-doc-parser/src/Printer/PatternFactory.php
- packages/better-php-doc-parser/src/Printer/PhpDocInfoPrinter.php
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureBasic/param_double_spacing.txt
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureBasic/param_double_spacing_with_same_type.txt
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureBasic/param_print_spacing.txt
> add space between name and value

- rules/phpunit/src/Rector/SpecificMethod/AssertTrueFalseToSpecificMethodRector.php
- rules/phpunit/tests/Rector/SpecificMethod/AssertTrueFalseToSpecificMethodRector/Fixture/fixture3.php.inc
Same as https://github.com/rectorphp/rector/pull/2953.
> AssertTrueFalseToSpecificMethodRector: add broken test ('Pick more specific node than PhpParser\Node\Expr\StaticCall')

- rules/phpunit/src/Rector/SpecificMethod/AssertFalseStrposToContainsRector.php
- rules/phpunit/src/Rector/SpecificMethod/AssertPropertyExistsRector.php
- rules/phpunit/src/Rector/SpecificMethod/AssertTrueFalseToSpecificMethodRector.php
- rules/phpunit/tests/Rector/SpecificMethod/AssertFalseStrposToContainsRector/Fixture/skip_static_call.php.inc
- rules/phpunit/tests/Rector/SpecificMethod/AssertPropertyExistsRector/Fixture/skip_static_call.php.inc
- rules/phpunit/tests/Rector/SpecificMethod/AssertTrueFalseToSpecificMethodRector/Fixture/skip_static_call.php.inc
Fixes remaining Rectors of #2953 and #2990 (PS: I tried `! $firstArgumentValue instanceof FuncCall` but it broke many tests, so I kept `$firstArgumentValue instanceof StaticCall` and put it in its own `if`)
> Fix various static calls errors in PHPUnit Rectors.

- rules/symfony/tests/Rector/ClassMethod/MergeMethodAnnotationToRouteAnnotationRector/Fixture/fixture_with_template_annotation.php.inc
- rules/symfony/tests/Rector/ClassMethod/MergeMethodAnnotationToRouteAnnotationRector/Fixture/fixture_with_template_annotation2.php.inc
I've added two failing tests for the MergeMethodAnnotationToRouteAnnotationRector.
In my opinion it shouldn't change the template annotation and it seems that the method won't be merged if some other annotation stands between the Route and Method annoation.
When the tests will get fixed, this PR will fix issue #2785.
I wasn't able to get this fixed by myself, maybe you could help me?
> Add failing tests for method annotation

- config/set/phpunit/phpunit90.yaml
- docs/AllRectorsOverview.md
- rules/phpunit/src/Rector/MethodCall/SpecificAssertContainsWithoutIdentityRector.php
- rules/phpunit/tests/Rector/MethodCall/SpecificAssertContainsWithoutIdentityRector/Fixture/check_identity.php.inc
- rules/phpunit/tests/Rector/MethodCall/SpecificAssertContainsWithoutIdentityRector/Fixture/fixture.php.inc
- rules/phpunit/tests/Rector/MethodCall/SpecificAssertContainsWithoutIdentityRector/Fixture/partial_arguments.php.inc
- rules/phpunit/tests/Rector/MethodCall/SpecificAssertContainsWithoutIdentityRector/Fixture/strings.php.inc
- rules/phpunit/tests/Rector/MethodCall/SpecificAssertContainsWithoutIdentityRector/SpecificAssertContainsWithoutIdentityRectorTest.php
As of https://github.com/sebastianbergmann/phpunit/issues/3426 assertContains() and assertNotContains() will perform strict comparisons starting with PHPUnit 9 where non-strict comparisons were performed in PHPUnit 8 and earlier; assertContainsEqual() and assertNotContainsEqual() should be used instead if needed non-strict comparison
> add phpunit 9 rector to convert non-strict assertContains

- packages/node-type-resolver/src/PhpDoc/NodeAnalyzer/DocBlockManipulator.php
> fix asterisk indent

- docs/AllRectorsOverview.md
- packages/node-type-resolver/src/Node/AttributeKey.php
- packages/node-type-resolver/src/NodeScopeAndMetadataDecorator.php
- packages/node-type-resolver/src/NodeVisitor/MethodCallNodeVisitor.php
- rules/phpunit/src/Rector/MethodCall/CreateMockToCreateStubRector.php
- rules/phpunit/tests/Rector/MethodCall/CreateMockToCreateStubRector/CreateMockToCreateStubRectorTest.php
- rules/phpunit/tests/Rector/MethodCall/CreateMockToCreateStubRector/Fixture/fixture.php.inc
- rules/phpunit/tests/Rector/MethodCall/CreateMockToCreateStubRector/Fixture/skip_with_expects.php.inc
- src/PhpParser/Node/BetterNodeFinder.php
- src/PhpParser/Node/Manipulator/MethodCallManipulator.php
> [PHPUnit] Add CreateMockToCreateStubRector

- packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php
> Fix assert choice tag value node with class constant reference

- packages/phpstan-static-type-mapper/src/DoctrineTypeAnalyzer.php
- packages/phpstan-static-type-mapper/src/TypeMapper/UnionTypeMapper.php
- rules/php-74/src/Rector/Property/TypedPropertyRector.php
- rules/php-74/tests/Rector/Property/TypedPropertyRector/DoctrineTypedPropertyRectorTest.php
- rules/php-74/tests/Rector/Property/TypedPropertyRector/FixtureDoctrine/doctrine_collection.php.inc
- rules/php-74/tests/Rector/Property/TypedPropertyRector/FixtureDoctrine/doctrine_intersect_collection.php.inc
```php
<?php
namespace Rector\Php74\Tests\Rector\Property\TypedPropertyRector\Fixture;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Pehapkari\Training\Entity\TrainingTerm;
/**
* @ORM\Entity
*/
class DoctrineCollection
{
/**
* @ORM\OneToMany(targetEntity="Pehapkari\Training\Entity\TrainingTerm", mappedBy="training")
* @var TrainingTerm[]&Collection
*/
private $trainingTerms;
}
```
```diff
<?php
namespace Rector\Php74\Tests\Rector\Property\TypedPropertyRector\Fixture;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Pehapkari\Training\Entity\TrainingTerm;
/**
* @ORM\Entity
*/
class DoctrineCollection
{
/**
* @ORM\OneToMany(targetEntity="Pehapkari\Training\Entity\TrainingTerm", mappedBy="training")
* @var …
```
> [PHP 7.4] Improve TypedPropertyRector for Doctrine collection

- config/set/dead-code/dead-code.yaml
- docs/AllRectorsOverview.md
- packages/node-collector/src/NodeCollector/ParsedFunctionLikeNodeCollector.php
- packages/node-name-resolver/src/NodeNameResolver/FuncCallNameResolver.php
- packages/node-name-resolver/src/NodeNameResolver/FunctionNameResolver.php
- rules/dead-code/src/Rector/Function_/RemoveUnusedFunctionRector.php
- rules/dead-code/src/Rector/MethodCall/RemoveDefaultArgumentValueRector.php
- rules/dead-code/tests/Rector/Function_/RemoveUnusedFunctionRector/Fixture/fixture.php.inc
- rules/dead-code/tests/Rector/Function_/RemoveUnusedFunctionRector/RemoveUnusedFunctionRectorTest.php
> [DeadCode] Add RemoveUnusedFunctionRector

- rules/php55/config/config.yaml
- rules/php55/src/NodeFactory/AnonymousFunctionNodeFactory.php
- rules/php55/src/Rector/FuncCall/PregReplaceEModifierRector.php
- rules/php55/src/RegexMatcher.php
- rules/php55/tests/Rector/FuncCall/PregReplaceEModifierRector/Fixture/preg_quoted.php.inc
- rules/php55/tests/Rector/FuncCall/PregReplaceEModifierRector/Fixture/remove_only_end_e.php.inc
- rules/php55/tests/Rector/FuncCall/PregReplaceEModifierRector/Fixture/skip_non_string.php.inc
- src/Rector/AbstractRector/ValueResolverTrait.php
> [PHP 5.5] Prevent error on non-string value in PregReplaceEModifierRector

- packages/better-php-doc-parser/src/AnnotationReader/NodeAnnotationReader.php
> Fix multiple annotation reading of same type at class method

- config/set/dead-code/dead-code.yaml
- docs/AllRectorsOverview.md
- rules/dead-code/src/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector.php
- rules/dead-code/tests/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/fixture.php.inc
- rules/dead-code/tests/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/not_equal.php.inc
- rules/dead-code/tests/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/skip_different_foreach.php.inc
- rules/dead-code/tests/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/RemoveUnusedNonEmptyArrayBeforeForeachRectorTest.php
- src/PhpParser/Node/Manipulator/IfManipulator.php
> [DeadCode] Add RemoveUnusedNonEmptyArrayBeforeForeachRector

- rules/dead-code/src/NodeManipulator/CountManipulator.php
- rules/dead-code/src/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector.php
- rules/dead-code/src/UselessIfCondBeforeForeachDetector.php
- rules/dead-code/tests/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/keep_if_else.php.inc
- rules/dead-code/tests/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/more_or_equal_than_one.php.inc
- rules/dead-code/tests/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/more_or_equal_than_one_other_side.php.inc
- rules/dead-code/tests/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/more_than_zero.php.inc
- rules/dead-code/tests/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/more_than_zero_other_side.php.inc
- rules/dead-code/tests/Rector/If_/RemoveUnusedNonEmptyArrayBeforeForeachRector/Fixture/not_empty.php.inc
- rules/symfony/src/ValueObject/ServiceMap/ServiceMap.php
> [DeadCode] Add empty() + count($values) > 0 checks to RemoveUnusedNonEmptyArrayBeforeForeachRector

- packages/renaming/tests/Rector/Class_/RenameClassRector/FixtureAutoImportNames/class_imported_as_alias.php.inc
- packages/renaming/tests/Rector/Class_/RenameClassRector/FixtureAutoImportNames/class_imported_as_alias_with_namespace_with_false_condition.php.inc
- packages/renaming/tests/Rector/Class_/RenameClassRector/FixtureAutoImportNames/class_imported_as_alias_without_namespace.php.inc
- packages/renaming/tests/Rector/Class_/RenameClassRector/FixtureAutoImportNames/class_imported_as_alias_without_namespace_with_false_condition.php.inc
- packages/renaming/tests/Rector/Class_/RenameClassRector/Source/FirstNamespace/FirstOriginalClass.php
- packages/renaming/tests/Rector/Class_/RenameClassRector/Source/SecondNamespace/SecondOriginalClass.php
**WIP**
Ref  #2753.
Added 4 tests and 3 will fail. I need a help to understand expected result.
1) **class_imported_as_alias.php.inc**
`SecondOriginalClass` was imported but `SecondNamespace` was not removed from `use` section.
2) **class_imported_as_alias_with_namespace_with_false_condition.php.inc**
Passed however `NotExistingNamespace\ClassName` was not exist. Did `if (false) {` condition make it pass?
3) **class_imported_as_alias_without_namespace.php.inc**
Failed because `NotExistingNamespace\ClassName` didn't exist. Looks right.
4) **class_imported_as_alias_without_namespace_with_false_condition.php.inc**
This is the case from issue #2753. Alias replaced by original class name and alias was not removed from `use` section.
And one more question to this case: why it's not the same as …
> WIP: #2753 Fix Auto Import Names

- rules/dead-code/tests/Rector/Class_/RemoveSetterOnlyPropertyAndMethodCallRector/Fixture/deal_with_property_fetches.php.inc
- rules/dead-code/tests/Rector/Class_/RemoveSetterOnlyPropertyAndMethodCallRector/Fixture/in_constructor.php.inc
- rules/dead-code/tests/Rector/Property/RemoveUnusedPrivatePropertyRector/Fixture/constructor_only.php.inc
- src/Rector/AbstractRector/ComplexRemovalTrait.php
> remove ctor dependency on property/assign removal

- packages/better-php-doc-parser/src/PhpDocNode/AbstractTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Symfony/SymfonyRouteTagValueNode.php
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureBasic/route_with_brackets.txt
- rules/sensio/tests/Rector/FrameworkExtraBundle/TemplateAnnotationRector/FixtureVersion5/with_route_options.php.inc
> Fix annotation in requirements of @Route

- packages/vendor-locker/src/VendorLockResolver.php
- rules/type-declaration/src/ChildPopulator/ChildParamPopulator.php
- rules/type-declaration/src/Rector/FunctionLike/AbstractTypeDeclarationRector.php
- rules/type-declaration/src/Rector/FunctionLike/ParamTypeDeclarationRector.php
- rules/type-declaration/src/TypeAlreadyAddedChecker/ReturnTypeAlreadyAddedChecker.php
- rules/type-declaration/src/TypeInferer/ParamTypeInferer.php
- rules/type-declaration/src/TypeInferer/ParamTypeInferer/FunctionLikeDocParamTypeInferer.php
- rules/type-declaration/src/ValueObject/NewType.php
- rules/type-declaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/Fixture/infer_from_property_phpdoc_type.php.inc
- rules/type-declaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/Fixture/infer_from_property_type.php.inc
- rules/type-declaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/FixturePropertyType/infer_from_property_type.php.inc
- rules/type-declaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/PropertyTypeParamTypeDeclarationRectorTest.php
> [TypeDeclaration] Add class method param type resolving by property

- .github/workflows/sets_check_parallel.yaml
- ci/run_all_sets_parallel.php
- composer.json
- packages/node-type-resolver/src/DependencyInjection/PHPStanServicesFactory.php
- utils/parallel-process-runner/src/Exception/CouldNotDeterminedCpuCoresException.php
- utils/parallel-process-runner/src/Exception/ProcessResultInvalidException.php
- utils/parallel-process-runner/src/SystemInfo.php
- utils/parallel-process-runner/src/Task.php
- utils/parallel-process-runner/src/TaskRunner.php
- add a task runner to run the sets in parallel
- number of cores is determined automatically via https://gist.github.com/divinity76/01ef9ca99c111565a72d3a8a6e42f7fb
- added github action at `ci/sets_check_parallel.yaml` to make sure it works in CI
==> roughly 3 times faster on my local machine with 8 cores
Usage:
`php ci/run_all_sets_parallel.php`
Output:
```
www-data@f273549c9848:/codebase/rector$ time php ci/run_all_sets_parallel.php
Running 135 sets with 8 parallel processes
✔ Set "cakephp-24-to-symfony-51" is OK ( 1 / 135)
✔ Set "cakephp34" is OK ( 2 / 135)
✔ Set "action-injection-to-constructor-injection" is OK ( 3 / 135)
✔ Set "array-str-functions-to-static-call" is OK ( 4 / 135)
✔ Set "cakephp30" is OK ( 5 / 135)
✔ Set "cakephp35" is OK ( 6 / 135)
✔ Set "cakephp36" is OK ( 7 / …
```
> Add parallel execution to ci/run_all_sets

- rules/code-quality/tests/Rector/FuncCall/ArrayKeysAndInArrayToArrayKeyExistsRector/ArrayKeysAndInArrayToArrayKeyExistsRectorTest.php
- rules/code-quality/tests/Rector/FuncCall/ArrayKeysAndInArrayToArrayKeyExistsRector/Fixture/fixture.php.inc
- src/Testing/PHPUnit/AbstractRunnableRectorTestCase.php
- src/Testing/PHPUnit/RunnableInterface.php
- added RunnableTestCase::assertOriginalAndFixedFileYieldSameResult($file)
that takes a fixture file and expects fixture classes that implement the
new RunnableInterface which exposes a run() method
- the fixture class is dynamically renamed to avoid naming conflicts
and loaded via eval()
- fixtures that don't implement the RunnableInterface are ignored
otherwise the run() method is called on the original class as well
as on the fixed one and the output is expected to be equal
(via assertSame) by default
- the default assertion behavior can be changed via $assertion callable
> Add RunnableTestCase to run fixed code in a test

- config/set/phpunit/phpunit91.yaml
- docs/AllRectorsOverview.md
- packages/post-rector/src/Application/PostFileProcessor.php
- packages/rector-generator/src/Command/CreateRectorCommand.php
- packages/rector-generator/src/TemplateVariablesFactory.php
- packages/rector-generator/src/ValueObject/Configuration.php
- rules/architecture/src/Rector/Class_/ConstructorInjectionToActionInjectionRector.php
- rules/doctrine-code-quality/src/Rector/Class_/ChangeQuerySetParametersMethodParameterFromArrayToArrayCollectionRector.php
- rules/doctrine-gedmo-to-knplabs/src/Rector/Class_/TimestampableBehaviorRector.php
- rules/phpunit/src/Rector/Class_/AddProphecyTraitRector.php
- rules/phpunit/tests/Rector/Class_/AddProphecyTraitRector/AddProphecyTraitRectorTest.php
- rules/phpunit/tests/Rector/Class_/AddProphecyTraitRector/Fixture/fixture.php.inc
- rules/phpunit/tests/Rector/Class_/AddProphecyTraitRector/Fixture/skip_if_already_added.php.inc
- rules/phpunit/tests/Rector/Class_/AddProphecyTraitRector/Fixture/skip_non_prophesize.php.inc
- src/Console/Command/ScreenFileCommand.php
- src/PhpParser/Node/Manipulator/ClassInsertManipulator.php
- src/PhpParser/Node/Manipulator/ClassManipulator.php
- src/Rector/AbstractRector/NameResolverTrait.php
- src/Testing/Finder/RectorsFinder.php
- stubs/Prophecy/PhpUnit/ProphecyTrait.php
- utils/documentation-generator/src/Command/DumpNodesCommand.php
- utils/documentation-generator/src/Command/DumpRectorsCommand.php
- utils/phpstan-attribute-type-syncer/src/Command/SyncTypesCommand.php
- utils/phpstan-static-type-mapper-checker/src/Command/CheckStaticTypeMappersCommand.php
Closes #3099 
- Ref https://github.com/sebastianbergmann/phpunit/issues/4141
- Ref https://github.com/sebastianbergmann/phpunit/issues/4142
> [PHPUnit] Add AddProphecyTraitRector

- rules/doctrine/src/Rector/MethodCall/EntityAliasToClassConstantReferenceRector.php
- rules/doctrine/tests/Rector/MethodCall/EntityAliasToClassConstantReferenceRector/Fixture/fixture2.php.inc
- stubs/Doctrine/Persistence/ManagerRegistry.php
- stubs/Doctrine/Persistence/ObjectManager.php
- stubs/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php
While using this rector on a project, I noticed it didn't work on symfony controllers. Because the `$this->getDoctrine()->getManager()` returns an instance of `Doctrine\Persistence\ObjectManager` (or the deprecated interface `Doctrine\Common\Persistence\ObjectManager`). So I've debugged and adjusted the check so it would also work in symfony controllers.
The only strange thing is that the original example (test fixture) does work in the test suite with the old code, but it didn't work in the project I was debugging 🤷‍♂
> Make sure doctrine alias rector works in symfony controllers

- rules/doctrine/src/Rector/MethodCall/EntityAliasToClassConstantReferenceRector.php
- rules/doctrine/tests/Rector/MethodCall/EntityAliasToClassConstantReferenceRector/Fixture/fixture3.php.inc
This is an extension to the changes in #3146. I've discovered some other usages which were not covered by this rector. So these extra interfaces will allow to fix these cases also.
```
$this->getDoctrine()->getRepository();
```
This is also possible as the manager registry will select to correct manager based on the provided entity. 
https://github.com/doctrine/persistence/blob/fdaaa50cb23760c9da2d6dcab9f10caa34d92b61/lib/Doctrine/Persistence/AbstractManagerRegistry.php#L226-L233
> Add extra allowed interface to EntityAliasToClassConstantReferenceRector

- packages/attribute-aware-php-doc/src/Ast/Type/AttributeAwareCallableTypeNode.php
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureCallable/callable_empty_params.txt
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureCallable/callable_mixed.txt
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureCallable/callable_param.txt
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/FixtureCallable/callable_without_types.txt
> Typed callable when mixed used

- config/set/php-office/phpexcel-to-phpspreadsheet.yaml
- docs/AllRectorsOverview.md
- helpers/extract_default_value_changes_from_diff.php
- phpstan.neon
- rules/php-office/src/Rector/MethodCall/IncreaseColumnIndexRector.php
- rules/php-office/tests/Rector/MethodCall/IncreaseColumnIndexRector/Fixture/concat_number.php.inc
- rules/php-office/tests/Rector/MethodCall/IncreaseColumnIndexRector/Fixture/fixture.php.inc
- rules/php-office/tests/Rector/MethodCall/IncreaseColumnIndexRector/Fixture/for_.php.inc
- rules/php-office/tests/Rector/MethodCall/IncreaseColumnIndexRector/Fixture/variable_.php.inc
- rules/php-office/tests/Rector/MethodCall/IncreaseColumnIndexRector/IncreaseColumnIndexRectorTest.php
> [PHPOffice] Add IncreaseColumnIndexRector

- packages/better-php-doc-parser/src/PhpDocNode/AbstractTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Symfony/SymfonyRouteTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertTypeTagValueNode.php
- packages/better-php-doc-parser/src/Printer/WhitespaceDetector.php
- packages/better-php-doc-parser/tests/PhpDocParser/SymfonyRouteTagParser/Fixture/RouteName.php
> Spacing + quoting improvements in @Route

- README.md
- packages/better-php-doc-parser/src/PhpDocNode/AbstractTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Class_/EntityTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Property_/CustomIdGeneratorTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Symfony/SymfonyRouteTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertChoiceTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertTypeTagValueNode.php
- packages/better-php-doc-parser/tests/PhpDocParser/AbstractPhpDocInfoTest.php
- packages/better-php-doc-parser/tests/PhpDocParser/DoctrineOrmTagParser/DoctrineOrmTagNodeTest.php
- packages/better-php-doc-parser/tests/PhpDocParser/DoctrineOrmTagParser/Fixture/Class_/Entity/EntityRepositoryConstant.php
- packages/better-php-doc-parser/tests/PhpDocParser/DoctrineOrmTagParser/Fixture/Property/Column/QuotesInNestedArray.php
- packages/better-php-doc-parser/tests/PhpDocParser/DoctrineOrmTagParser/Fixture/Property/CustomIdGenerator/CustomIdGenerator.php
- packages/better-php-doc-parser/tests/PhpDocParser/SymfonyRouteTagParser/Fixture/SomeClassMethod.php
- rector-temp-phpstan20343.neon
- rules/doctrine/src/Rector/Class_/RemoveRepositoryFromEntityAnnotationRector.php
- src/Testing/PHPUnit/AbstractRectorTestCase.php
> [PhpDoc] Use generic approach to TagValueNode annotations quotes and explicitness

- packages/better-php-doc-parser/src/AnnotationReader/NodeAnnotationReader.php
- packages/better-php-doc-parser/src/PhpDocNodeFactory/Symfony/SymfonyRoutePhpDocNodeFactory.php
- packages/better-php-doc-parser/src/Printer/PhpDocInfoPrinter.php
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/DoctrineTest.php
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/MultilineTest.php
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/Source/Doctrine/case_sensitive.txt
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/Source/Doctrine/short.txt
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/Source/Multiline/assert_serialize.txt
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/Source/Multiline/assert_serialize_single_line.txt
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/Source/Multiline/many_to.txt
- packages/better-php-doc-parser/tests/PhpDocInfo/PhpDocInfoPrinter/Source/Multiline/multiline6.txt
- packages/better-php-doc-parser/tests/PhpDocParser/TagValueNodeReprint/Fixture/DoctrineColumn/InlinedColumn.php
- packages/better-php-doc-parser/tests/PhpDocParser/TagValueNodeReprint/Fixture/SymfonyRoute/MultiRoute.php
> Fix single-line doc end

- packages/node-type-resolver/src/Node/AttributeKey.php
- packages/phpstan-static-type-mapper/src/TypeMapper/StaticTypeMapper.php
- rules/type-declaration/src/Rector/FunctionLike/ReturnTypeDeclarationRector.php
- rules/type-declaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/FixtureForPhp80/static_.php.inc
- rules/type-declaration/tests/Rector/FunctionLike/ReturnTypeDeclarationRector/Php80RectorTest.php
- src/ValueObject/PhpVersionFeature.php
> [PHP 8.0] Add static type

- packages/better-php-doc-parser/src/Annotation/AnnotationItemsResolver.php
- packages/better-php-doc-parser/src/Annotation/AnnotationVisibilityDetector.php
- packages/better-php-doc-parser/src/AnnotationReader/NodeAnnotationReader.php
- packages/better-php-doc-parser/src/PhpDocNode/AbstractTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Class_/IndexTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Class_/UniqueConstraintTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Property_/JoinColumnTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Property_/ManyToManyTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Property_/ManyToOneTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Property_/OneToManyTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Property_/OneToOneTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/JMS/JMSInjectTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNodeFactory/AbstractPhpDocNodeFactory.php
- packages/better-php-doc-parser/src/PhpDocNodeFactory/Doctrine/Class_/IndexPhpDocNodeFactory.php
- packages/better-php-doc-parser/src/PhpDocNodeFactory/Doctrine/Class_/TablePhpDocNodeFactory.php
- packages/better-php-doc-parser/src/PhpDocNodeFactory/Doctrine/Class_/UniqueConstraintPhpDocNodeFactory.php
- packages/better-php-doc-parser/src/PhpDocNodeFactory/Doctrine/Property_/DoctrineTargetEntityPhpDocNodeFactory.php
- packages/better-php-doc-parser/src/PhpDocNodeFactory/Doctrine/Property_/JoinTablePhpDocNodeFactory.php
- packages/better-php-doc-parser/src/PhpDocNodeFactory/JMS/JMSInjectPhpDocNodeFactory.php
- packages/better-php-doc-parser/src/PhpDocNodeFactory/MultiPhpDocNodeFactory.php
- packages/doctrine-annotation-generated/src/PhpDocNode/ConstantReferenceIdentifierRestorer.php
- stubs/Symfony/Component/Routing/Annotation/Route.php
See https://github.com/rectorphp/rector/pull/3281#discussion_r417944315
> Add resolving for private properties of annotation object

- README.md
- src/Application/RectorApplication.php
- src/Configuration/Configuration.php
- src/Configuration/Option.php
- src/Console/Command/ProcessCommand.php
- it's confusing, people are unable to use it https://github.com/rectorphp/rector/issues/3020#issuecomment-621765729
- the `--only="Namespace\Class"` must be quoted right - slashes? single? double? + OS differences
- unable to configure, e.g. rename class method
- no CLI tool has this *feature*, so API is not intuitive
<br>
- configurable
- [YAML autocomplete](https://www.tomasvotruba.com/blog/2018/08/23/9-features-of-symfony-plugin-you-should-not-miss-in-gifs/#4-instant-service-autocomplete-in-yaml-yaml)
- easy to reproduce in [demo](getrector.org/demo)
```yaml
services:
Namespace\Class: null
```
> [DX] drop confusing --only option to promote config

- packages/node-collector/src/NodeCollector/ParsedPropertyFetchNodeCollector.php
- packages/node-name-resolver/src/NodeNameResolver.php
- packages/node-type-resolver/tests/NodeVisitor/FunctionMethodAndClassNodeVisitor/FunctionMethodAndClassNodeVisitorTest.php
```
[ERROR] Could not process "abz/SomeClass.php" file, due to:                                                            
"Pick more specific node than "PhpParser\Node\Expr\MethodCall"
```
```
[ERROR] Could not process "abz/SomeClass.php" file, due to:                                                            
"Pick more specific node than "PhpParser\Node\Expr\MethodCall", e.g. "$node->name"                             
Caused in "abz/SomeClass.php" file on line 9 on code "$this->foo()".     
Look at "InnerRectorClass.php:35"
```
> Improve $node name get on static or method call

- README.md
- phpstan.neon
- phpunit.xml
- rules/nette-tester-to-phpunit/src/Rector/StaticCall/NetteAssertToPHPUnitAssertRector.php
- rules/oxid/src/Rector/FuncCall/OxidReplaceBackwardsCompatabilityClassRector.php
- rules/php72/src/Rector/Each/ListEachRector.php
- rules/php72/src/Rector/Each/WhileEachToForeachRector.php
- rules/psr4/config/config.yaml
- rules/sensio/src/Rector/FrameworkExtraBundle/TemplateAnnotationRector.php
- src/Rector/Architecture/DependencyInjection/ReplaceVariableByPropertyFetchRector.php
- utils/phpstan-extensions/config/phpstan-extensions.neon
- utils/phpstan-extensions/src/Rule/ClassLike/KeepRectorNamespaceForRectorRule.php
- utils/phpstan-extensions/src/Rule/ClassMethod/PreventParentMethodVisibilityOverrideRule.php
- utils/phpstan-extensions/src/Rule/SeeAnnotationToTestRule.php
- utils/phpstan-extensions/tests/AbstractServiceAwareRuleTestCase.php
- utils/phpstan-extensions/tests/Rule/ClassLike/KeepRectorNamespaceForRectorRuleTest.php
- utils/phpstan-extensions/tests/Rule/ClassLike/Source/Rector/WrongClass.php
- utils/phpstan-extensions/tests/Rule/ClassMethod/PreventParentMethodVisibilityOverrideRuleTest.php
- utils/phpstan-extensions/tests/Rule/ClassMethod/Source/GoodVisibility.php
- utils/phpstan-extensions/tests/Rule/SeeAnnotationToTestRule/Fixture/ClassMissingDocBlockRector.php
- utils/phpstan-extensions/tests/Rule/SeeAnnotationToTestRule/Fixture/ClassMissingSeeAnnotationRector.php
- utils/phpstan-extensions/tests/Rule/SeeAnnotationToTestRule/SeeAnnotationToTestRuleTest.php
Every Rector should have `@see` annotation with test case reference, so it's easy to jump in and create a fixture. 
Also will be useful in the future for: https://github.com/rectorphp/getrector.org/issues/155
<br>
:no_entry_sign: 
```php
final class NetteAssertToPHPUnitAssertRector extends AbstractRector
```
<br>
:+1: 
```php
/**
* @see \Rector\NetteTesterToPHPUnit\Tests\Rector\Class_\NetteTesterClassToPHPUnitClassRector\NetteTesterPHPUnitRectorTest
*/
final class NetteAssertToPHPUnitAssertRector extends AbstractRector
```
> [Utils] PHPStan rule improvements

- composer.json
- config/set/order/order.yaml
- docs/rector_rules_overview.md
- phpstan.neon
- rules/order/src/Rector/Class_/OrderPrivateMethodsByUseRector.php
- rules/order/tests/Rector/Class_/OrderPrivateMethodsByUseRector/Fixture/fixture.php.inc
- rules/order/tests/Rector/Class_/OrderPrivateMethodsByUseRector/Fixture/multi_call.php.inc
- rules/order/tests/Rector/Class_/OrderPrivateMethodsByUseRector/OrderPrivateMethodsByUseRectorTest.php
Mimics https://github.com/symplify/coding-standard/blob/master/src/Fixer/Order/PrivateMethodOrderByUseFixer.php
> [Order] Add OrderPrivateMethodsByUseRector

- config/set/order/order.yaml
- docs/rector_rules_overview.md
- rules/order/src/PropertyRanker.php
- rules/order/src/Rector/Class_/OrderPropertyByComplexityRector.php
- rules/order/src/StmtOrder.php
- rules/order/tests/Rector/Class_/OrderPropertyByComplexityRector/Fixture/complex_types.php.inc
- rules/order/tests/Rector/Class_/OrderPropertyByComplexityRector/Fixture/fixture.php.inc
- rules/order/tests/Rector/Class_/OrderPropertyByComplexityRector/Fixture/skip_correct.php.inc
- rules/order/tests/Rector/Class_/OrderPropertyByComplexityRector/OrderPropertyByComplexityRectorTest.php
- rules/order/tests/Rector/Class_/OrderPropertyByComplexityRector/Source/AnotherSimpleType.php
- rules/order/tests/Rector/Class_/OrderPropertyByComplexityRector/Source/ComplexType.php
Mimics https://github.com/symplify/coding-standard/blob/a7a665c88845545b314f16ecf1081883ae51adfb/src/Fixer/Order/PropertyOrderByComplexityFixer.php
> [Order] Add OrderPropertyByComplexityRector

- docs/create_own_rule.md
It was linking to non existing page.
I've also changed the link name to match my another pull request :)
> Fix link and it's name

- rules/coding-style/src/Rector/ClassConst/VarConstantCommentRector.php
If we don't redeclare the `$phpDocInfo` variable, it will fail at the next line, as calling a method on null will fail.
> Rule "Rector\ClassConst\VarConstantCommentRector" keeps throwing "could not process" errors.

- rules/type-declaration/src/Rector/ClassMethod/AddArrayReturnDocTypeRector.php
I'm in over my head on this one, as I don't really understand what the code is trying to do in that part. But I get errors like:
```
[ERROR] Could not process "<filename>" file by "Rector\TypeDeclaration\Rector\ClassMethod\AddArrayReturnDocTypeRector", due to:
"Call to a member function changeReturnType() on null".
```
The function is being called on `$phpDocInfo`, which can be null. It is declared in the docblock as being an object of type `PhpDocInfo`, but it seems that's not always true (in my code at least). 
This change is not the right solution! It fixed the processing errors. But it still is not correctly recognizing the classes being added to the docblock, as they show up as long names, even when both 'auto_import_names' and 'import_doc_blocks' are set to true.
I'm not going to …
> Rule Rector\ClassMethod\AddArrayReturnDocTypeRector could not process files

- docs/rector_rules_overview.md
- ecs.yaml
- packages/node-collector/src/NodeCollector/ParsedFunctionLikeNodeCollector.php
- packages/node-collector/src/NodeFinder/MethodCallParsedNodesFinder.php
- packages/node-type-resolver/src/NodeScopeAndMetadataDecorator.php
- packages/node-type-resolver/src/PHPStan/TypeComparator.php
- rules/code-quality/src/Rector/FuncCall/SingleInArrayToCompareRector.php
- rules/coding-style/src/Naming/ClassNaming.php
- rules/dead-code/src/Rector/MethodCall/RemoveDefaultArgumentValueRector.php
- rules/laravel/src/Rector/StaticCall/MinutesToSecondsInCacheRector.php
- rules/legacy/config/config.yaml
- rules/legacy/src/Rector/Node/FunctionToStaticMethodRector.php
- rules/legacy/src/ValueObject/StaticCallPointer.php
- rules/legacy/tests/Rector/FileSystem/FunctionToStaticMethodRector/FunctionToStaticMethodRectorTest.php
- rules/legacy/tests/Rector/FileSystem/FunctionToStaticMethodRector/Source/ExpectedStaticFunctions.php
- rules/legacy/tests/Rector/FileSystem/FunctionToStaticMethodRector/Source/static_functions.php
- rules/php55/src/Rector/String_/StringClassNameToClassConstantRector.php
- rules/php70/src/EregToPcreTransformer.php
- rules/phpunit/src/Rector/ExceptionAnnotationRector.php
- rules/phpunit/src/Rector/MethodCall/GetMockBuilderGetMockToCreateMockRector.php
- src/Console/Command/ShowCommand.php
- src/FileSystem/FilesystemTweaker.php
- src/Php/PhpVersionProvider.php
- src/Rector/MethodBody/NormalToFluentRector.php
- src/Rector/Property/PropertyToMethodRector.php
- src/Testing/PHPUnit/AbstractFileSystemRectorTestCase.php
- src/Util/StaticRectorStrings.php
> [Legacy] Add FunctionToStaticMethodRector

- composer.json
- config/set/framework-migration/mockista-to-mockery.yaml
- docs/rector_rules_overview.md
- packages/node-name-resolver/src/NodeNameResolver.php
- rules/mockista-to-mockery/config/config.yaml
- rules/mockista-to-mockery/src/MockistaDetector.php
- rules/mockista-to-mockery/src/Rector/ClassMethod/MockistaMockToMockeryMockRector.php
- rules/mockista-to-mockery/src/Rector/Class_/MockeryTearDownRector.php
- rules/mockista-to-mockery/tests/Rector/ClassMethod/MockistaMockToMockeryMockRector/Fixture/fixture.php.inc
- rules/mockista-to-mockery/tests/Rector/ClassMethod/MockistaMockToMockeryMockRector/Fixture/method_args.php.inc
- rules/mockista-to-mockery/tests/Rector/ClassMethod/MockistaMockToMockeryMockRector/Fixture/method_with_args_without_any.php.inc
- rules/mockista-to-mockery/tests/Rector/ClassMethod/MockistaMockToMockeryMockRector/Fixture/methods_to_remove.php.inc
- rules/mockista-to-mockery/tests/Rector/ClassMethod/MockistaMockToMockeryMockRector/Fixture/property_or_method.php.inc
- rules/mockista-to-mockery/tests/Rector/ClassMethod/MockistaMockToMockeryMockRector/Fixture/set_value.php.inc
- rules/mockista-to-mockery/tests/Rector/ClassMethod/MockistaMockToMockeryMockRector/Fixture/twice.php.inc
- rules/mockista-to-mockery/tests/Rector/ClassMethod/MockistaMockToMockeryMockRector/Fixture/use_value.php.inc
- rules/mockista-to-mockery/tests/Rector/ClassMethod/MockistaMockToMockeryMockRector/MockistaMockToMockeryMockRectorTest.php
- rules/mockista-to-mockery/tests/Rector/ClassMethod/MockistaMockToMockeryMockRector/Source/User.php
- rules/mockista-to-mockery/tests/Rector/Class_/MockeryTearDownRector/Fixture/add_to_existing_tear_down.php.inc
- rules/mockista-to-mockery/tests/Rector/Class_/MockeryTearDownRector/Fixture/fixture.php.inc
- rules/mockista-to-mockery/tests/Rector/Class_/MockeryTearDownRector/Fixture/skip_existing.php.inc
- rules/mockista-to-mockery/tests/Rector/Class_/MockeryTearDownRector/MockeryTearDownRectorTest.php
- stubs/Mockista/DummyMock.php
- stubs/Mockista/MockInterface.php
- stubs/Mockista/mock_function.php
- From: https://github.com/janmarek/mockista
- To: https://github.com/mockery/mockery
> [MockistaToMockery] init

- packages/rector-generator/src/Node/NodeClassProvider.php
> Fix invalid path

- rules/type-declaration/src/Rector/Property/PropertyTypeDeclarationRector.php
- rules/type-declaration/src/TypeInferer/PropertyTypeInferer/VarDocPropertyTypeInferer.php
> fix missing doc for property type infering

- rules/renaming/src/Rector/Annotation/RenameAnnotationRector.php
- rules/renaming/tests/Rector/Annotation/RenameAnnotationRector/Fixture/skip_method_with_comment_not_php_doc.php.inc
Fixes #3381
Including the fixture produces error:
```
$ phpunit rules/renaming/tests/Rector/Annotation/RenameAnnotationRector/RenameAnnotationRectorTest.php 
PHPUnit 9.1.4 by Sebastian Bergmann and contributors.
Runtime:       PHP 7.3.15-3
Configuration: /home/eclipxe/work/github/rector/phpunit.xml
.E                                                                  2 / 2 (100%)
Time: 00:02.103, Memory: 82.36 MB
There was 1 error:
1) Rector\Renaming\Tests\Rector\Annotation\RenameAnnotationRector\RenameAnnotationRectorTest::test with data set #1 ('/home/eclipxe/work/github/rec...hp.inc')
Error: Call to a member function hasByName() on null
/home/eclipxe/work/github/rector/rules/renaming/src/Rector/Annotation/RenameAnnotationRector.php:106
...
```
The null check and return make the test pass …
> Fix RenameAnnotationRector for null phpdoc

- src/PhpParser/Printer/BetterStandardPrinter.php
(Resolving the same type of issue as in https://github.com/rectorphp/rector/pull/3394)
To maintain the assumption, that rector would only change what it was instructed to, when there's an empty php code `<?php ?>`, we want to preserve it.
You can see an example of when it's necessary here: https://github.com/rectorphp/rector/issues/3352#issuecomment-631691576
Removing empty php code should be a specific Rector rule that people can opt-in to run, instead of automatically being removed every time Rector runs.
> Keep empty php code as is

- docs/rector_rules_overview.md
- packages/node-collector/src/NodeCollector/ParsedClassConstFetchNodeCollector.php
- rules/nette/src/Rector/MethodCall/ContextGetByTypeToConstructorInjectionRector.php
- rules/nette/tests/Rector/MethodCall/ContextGetByTypeToConstructorInjectionRector/ContextGetByTypeToConstructorInjectionRectorTest.php
- rules/nette/tests/Rector/MethodCall/ContextGetByTypeToConstructorInjectionRector/Fixture/Source/SomeTypeToInject.php
- rules/nette/tests/Rector/MethodCall/ContextGetByTypeToConstructorInjectionRector/Fixture/fixture.php.inc
Do you want to get rid of `$this->context`?
```diff
{
/**
* @var \Nette\DI\Container
*/
private $context;
+    /**
+     * @var SomeTypeToInject
+     */
+    private $someTypeToInject;
+
+    public function __construct(SomeTypeToInject $someTypeToInject)
+    {
+        $this->someTypeToInject = $someTypeToInject;
+    }
+
{
-        $someTypeToInject = $this->context->getByType(SomeTypeToInject::class);
+        $someTypeToInject = $this->someTypeToInject;
}
}
```
> [Nette] Add ContextGetByTypeToConstructorInjectionRector

- config/set/nette/kdyby-events-to-contributte-event-dispatcher.yaml
- docs/rector_rules_overview.md
- rules/nette-kdyby/src/Naming/EventClassNaming.php
- rules/nette-kdyby/src/NodeFactory/CustomEventFactory.php
- rules/nette-kdyby/src/Rector/MethodCall/ReplaceMagicPropertyEventWithEventClassRector.php
- rules/nette-kdyby/tests/Rector/MethodCall/ReplaceMagicPropertyEventWithEventClassRector/Fixture/fixture.php.inc
- rules/nette-kdyby/tests/Rector/MethodCall/ReplaceMagicPropertyEventWithEventClassRector/ReplaceMagicPropertyEventWithEventClassRectorTest.php
- rules/nette-kdyby/tests/Rector/MethodCall/ReplaceMagicPropertyEventWithEventClassRector/Source/ExpectedClass.php
- src/Testing/PHPUnit/AbstractRectorTestCase.php
> [NetteKdyby] Add ReplaceMagicPropertyEventWithEventClassRector

- config/set/coding-style/coding-style.yaml
- rules/coding-style/src/Rector/Variable/UnderscoreToPascalCaseVariableAndPropertyNameRector.php
- rules/coding-style/tests/Rector/Variable/UnderscoreToPascalCaseVariableAndPropertyNameRector/Fixture/fixture.php.inc
- rules/coding-style/tests/Rector/Variable/UnderscoreToPascalCaseVariableAndPropertyNameRector/Fixture/property_and_static_property.php.inc
- rules/coding-style/tests/Rector/Variable/UnderscoreToPascalCaseVariableAndPropertyNameRector/Fixture/skip_first_underscore.php.inc
- rules/coding-style/tests/Rector/Variable/UnderscoreToPascalCaseVariableAndPropertyNameRector/Fixture/skip_reserved_names.php.inc
- rules/coding-style/tests/Rector/Variable/UnderscoreToPascalCaseVariableAndPropertyNameRector/UnderscoreToPascalCaseVariableAndPropertyNameRectorTest.php
- rules/php73/src/Rector/FuncCall/SetCookieRector.php
- rules/privatization/src/Rector/Class_/ChangeLocalPropertyToVariableRector.php
> [CodingStyle] UnderscoreToCamelCaseVariableAndPropertyNameRector

- config/set/privatization/privatization.yaml
- rules/privatization/src/Rector/ClassMethod/PrivatizeFinalClassMethodRector.php
- rules/privatization/tests/Rector/ClassMethod/PrivatizeFinalClassMethodRector/Fixture/change_parent_without_care.php.inc
- rules/privatization/tests/Rector/ClassMethod/PrivatizeFinalClassMethodRector/Fixture/fixture.php.inc
- rules/privatization/tests/Rector/ClassMethod/PrivatizeFinalClassMethodRector/Fixture/keep_create_component.php.inc
- rules/privatization/tests/Rector/ClassMethod/PrivatizeFinalClassMethodRector/Fixture/keep_parent_protected_method.php.inc
- rules/privatization/tests/Rector/ClassMethod/PrivatizeFinalClassMethodRector/PrivatizeFinalClassMethodRectorTest.php
- rules/privatization/tests/Rector/ClassMethod/PrivatizeFinalClassMethodRector/Source/AbstractClassWithProtectedClassMethod.php
- rules/privatization/tests/Rector/Property/PrivatizeFinalClassPropertyRector/Fixture/change_parent_without_care.php.inc
- rules/privatization/tests/Rector/Property/PrivatizeFinalClassPropertyRector/Fixture/keep_parent_protected.php.inc
- rules/privatization/tests/Rector/Property/PrivatizeFinalClassPropertyRector/Source/AbstractClassWithProtectedProperty.php
> [Privatization] Add PrivatizeFinalClassMethodRector

- config/set/php/php52.yaml
- docs/rector_rules_overview.md
- rules/php53/src/Rector/Assign/ClearReturnNewByReferenceRector.php
- rules/php53/src/Rector/Variable/ReplaceHttpServerVarsByServerRector.php
- rules/php53/tests/Rector/Assign/ClearReturnNewByReferenceRector/ClearReturnNewByReferenceRectorTest.php
- rules/php53/tests/Rector/Assign/ClearReturnNewByReferenceRector/Fixture/fixture.php.inc
- rules/php53/tests/Rector/Variable/ReplaceHttpServerVarsByServerRector/Fixture/fixture.php.inc
- rules/php53/tests/Rector/Variable/ReplaceHttpServerVarsByServerRector/ReplaceHttpServerVarsByServerRectorTest.php
- src/Rector/FuncCall/RemoveFuncCallArgRector.php
- src/Rector/FuncCall/RemoveIniGetSetFuncCallRector.php
- tests/Rector/FuncCall/RemoveFuncCallArgRector/Fixture/remove_ldap.php.inc
- tests/Rector/FuncCall/RemoveFuncCallArgRector/RemoveFuncCallArgRectorTest.php
- tests/Rector/FuncCall/RemoveIniGetSetFuncCallRector/Fixture/keep_other.php.inc
- tests/Rector/FuncCall/RemoveIniGetSetFuncCallRector/Fixture/remove_listed.php.inc
- tests/Rector/FuncCall/RemoveIniGetSetFuncCallRector/RemoveIniGetSetFuncCallRectorTest.php
These rules were created in cooperation with @afilina to help legacy code cleanup
> Add RemoveFuncCallArgRector, ClearReturnNewByReferenceRector, RemoveIniGetSetFuncCallRector, ReplaceHttpServerVarsByServerRector

- packages/node-type-resolver/config/config.yaml
- packages/node-type-resolver/src/PHPStan/Scope/ScopeFactory.php
As MutatingScope constructor can change often and is not covered by backwards compatibility promise, this is a much better way to construct it. As you can notice, it's just a bunch of code deleted as you can simply call `$this->phpStanScopeFactory->create()` for the same effect.
Thanks.
> Future-proof ScopeFactory

- config/set/php/php80.yaml
- ecs.yaml
- packages/post-rector/src/Rector/NodeRemovingRector.php
- rules/php53/tests/Rector/Variable/ReplaceHttpServerVarsByServerRector/ReplaceHttpServerVarsByServerRectorTest.php
- rules/php80/src/NodeManipulator/TokenManipulator.php
- rules/php80/src/Rector/FuncCall/TokenGetAllToObjectRector.php
- rules/php80/tests/Rector/FuncCall/TokenGetAllToObjectRector/Fixture/code_sniffer_case.php.inc
- rules/php80/tests/Rector/FuncCall/TokenGetAllToObjectRector/Fixture/fixture.php.inc
- rules/php80/tests/Rector/FuncCall/TokenGetAllToObjectRector/Fixture/not_array_first.php.inc
- rules/php80/tests/Rector/FuncCall/TokenGetAllToObjectRector/Fixture/skip_non_token_array.php.inc
- rules/php80/tests/Rector/FuncCall/TokenGetAllToObjectRector/TokenGetAllToObjectRectorTest.php
Ref #3127 
/cc @staabm This is going to be a bit wobbly, as Rector doesn't have API for tracking variable flow, but it will do the job.
> [PHP 8.0] Add TokenGetAllToObjectRector

- composer.json
- config/set/php/php80.yaml
- rules/code-quality/src/Rector/Catch_/ThrowWithPreviousExceptionRector.php
- rules/coding-style/src/Rector/Catch_/CatchExceptionNameMatchingTypeRector.php
- rules/php80/src/Rector/Catch_/RemoveUnusedVariableInCatchRector.php
- rules/php80/tests/Rector/Catch_/RemoveUnusedVariableInCatchRector/Fixture/fixture.php.inc
- rules/php80/tests/Rector/Catch_/RemoveUnusedVariableInCatchRector/RemoveUnusedVariableInCatchRectorTest.php
- rules/phpunit/src/Rector/TryCatchToExpectExceptionRector.php
Ref #3127 
Enabled in php-parser 4.5 - https://github.com/nikic/PHP-Parser/pull/666
> [PHP 8.0] Add RemoveUnusedVariableInCatchRector

- packages/node-type-resolver/src/PHPStan/Type/TypeFactory.php
- phpstan.neon
- stubs/PHPUnit/Framework/TestListener.php
PHPStan 0.12.26 makes user's lives easier by a mile. See [the release notes](https://github.com/phpstan/phpstan/releases/tag/0.12.26) and [the accompanying article](https://phpstan.org/blog/zero-config-analysis-with-static-reflection).
> PHPStan compatibility fixes

- docs/rector_rules_overview.md
- src/Rector/MethodBody/ReturnThisRemoveRector.php
Change classname in ReturnThisRemoveRector example.
Looks like it should be the same with config in example above.
> Fix typo in rector_rules_overview.md

- config/set/cakephp/cakephp-fluent-options.yaml
- rules/cakephp/src/Rector/MethodCall/ArrayToFluentCallRector.php
- rules/cakephp/tests/Rector/MethodCall/ArrayToFluentCallRector/ArrayToFluentCallRectorTest.php
- rules/cakephp/tests/Rector/MethodCall/ArrayToFluentCallRector/Fixture/fixture.php.inc
- rules/cakephp/tests/Rector/MethodCall/ArrayToFluentCallRector/Fixture/fixture2.php.inc
- rules/cakephp/tests/Rector/MethodCall/ArrayToFluentCallRector/Source/ConfigurableClass.php
- rules/cakephp/tests/Rector/MethodCall/ArrayToFluentCallRector/Source/FactoryClass.php
CakePHP historically used arrays to configure various objects. Since 3.x, it also allows to use chain of fluent method calls to configure them, this also helps to avoid typos, enables type checks.
This rector converts
```php
$this->belongsTo('Authors', [
'foreignKey' => 'author_id',
'propertyName' => 'person'
]);
```
into call chain like
```php
$this->belongsTo('Authors')->setForeignKey('author_id')->setProperty('person');
```
Ideally output should be one call per line, but as I understand Rector only manipulates AST, not formatting.
```php
$this->belongsTo('Authors')
->setForeignKey('author_id')
->setProperty('person');
```
> [CakePHP] Convert array options to fluent method calls 

- rules/type-declaration/src/Rector/FunctionLike/ParamTypeDeclarationRector.php
- rules/type-declaration/tests/Rector/FunctionLike/ParamTypeDeclarationRector/Fixture/trait.php.inc
Fixes #3431
I'm not sure about my logic here of checking if it's a trait at all. I tried to use the inferred type's getClassReflection method, but that was null, and I felt like it should not be.
> Don't type hint to traits

- rules/solid/tests/Rector/Foreach_/ChangeNestedForeachIfsToEarlyContinueRector/Fixture/comment_inside_if_statement.php.inc
When there is a comment inside the if statement before the brace, it misses a brace creating the early continue statement.
https://getrector.org/demo/9757fa4a-ed15-4130-8bdc-ae150305360e
> I found a bug with the ChangeNestedForeachIfsToEarlyContinueRector

- README.md
- config/config.yaml
- packages/node-type-resolver/src/NodeScopeAndMetadataDecorator.php
- packages/node-type-resolver/src/PHPStan/Scope/PHPStanNodeScopeResolver.php
- phpstan.neon
- rules/php74/tests/Rector/Property/TypedPropertyRector/FixtureSafeTypes/complete_strict_type.php.inc
- rules/php74/tests/Rector/Property/TypedPropertyRector/FixtureSafeTypes/make_sure_docs_is_kept.php.inc
- rules/php74/tests/Rector/Property/TypedPropertyRector/FixtureSafeTypes/skip_for_doc.php.inc
- rules/php74/tests/Rector/Property/TypedPropertyRector/SafeTypesTest.php
- src/Configuration/Option.php
Do you want to use only explicit PHP type declaration? Enable `safe_types`:
```yaml
parameters:
safe_types: true
```
Then, **docblocks are skipped** and only pure PHP is source of type truth:
```diff
<?php
class ValueObject
{
public $value;
-    public $count;
+    public int $count;
/**
* @param string $value
*/
public function __construct($value, string $count)
{
$this->value = $value;
$this->count = $count
}
}
```
> [Experimental] Add safe_types option

- rules/php56/src/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector.php
- rules/php56/tests/Rector/FunctionLike/AddDefaultValueForUndefinedVariableRector/Fixture/arrow_function.php.inc
* do not try to set variables in arrow functions, fixes error `Undefined property: PhpParser\Node\Expr\ArrowFunction::$stmts at AddDefaultValueForUndefinedVariableRector.php:118`
* consider that arrow functions inherit the parent scope
> [PHP] Handle arrow functions in AddDefaultValueForUndefinedVariableRector 

- rules/symfony/src/Rector/MethodCall/FormTypeInstanceToClassConstRector.php
- tests/Rector/MethodBody/FluentReplaceRector/FluentReplaceRectorTest.php
Fixes #3570 by adding `Symfony\Bundle\FrameworkBundle\Controller\AbstractController` as a valid object type.
> Symfony FormTypeInstanceToClassConstRector: Include AbstractController in allowed object types

- docs/rector_rules_overview.md
- rules/coding-style/src/Rector/String_/UseClassKeywordForClassNameResolutionRector.php
- rules/coding-style/tests/Rector/String_/UseClassKeywordForClassNameResolutionRector/Fixture/empty_string_before_class_name.php.inc
- rules/coding-style/tests/Rector/String_/UseClassKeywordForClassNameResolutionRector/Fixture/fixture.php.inc
- rules/coding-style/tests/Rector/String_/UseClassKeywordForClassNameResolutionRector/Fixture/skip_non_existing_class.php.inc
- rules/coding-style/tests/Rector/String_/UseClassKeywordForClassNameResolutionRector/UseClassKeywordForClassNameResolutionTest.php
It seems like `SplitStringClassConstantToClassConstFetchRector` might be replaced with this new rector.
Closes https://github.com/rectorphp/rector/issues/3389
> Add new rector to replace hardcoded class name reference in string with `class` keyword reference

- rules/coding-style/src/Rector/String_/UseClassKeywordForClassNameResolutionRector.php
- rules/coding-style/tests/Rector/String_/UseClassKeywordForClassNameResolutionRector/Fixture/mutiple_occurrences_in_one_string.php.inc
> update rule to support multiple occurrences of the class in the string

- rules/coding-style/src/Rector/Variable/UnderscoreToPascalCaseVariableNameRector.php
- rules/coding-style/tests/Rector/Variable/UnderscoreToPascalCaseVariableNameRector/Fixture/skip_underscored_reserved_names.php.inc
- src/Php/ReservedKeywordAnalyzer.php
Follow up to #https://github.com/rectorphp/rector/pull/3653
> [CodingStyle] Make UnderscoreToPascalCaseVariableNameRector skip native variables, like _SERVER

- rules/mockery-to-prophecy/src/Rector/StaticCall/MockeryCloseRemoveRector.php
- rules/mockery-to-prophecy/tests/Rector/StaticCall/MockeryToProphecyRector/Fixture/MockeryClose.php.inc
- rules/mockery-to-prophecy/tests/Rector/StaticCall/MockeryToProphecyRector/MockeryToProphecyRectorTest.php
A second step in removing mockery, remove the call to `\Mockery::close()`
> [MockeryToProphecy]  Remove close call to mockery from test classes

- src/PhpParser/Printer/BetterStandardPrinter.php
This fixes the following warning.
Warning: str_repeat(): Second argument has to be greater than or equal to 0 in vendor\rector\rector\src\PhpParser\Printer\BetterStandardPrinter.php on line 158
Not sure why my source is producing this, but very old PHP 4 -> 5.6 code that is poorly formatted.  I may be able to come up with a case that reproduces it, but it does not seem worth the effort, as it is a very local fix and should not impact anything else.
> Prevent negative values for IndentLevel

- config/set/coding-style/coding-style.yaml
- docs/rector_rules_overview.md
- phpstan.neon
- rules/coding-style/src/Rector/Ternary/TernaryConditionVariableAssignmentRector.php
- rules/coding-style/tests/Rector/Ternary/TernaryConditionVariableAssignmentRector/Fixture/fixture.php.inc
- rules/coding-style/tests/Rector/Ternary/TernaryConditionVariableAssignmentRector/Fixture/skip_different_variable_names.php.inc
- rules/coding-style/tests/Rector/Ternary/TernaryConditionVariableAssignmentRector/Fixture/skip_ternary_with_variable_assignment.php.inc
- rules/coding-style/tests/Rector/Ternary/TernaryConditionVariableAssignmentRector/Fixture/skip_ternary_without_variable_assignment.php.inc
- rules/coding-style/tests/Rector/Ternary/TernaryConditionVariableAssignmentRector/TernaryConditionVariableAssignmentRectorTest.php
After discussion at https://github.com/symplify/symplify/issues/2006, here is a new Rector to convert the following:
```php
$value ? $a = 1 : $a = 0; // Before
$a = $value ? 1 : 0; // After
```
> [CodingStyle] Create new TernaryConditionVariableAssignmentRector

- config/set/naming/naming.yaml
- docs/rector_rules_overview.md
- rules/naming/src/Naming/ExpectedNameResolver.php
- rules/naming/src/Rector/Assign/RenameVariableToMatchGetMethodNameRector.php
- rules/naming/tests/Rector/Assign/RenameVariableToMatchGetMethodNameRector/Fixture/clousure.php.inc
- rules/naming/tests/Rector/Assign/RenameVariableToMatchGetMethodNameRector/Fixture/fixture.php.inc
- rules/naming/tests/Rector/Assign/RenameVariableToMatchGetMethodNameRector/Fixture/function.php.inc
- rules/naming/tests/Rector/Assign/RenameVariableToMatchGetMethodNameRector/Fixture/last_in_chain.php.inc
- rules/naming/tests/Rector/Assign/RenameVariableToMatchGetMethodNameRector/Fixture/rename_in_docblock.php.inc
- rules/naming/tests/Rector/Assign/RenameVariableToMatchGetMethodNameRector/Fixture/skip_array_dim_fetch.php.inc
- rules/naming/tests/Rector/Assign/RenameVariableToMatchGetMethodNameRector/Fixture/skip_no_get.php.inc
- rules/naming/tests/Rector/Assign/RenameVariableToMatchGetMethodNameRector/Fixture/skip_on_conflict.php.inc
- rules/naming/tests/Rector/Assign/RenameVariableToMatchGetMethodNameRector/Fixture/skip_on_conflict_with_closure_uses.php.inc
- rules/naming/tests/Rector/Assign/RenameVariableToMatchGetMethodNameRector/Fixture/skip_on_conflict_with_param_name.php.inc
- rules/naming/tests/Rector/Assign/RenameVariableToMatchGetMethodNameRector/Fixture/skip_variables_from_params.php.inc
- rules/naming/tests/Rector/Assign/RenameVariableToMatchGetMethodNameRector/Fixture/static_call.php.inc
- rules/naming/tests/Rector/Assign/RenameVariableToMatchGetMethodNameRector/FixturePhp74/arrow_function.php.inc
- rules/naming/tests/Rector/Assign/RenameVariableToMatchGetMethodNameRector/RenameVariableToMatchGetMethodNameRectorTest.php
Partially closes https://github.com/rectorphp/rector/issues/3656
Renames only after get method. It seems to me that for create method we should create a separate rule.
> [Naming] Name variable after get method

- config/set/coding-style/coding-style.php
- docs/rector_rules_overview.md
- rules/coding-style/src/Rector/Variable/WrapVariableVariableNameInCurlyBracesRector.php
- rules/coding-style/tests/Rector/Variable/WrapVariableVariableNameInCurlyBracesRector/Fixture/skip_global_variable_variables_with_braces.php.inc
- rules/coding-style/tests/Rector/Variable/WrapVariableVariableNameInCurlyBracesRector/Fixture/skip_property_fetch_variable.php.inc
- rules/coding-style/tests/Rector/Variable/WrapVariableVariableNameInCurlyBracesRector/Fixture/skip_variable.php.inc
- rules/coding-style/tests/Rector/Variable/WrapVariableVariableNameInCurlyBracesRector/Fixture/skip_variable_variables_with_braces.php.inc
- rules/coding-style/tests/Rector/Variable/WrapVariableVariableNameInCurlyBracesRector/Fixture/variable_variables.php.inc
- rules/coding-style/tests/Rector/Variable/WrapVariableVariableNameInCurlyBracesRector/WrapVariableVariableNameInCurlyBracesRectorTest.php
After discussion at https://github.com/symplify/symplify/issues/2006, here is a new Rector to convert the following:
```php
function run($foo)
{
// Before: valid in PHP 5 only
global $$foo->bar;
// After: valid in PHP 5 and 7
global ${$foo->bar};
}
```
The Rector also wraps other [variable variables](https://www.php.net/manual/en/language.variables.variable.php) in curly braces.
```php
$$value = true; // Before
${$value} = true; // After
```
> [CodingStyle] Create new WrapVariableVariableNameInCurlyBracesRector

- rules/coding-style/src/Rector/Catch_/CatchExceptionNameMatchingTypeRector.php
- rules/coding-style/tests/Rector/Catch_/CatchExceptionNameMatchingTypeRector/Fixture/pdo_exception.php.inc
[CatchExceptionNameMatchingTypeRector](https://github.com/rectorphp/rector/blob/master/docs/rector_rules_overview.md#catchexceptionnamematchingtyperector)
- `PDOException`
- `SQLException`
> Support exception names that begin with an abbreviation

- composer.json
- packages/node-type-resolver/src/PHPStan/Scope/PHPStanNodeScopeResolver.php
- phpstan.neon
- rules/dead-code/src/Rector/StaticCall/RemoveParentCallWithoutParentRector.php
- Resolves #3771
- Resolves #3668 
- Resolves #3643 
- Resolves #3640 
To get to php-parser 4.7, now we have to wait for @phpstan release with supporting it.
@ondrejmirtes Hi Ondra. It would fix BC breaks php-parser and phpstan's scoped parser. These is race condition since php-aprser 4.6 and different classes are picked to autoload.
Latest 0.12.33 seems to be locked with php-parser 4.6.x, as constant is missing.
Any ETA on this?
> Bump to phpstan 0.12.33, nikic/php-parser to 4.6

- composer.json
- config/set/php80.php
- docs/nodes_overview.md
- docs/rector_rules_overview.md
- phpstan.neon
- rules/php80/src/Rector/Switch_/ChangeSwitchToMatchRector.php
- rules/php80/tests/Rector/Switch_/ChangeSwitchToMatchRector/ChangeSwitchToMatchRectorTest.php
- rules/php80/tests/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/fixture.php.inc
- rules/php80/tests/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_2_and_more_stmts.php.inc
- rules/php80/tests/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_different_variable_assign.php.inc
- rules/php80/tests/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/skip_missing_break.php.inc
- utils/documentation-generator/src/Command/DumpNodesCommand.php
Covers https://github.com/nikic/PHP-Parser/pull/672, https://wiki.php.net/rfc/match_expression_v2
```diff
{
{
-        $statement = switch ($this->lexer->lookahead['type']) {
-            case Lexer::T_SELECT:
-                $statement = $this->SelectStatement();
-                break;
-            default:
-                $this->syntaxError('SELECT, UPDATE or DELETE');
-                break;
-        }
+        $statement = match ($this->lexer->lookahead['type']) {
+            Lexer::T_SELECT => $this->SelectStatement(),
+            default => $this->syntaxError('SELECT, UPDATE or DELETE'),
+        };
}
}
```
Ref #3127
> [PHP 8.0] Add ChangeSwitchToMatchRector

- packages/set/src/ValueObject/SetList.php
Only these four sets have different paths, ignore me if there's any reason for that.
Close #3915
> Fix set path was not found

- rules/php74/tests/Rector/Property/TypedPropertyRector/Fixture/property_from_method_call.php.inc
- src/PhpParser/Node/Manipulator/ClassMethodPropertyFetchManipulator.php
Before the fix, the following error occurred:
```
In NodeNameResolver.php line 223:
[Rector\Core\Exception\ShouldNotHappenException]                                                  
Pick more specific node than "PhpParser\Node\Expr\StaticCall", e.g. "$node->name"                 
```
> Fixed ClassMethodPropertyFetchManipulator to omit property assign by method call

- rules/nette-kdyby/src/Naming/VariableNaming.php
- rules/php70/tests/Rector/FuncCall/NonVariableToVariableOnFunctionCallRector/Fixture/reset_over_static_call.php.inc
Fixes error
```
[ERROR] Could not process "test.php" file, due to:                                            
"Pick more specific node than "PhpParser\Node\Expr\StaticCall", e.g. "$node->name"      
```
for the case in the attached test
> Fix variable name resolving for static method calls

- rules/solid/src/Rector/Class_/RepeatedLiteralToClassConstantRector.php
- rules/solid/tests/Rector/Class_/RepeatedLiteralToClassConstantRector/Fixture/beginning_with_number.php.inc
- rules/solid/tests/Rector/Class_/RepeatedLiteralToClassConstantRector/Fixture/with_dash_and_number.php.inc
Fixed constant names created from values:
| Bug | Value | Original constant | Fixed constant |
| - | - | - | - |
| empty string (syntax error) | "UTF-8" | | UTF-8 |
| trimmed number  | "camelCase-2" | CAMEL_CASE | CAMEL_CASE_2 |
| constant beginning with number (syntax error) | "1mb" | 1_MB | CONST_1_MB |
> Fixed some edge cases of creating constant name from value

- rules/code-quality/src/Rector/Concat/JoinStringConcatRector.php
- rules/code-quality/tests/Rector/Concat/JoinStringConcatRector/Fixture/skip_when_one_of_the_lines_becomes_longer_than_120.php.inc
This enhancement of `JoinStringConcatRector` prevents string joining if the whole concatenated string is longer than 120 chars
Useful for multi-line docs, CLI calls, etc.
> [Code Quality] If the whole concatenated string is longer than 120 chars, skip it

- rules/symfony/src/Rector/MethodCall/ContainerGetToConstructorInjectionRector.php
- rules/symfony/src/Rector/MethodCall/GetToConstructorInjectionRector.php
The properties `$containerAwareParentTypes` & `$getMethodAwareTypes` are set as property defaults, so that if they were explicitly enabled (without using config/set/symfony-constructor-injection.php), they would still work as expected without additional setup needed.
Other 'ContainerAware' classes may be useful to add, such as `\Symfony\Component\DependencyInjection\ContainerAwareTrait` & '\Symfony\Component\DependencyInjection\ContainerAwareInterface'.
> Replace types with container access from fe72e003e. fixes #4090

- compiler/src/Composer/ComposerJsonManipulator.php
Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>
> Typo fix: allowDevDependnecies to allowDevDependencies

- rules/symfony/src/Rector/ClassMethod/ConsoleExecuteReturnIntRector.php
- rules/symfony/tests/Rector/ClassMethod/ConsoleExecuteReturnIntRector/Fixture/skip-already-typehinted.php.inc
> Fixes #4013 ConsoleExecuteReturnIntRector ignores already type casted variable

- rules/phpunit/src/Rector/MethodCall/AssertEqualsToSameRector.php
- rules/phpunit/tests/Rector/MethodCall/AssertEqualsToSameRector/Fixture/fixture_2.php.inc
- rules/phpunit/tests/Rector/MethodCall/AssertEqualsToSameRector/Fixture/skip_2.php.inc
- There're two approaches about calling PHPUnit assertion methods.
One is about the `$this` and another is about the `self`.
- The ` AssertEqualsToSameRector` class should add fixtures about `self` method call.
> [PHPUnit] Add self call fixtures for AssertEqualsToSame rule

- rules/downgrade/src/Rector/Property/DowngradeTypedPropertyRector.php
- rules/downgrade/tests/Rector/Property/NoDocBlockDowngradeTypedPropertyRector/DowngradeTypedPropertyRectorTest.php
- rules/downgrade/tests/Rector/Property/NoDocBlockDowngradeTypedPropertyRector/Fixture/classname_nullable_type.php.inc
- rules/downgrade/tests/Rector/Property/NoDocBlockDowngradeTypedPropertyRector/Fixture/classname_type.php.inc
- rules/downgrade/tests/Rector/Property/NoDocBlockDowngradeTypedPropertyRector/Fixture/docblock_exists.php.inc
- rules/downgrade/tests/Rector/Property/NoDocBlockDowngradeTypedPropertyRector/Fixture/fixture.php.inc
- rules/downgrade/tests/Rector/Property/NoDocBlockDowngradeTypedPropertyRector/Fixture/nullable_type.php.inc
- rules/downgrade/tests/Rector/Property/NoDocBlockDowngradeTypedPropertyRector/Source/AnotherClass.php
Fixes #4094 
Please check the following:
- Option called `ADD_DOC_BLOCK`
- Default value: `true`
- To configure it, I've added in `rector.php`:
```php
// Don't output the docBlocks when removing typed properties
$services = $containerConfigurator->services();
$services->set(DowngradeTypedPropertyRector::class)
->call('configure', [[
DowngradeTypedPropertyRector::ADD_DOC_BLOCK => false,
]]);
```
Is this right? (Btw, it took me some time to find out about how to configure rectors, this info is not in the README... maybe you want to add a section to explain?)
- The tests have 2 configuration values (`true` and `false`). I couldn't find an example of a same test for different configurations. So I kept the original test (`DowngradeTypedPropertyRector`), and duplicated it under as …
> Configurable downgrade

- .gitignore
- rules/php74/src/Rector/Property/TypedPropertyRector.php
- rules/php74/tests/Rector/Property/TypedPropertyRector/Fixture/do_not_remove_class_docblock_array.php.inc
- rules/php74/tests/Rector/Property/TypedPropertyRector/Fixture/skip_class_docblock_array.php.inc
Fixes #3930
Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>
> Fixes #3930 : TypedPropertyRector should not remove DocBlock comment when it specifies the values contained in an array

- composer.json
Fix #4109: Require `webmozart/assert`.
> Fix #4109: Require `webmozart/assert`.

- config/set/mysql-to-mysqli.php
- rules/mysql-to-mysqli/src/Rector/Assign/MysqlAssignToMysqliRector.php
- rules/mysql-to-mysqli/src/Rector/FuncCall/MysqlQueryMysqlErrorWithLinkRector.php
- rules/mysql-to-mysqli/tests/Fixture/SetFixture.php.inc
- rules/mysql-to-mysqli/tests/Rector/Assign/MysqlAssignToMysqliRector/Fixture/fixture2.php.inc
This change addresses the following:
* Remove additional arguments (beyond host, username, and password) when converting `mysql_connect` and `mysql_pconnect`. The remaining arguments do not match up between the mysql and mysqli versions.
* Don't swap arguments on `mysql_fetch_row` — both it and the mysqli version take exactly one argument.
* Convert `mysql_fetch_field` into `mysqli_fetch_field` (no argument case) or `mysqli_fetch_field_direct` (one argument case). The pre-existing code adds a static loop for running `mysqli_fetch_field` five times. It is unclear why.
* `mysql_num_fields` should map to `mysqli_num_fields`; not `mysqli_field_count`.
* The pre-existing handling of `mysql_query` would convert `$result = mysql_query($sql);`into `$result = mysqli_query($result, $sql);`; and …
> Correct various mysql_* to mysqli_* conversion bugs

- config/set/downgrade.php
- rules/downgrade/src/Contract/Rector/DowngradeRectorInterface.php
- rules/downgrade/src/Contract/Rector/DowngradeTypeRectorInterface.php
- rules/downgrade/src/Rector/DowngradeRectorInterface.php
- rules/downgrade/src/Rector/DowngradeRectorTrait.php
- rules/downgrade/src/Rector/FunctionLike/AbstractDowngradeParamTypeDeclarationRector.php
- rules/downgrade/src/Rector/FunctionLike/AbstractDowngradeReturnTypeDeclarationRector.php
- rules/downgrade/src/Rector/FunctionLike/DowngradeParamObjectTypeDeclarationRector.php
- rules/downgrade/src/Rector/FunctionLike/DowngradeReturnObjectTypeDeclarationRector.php
- rules/downgrade/src/Rector/Property/DowngradeTypedPropertyRector.php
- rules/downgrade/tests/Rector/FunctionLike/DowngradeParamObjectTypeDeclarationRector/DowngradeParamObjectTypeDeclarationRectorTest.php
- rules/downgrade/tests/Rector/FunctionLike/DowngradeParamObjectTypeDeclarationRector/Fixture/docblock_exists.php.inc
- rules/downgrade/tests/Rector/FunctionLike/DowngradeParamObjectTypeDeclarationRector/Fixture/docblock_tag_exists.php.inc
- rules/downgrade/tests/Rector/FunctionLike/DowngradeParamObjectTypeDeclarationRector/Fixture/fixture.php.inc
- rules/downgrade/tests/Rector/FunctionLike/DowngradeParamObjectTypeDeclarationRector/Fixture/multiple_matching_params.php.inc
- rules/downgrade/tests/Rector/FunctionLike/DowngradeParamObjectTypeDeclarationRector/Fixture/multiple_params.php.inc
- rules/downgrade/tests/Rector/FunctionLike/DowngradeParamObjectTypeDeclarationRector/Fixture/nullable_type.php.inc
- rules/downgrade/tests/Rector/FunctionLike/DowngradeParamObjectTypeDeclarationRector/Source/AnotherClass.php
- rules/downgrade/tests/Rector/FunctionLike/DowngradeReturnObjectTypeDeclarationRector/DowngradeReturnObjectTypeDeclarationRectorTest.php
- rules/downgrade/tests/Rector/FunctionLike/DowngradeReturnObjectTypeDeclarationRector/Fixture/docblock_exists.php.inc
- rules/downgrade/tests/Rector/FunctionLike/DowngradeReturnObjectTypeDeclarationRector/Fixture/docblock_tag_exists.php.inc
- rules/downgrade/tests/Rector/FunctionLike/DowngradeReturnObjectTypeDeclarationRector/Fixture/fixture.php.inc
- rules/downgrade/tests/Rector/FunctionLike/DowngradeReturnObjectTypeDeclarationRector/Fixture/nullable_type.php.inc
- rules/downgrade/tests/Rector/FunctionLike/DowngradeReturnObjectTypeDeclarationRector/Source/AnotherClass.php
- rules/downgrade/tests/Rector/Property/DowngradeTypedPropertyRector/DowngradeTypedPropertyRectorTest.php
- rules/downgrade/tests/Rector/Property/NoDocBlockDowngradeTypedPropertyRector/DowngradeTypedPropertyRectorTest.php
- src/ValueObject/PhpVersionFeature.php
Fixes #4108 (well, 99% of it, read below)
The original proposal is to downgrade the `mixed` type. In this PR, I did something better: 
- I implemented it as an abstract class, so that any type can be downgraded
- `AbstractDowngradeParamTypeDeclarationRector`
- `AbstractDowngradeReturnTypeDeclarationRector`
- I implemented it for `object`:
- `DowngradeParamObjectTypeDeclarationRector`
- `DowngradeReturnObjectTypeDeclarationRector`
With these downgrade rules, I can already:
- Code using PHP 7.4
- Deploy it to PHP 7.1 (yay!)
I haven't implemented it for the `mixed` type yet, since PHP 8.0 is still a few months away. But it's a copy/paste of the `object` type implementations, so be welcome to do it at any time.
I've also added the 2 new rectors to the downgrade set, and I made all rules in …
> Abstract downgrade type + Implementation for object type

- rules/downgrade/src/Rector/FunctionLike/AbstractDowngradeParamTypeDeclarationRector.php
Fixes #4131 
Possible solution: It removes the code calling `isVendorLock`.
> Commented out vendor locking

- README.md
The line looks wrong. I am not sure if the PR is correct or if a trailing slash is required.
> Fix example: exclude directory in config

- README.md
@TomasVotruba here I try run `MarkdownCodeFormatter` at https://github.com/symplify/symplify/pull/2118 to format `README.md`
> run ecs markdown-code-format to README.md

- rules/downgrade/src/Contract/Rector/DowngradeParamDeclarationRectorInterface.php
- rules/downgrade/src/Contract/Rector/DowngradeReturnDeclarationRectorInterface.php
- rules/downgrade/src/Contract/Rector/DowngradeTypedPropertyRectorInterface.php
- rules/downgrade/src/Rector/FunctionLike/AbstractDowngradeParamDeclarationRector.php
- rules/downgrade/src/Rector/FunctionLike/AbstractDowngradeParamTypeDeclarationRector.php
- rules/downgrade/src/Rector/FunctionLike/AbstractDowngradeReturnDeclarationRector.php
- rules/downgrade/src/Rector/FunctionLike/AbstractDowngradeReturnTypeDeclarationRector.php
- rules/downgrade/src/Rector/Property/AbstractDowngradeRector.php
- rules/downgrade/src/Rector/Property/AbstractDowngradeTypedPropertyRector.php
- rules/downgrade/src/Rector/Property/AbstractMaybeAddDocBlockRector.php
- rules/downgrade/src/Rector/Property/DowngradeTypedPropertyRector.php
This PR adds no new functionality, but has restructured the different downgrade classes, so that they are more SOLID.
In particular, it enables to easily implement the rules for downgrading the PHP 8.0 type union (type property, param and return declarations).
> Restructure class hierarchy to implement downgrade rules

- rules/code-quality/src/Rector/Foreach_/ForeachToInArrayRector.php
- rules/dead-code/src/Rector/BinaryOp/RemoveDuplicatedInstanceOfRector.php
- rules/doctrine-code-quality/src/Rector/MethodCall/ChangeQuerySetParametersMethodParameterFromArrayToArrayCollectionRector.php
- rules/php-spec-to-phpunit/src/Rector/AbstractPhpSpecToPHPUnitRector.php
- rules/php71/src/Rector/TryCatch/MultiExceptionCatchRector.php
- rules/phpunit/src/Rector/Foreach_/SimplifyForeachInstanceOfRector.php
- rules/phpunit/src/Rector/MethodCall/DelegateExceptionArgumentsRector.php
Run `ecs` command for `HeredocNowdocPHPCodeFormatter` to `rules` and `packages` directory:
```
packages/easy-coding-standard/bin/ecs check-heredoc-nowdoc ../rector/packages
packages/easy-coding-standard/bin/ecs check-heredoc-nowdoc ../rector/rules
```
by https://github.com/symplify/symplify/pull/2137
> apply run ecs check-heredoc-nowdoc command to packages and rules directory

- rules/downgrade-php80/src/Rector/FunctionLike/DowngradeParamMixedTypeDeclarationRector.php
- rules/downgrade-php80/src/Rector/FunctionLike/DowngradeReturnMixedTypeDeclarationRector.php
- rules/downgrade-php80/src/Rector/FunctionLike/DowngradeReturnStaticTypeDeclarationRector.php
- rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeParamMixedTypeDeclarationRector/DowngradeParamMixedTypeDeclarationRectorTest.php
- rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeParamMixedTypeDeclarationRector/Fixture/docblock_exists.php.inc
- rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeParamMixedTypeDeclarationRector/Fixture/docblock_tag_exists.php.inc
- rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeParamMixedTypeDeclarationRector/Fixture/fixture.php.inc
- rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeParamMixedTypeDeclarationRector/Fixture/multiple_matching_params.php.inc
- rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeParamMixedTypeDeclarationRector/Fixture/multiple_params.php.inc
- rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeParamMixedTypeDeclarationRector/Source/AnotherClass.php
- rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeReturnMixedTypeDeclarationRector/DowngradeReturnMixedTypeDeclarationRectorTest.php
- rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeReturnMixedTypeDeclarationRector/Fixture/docblock_exists.php.inc
- rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeReturnMixedTypeDeclarationRector/Fixture/docblock_tag_exists.php.inc
- rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeReturnMixedTypeDeclarationRector/Fixture/fixture.php.inc
- rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeReturnMixedTypeDeclarationRector/Source/AnotherClass.php
- rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeReturnStaticTypeDeclarationRector/DowngradeReturnStaticTypeDeclarationRectorTest.php
- rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeReturnStaticTypeDeclarationRector/Fixture/docblock_exists.php.inc
- rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeReturnStaticTypeDeclarationRector/Fixture/docblock_tag_exists.php.inc
- rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeReturnStaticTypeDeclarationRector/Fixture/fixture.php.inc
- rules/downgrade-php80/tests/Rector/FunctionLike/DowngradeReturnStaticTypeDeclarationRector/Source/AnotherClass.php
- src/ValueObject/PhpVersionFeature.php
Remove `mixed` and `static` types:
```php
public function foo(mixed $anything): mixed
{
}
public function bar(): static
{
}
```
> [Downgrade PHP 8.0] mixed and static types

- rules/symfony/src/Rector/ClassMethod/ConsoleExecuteReturnIntRector.php
The rule doesn't change the method name from index to execute, it only fixes the return type and the TypeHint.
> Fixed invalid method name in code sample.

- .github/workflows/tests.yaml
- composer.json
in https://github.com/rectorphp/rector/issues/4218 there was identified, that rector cannot be installed properly with lowest dependency resolution.
this PR adds automated coverage to prevent regressing the lower version boundary
> Github Actions: add a job which tests the lowest supported versions

- docs/rector_rules_overview.md
- rules/nette-to-symfony/src/Rector/Class_/FormControlToControllerAndFormTypeRector.php
This is an easy fix. We have one more rule with extra file content and it has opening php tag.
We might add PHPStan rule that will check that this tag is present or... make doc generator check whether it is present or not. If not it can add it.
> [Docs] Add missing php opening tag

- packages/better-php-doc-parser/config/config.php
- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Class_/EntityTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Property_/ColumnTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Property_/GeneratedValueTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Property_/IdTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Property_/JoinColumnTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Property_/JoinTableTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Doctrine/Property_/ManyToManyTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Symfony/SymfonyRouteTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertEmailTagValueNode.php
- packages/better-php-doc-parser/src/PhpDocNode/Symfony/Validator/Constraints/AssertRangeTagValueNode.php
- packages/php-attribute/src/Contract/PhpAttributableTagNodeInterface.php
- packages/php-attribute/src/Printer/PhpAttributteGroupFactory.php
- packages/rector-generator/config/config.php
- packages/rector-generator/src/Composer/ComposerPackageAutoloadUpdater.php
- rules/php80/tests/Rector/Class_/AnnotationToAttributeRector/Fixture/RFC/assert_range.php.inc
- rules/php80/tests/Rector/Class_/AnnotationToAttributeRector/Fixture/RFC/entity_column_and_assert_email.php.inc
- rules/php80/tests/Rector/Class_/AnnotationToAttributeRector/Fixture/RFC/id_column_generated_value.php.inc
- rules/php80/tests/Rector/Class_/AnnotationToAttributeRector/Fixture/RFC/join_table.php.inc
- rules/php80/tests/Rector/Class_/AnnotationToAttributeRector/Fixture/RFC/many_to_many.php.inc
- rules/php80/tests/Rector/Class_/AnnotationToAttributeRector/Fixture/entity_with_repository.php.inc
- rules/php80/tests/Rector/Class_/AnnotationToAttributeRector/Fixture/symfony_route.php.inc
- rules/symfony/config/config.php
- rules/type-declaration/config/config.php
- src/PhpParser/Printer/BetterStandardPrinter.php
Closes https://github.com/rectorphp/rector/issues/4310
Ref https://github.com/symfony/symfony/pull/37474
```diff
-use Symfony\Component\Routing\Annotation\Route;
+use Symfony\Component\Routing\Attribute\Route;
class SymfonyRoute
{
-    /**
-     * @Route("/path", name="action")
-     */
+    #[Route('/path', name: 'action')]
public function action()
{
}
}
```
> [PHP 8.0] Add @route to #[Route] attribute in Symfony 5.2

- rules/php74/src/Rector/Property/TypedPropertyRector.php
- rules/php74/tests/Rector/Property/TypedPropertyRector/Fixture/property.php.inc
Before
```php
final class ClassWithProperty
{
/**
* @var callable|null
*/
private $shouldBeSkippedAlso;
}
```
would have been transformed to 
```php
final class ClassWithProperty
{
private ?callable $shouldBeSkippedAlso = null;
}
```
Which result in invalid PHP as explained in the  [RFC](https://wiki.php.net/rfc/typed_properties_v2)
I'm not familiar with the project, this is my first contribution so you might know a less dirty way to fix this.
Thanks by advance for your consideration
> [PHP74] Do not transform callable|null into typed property

- composer.json
- config/set/downgrade-php73.php
- packages/set/src/ValueObject/SetList.php
- rules/downgrade-php73/src/Rector/List_/DowngradeListReferenceAssignmentRector.php
- rules/downgrade-php73/tests/Rector/List_/DowngradeListReferenceAssignmentRector/DowngradeListReferenceAssignmentRectorTest.php
- rules/downgrade-php73/tests/Rector/List_/DowngradeListReferenceAssignmentRector/Fixture/array_destructuring.php.inc
- rules/downgrade-php73/tests/Rector/List_/DowngradeListReferenceAssignmentRector/Fixture/array_destructuring_with_array_keys.php.inc
- rules/downgrade-php73/tests/Rector/List_/DowngradeListReferenceAssignmentRector/Fixture/fixture.php.inc
- rules/downgrade-php73/tests/Rector/List_/DowngradeListReferenceAssignmentRector/Fixture/multilevel_nested_array_destructuring_with_array_keys.php.inc
- rules/downgrade-php73/tests/Rector/List_/DowngradeListReferenceAssignmentRector/Fixture/multilevel_nested_list.php.inc
- rules/downgrade-php73/tests/Rector/List_/DowngradeListReferenceAssignmentRector/Fixture/multilevel_nested_list_with_array_keys.php.inc
- rules/downgrade-php73/tests/Rector/List_/DowngradeListReferenceAssignmentRector/Fixture/nested_array_destructuring.php.inc
- rules/downgrade-php73/tests/Rector/List_/DowngradeListReferenceAssignmentRector/Fixture/nested_list.php.inc
- rules/downgrade-php73/tests/Rector/List_/DowngradeListReferenceAssignmentRector/Fixture/skipped_values.php.inc
- rules/downgrade-php73/tests/Rector/List_/DowngradeListReferenceAssignmentRector/Fixture/with_array_keys.php.inc
- src/ValueObject/PhpVersionFeature.php
> [Downgrade PHP 7.3] List reference assignment

- README.md
The link previously got 404 page. I think root `/config/set` link is enough since there are multiple set in per-each category, eg: symfony (symfony-autowire.php, symfony-codequality.php, etc).
> Fixes config/set link in readme

- rules/downgrade-php74/src/Rector/Array_/DowngradeArraySpreadRector.php
- rules/downgrade-php74/tests/Rector/Array_/DowngradeArraySpreadRector/DowngradeArraySpreadRectorTest.php
- rules/downgrade-php74/tests/Rector/Array_/DowngradeArraySpreadRector/Fixture/array_fn_name.php.inc
- rules/downgrade-php74/tests/Rector/Array_/DowngradeArraySpreadRector/Fixture/combined_items.php.inc
- rules/downgrade-php74/tests/Rector/Array_/DowngradeArraySpreadRector/Fixture/different_positions.php.inc
- rules/downgrade-php74/tests/Rector/Array_/DowngradeArraySpreadRector/Fixture/fixture.php.inc
- rules/downgrade-php74/tests/Rector/Array_/DowngradeArraySpreadRector/Fixture/multiple_unpacks.php.inc
- rules/downgrade-php74/tests/Rector/Array_/DowngradeArraySpreadRector/Fixture/no_unpacks.php.inc
- rules/downgrade-php74/tests/Rector/Array_/DowngradeArraySpreadRector/Fixture/single_unpack.php.inc
- rules/downgrade-php74/tests/Rector/Array_/DowngradeArraySpreadRector/Fixture/with_array_item.php.inc
- rules/downgrade-php74/tests/Rector/Array_/DowngradeArraySpreadRector/Fixture/with_array_iterator_item.php.inc
- rules/downgrade-php74/tests/Rector/Array_/DowngradeArraySpreadRector/Fixture/with_function_item.php.inc
- rules/downgrade-php74/tests/Rector/Array_/DowngradeArraySpreadRector/Fixture/with_function_item_and_existing_var.php.inc
- rules/downgrade-php74/tests/Rector/Array_/DowngradeArraySpreadRector/Fixture/with_multiple_array_iterator_items.php.inc
- rules/downgrade-php74/tests/Rector/Array_/DowngradeArraySpreadRector/Fixture/with_multiple_function_item.php.inc
- rules/downgrade-php74/tests/Rector/Array_/DowngradeArraySpreadRector/Fixture/with_null_item.php.inc
- src/ValueObject/PhpVersionFeature.php
> Downgrade php74 array spread

- config/set/downgrade-php74.php
I forgot to add rector `DowngradeArraySpreadRector` to the set in #4375, fixed now.
Can generate a new tag after merged?
> [Downgrade PHP 7.4] Added downgrade array spread rule to set

- rules/downgrade-php74/src/Rector/LNumber/DowngradeNumericLiteralSeparatorRector.php
- rules/downgrade-php74/tests/Rector/LNumber/DowngradeNumericLiteralSeparatorRector/Fixture/skip_float_max.php.inc
- rules/downgrade-php74/tests/Rector/LNumber/DowngradeNumericLiteralSeparatorRector/Fixture/skip_no_change.php.inc
>  [Downgrade PHP 7.4] Skip DowngradeNumericLiteralSeparatorRector on value contains + char

- .github/workflows/weekly_code_coverage.yaml
it got error at https://github.com/rectorphp/rector/actions/runs/474871156
```
The workflow is not valid. .github/workflows/weekly_code_coverage.yaml (Line: 34, Col: 51): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.GITHUB_TOKEN
```
The `secrets` seems only needed for automatic PR.
> Fix weekly code coverage github action

- .github/workflows/weekly_code_coverage.yaml
`secrets.GITHUB_TOKEN` should be `secrets.ACCESS_TOKEN` like in other action.
> Another fix weekly code coverage action

- rules/restoration/src/Type/ConstantReturnToParamTypeConverter.php
- rules/restoration/tests/Rector/ClassMethod/InferParamFromClassMethodReturnRector/Fixture/skip_empty_array.php.inc
When inferring param from class method return, an empty array should be fine. In the current situation it throws a `ShouldNotHappenException`. This PR returns `null` instead, which solves the issue.
> InferParamFromClassMethodReturnRector: Don't fail with empty array

- rules/downgrade-php74/src/Rector/ClassMethod/DowngradeContravariantArgumentTypeRector.php
- rules/downgrade-php74/tests/Rector/ClassMethod/DowngradeContravariantArgumentTypeRector/Fixture/skip_overloading_construct.php.inc
> [Downgrade PHP 7.4] Skip downgrading contravariant argument for __construct

- rules/coding-style/tests/Rector/Encapsed/EncapsedStringsToSprintfRector/Fixture/encapsed_strings_to_sprintf_should_escape_percent.php.inc
Based on https://getrector.org/demo/197507f8-e9cb-4f9c-8aa1-b08702496253
> Add failing test fixture for EncapsedStringsToSprintfRector

- phpstan.neon
> [PHPStan] Clean up duplicated ignore error "Class cognitive complexity is \d+, keep it under 40" in phpstan.neon

- rules/dead-code/src/Rector/Assign/RemoveDoubleAssignRector.php
- rules/dead-code/tests/Rector/Assign/RemoveDoubleAssignRector/Fixture/skip_calls.php.inc
RemoveDoubleAssignRector was checking if the _current_ assignment includes a call, rather than the preceding one. This was resulting in wrong removals:
```
$a = echo(''); // was removed before, is skipped now.
$a = 7;
```
> (fix) RemoveDoubleAssignRector: properly skip if the assigned expression is a call

- rules/code-quality-strict/src/Rector/Variable/MoveVariableDeclarationNearReferenceRector.php
- rules/code-quality-strict/tests/Rector/Variable/MoveVariableDeclarationNearReferenceRector/Fixture/skip_assign_expr_array_dim_fetch.php.inc
Fixes #5200 ref https://github.com/symplify/symplify/pull/2811#discussion_r558815457
> [CodeQualityStrict] Skip MoveVariableDeclarationNearReferenceRector on assign expr is ArrayDimFetch

- .github/workflows/weekly_code_coverage.yaml
It previously got error:
```bash
The workflow is not valid. .github/workflows/weekly_code_coverage.yaml (Line: 34, Col: 51): Unrecognized named-value: 'secrets'. Located at position 1 within expression: secrets.ACCESS_TOKEN
```
at https://github.com/rectorphp/rector/actions/runs/490896171 . This change moved COVERALLS_REPO_TOKEN env definition on `run` part.
> [CodeCoverage] Fixes weekly code coverage by move COVERALLS_REPO_TOKEN on run

- rules/dead-code/src/Rector/ClassMethod/RemoveUnusedPublicMethodRector.php
- rules/dead-code/tests/Rector/ClassMethod/RemoveUnusedPublicMethodRector/Fixture/skip-constructor.php.inc
- rules/dead-code/tests/Rector/ClassMethod/RemoveUnusedPublicMethodRector/Fixture/skip_constructor.php.inc
> [DeadCode] Skip RemoveUnusedPublicMethodRector on __construct

- src/PhpParser/Node/NodeFactory.php
Allows passing a Cast node to NodeFactory::createArrayItems. Not much to say here.
> NodeFactory: Allow passing a Cast node to createArrayItems

- composer.json
It was used only as dev dependency so it doesn't appear in build and prefixed-rector. Throws an error:
```
Class 'RectorPrefix20210117\Symfony\Component\Process\Process' not found
```
> Added missing symfony/process to composer.json

- rules/php80/tests/Rector/Switch_/ChangeSwitchToMatchRector/Fixture/without_return.php.inc
I am getting left with something like:
```php
function x($value)
{
match $value { // notice missing braces
1 => y($value);
default => z($value);
}
}
```
> Fix match without return

- rules/coding-style/src/Node/NameImporter.php
- rules/performance/tests/Rector/FuncCall/PreslashSimpleFunctionRector/FixtureAutoImport/do_not_auto_import_names.php.inc
This is a follow-up to #5268, which enabled the `\` prefix to be added again to functions when using auto-import names
> Don't skip add `\` prefix for function when auto import name enabled

- docs/rector_rules_overview.md
- rules/privatization/src/Rector/MethodCall/ReplaceStringWithClassConstantRector.php
- `argument position` and `class with constants` are swapped
- `argument position` starts with zero (0), so `1` is the second argument
> Make example of ReplaceStringWithClassConstantRector more correct

- rules/doctrine/src/Rector/ClassMethod/ServiceEntityRepositoryParentCallToDIRector.php
- rules/doctrine/tests/Rector/ClassMethod/ServiceEntityRepositoryParentCallToDIRector/Fixture/do_not_change_other_methods.php.inc
- rules/doctrine/tests/Rector/ClassMethod/ServiceEntityRepositoryParentCallToDIRector/Fixture/dont_change_other_methods.php.inc
> [Doctrine] Skip ServiceEntityRepositoryParentCallToDIRector on non __construct method

- config/set/php55.php
- config/set/php74.php
- rules/php55/src/Rector/Class_/ClassConstantToSelfClassRector.php
- rules/php55/tests/Rector/Class_/ClassConstantToSelfClassRector/ClassConstantToSelfClassRectorTest.php
- rules/php55/tests/Rector/Class_/ClassConstantToSelfClassRector/Fixture/fixture.php.inc
> [PHP 5.5] Move ClassConstantToSelfClassRector from Php 7.4 to Php 5.5 set

- config/set/php55.php
- docs/rector_rules_overview.md
- packages/changes-reporting/src/ValueObject/RectorWithFileAndLineChange.php
- packages/changes-reporting/src/Xml/CheckstyleDOMElementFactory.php
- packages/post-rector/src/Rector/ClassRenamingPostRector.php
- packages/post-rector/src/Rector/NameImportingPostRector.php
- packages/post-rector/src/Rector/NodeAddingPostRector.php
- packages/post-rector/src/Rector/NodeRemovingPostRector.php
- packages/post-rector/src/Rector/NodeToReplacePostRector.php
- packages/post-rector/src/Rector/PropertyAddingPostRector.php
- packages/post-rector/src/Rector/UseAddingPostRector.php
- rules/composer/src/Contract/Rector/ComposerRectorInterface.php
- rules/composer/src/Contract/Rector/CoreComposerRectorInterface.php
- src/Contract/Rector/ConfigurableRectorInterface.php
- src/Contract/Rector/CorePhpRectorInterface.php
- src/Contract/Rector/CoreRectorInterface.php
- src/Contract/Rector/PhpCoreRectorInterface.php
- src/Contract/Rector/RectorInterface.php
- src/Rector/AbstractRector.php
Closes #5343, cc @matthiasnoback 
<br>
The proposed structure is:
- RectorInterface (↓ is parent to)
- ComposerRectorInterface
- CoreComposerRectorInterface (+ DocumentedRuleInterface)
- PhpRectorInterface
- CorePhpRectorInterface (+ DocumentedRuleInterface)
<br>
So `ComposerRectorInterface` and `PhpRectorInterface` are for temporary rules.
> add CoreRectorInterface and PhpCoreRectorInterface to allow PhpRectorInterface to be RectorInterface without getDefinition()

- config/set/symfony51.php
- rules/early-return/tests/Rector/Return_/ReturnBinaryAndToEarlyReturnRector/Fixture/some_not_identical.php.inc
- rules/symfony-code-quality/src/Contract/EventReferenceToMethodNameInterface.php
- rules/symfony-code-quality/src/NodeFactory/GetSubscribedEventsClassMethodFactory.php
- rules/symfony-code-quality/src/ValueObject/EventReferenceToMethodNameWithPriority.php
- rules/symfony5/src/NodeFactory/BareLogoutClassMethodFactory.php
- rules/symfony5/src/NodeFactory/OnLogoutClassMethodFactory.php
- rules/symfony5/src/NodeFactory/OnSuccessLogoutClassMethodFactory.php
- rules/symfony5/src/Rector/Class_/LogoutSuccessHandlerToLogoutEventSubscriberRector.php
- rules/symfony5/tests/Rector/Class_/LogoutHandlerToLogoutEventSubscriberRector/Fixture/logout_handle_without_any_usage.php.inc
- rules/symfony5/tests/Rector/Class_/LogoutSuccessHandlerToLogoutEventSubscriberRector/Fixture/simple_logout_success_handler.php.inc
- rules/symfony5/tests/Rector/Class_/LogoutSuccessHandlerToLogoutEventSubscriberRector/LogoutSuccessHandlerToLogoutEventSubscriberRectorTest.php
Ref https://github.com/rectorphp/rector/issues/4831
> [Symfony 5.1] Add LogoutSuccessHandlerToLogoutEventSubscriberRector

- composer.json
This simple bump allows for the 2.0 version of this lib, which leverages Composer 2 APIs and drops any sub dependency.
There are basically no BC; for more details, see the [the changelog](https://github.com/Jean85/pretty-package-versions/blob/2.x/CHANGELOG.md).
> Allow PrettyVersion 2

- .github/workflows/build_php71.yaml
- .github/workflows/scripts/downgrade_packages.sh
- composer.json
- packages/changes-reporting/src/Output/ConsoleOutputFormatter.php
- rector.php
- rules/type-declaration/src/TypeInferer/PropertyTypeInferer/ConstructorPropertyTypeInferer.php
- src/Configuration/Configuration.php
- src/Configuration/Option.php
- src/Console/Command/ProcessCommand.php
Huge diffs like https://github.com/rectorphp/rector/runs/1793965107 are impossible to debug,
because there is 10 km of diffs bellow.
This should help to display only failing errors
> [Process] Add --no-diffs for better huge CI debug

- rules/symfony/src/ServiceMapProvider.php
For some services (E.G Workflow definitions), the tag has a string value instead of an array with the attributes. This causes the error `Cannot unset string offsets` when running Rector.
An example of such a tag is
```xml
<tag name="application" type="state_machine">workflow.definition</tag>
```
When the xml element gets converted, the `$tag` variable just contains the string `workflow.definition`. So this PR helps to cater for these scenarios and not cause an error
> Support string tags for Symfony ServiceMapProvider

- config/set/nette-31.php
- rules/symfony/src/ServiceMapProvider.php
- rules/transform/src/NodeFactory/UnwrapClosureFactory.php
- rules/transform/src/Rector/MethodCall/CallableInMethodCallToVariableRector.php
- rules/transform/src/ValueObject/CallableInMethodCallToVariable.php
- rules/transform/tests/Rector/MethodCall/CallableInMethodCallToVariableRector/CallableInMethodCallToVariableRectorTest.php
- rules/transform/tests/Rector/MethodCall/CallableInMethodCallToVariableRector/Fixture/many_stmts.php.inc
- rules/transform/tests/Rector/MethodCall/CallableInMethodCallToVariableRector/Fixture/some_class.php.inc
- rules/transform/tests/Rector/MethodCall/CallableInMethodCallToVariableRector/Source/DummyCache.php
Closes https://github.com/rectorphp/rector/issues/5318
> [Nette 3.1] Add CallableInMethodCallToVariableRector

- packages/better-php-doc-parser/src/PhpDocInfo/PhpDocInfoFactory.php
- rules/dead-doc-block/tests/Rector/Node/RemoveNonExistingVarAnnotationRector/Fixture/other_comment_before_var.php.inc
It seems removed in the following commit: https://github.com/rectorphp/rector/commit/bbe758ab60e7a5a6cb5762441298c24f42dbe8b8#diff-7d9f31651e0271c499388038db8bdef6af038aec9ed0507e0a9bf7636ab7117e . Rollback it make failing test : 
```bash
There was 1 error:
1) Rector\DeadDocBlock\Tests\Rector\Node\RemoveNonExistingVarAnnotationRector\RemoveNonExistingVarAnnotationRectorTest::test with data set #6 (Symplify\SmartFileSystem\SmartFileInfo Object (...))
PHPStan\PhpDocParser\Parser\ParserException: Unexpected token "//", expected '/**' at offset 0
phar:///Users/samsonasik/www/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/phpstan/phpdoc-parser/src/Parser/TokenIterator.php:132
phar:///Users/samsonasik/www/rector/vendor/phpstan/phpstan/phpstan.phar/vendor/phpstan/phpdoc-parser/src/Parser/Token …
```
> [DeadDocBlock] Rollback other_comment_before_var.php.inc for RemoveNonExistingVarAnnotationRector

- packages/post-rector/src/Rector/NameImportingPostRector.php
- rules/code-quality/tests/Rector/Return_/SimplifyUselessVariableRector/Fixture/special_class_name_with_anonymous_class.php.inc
- rules/code-quality/tests/Rector/Return_/SimplifyUselessVariableRector/SimplifyUselessVariableRectorTest.php
Fixes #5426
This makes sure that special class names like `self, parent, static` are not automatically imported.
> Ignore special class names when using Option::AUTO_IMPORT_NAMES

- packages/read-write/src/ReadNodeAnalyzer/AbstractReadNodeAnalyzer.php
- rules/dead-code/tests/Rector/Property/RemoveSetterOnlyPropertyAndMethodCallRector/Fixture/value_call_setter_only.php.inc
Closes https://github.com/rectorphp/rector/issues/5234
@olivernybroe This was the problematic snippet:
```php
public function data()
{
$this->data;
}
```
This method does nothing, no set, no return. Now it's evalueated as no-read property use, so it's skipped.
It looks like dead code. What does it do actually?
> [DeadCode] Fix RemoveSetterOnlyPropertyAndMethodCallRector for no-read, no-write expression

- config/set/symfony52.php
part of https://github.com/rectorphp/rector/issues/4824
> [Symfony 5.2] Rename AbstractRememberMeServices providerKey to firewallName property

- rules/php73/src/NodeTypeAnalyzer/NodeTypeAnalyzer.php
- rules/php73/tests/Rector/FuncCall/StringifyStrNeedlesRector/Fixture/skip_default_constants.php.inc
Based on https://getrector.org/demo/d2da9632-23c3-4f71-b800-219c8871639c
It should understand that `PHP_EOL` is a constant that is always a `string`. Therefore, no need to cast it to string.
> Add failing test fixture for StringifyStrNeedlesRector

- rules/dead-code/src/Rector/If_/RemoveDeadInstanceOfRector.php
- rules/dead-code/tests/Rector/If_/RemoveDeadInstanceOfRector/Fixture/do_not_remove_parent_child_flip.php.inc
- rules/dead-code/tests/Rector/If_/RemoveDeadInstanceOfRector/Fixture/fixture.php.inc
- rules/dead-code/tests/Rector/If_/RemoveDeadInstanceOfRector/Fixture/skip_has_else.php.inc
- rules/dead-code/tests/Rector/If_/RemoveDeadInstanceOfRector/Fixture/skip_has_elseif.php.inc
- rules/dead-code/tests/Rector/If_/RemoveDeadInstanceOfRector/Fixture/skip_no_previous_var.php.inc
- rules/dead-code/tests/Rector/If_/RemoveDeadInstanceOfRector/Fixture/skip_not_instanceof.php.inc
- rules/dead-code/tests/Rector/If_/RemoveDeadInstanceOfRector/Fixture/truthy.php.inc
- rules/dead-code/tests/Rector/If_/RemoveDeadInstanceOfRector/RemoveDeadInstanceOfRectorTest.php
- src/NodeManipulator/IfManipulator.php
> [DeadCode] Add RemoveDeadInstanceOfRector

- config/set/early-return.php
- packages/node-type-resolver/src/TypeAnalyzer/ArrayTypeAnalyzer.php
- packages/rector-generator/src/Provider/NodeTypesProvider.php
- rules/code-quality/src/Rector/Isset_/IssetOnPropertyObjectToPropertyExistsRector.php
- rules/downgrade-php74/src/Rector/ClassMethod/DowngradeCovariantReturnTypeRector.php
- rules/early-return/src/Rector/If_/ChangeAndIfContinueToMultiContinueRector.php
- rules/early-return/src/Rector/If_/ChangeOrIfContinueToMultiContinueRector.php
- rules/early-return/tests/Rector/If_/ChangeOrIfContinueToMultiContinueRector/ChangeOrIfContinueToMultiContinueRectorTest.php
- rules/early-return/tests/Rector/If_/ChangeOrIfContinueToMultiContinueRector/Fixture/fixture.php.inc
- rules/early-return/tests/Rector/If_/ChangeOrIfContinueToMultiContinueRector/Fixture/has_comment.php.inc
- rules/early-return/tests/Rector/If_/ChangeOrIfContinueToMultiContinueRector/Fixture/identical.php.inc
- rules/early-return/tests/Rector/If_/ChangeOrIfContinueToMultiContinueRector/Fixture/many_and.php.inc
- rules/early-return/tests/Rector/If_/ChangeOrIfContinueToMultiContinueRector/Fixture/negated.php.inc
- rules/early-return/tests/Rector/If_/ChangeOrIfContinueToMultiContinueRector/Fixture/not_identical.php.inc
- rules/early-return/tests/Rector/If_/ChangeOrIfContinueToMultiContinueRector/Fixture/skip_and.php.inc
- rules/early-return/tests/Rector/If_/ChangeOrIfContinueToMultiContinueRector/Fixture/skip_multi_stmts.php.inc
- rules/early-return/tests/Rector/If_/ChangeOrIfContinueToMultiContinueRector/Fixture/skip_not_continue.php.inc
- rules/generic/src/Rector/FuncCall/SwapFuncCallArgumentsRector.php
- rules/mysql-to-mysqli/src/Rector/Assign/MysqlAssignToMysqliRector.php
- rules/naming/src/Rector/ClassMethod/RenameVariableToMatchNewTypeRector.php
- rules/symfony3/src/Rector/MethodCall/ChangeStringCollectionOptionToConstantRector.php
- rules/type-declaration/src/TypeInferer/PropertyTypeInferer.php
- src/NodeManipulator/IfManipulator.php
- src/PhpParser/Node/Value/ClassResolver.php
@TomasVotruba based on https://github.com/rectorphp/rector/pull/5480#discussion_r573181752  I think the rule is invalid, summary:
**It will only works for `BooleanOr`, refs :**
https://3v4l.org/UZ2rD vs https://3v4l.org/MFf4O
https://3v4l.org/ZlWch vs https://3v4l.org/L8XB8
**While in `BooleanAnd`, that's invalid:**
https://3v4l.org/Ip0J6 vs https://3v4l.org/MFf4O
https://3v4l.org/5IIDX vs https://3v4l.org/gRqe5
This PR change name to `ChangeOrIfContinueToMultiContinueRector` instead.
Closes https://github.com/rectorphp/rector/pull/5480
> [EarlyReturn] Rename ChangeAndIfContinueToMultiContinueRector to ChangeOrIfContinueToMultiContinueRector

- rules/code-quality-strict/src/Rector/If_/MoveOutMethodCallInsideIfConditionRector.php
- rules/code-quality-strict/tests/Rector/If_/MoveOutMethodCallInsideIfConditionRector/Fixture/skip_parent_assign.php.inc
- rules/code-quality-strict/tests/Rector/If_/MoveOutMethodCallInsideIfConditionRector/Fixture/variable_has_space.php.inc
- rules/code-quality/src/Naming/MethodCallToVariableNameResolver.php
Fixes #5506 Fixes 2 issues:
- variable new name in assign inside if cond, skipped
- variable new name as space, fallback to `$methodCallVarName . ucfirst($methodCallName)`
> [CodeQualityStrict] Handle space in variable new name and assign in if cond at MoveOutMethodCallInsideIfConditionRector

- rules/php55/src/Rector/String_/StringClassNameToClassConstantRector.php
- rules/php55/tests/Rector/String_/StringClassNameToClassConstantRector/Fixture/skip_is_a.php.inc
In practise, checks of `is_a()` are mostly on intention with specific string class. This string class should work on external code, as instanceof would be used otherwise on purpose here.
> [PHP 5.5] Skip StringClassNameToClassConstantRector for is_a() checks

- ci/downgrade/target-repo/.github/workflows/tests_root.yaml
Add different yaml config `ci/downgrade/target-repo/.github/workflows/tests_root.yaml` for run phpunit in root directory.
> [[PHP 7.1 Scoped] Run phpunit on root directory [part 2]

- src/DependencyInjection/Loader/ConfigurableCallValuesCollectingPhpFileLoader.php
- tests/DependencyInjection/ConfigurableRectorImportConfigCallsMergeTest.php
- tests/DependencyInjection/config/main_config_with_override_value.php
- tests/DependencyInjection/config/main_config_with_own_value.php
- tests/DependencyInjection/config/one_set.php
- tests/DependencyInjection/config/one_set_with_own_rename.php
- tests/DependencyInjection/config/two_sets.php
- tests/DependencyInjection/config/two_sets_with_own_rename.php
I spent a lot of time debugging this but when I fixed one issue another one popped up 🤯 
It's all related to the loading of sets that is different from the normal rector.php configuration. 
There were 3 failing scenarios:
- ✅ load one set that configures RenameClassRector + configure your own
- ❌ load two sets that configure both RenameClassRector ( they should merge, they don't )
- ❌ load two sets that configure both RenameClassRector + configure your own
Chained configure calls inside your own config were already working fine. 
@samsonasik @TomasVotruba Any advice? 
Another thing I noticed that drove me completely insane is that the tests are re-using the same container that is stored somewhere in a temp directory on my filesystem. In my case, …
> Fix merging of multiple calls to configure in sets

- bin/rector
To avoid the following error in PHP < 8.0
```bash
"Class 'ReflectionUnionType' not found". 
```
> [Bin] Add PHPStan Stub ReflectionUnionType and Attribute to bin/rector

- bin/rector
@TomasVotruba In https://getrector.org/demo/3ab7d981-2708-4f30-af81-b983a7a75135 , seems got error:
```bash
Fatal error: Warning: require_once(phar://vendor/phpstan/phpstan/phpstan.phar/stubs/runtime/ReflectionUnionType.php): Failed to open stream: phar error: invalid url or non-existent phar "phar://vendor/phpstan/phpstan/phpstan.phar/stubs/runtime/ReflectionUnionType.php" in /rector/bin/rector on line 5
Fatal error: Uncaught Error: Failed opening required 'phar://vendor/phpstan/phpstan/phpstan.phar/stubs/runtime/ReflectionUnionType.php' (include_path='.:/usr/local/lib/php') in /rector/bin/rector:5
Stack trace:
#0 {main}
thrown in /rector/bin/rector on line 5
```
> [Bin] Using file_exists() for check PHPStan stub ReflectionUnionType and Attribute exists

- rules/renaming/src/Rector/MethodCall/RenameMethodRector.php
- rules/renaming/tests/Rector/MethodCall/RenameMethodRector/Fixture/skip_private_to_invoke.php.inc
- rules/renaming/tests/Rector/MethodCall/RenameMethodRector/Fixture/skip_protected_to_invoke.php.inc
- rules/renaming/tests/Rector/MethodCall/RenameMethodRector/config/configured_rule.php
> [Renaming] Skip RenameMethodRector when target method is __invoke with private/protected modifier

- packages/node-name-resolver/src/NodeNameResolver.php
- rules/removing/src/Rector/FuncCall/RemoveFuncCallArgRector.php
- rules/removing/tests/Rector/FuncCall/RemoveFuncCallArgRector/Fixture/skip_method_call_returning_closure.php.inc
https://getrector.org/demo/cd027c68-3b85-4f98-8b9d-5aa3843bb4bd
> [RemoveFuncCallArgRector] Use getName instead of isName to fix closure call

- build-rector-scoped.sh
* Prevent an  endless loop when `rsync` copies the `rector-nested` and `rector-scoped` directories
* Work around a possible PHP memory limit
> Tweak build-rector-scoped.sh so it "works on my machine"(TM)

- rules/dead-doc-block/src/TagRemover/VarTagRemover.php
- rules/type-declaration/tests/Rector/Property/TypedPropertyFromStrictConstructorRector/Fixture/iterable_namespaced_interface_var_tag.php.inc
- rules/type-declaration/tests/Rector/Property/TypedPropertyFromStrictConstructorRector/Fixture/keep_var_tag_when_iterable.php.inc
Based on https://getrector.org/demo/96c31357-6d0e-4f31-ac9a-2df5828efed9
It's not nice that Rector removes the iterable type definition as that will cause PHPStan to complain about it.
Turns out this only happens inside a namespace 🤔 
If the type is there, leave it. Same for array I think.
> [TypedPropertyFromStrictConstructorRector] Keep var tag when it defines iterable type

- .github/workflows/weekly_code_coverage.yaml
- packages/node-type-resolver/src/NodeTypeCorrector/GenericClassStringTypeCorrector.php
- rules/type-declaration/src/TypeInferer/ParamTypeInferer/PHPUnitDataProviderParamTypeInferer.php
Last week, there is unknown error on phpunit generation:
I added `--testdox` to know the nearest source of error when coverage regenerated tomorrow if happen again.
> [Coverage] Add --testdox to phpunit command on weekly code coverage generation

- rules/early-return/src/Rector/Foreach_/ReturnAfterToEarlyOnBreakRector.php
- rules/early-return/tests/Rector/Foreach_/ReturnAfterToEarlyOnBreakRector/Fixture/skip_prev_assign_not_linear_expression.php.inc
It handle for example, previous foreach has assignment, but inside if, not directly.
> [EarlyReturn] Skip ReturnAfterToEarlyOnBreakRector on non-linear previous assignment before foreach

- bin/rector
- ci/downgrade/configuration.php
- src/DependencyInjection/RectorContainerFactory.php
- src/Stubs/PHPStanStubLoader.php
- tests/bootstrap.php
Point possible vendor locations by use the` __DIR__` as start to locate
Like in https://github.com/rectorphp/rector/pull/5581 that may not detected in https://getrector.org/ which uses docker to run
> [Bin] Handle possible PHPStan Stubs runtime locations

- rules/dead-doc-block/src/DeadReturnTagValueNodeAnalyzer.php
- rules/dead-doc-block/tests/Rector/ClassMethod/RemoveUselessReturnTagRector/Fixture/skip_generic_type.php.inc
> [DeadDocBlock] Skip RemoveUselessReturnTagRector on Generic Type

- rules/coding-style/src/Rector/Use_/RemoveUnusedAliasRector.php
- rules/coding-style/tests/Rector/Use_/RemoveUnusedAliasRector/Fixture/skip_used_in_class_constant.php.inc
>  [CodingStyle] Skip RemoveUnusedAliasRector on used in ClassConstFetch

- packages/node-name-resolver/src/NodeNameResolver.php
- packages/node-type-resolver/src/TypeAnalyzer/CountableTypeAnalyzer.php
- packages/read-write/src/ReadNodeAnalyzer/PropertyFetchReadNodeAnalyzer.php
- packages/read-write/src/ReadNodeAnalyzer/ReadExprAnalyzer.php
- packages/read-write/src/ReadNodeAnalyzer/VariableReadNodeAnalyzer.php
- phpstan.neon
- rules/doctrine-code-quality/src/Rector/Class_/MoveRepositoryFromParentToConstructorRector.php
- rules/doctrine-code-quality/tests/Rector/DoctrineRepositoryAsService/Fixture/PostController.php
- rules/downgrade-php70/src/Rector/FunctionLike/AbstractDowngradeReturnDeclarationRector.php
- rules/naming/src/Naming/PropertyNaming.php
- rules/naming/src/PropertyRenamer/BoolPropertyRenamer.php
- rules/naming/src/PropertyRenamer/MatchTypePropertyRenamer.php
- rules/naming/src/PropertyRenamer/PropertyFetchRenamer.php
- rules/naming/src/PropertyRenamer/PropertyRenamer.php
- rules/naming/src/PropertyRenamer/UnderscoreCamelCasePropertyRenamer.php
- rules/naming/src/ValueObject/PropertyRename.php
- rules/nette-kdyby/src/Rector/MethodCall/ReplaceMagicPropertyEventWithEventClassRector.php
- rules/symfony2/src/Rector/MethodCall/AddFlashRector.php
- rules/symfony3/src/Rector/MethodCall/FormTypeInstanceToClassConstRector.php
- rules/type-declaration/src/TypeInferer/PropertyTypeInferer/DoctrineColumnPropertyTypeInferer.php
- rules/type-declaration/src/TypeInferer/ReturnTypeInferer/YieldNodesReturnTypeInferer.php
- src/NodeManipulator/ClassMethodAssignManipulator.php
- utils/phpstan-extensions/config/rector-rules.neon
Should fix cases like https://github.com/rectorphp/rector-prefixed/blob/c875b75d79b39d8882389670f6043c223cea60b8/rules/doctrine-code-quality/src/Rector/Class_/MoveRepositoryFromParentToConstructorRector.php#L6-L7
> remove unmatched errors + require string in object types to avoid prefixing of generics objects

- src/Contract/Rector/PhpRectorInterface.php
This would make it easier to include the interface in the book, @TomasVotruba Would you agree to do it like this?
> Point to the new parser nodes docs URL

- .dockerignore
- .github/workflows/publish_docker_images.yaml
- Dockerfile
This follows up on #5599, in particular [this comment](https://github.com/rectorphp/rector/pull/5599#issuecomment-784370131).
It will build the "scoped" version of Rector for all pushes to `master` and for all `tags`. Images will be built for PHP 7.3, 7.4 and 8.0, based on the respective official PHP Docker images.
To keep the final images small and clean, this uses a multistage build. To allow for build caching on GitHub Actions and across all stages, the Docker `buildx` builder is used. That allows to push the resulting image and all intermediate layers (cache) separately.
According to [this research](https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei) and the corresponding [POC …
> Build "scoped" Docker images in GitHub Actions

- .github/workflows/rector.yaml
- packages/node-type-resolver/src/Reflection/BetterReflection/SourceLocatorProvider/DynamicSourceLocatorProvider.php
- packages/testing/src/PHPUnit/AbstractRectorTestCase.php
- rules/naming/src/Rector/Property/MakeBoolPropertyRespectIsHasWasMethodNamingRector.php
- src/Application/RectorApplication.php
- src/Autoloading/AdditionalAutoloader.php
- src/Console/Command/ProcessCommand.php
- src/FileSystem/PhpFilesFinder.php
- src/StaticReflection/DynamicSourceLocatorDecorator.php
Rector is failing in some weird combination of directories, after #5665 was merged.
I'm trying to figure out what combination on GitHub Actoins is causing this.
The `process` command is being stuck after 2 minutes, where usually is couple of hundred files:
With `--debug`, it gets stuck on 1st file:
```bash
➜  rector git:(multi-rector-matrix) bin/rector p rules -n --debug
[parsing] rules/arguments/config/config.php
[parsing] rules/arguments/src/NodeAnalyzer/ArgumentAddingScope.php
```
<br><br>
@ondrejmirtes Hi Ondra, do you have any tips on how to improve performance with static reflection? The parsing of each file is super slow after the #5665 gets merged.
Right now we're adding adding all the files found in processed directory right to SourceLocator: …
> [StaticReflection] Add OptimizedDirectorySourceLocator to speedup directory analysis

- packages/changes-reporting/src/Output/ConsoleOutputFormatter.php
Changes the success messages from
- Rector changed 175 files have been changed.
- Rector changed 175 would have changed (dry-run).
to
- 175 files has been changed by Rector.
- 175 files would have changed (dry-run) by Rector.
Not sure if you have any idea for better wording, but already a huge improvement I would say 👍 
closes #5743
> Change success message

- rules/symfony4/src/Rector/ClassMethod/ConsoleExecuteReturnIntRector.php
- rules/symfony4/tests/Rector/ClassMethod/ConsoleExecuteReturnIntRector/Fixture/skip_ternary_return_int.php.inc
- rules/symfony4/tests/Rector/ClassMethod/ConsoleExecuteReturnIntRector/Fixture/skip_ternary_return_int_variable.php.inc
- rules/symfony4/tests/Rector/ClassMethod/ConsoleExecuteReturnIntRector/Fixture/skip_ternary_return_int_variable_assign_bool.php.inc
- rules/symfony4/tests/Rector/ClassMethod/ConsoleExecuteReturnIntRector/Fixture/skip_ternary_return_int_variable_in_if_else.php.inc
> [Symfony4] Skip ConsoleExecuteReturnIntRector on ternary returns number

- .github/workflows/publish_docker_images.yaml
As discussed in https://github.com/rectorphp/rector/pull/5667#issuecomment-788387982.
```
rector/rector:latest     # php 8.0 + master branch
rector/rector:0.9.31    # php 8.0 + 0.9.31 git ref
rector/rector:0.9.31-php7.4    # specific git ref + specific php version
rector/rector:php7.4                # (same as latest-php7.4 but without latest keyword)
rector/rector:0.9.31-php8.0    # same as :0.9.31
rector/rector:php8.0                # same as :latest
```
Not modified/affected:
```
rector/rector:secured     # we need only one version of secured for online demo, can be master + php 8 
```
Not sure how to reasonably test this, though...
> Improve Docker image tagging

- bin/rector.php
#5665 should allow Rector to work without autoloading code from the project that's analyzed. Since I knew about the conflicts between Rector and older Symfony versions, and since I happen to have an older project with Symfony 2.3 around here, I tried to run a Rector Docker image with the changes from #5665 on in.
It fails with
```
Fatal error: Declaration of Symfony\Component\Console\Style\OutputStyle::write($messages, bool $newline = false, int $type = self::OUTPUT_NORMAL) must be compatible with Symfony\Component\Console\Output\OutputInterface::write($messages, $newline = false, $type = self::OUTPUT_NORMAL) in /rector/vendor/symfony/console/Style/OutputStyle.php on line 52
```
So, proably some mess-up between my project's version of Symfony and the one included in Rector. 
I then …
> Use the autoloader from where Rector was installed, not started

- .github/workflows/weekly_pull_requests.yaml
It seems automatic PR https://github.com/rectorphp/rector/pull/5789 doesn't generate tag header like manual delete and re-create at https://github.com/rectorphp/rector/pull/5719 . 
This ensure CHANGELOG.md re-generated by remove it first.
> [changelog] remove CHANGELOG.md first before run composer changelog on weekly composer changelog

- rules/phpunit/src/Rector/MethodCall/AssertFalseStrposToContainsRector.php
- rules/phpunit/src/Rector/MethodCall/AssertPropertyExistsRector.php
- rules/phpunit/src/Rector/MethodCall/AssertTrueFalseToSpecificMethodRector.php
- rules/phpunit/tests/Rector/MethodCall/AssertFalseStrposToContainsRector/Fixture/skip_method_call.php.inc
- rules/phpunit/tests/Rector/MethodCall/AssertPropertyExistsRector/Fixture/skip_method_call.php.inc
- rules/phpunit/tests/Rector/MethodCall/AssertTrueFalseToSpecificMethodRector/Fixture/skip_method_call.php.inc
Fix for https://github.com/rectorphp/rector/issues/5797
---
Edit @TomasVotruba  Fixes #5797
> [Phpunit] Prevent MethodCall instances of being processed

- rules/phpunit/src/Rector/MethodCall/AssertEqualsToSameRector.php
- rules/phpunit/tests/Rector/MethodCall/AssertEqualsToSameRector/Fixture/mark_test_incomplete.php.inc
- rules/phpunit/tests/Rector/MethodCall/AssertEqualsToSameRector/Fixture/mark_test_skipped.php.inc
Requested failing fixtures for https://github.com/rectorphp/rector/issues/5799
> Fix AssertEqualsToSameRector

- rules-tests/TypeDeclaration/Rector/Property/CompleteVarDocTypePropertyRector/Fixture/private_var_null_unused.php.inc
- rules-tests/TypeDeclaration/Rector/Property/CompleteVarDocTypePropertyRector/Fixture/public_var_null_used.php.inc
- rules-tests/TypeDeclaration/Rector/Property/CompleteVarDocTypePropertyRector/Fixture/skip_public_var_null_unused.php.inc
- rules/TypeDeclaration/Rector/Property/CompleteVarDocTypePropertyRector.php
Skip null default value on non-private property, eg: public can be used by outside class.
> [TypeDeclaration] Skip null type on non-private property and not used on CompleteVarDocTypePropertyRector

- .github/workflows/publish_docker_images.yaml
> [Github Action]  Fixes fail-fast location to be in strategy on publish_docker_images action

- scoped/.github/workflows/along_phpstan.yaml
- scoped/.github/workflows/bare_run.yaml
- scoped/.github/workflows/composer_dependency.yaml
Rector now runs also without `process` command.
This PR fixes exception if no config is around https://github.com/rectorphp/rector-prefixed/runs/2107855629
/cc @samsonasik
> [scoped] rector now runs without command name too

- rules-tests/CodeQuality/Rector/Include_/AbsolutizeRequireAndIncludePathRector/Fixture/dots.php.inc
- rules-tests/CodeQuality/Rector/Include_/AbsolutizeRequireAndIncludePathRector/Fixture/vendor_phar.php.inc
- rules/CodeQuality/Rector/Include_/AbsolutizeRequireAndIncludePathRector.php
Absolute paths should not be changed, dots need a leading slash.
Here is the original code I found this bug with:
- `include('../../prepend_light.php'); // unmodified`
After running Rector:
- `include(__DIR__ . '../../prepend_light.php'); // incorrectly modified (without this PR)`
- `include(__DIR__ . '/../../prepend_light.php'); // correctly modified (with this PR)`
See https://www.php.net/manual/en/function.include.php for how PHP treats the string passed to `include` and the related language constructs.
I am a bit confused how the broken PHPUnit fixtures were checked. What am I forgetting? 🤔
> Bugfix for AbsolutizeRequireAndIncludePathRector

- packages/Testing/PHPUnit/AbstractRectorTestCase.php
- rules-tests/CodeQuality/Rector/Foreach_/SimplifyForeachToArrayFilterRector/Fixture/same_var.php.inc
- rules/CodeQuality/Rector/Foreach_/SimplifyForeachToArrayFilterRector.php
Bugfix: leave the loop as it is if the array looped over is modified within the loop (rather then filled from scratch).
I have added an example to the PHPUnit tests which this Rector rule should not touch. The example is odd, but harmless. If the rule applies it would break.
> Bugfix for SimplifyForeachToArrayFilterRector

- rules-tests/PhpSpecToPHPUnit/Rector/Variable/PhpSpecToPHPUnitRector/Fixture/identity_matcher.php.inc
- rules/PhpSpecToPHPUnit/Rector/MethodCall/PhpSpecPromisesToPHPUnitAssertRector.php
Hi
Here is a quick fix for handling PhpSpec method `shouldEqual` when using rector suite PhpSpecToPHPUnit
> Fix for PhpSpec method shouldEqual

- src/NodeManipulator/ClassMethodAssignManipulator.php
ObjectTypeMethodReflection is just one of the implementations of MethodReflection interface, its existence was never part of a public API promise. Now a different implementation is returned, it depends on the situation. I guess this change is sufficient.
> Forward compatibility with PHPStan 0.12.82

- docs/how_to_add_test_for_rector_rule.md
it seems tests were moved to `rules-tests` lately and namespaces therefore changed a bit.
this PR tries to adjust the docs for the changed conditions.
> docs: fix path to tests and namespace in "how to add a test"

- packages/NodeNameResolver/NodeNameResolver.php
- rules/Php70/Rector/ClassMethod/Php4ConstructorRector.php
- rules/RemovingStatic/Rector/Property/DesiredPropertyClassMethodTypeToDynamicRector.php
- rules/RemovingStatic/Rector/StaticPropertyFetch/DesiredStaticPropertyFetchTypeToDynamicRector.php
- rules/Restoration/Rector/ClassMethod/InferParamFromClassMethodReturnRector.php
- rules/Restoration/ValueObject/InferParamFromClassMethodReturn.php
- utils/doctrine-annotation-parser-syncer/src/Rector/Assign/AssignNewDocParserRector.php
- utils/doctrine-annotation-parser-syncer/src/Rector/ClassMethod/ChangeOriginalTypeToCustomRector.php
- utils/doctrine-annotation-parser-syncer/src/Rector/ClassMethod/LogIdentifierAndResolverValueInConstantClassMethodRector.php
- utils/doctrine-annotation-parser-syncer/src/Rector/StaticCall/RemoveAnnotationRegistryRegisterFileRector.php
Ref https://github.com/rectorphp/rector/pull/5665
> [DX] Remove isInClassNamed()

- rules/CodeQuality/Rector/Catch_/ThrowWithPreviousExceptionRector.php
- rules/NetteToSymfony/NodeAnalyzer/NetteControlFactoryInterfaceAnalyzer.php
Fixes https://github.com/rectorphp/rector/issues/5906
> Refactor is_a

- .gitattributes
I have added a bunch of files to being ignored in exports. 
I think the biggest difference here is adding docs folder as it contains pictures. 
I have also re-added back the license file, as I don't think the license should be excluded when I include the package 👍 
I was unsure if the `phpstan-for-rector.neon` file should be excluded or not, so I left it in.
closes: #5948
> Add missing paths to .gitattributes

- README.md
- config/parameters.php
- config/set/league-event-30.php
- src/Configuration/Option.php
- src/Console/Command/ProcessCommand.php
With #5665 change in Rector 0.10, the option to include files in config was removed, as included files are now processed by static reflection.
This PR adds parameter `BOOTSTRAP_FILES` that includes files again.
Inspired by same-named option from PHPStan
https://phpstan.org/user-guide/discovering-symbols#global-constants
> Add bootstrap files option to allow including files

- .gitattributes
- README.md
I think Readme and docs files should be included in rector installation so user doesn't need to look at github repo to read it.
> Readme and docs should be included in rector installation

- rules-tests/Naming/Rector/Foreach_/RenameForeachValueVariableToMatchExprVariableRector/Fixture/skip_empty_singular_value.php.inc
- rules/Naming/ExpectedNameResolver/InflectorSingularResolver.php
- rules/Naming/Rector/Foreach_/RenameForeachValueVariableToMatchExprVariableRector.php
> [Naming] Skip RenameForeachValueVariableToMatchExprVariableRector on empty singular value name result

- rules-tests/CodingStyle/Rector/FuncCall/ConsistentPregDelimiterRector/Fixture/escape_content_delimiter_in_pattern.php.inc
- rules-tests/CodingStyle/Rector/FuncCall/ConsistentPregDelimiterRector/Fixture/escape_content_delimiter_in_pattern_multi.php.inc
- rules/CodingStyle/Rector/FuncCall/ConsistentPregDelimiterRector.php
> [CodingStyle]  Escape content delimiter in pattern for ConsistentPregDelimiterRector

- docs/rector_rules_overview.md
- rules/Arguments/Rector/ClassMethod/ArgumentAdderRector.php
When I follow the instructions to configure `ArgumentAdderRector`
```php
use Rector\Arguments\Rector\ClassMethod\ArgumentAdderRector;
use Rector\Arguments\ValueObject\ArgumentAdder;
use Symfony\Component\DependencyInjection\Loader\Configurator\ContainerConfigurator;
use Symplify\SymfonyPhpConfig\ValueObjectInliner;
return static function (ContainerConfigurator $containerConfigurator): void {
$services = $containerConfigurator->services();
$services->set(ArgumentAdderRector::class)
->call('configure', [[
ArgumentAdderRector::ADDED_ARGUMENTS => ValueObjectInliner::inline([
new ArgumentAdder('SomeExampleClass', 'someMethod', 0, 'someArgument', 'true', 'SomeType', null),
]),
]]);
};
```
```diff
$someObject = new SomeExampleClass;
-$someObject->someMethod();
+$someObject->someMethod('true'); …
```
> Stripping quotation marks of argument default value

- rules-tests/CodeQualityStrict/Rector/Variable/MoveVariableDeclarationNearReferenceRector/Fixture/static_call_next_exception.php.inc
- rules-tests/CodeQualityStrict/Rector/Variable/MoveVariableDeclarationNearReferenceRector/Source/MyException.php
- rules/CodeQualityStrict/Rector/Variable/MoveVariableDeclarationNearReferenceRector.php
Throwable instance with static call mostly used for named constructor call, eg:
```php
throw MyException::notFound();
```
which usually not change external data. This allow to pass it to move variable after it.
> [CodeQualityStrict] Allow MoveVariableDeclarationNearReferenceRector to pass static call on Throwable instance

- rules-tests/TypeDeclaration/Rector/Property/PropertyTypeDeclarationRector/Fixture/private_var_null_unused.php.inc
- rules-tests/TypeDeclaration/Rector/Property/PropertyTypeDeclarationRector/Fixture/public_var_null_used.php.inc
- rules-tests/TypeDeclaration/Rector/Property/PropertyTypeDeclarationRector/Fixture/skip_public_var_null_unused.php.inc
- rules/TypeDeclaration/Rector/Property/PropertyTypeDeclarationRector.php
like in https://github.com/rectorphp/rector/pull/5833
> [TypeDeclaration] Skip null type on non-private property and not used on PropertyTypeDeclarationRector

- rules-tests/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture/skip_used_in_method_call.php.inc
- rules-tests/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture/skip_used_in_property_fetch.php.inc
- rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php
> [DeadCode] Skip RemoveUnusedVariableAssignRector on used in Method call and PropertyFetch name

- packages/NodeTypeResolver/PhpDocNodeVisitor/NameImportingPhpDocNodeVisitor.php
Use existing NodeTypeResolver object and change public name property instead of re-create new object when name is equal. Fixes #6065
> [NodeTypeResolver] Fixes #6065 Use existing NodeTypeResolver object on Auto Imports short name

- rules-tests/DowngradePhp72/Rector/FuncCall/DowngradePregUnmatchedAsNullConstantRector/Fixture/skip_different_flag2.php.inc
- rules-tests/DowngradePhp72/Rector/FuncCall/DowngradePregUnmatchedAsNullConstantRector/Fixture/skip_different_flag3.php.inc
- rules/DowngradePhp72/Rector/FuncCall/DowngradePregUnmatchedAsNullConstantRector.php
- rules/LeagueEvent/Rector/MethodCall/DispatchStringToObjectRector.php
> [DowngradePhp72] Skip DowngradePregUnmatchedAsNullConstantRector on different flags in BitwiseOr

- rules-tests/CodeQualityStrict/Rector/Variable/MoveVariableDeclarationNearReferenceRector/Fixture/skip_pass_bcdiv.php.inc
- rules-tests/CodeQualityStrict/Rector/Variable/MoveVariableDeclarationNearReferenceRector/Fixture/skip_pass_json_last_error.php.inc
- rules-tests/CodeQualityStrict/Rector/Variable/MoveVariableDeclarationNearReferenceRector/Fixture/static_call_next_exception.php.inc
- rules/CodeQualityStrict/Rector/Variable/MoveVariableDeclarationNearReferenceRector.php
- rules/DeadCode/SideEffect/PureFunctionDetector.php
use `PureFunctionDetector` service.
> [CodeQualityStrict] Skip MoveVariableDeclarationNearReferenceRector on pass impure function

- rules-tests/CodeQuality/Rector/Ternary/UnnecessaryTernaryExpressionRector/Fixture/multiple_negation_array.php.inc
- rules-tests/CodeQuality/Rector/Ternary/UnnecessaryTernaryExpressionRector/Fixture/multiple_negation_array2.php.inc
- rules-tests/CodeQuality/Rector/Ternary/UnnecessaryTernaryExpressionRector/Fixture/multiple_negation_bool.php.inc
- rules-tests/CodeQuality/Rector/Ternary/UnnecessaryTernaryExpressionRector/Fixture/negation_array.php.inc
- rules-tests/CodeQuality/Rector/Ternary/UnnecessaryTernaryExpressionRector/Fixture/negation_array2.php.inc
- rules-tests/CodeQuality/Rector/Ternary/UnnecessaryTernaryExpressionRector/Fixture/negation_bool.php.inc
- rules/CodeQuality/Rector/Ternary/UnnecessaryTernaryExpressionRector.php
This patch remove double negation for `BooleanNot` got flipped `false ? true`, eg:
```php
return !! $data
```
as refactor result for the following code:
```php
return ! $data ? false : true;
```
to be:
```php
return $data;
```
or 
```php
return (bool) $data;
```
based on the condition type.
> [CodeQuality] Avoid double negation on UnnecessaryTernaryExpressionRector

- rules-tests/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture/method_call_only.php.inc
- rules-tests/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector/config/configured_rule.php
- rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php
Fixes case where business logic was accidentaly removed too
> [DeadCode] Fix RemoveUnusedVariableAssignRector for variable removal

- rules-tests/Php73/Rector/FuncCall/RegexDashEscapeRector/Fixture/skip_three_backslash.php.inc
- rules/Downgrade72/Rector/FuncCall/DowngradeStreamIsattyRector.php
- rules/Php73/Rector/FuncCall/RegexDashEscapeRector.php
It previously produce invalid regex ref https://regex101.com/r/QkRzuF/1 , also, if passed to `preg_match()`, it will result different data ref https://github.com/codeigniter4/CodeIgniter4/runs/2345676568#step:11:177
> [Php73] Skip RegexDashEscapeRector on 3 backslash with next to be escaped

- rules-tests/Php73/Rector/FuncCall/JsonThrowOnErrorRector/Fixture/fixture.php.inc
- rules-tests/Php73/Rector/FuncCall/JsonThrowOnErrorRector/Fixture/json_last_error_next_after_return.php.inc
- rules-tests/Php73/Rector/FuncCall/JsonThrowOnErrorRector/Fixture/json_last_error_next_after_return2.php.inc
- rules-tests/Php73/Rector/FuncCall/JsonThrowOnErrorRector/Fixture/skip_json_last_error_next.php.inc
- rules-tests/Php73/Rector/FuncCall/JsonThrowOnErrorRector/Fixture/skip_json_last_error_next2.php.inc
- rules-tests/Php73/Rector/FuncCall/JsonThrowOnErrorRector/Fixture/skip_json_last_error_next3.php.inc
- rules/Downgrade72/Rector/FuncCall/DowngradeStreamIsattyRector.php
- rules/Php73/Rector/FuncCall/JsonThrowOnErrorRector.php
- src/PhpParser/Node/BetterNodeFinder.php
- change 2nd parameter of json_decode to null  as default value is null, ref https://www.php.net/manual/en/function.json-decode.php 
- skip when next func call is/are `json_last_error()`, `json_last_error_msg()` as may be used next ref https://3v4l.org/3R5fM
> [Php73] Refactor JsonThrowOnErrorRector: change 2nd parameter of json_decode to null and skip on json_last_error, json_last_error_msg

- docs/rector_rules_overview.md
- rules-tests/DowngradePhp80/Rector/NullsafeMethodCall/DowngradeNullsafeToTernaryOperatorRector/Fixture/fixture.php.inc
- rules-tests/DowngradePhp80/Rector/NullsafeMethodCall/DowngradeNullsafeToTernaryOperatorRector/Fixture/multiple_call.php.inc
- rules/DowngradePhp80/Rector/NullsafeMethodCall/DowngradeNullsafeToTernaryOperatorRector.php
It looks like the current transpilation of the PHP 8 null safe operator results in multiple calls to the method which may be undesired and cause subtle bugs. This fixes that by storing the result of the null-check in a temporary variable and relying on PHP's order-of-operations to reuse the same variable name. `$_` may result in a collision with other code, so if there's reason to fear that, perhaps a hash of some kind could be used instead; I'm open to any suggestion.
> Fix nullsafe transpile

- rules-tests/PSR4/Rector/FileWithoutNamespace/NormalizeNamespaceByPSR4ComposerAutoloadRector/Fixture/namespace_less_class.php.inc
- rules-tests/PSR4/Rector/FileWithoutNamespace/NormalizeNamespaceByPSR4ComposerAutoloadRector/Fixture/no_prefix_consts.php.inc
- rules-tests/PSR4/Rector/FileWithoutNamespace/NormalizeNamespaceByPSR4ComposerAutoloadRector/Fixture/skip_class_consts.php.inc
- rules/DeadCode/NodeAnalyzer/UsedVariableNameAnalyzer.php
- rules/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector.php
- rules/PSR4/NodeManipulator/FullyQualifyStmtsAnalyzer.php
- rules/PSR4/Rector/FileWithoutNamespace/NormalizeNamespaceByPSR4ComposerAutoloadRector.php
- src/Bootstrap/ExtensionConfigResolver.php
Closes https://github.com/rectorphp/rector/issues/6146
> Do not prefix "parent", "self", "static" and native constants

- build/config/config-downgrade.php
- build/target-repository/.github/workflows/bare_run.yaml
- build/target-repository/.github/workflows/finalize_classes.yaml
- build/target-repository/composer.json
Part of https://github.com/rectorphp/rector/issues/6079 . I think most of downgrade 7.1 have implemented, lets try to downgrade to 7.0 for rector-prefixed build.
> [Scoped] Allow PHP 7.0 on rector-prefixed build

- build/target-repository/composer.json
- rules/DowngradePhp71/Rector/List_/DowngradeKeysInListRector.php
Closes https://github.com/rectorphp/rector/issues/6180
> [prefixed] require compatible PHPStan with attribute phpdoc-parser

- config/set/downgrade-php71.php
> Add iterable to PHP 7.1 downgrade set

- rules-tests/Php74/Rector/Property/TypedPropertyRector/Fixture/skip_callable_property_type.php.inc
Based on https://getrector.org/demo/e8724b53-a00c-4f0c-b10f-e4e54be0a664
```
PHP Fatal error:  Property SkipCallablePropertyType::$startDate cannot have type DateTimeImmutable|callable
```
> [TypedPropertyRector] Do not refactor to `callable` property type

- rules-tests/Php74/Rector/Property/TypedPropertyRector/Fixture/skip_iterable_property_type.php.inc
Based on https://getrector.org/demo/3a8fc4f5-898d-4fb4-8ed3-99dc8312df77
```
Fatal error: Cannot use iterable as iterable because 'iterable' is a special class name
```
> [TypedPropertyRector] Do not refactor to `iterable` property type

- rules-tests/Php80/Rector/FunctionLike/UnionTypesRector/Fixture/some_parent.php.inc
Based on https://getrector.org/demo/6298a30b-d9f5-4fa0-b1f8-9712b0e98582
```
PHP Fatal error:  Declaration of Child::enqueueAt(DateTime|int $at) must be compatible with SomeParent::enqueueAt($at)
```
> [UnionTypesRector] Do not refactor inherited methods

- rules-tests/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture/skip_else_nop.php.inc
- rules-tests/DeadCode/Rector/Assign/RemoveUnusedVariableAssignRector/Fixture/skip_if_nop.php.inc
- src/PhpParser/Comparing/ConditionSearcher.php
Nop stmt doesn't has expr property on next check.
> [DeadCode] Skip expr check from statement on RemoveUnusedVariableAssignRector for Nop stmt

- build/config/config-downgrade.php
@samsonasik Just a note, current downgrade set for PHP 7.1 cannot be used with `phpstan.phar`.
It would create return type conflict, as it only downgraded our code but parent class is in `phpstan.phar`
The solution is to downgrade https://github.com/phpstan/phpstan-src or unwrap `phpstan.phar` and downgrade it too
> Fix php70 on prefixed - skip nullable till phpstan is downgraded

- phpstan.neon
- rules-tests/DowngradePhp71/Rector/Array_/SymmetricArrayDestructuringToListRector/Fixture/include_empty.php.inc
- rules/DowngradePhp71/Rector/Array_/SymmetricArrayDestructuringToListRector.php
Closes https://github.com/rectorphp/rector/issues/6210
See https://3v4l.org/3SYSp
> [Downgrade PHP 7.1] Fix empty item on SymmetricArrayDestructuringToListRector

- composer.json
- config/services.php
- src/functions/node_helper.php
Closes https://github.com/rectorphp/rector/issues/6186
This is a must have for working with Rector.
```php
dump_node($node);
// second parameter is depth of parameters to dump
dump_node($node, 2);
dump_node($node, 4);
```
> add dump_node() helper functoin

- packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/assert_not_blank.php.inc
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/config/configured_rule.php
Hi, seems AnnotationToAttributeRector has bug if annotation has bool param
```
-    #[\Symfony\Component\Validator\Constraints\NotBlank(allowNull: true)]
+    #[\Symfony\Component\Validator\Constraints\NotBlank(allowNull: 'true')]
```
> AnnotationToAttributeRector: ensure bool param in attribute

- packages/NodeCollector/NodeCollector/NodeRepository.php
- rules-tests/Defluent/Rector/ClassMethod/ReturnThisRemoveRector/Fixture/skip_parent_in_vendor.php.inc
- rules-tests/Defluent/Rector/ClassMethod/ReturnThisRemoveRector/Source/vendor/ParentInVendor.php
- rules-tests/Privatization/Rector/Property/ChangeReadOnlyPropertyWithDefaultValueToConstantRector/Fixture/skip_referenced_in_method_call_with_another_class.php.inc
- rules-tests/Privatization/Rector/Property/ChangeReadOnlyPropertyWithDefaultValueToConstantRector/Fixture/skip_referenced_in_static_call_with_another_class.php.inc
- rules-tests/Privatization/Rector/Property/ChangeReadOnlyPropertyWithDefaultValueToConstantRector/Source/ReferencedInMethodCall.php
- rules-tests/Privatization/Rector/Property/ChangeReadOnlyPropertyWithDefaultValueToConstantRector/Source/ReferencedInStaticCall.php
- rules/Defluent/ConflictGuard/ParentClassMethodTypeOverrideGuard.php
- src/NodeManipulator/PropertyManipulator.php
- src/Reflection/FunctionLikeReflectionParser.php
Closes #6214 by update `NodeRepository` to parse outside file if not found in the list of registered class method.
> [Privatization] Handle Reference Method/Static Call from outside file on ChangeReadOnlyPropertyWithDefaultValueToConstantRector

- packages/PhpAttribute/Printer/PhpAttributeGroupFactory.php
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/Fixture/assert_choice.php.inc
- rules-tests/Php80/Rector/Class_/AnnotationToAttributeRector/config/configured_rule.php
There are some issues when handling arrays:
```php
/**
* @Assert\Choice(choices={"foo", "bar"})
*/
public $surname;
```
is converted into
```php
#[\Symfony\Component\Validator\Constraints\Choice(choices: '{"foo", "bar"}')]
public $surname;
```
This PR solves it
> AnnotationToAttributeRector: array handling

- tests/Application/ApplicationFileProcessor/Source/Contract/TextRectorInterface.php
- tests/Application/ApplicationFileProcessor/Source/Rector/ChangeTextRector.php
- tests/Application/ApplicationFileProcessor/Source/TextFileProcessor.php
- tests/Application/ApplicationFileProcessor/config/configured_rule.php
Ref https://github.com/rectorphp/rector/issues/6087
> Update text for FileProccessor to use Rector interface contract

- scoper.php
Reverts rectorphp/rector#6293 change all `$prefix\Composer\` to `Composer` cause error on php 7.1 scoped. Reverting it.
> Revert "[Scoper] Skip Prefix\Composer\ usage"

- composer.json
- scoper-php70.php
- utils/compiler/src/Command/DowngradePathsCommand.php
I installed php 7.0 in my local dev and it seems working ok:
```bash
/opt/homebrew/bin/php php-parallel-lint/parallel-lint rector-prefixed-downgraded-php70 --exclude rector-prefixed-downgraded-php70/stubs --exclude rector-prefixed-downgraded-php70/vendor/symfony/error-handler/Resources --exclude rector-prefixed-downgraded-php70/vendor/symfony/http-kernel/Resources --exclude rector-prefixed-downgraded-php70/vendor/rector/rector-nette/tests --exclude rector-prefixed-downgraded-php70/vendor/symfony/polyfill-mbstring/bootstrap80.php --exclude rector-prefixed-downgraded-php70/vendor/tracy/tracy/examples --exclude rector-prefixed-downgraded-php70/vendor/rector/rector-installer/tests --exclude rector-prefixed-downgraded-php70/vendor/symplify/smart-file-system/tests --exclude …
```
> [Scoper] Patch ParameterSkipper class via scoper-php70 config

- rules-tests/DowngradePhp71/Rector/String_/DowngradeNegativeStringOffsetToStrlenRector/Fixture/property_fetch.php.inc
- rules-tests/DowngradePhp71/Rector/String_/DowngradeNegativeStringOffsetToStrlenRector/Fixture/static_property_fetch.php.inc
- rules-tests/DowngradePhp71/Rector/String_/DowngradeNegativeStringOffsetToStrlenRector/Fixture/variable.php.inc
- rules/DowngradePhp71/Rector/String_/DowngradeNegativeStringOffsetToStrlenRector.php
ref https://github.com/rectorphp/rector/pull/6310#issuecomment-831321508 . It is no need `string` type check on variable as if variable is not string, it will got syntax error https://3v4l.org/TM68C
> [DowngradePhp71] Allow downgrade negative offset string on variable/PropertyFetch/StaticPropertyFetch

- scoper-php70.php
ref https://github.com/rectorphp/rector-prefixed-php70/runs/2493424282#step:4:6 . Some vendor dependencies seems overlapped make `: void` not updated. use scoper config to patch
> [Scoper] Patch : void in vendor via scoper-php70 config

- bin/rector.php
- composer.json
- config/services.php
- phpstan.neon
- rules-tests/Php55/Rector/FuncCall/PregReplaceEModifierRector/Fixture/preg_quoted.php.inc
- rules-tests/Php72/Rector/FuncCall/CreateFunctionToAnonymousFunctionRector/Fixture/drupal.php.inc
- src/constants.php
- tests/bootstrap.php
Ref https://github.com/rectorphp/rector/issues/6326
> [php-parser] upgrade to 4.10.5 - add src/constants.php to mimic new PHP 8.1 tokens; update test with unicode

- scoper-php70.php
Based on https://github.com/rectorphp/rector/issues/6079#issuecomment-832429702
> [Scoped] Keep \Composer\InstalledVersions not prefixed for composer/InstalledVersions.php

- .github/workflows/build_scoped_rector_php70.yaml
Handle error : 
```bash
Problem 1
483
- Root composer.json requires phpstan/phpstan-src 0.12.85 -> satisfiable by phpstan/phpstan-src[0.12.85].
484
- phpstan/phpstan-src 0.12.85 requires composer/xdebug-handler ^1.3.0 -> found composer/xdebug-handler[1.3.0, ..., 1.4.x-dev] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
- 
- 
```
> [Scoped] Remove composer.lock after remove ecs,cs,php-cs-fixer

- config/services.php
> [TASK] Remove RenameClassNonPhpRector from the defaults

- rules-tests/Php74/Rector/Property/TypedPropertyRector/Fixture/generic_object_type.php.inc
- rules/Php74/Rector/Property/TypedPropertyRector.php
> [Php74] Handle Generic Type on TypedPropertyRector

- .github/workflows/build_scoped_rector_php70.yaml
- rules/DowngradePhp71/Rector/FunctionLike/DowngradeNullableTypeDeclarationRector.php
- scoper-php70.php
- utils/compiler/src/Command/DowngradePathsCommand.php
reduce syntax errors from : 383 to 14: 
Before:
```
Syntax error found in 383 files
```
After:
```
Syntax error found in 14 files
```
> [Scoped] Add more paths to downgrade, tweak scope configs 

- rules-tests/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector/Fixture/class_in_trait.php.inc
- rules/DowngradePhp70/NodeFactory/ClassFromAnonymousFactory.php
- rules/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector.php
Fixes case when trait has an anonmous class in it: https://github.com/symplify/easy-coding-standard/blob/7f89cf493b8140b257bcf38d449c0a33e414e5bb/vendor/symfony/service-contracts/ServiceLocatorTrait.php#L105-L113
<br>
This is invalid PHP
> [DowngradePhp70] Add anonymous class out of trait

- rules-tests/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector/Fixture/class_exist.php.inc
- rules-tests/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector/Fixture/class_in_trait.php.inc
- rules-tests/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector/Fixture/fixture.php.inc
- rules-tests/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector/Fixture/in_closure.php.inc
- rules-tests/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector/Fixture/in_closure_no_namespace.php.inc
- rules-tests/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector/Fixture/in_function.php.inc
- rules-tests/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector/Fixture/in_function_no_namespace.php.inc
- rules-tests/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector/Fixture/no_namespace.php.inc
- rules-tests/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector/Fixture/not_in_function.php.inc
- rules-tests/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector/Fixture/not_in_function_no_namespace.php.inc
- rules-tests/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector/Fixture/skip_not_anonymous.php.inc
- rules-tests/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector/Fixture/with_args.php.inc
- rules/DowngradePhp70/Rector/New_/DowngradeAnonymousClassRector.php
Fixes these bugs :bug: 
- with 2 classes in same file, previous all were named the same - see https://github.com/symplify/easy-coding-standard/blob/3402ffe98ed26247b3479628986f633d3a1084d4/vendor/symfony/service-contracts/ServiceLocatorTrait.php#L23
- with 2 classes in same namespace (different files)
<br>
Changes got inspired by https://github.com/spatie/7to5/blob/master/src/NodeVisitors/AnonymousClassReplacer.php
The new class name is now based on:
- current absolute file path - unique for every file :heavy_check_mark: 
- on number of already added anonymous classes :heavy_check_mark:
> [Downgrade 7.0] Fix DowngradeAnonymousClassRector bugs and simplify its naming
